src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AssessmentURLMobile__c</fullName>
        <label>AssessmentURLMobile</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>AssessmentURL__c</fullName>
        <inlineHelpText>This is the assessment URL</inlineHelpText>
        <label>AssessmentURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Create_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</description>
        <inlineHelpText>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</inlineHelpText>
        <label>Create Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Questionnaire_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Each account should be related to a Template</inlineHelpText>
        <label>Main_Questionnaire_Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>PublishPlace__c</fullName>
        <description>This field specifies whether the template is for access through external site or internal salesforce login</description>
        <inlineHelpText>This field specifies whether the template is accessable through external site or internal salesforce login</inlineHelpText>
        <label>PublishPlace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal to salesforce</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>External Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Static_Data_Object__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Add any field name which is static across orgs, they can have different values.Eg the Site URL, country codes</description>
    <fields>
        <fullName>Site_URL__c</fullName>
        <description>This is the url of the site. In salesforce create a Site which has a app guest user licence and add the url here.</description>
        <inlineHelpText>This is the url of the site. In salesforce create a Site which has a app guest user licence and add the url here.</inlineHelpText>
        <label>Site URL</label>
        <type>Url</type>
    </fields>
    <label>Static Data Object</label>
</CustomObject>

src/classes/CreateAssessmentController.cls
public with sharing class CreateAssessmentController {

    public Boolean MobileVersion{get;set;}

    public Account acc { get; set; }

    public Map<Id, Main_questionaire__c> templateMap;

    public PageReference refresh = new PageReference(ApexPages.currentPage().getUrl());

    public CreateAssessmentController(ApexPages.StandardSetController controller) {
        startProcess();
    }

    public CreateAssessmentController() {
        MobileVersion = false;
        startProcess();
    }

    public void startProcess() {

        try{
            acc = new Account();
            templateMap = new Map<Id, Main_questionaire__c>();

            SFDCAccessController accessObj = ExAMUtilClass.AccessController;
            List<string> fieldsListAT = new List<string>{'ExAM__Template_name__c','ExAM__PublishPlace__c'};
            accessObj.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Main_questionaire__c'), fieldsListAT);

            List<Main_questionaire__c> templatesList = new List<Main_questionaire__c>();
            templatesList = [SELECT Id, PublishPlace__c, Template_name__c FROM Main_questionaire__c WHERE Template_name__c <> null AND PublishPlace__c <> null ORDER BY Template_name__c];
            if (templatesList.size() > 0) {
                templateMap = new Map<Id, Main_questionaire__c>(templatesList);
            }
        } catch(Exception e){
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    }

    public PageReference mobilesave()
    {
        MobileVersion = true;
        PageReference ref = save();
        return ref;
    }

    public PageReference save() {
        try
        {
            PageReference saveClicked;
            //string mobversion=System.currentPageReference().getParameters().get('MobileVersion');

            if (acc.Name == null || acc.Main_Questionnaire_Template__c == null) {
                ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter Account name and choose a Assessment template') );
                return null;
            }
            else
            {
                acc.Create_Survey__c = true;
                if (templateMap.containsKey(acc.Main_Questionnaire_Template__c)
                    && templateMap.get(acc.Main_Questionnaire_Template__c) != null
                ) {
                    string templateName = templateMap.get(acc.Main_Questionnaire_Template__c).Template_name__c;
                    if (templateName.equalsIgnoreCase('DOI')) {
                        acc.AssessmentURL__c = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/QuestionnaireCustomDOI';
                        acc.AssessmentURLMobile__c = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/QuestionnaireCustomMobile';
                    }
                    else {
                        acc.AssessmentURL__c = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/QuestionnaireCustom';
                        acc.AssessmentURLMobile__c = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/QuestionnaireCustomMobile';
                    }
                }
                SFDCAccessController accessForAcc = ExAMUtilClass.AccessController;
                List<string> fieldsListAcc1 = new List<string>{'ExAM__AssessmentURL__c', 'ExAM__AssessmentURLMobile__c', 'ExAM__Create_Survey__c', 'ExAM__Main_Questionnaire_Template__c'};
                accessForAcc.assertAuthorizedToCreate(Schema.getGlobalDescribe().get('Account'), fieldsListAcc1);

                insert acc;

                if (templateMap.containsKey(acc.Main_Questionnaire_Template__c)
                    && templateMap.get(acc.Main_Questionnaire_Template__c) != null
                ) {

                    Account updateAcc = new Account(Id = acc.Id);
                    updateAcc.AssessmentURLMobile__c = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/QuestionnaireCustomMobile?accId='+acc.Id;
                    updateAcc.AssessmentURL__c = URL.getSalesforceBaseUrl().toExternalForm() + '/apex/QuestionnaireCustom?accId='+acc.Id;   

                    string templateName = templateMap.get(acc.Main_Questionnaire_Template__c).Template_name__c;
                    string templatePublishPlace = templateMap.get(acc.Main_Questionnaire_Template__c).PublishPlace__c;
                    if( templatePublishPlace.equalsIgnoreCase('Internal to salesforce') )
                    {
                        //returnAssessList.add('/apex/QuestionnaireCustom?accId='+acc.Id);
                        if(templateName.equalsIgnoreCase('DOI'))
                        {
                            saveClicked = new PageReference('/apex/QuestionnaireCustomDOI?accId='+acc.Id);
                        }
                        else
                        {
                            if(MobileVersion==true)
                            {
                                saveClicked = new PageReference('/apex/QuestionnaireCustomMobile?accId='+acc.Id);
                            }
                            else
                            {
                                saveClicked = new PageReference('/apex/QuestionnaireCustom?accId='+acc.Id);
                            }
                            //saveClicked=new PageReference('/apex/QuestionnaireCustom?accId='+acc.Id);
                        }
                    }
                    else if( templatePublishPlace.equalsIgnoreCase('External Site') )
                    {
                        //returnAssessList.add('http://exam4schools-developer-edition.na15.force.com/ExAM/QuestionnaireCustomSite?accId='+acc.Id);  
                        Static_Data_Object__c externalsiteurl = Static_Data_Object__c.getValues('SiteURL');
                        if (externalsiteurl != null) {
                            string siteCompleteUrl = externalsiteurl.Site_URL__c+'QuestionnaireCustomSite?accId='+acc.Id;
                            //http://exam4schools-developer-edition.na15.force.com/ExAM/QuestionnaireCustomSite?accId='+acc.Id
                            saveClicked = new PageReference(siteCompleteUrl);
                        }
                        List<User> guestUserList = new List<User>([SELECT Id, isActive, Name FROM User WHERE Name = 'ExAM Site Guest User' LIMIT 1]);
                        if(guestUserList.size() == 0)
                        {
                            saveClicked = refresh;
                        }
                        else
                        {
                            updateAcc.OwnerId = guestUserList[0].Id;
                        }
                    }
                    /*
                    else if( templatePublishPlace.equalsIgnoreCase('External Site') )
                    {
                        //returnAssessList.add('http://exam4schools-developer-edition.na15.force.com/ExAM/QuestionnaireCustomSite?accId='+acc.Id);
                        saveClicked=new PageReference('http://exam4schools-developer-edition.na15.force.com/ExAM/QuestionnaireCustomSite?accId='+acc.Id);
                        List<User> guestUserList = new List<User>([SELECT Id, isActive, Name FROM User WHERE Name = 'ExAM Site Guest User' LIMIT 1]);
                        if(guestUserList.size() == 0)
                        {
                            saveClicked=refresh;
                        }
                        else
                        {
                            updateAcc.OwnerId = guestUserList[0].Id;
                        }
                    }
                    */
                    if (updateAcc != null && updateAcc.Id != null) {
                        SFDCAccessController accessAcc = ExAMUtilClass.AccessController;
                        List<string> fieldsListAcc = new List<string>{'ExAM__AssessmentURLMobile__c', 'ExAM__AssessmentURL__c'};
                        accessAcc.assertAuthorizedToUpdate(Schema.getGlobalDescribe().get('Account'), fieldsListAcc);
                        update updateAcc;
                    }
                }
            }
            if(saveClicked!=null)
            {          
                saveClicked.setRedirect(true);
                return saveClicked;
            }
            else
            {
                return refresh;
            }
        }
        catch(Exception e){
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }  
        return null;
    } 
    
        
    public PageReference cancel()
    {
        return refresh;
    }
        
    public PageReference Home() {
        PageReference cancelClicked=new PageReference('/home/home.jsp');
        cancelClicked.setRedirect(true);
        return cancelClicked; 
    }

    public static testMethod void CreateAssessment_Test()
    {
        //Test converage for the visualforce page
        PageReference pageRef = Page.CreateAssessment;
        Test.setCurrentPageReference(pageRef);
        Test.startTest();
        Main_questionaire__c maintest=new Main_questionaire__c (Template_name__c ='test',PublishPlace__c='Internal to salesforce');
        upsert maintest;
        Main_questionaire__c maintest1=new Main_questionaire__c (Template_name__c ='test2',PublishPlace__c='External Site');
        upsert maintest1;
        Account acc=new Account(name='test acc',Create_Survey__c=true);
        acc.Main_Questionnaire_Template__c=maintest.id;
        insert acc;
        Account acc2=new Account(name='test acc2',Create_Survey__c=true);
        acc2.Main_Questionnaire_Template__c=maintest1.id;
        insert acc2;   
        CreateAssessmentController  d = new CreateAssessmentController();
        d.save();
        system.assertEquals(d.acc.Id, null);
        d.acc.Name = 'Test Account 1';
        d.acc.Main_Questionnaire_Template__c = maintest.Id;
        d.save();
        system.assertNotEquals(d.acc.Id, null);
        d.acc.Name = 'Test Account 2';
        d.acc.Main_Questionnaire_Template__c = maintest1.Id;
        d.save();
        system.assertNotEquals(d.acc.Id, null);
        d.mobilesave();
        d.Home();
        d.cancel();
        Test.stopTest();
    }
    public static testMethod void CreateAssessment_Test1()
    {
        //Test converage for the visualforce page
        PageReference pageRef = Page.CreateAssessment;
        Test.setCurrentPageReference(pageRef);
        Test.startTest();
        Main_questionaire__c maintest1=new Main_questionaire__c (Template_name__c ='test2',PublishPlace__c='External Site');
        upsert maintest1;
        Account acc=new Account(name='test acc',Create_Survey__c=true);
        acc.Main_Questionnaire_Template__c=maintest1.id;
        insert acc;
        Account acc2=new Account(name='test acc2',Create_Survey__c=true);
        acc2.Main_Questionnaire_Template__c=maintest1.id;
        insert acc2;   
        CreateAssessmentController  d = new CreateAssessmentController();
        d.save();
        system.assertEquals(d.acc.Id, null);
        d.acc.Name = 'Test Account 1';
        d.acc.Main_Questionnaire_Template__c = maintest1.Id;
        d.save();
        system.assertNotEquals(d.acc.Id, null);
        d.acc.Name = 'Test Account 2';
        d.acc.Main_Questionnaire_Template__c = maintest1.Id;
        d.save();
        system.assertNotEquals(d.acc.Id, null);
        d.mobilesave();
        d.Home();
        d.cancel();
        Test.stopTest();
    }
}