src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hide_AM_List_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide AM List Tab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Assessable_Record_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Assessable Record Tab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Data_Viewer_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Data Viewer Tab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Knowledge_Article_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Knowledge Article Tab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Related_Assignment_Manager1_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Related Assignment Manager1 Tab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Related_Assignment_Manager2_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Related Assignment Manager2 Tab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Related_Assignment_Manager3_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Related Assignment Manager3 Tab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Related_Assignment_Manager4_Tab__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Related Assignment Manager4 Tab</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hide_Save_Button__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hide Save Button</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Status_on_Submit__c</fullName>
        <label>Overall Status on Submit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Assessment_Type_Template__c</fullName>
        <label>Primary Assessment Type Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>One_Time_Assessment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Z-One Time Assessment (DO NOT USE)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree Result Page Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>One_Time_Assessment__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When One Time Assessment is checked answered provided during a previous submission will be displayed in the viewer. Without it checked they will not see any previously submitted answers and new answers can be added.</inlineHelpText>
        <label>One Time Assessment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree Result Page Fields Default</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Comment__c</fullName>
        <inlineHelpText>Any user comment associated with this specific Answer record.</inlineHelpText>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>This is the priority of the Answer being provided.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_Response__c</fullName>
        <description>This is score that user gets .It is in percentages from 0-100%.For N/A the score as 0 and dont add it to numerator or denominator</description>
        <inlineHelpText>The percentage of the total possible score possible for the answer that was achieved by the Answer.</inlineHelpText>
        <label>Raw Response Score(%)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestLensViewerController.cls
/**
    Code coverage for MultipleInspectionAssessmentViewCtrller class
**/
@isTest
private class TestLensViewerController {
    @testSetUp
    public static void testSetUp() {
       
        List<Account> aclist = new List<Account> {
                               new Account(Name = 'TestAcc1')};
        insert acList;
        
        List<Main_questionaire__c> asstempList = new List<Main_questionaire__c> {
            new Main_questionaire__c (Template_name__c = 'Template one', One_Time_Assessment__c = true),
            new Main_questionaire__c (Template_name__c = 'Site Template', One_Time_Assessment__c = true),
            new Main_questionaire__c (Template_name__c = 'Systems Template', One_Time_Assessment__c = true),
            new Main_questionaire__c (Template_name__c = 'Common Areas Template', One_Time_Assessment__c = true),
            new Main_questionaire__c (Template_name__c = 'Exterior  Template', One_Time_Assessment__c = true),
            new Main_questionaire__c (Template_name__c = 'Unit Template', One_Time_Assessment__c = true)};
        insert asstempList;
        
        List<Section_Template__c> secTempList = new List<Section_Template__c>{
                                                new Section_Template__c(Questionnaire_Section__c = asstempList[0].id)};
        insert secTempList;
        
        List<Question_Template__c> quesTempList1 = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Test Question1')};
        insert quesTempList1;                                             
         
        List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c>{
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[0].Id, Facility_Name__c = acList[0].Id, Status__c = 'Open' ),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[1].Id, Facility_Name__c = acList[0].Id, Status__c = 'Open' ),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[2].Id, Facility_Name__c = acList[0].Id, Status__c = 'Open' ),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[3].Id, Facility_Name__c = acList[0].Id, Status__c = 'Open' ),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[4].Id, Facility_Name__c = acList[0].Id, Status__c = 'Open' ),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[5].Id, Facility_Name__c = acList[0].Id, Status__c = 'Open' ),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[5].Id, Facility_Name__c = acList[0].Id, Status__c = 'Open' )};
        insert amList;
        
        List<Questionnaire_Response__c> dependAnsList = new  list<Questionnaire_Response__c>{
           new Questionnaire_Response__c(Question_Template__c=quesTempList1[0].Id,Response__c='optA',Issue_Request__c=amList[1].Id,
               Weight_Response__c = 50)};
        insert dependAnsList;       
        
        ExAM_Configuration__c ec = new ExAM_Configuration__c();
        ec.Name = 'Configuration';
        ec.Decision_Tree__c = 'Response__c~Priority__c~Comment__c~Pictures';
        ec.Hours__c = 50;
        ec.Primary_Assessment_Type_Template__c = assTempList[5].Id;
        
        ec.Hide_Related_Assignment_Manager1_Tab__c = false;
        ec.Hide_Related_Assignment_Manager2_Tab__c = false;
        ec.Hide_Related_Assignment_Manager3_Tab__c = false;
        ec.Hide_Related_Assignment_Manager4_Tab__c = false;
        ec.Hide_Data_Viewer_Tab__c = false;
        ec.Hide_AM_List_Tab__c = false;
        ec.Hide_Assessable_Record_Tab__c = false;
        ec.Hide_Knowledge_Article_Tab__c = false;
        ec.Hide_Save_Button__c = false;
        ec.Overall_Status_on_Submit__c = 'Completed';
        ec.Related_Assessment_Type_1_Template__c = assTempList[1].Id;
        ec.Related_Assessment_Type_2_Template__c = assTempList[2].Id;
        ec.Related_Assessment_Type_3_Template__c = assTempList[3].Id;
        ec.Related_Assessment_Type_4_Template__c = assTempList[4].Id;
        insert ec; 
        
        System.assertEquals(7, amList.size());
    }
    public static testMethod void testMultiInspecAssessViewCtrller() {

       List<IssueRequest_Life_Cycle__c> amList = [SELECT Id,Name FROM IssueRequest_Life_Cycle__c];
       List<ExAM_Configuration__c> ec = [SELECT Id, Primary_Assessment_Type_Template__c, Hide_Related_Assignment_Manager1_Tab__c, Hide_Related_Assignment_Manager2_Tab__c, Hide_Related_Assignment_Manager3_Tab__c, Hide_Related_Assignment_Manager4_Tab__c,
           Hide_Data_Viewer_Tab__c, Hide_AM_List_Tab__c, Hide_Assessable_Record_Tab__c,Hide_Knowledge_Article_Tab__c, Hide_Save_Button__c  FROM ExAM_Configuration__c];
       List<Main_questionaire__c> asstempList = [SELECT Id,Name FROM Main_questionaire__c];
       List<Account> acList = [SELECT Id,Name FROM Account];

        ApexPages.currentPage().getParameters().put('amid', amList[0].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss = new MultipleInspectionAssessmentViewCtrller();
       
        System.assertEquals(amList[0].Id, mulInsAss.currentASMId);
        System.assertEquals(amList[0].Name, mulInsAss.currentASMNameString);
        System.assertEquals(assTempList[0].Id, mulInsAss.currentASMAssessmentTemplateId);
        System.assertEquals(false, mulInsAss.hasAnswersAvailableForUnitTemplate);
        System.assertEquals(assTempList[0].Name, mulInsAss.currentASMAssessmentTemplateName);
        System.assertEquals('', mulInsAss.template_type);
        System.assertEquals(false, mulInsAss.isRelatedAM);
        System.assertEquals(false, mulInsAss.isLensViewerTemplate);
        System.assertEquals('', mulInsAss.primaryAMListStr);
        System.assertEquals('ExAM__Facility_Name__c', mulInsAss.assessableField_API);
        System.assertEquals(ec[0].Primary_Assessment_Type_Template__c, mulInsAss.primaryTemplateId);
        System.assertEquals(ec[0].Hide_Related_Assignment_Manager1_Tab__c, mulInsAss.hideRAMTab1);
        System.assertEquals(ec[0].Hide_Related_Assignment_Manager2_Tab__c, mulInsAss.hideRAMTab2);
        System.assertEquals(ec[0].Hide_Related_Assignment_Manager3_Tab__c, mulInsAss.hideRAMTab3);
        System.assertEquals(ec[0].Hide_Related_Assignment_Manager4_Tab__c, mulInsAss.hideRAMTab4);
        System.assertEquals(ec[0].Hide_Data_Viewer_Tab__c, mulInsAss.hideDataViewerTab);
        System.assertEquals(ec[0].Hide_AM_List_Tab__c, mulInsAss.hideAMListTab);
        System.assertEquals(ec[0].Hide_Assessable_Record_Tab__c, mulInsAss.hideAssessableRecordTab);
        System.assertEquals(ec[0].Hide_Knowledge_Article_Tab__c, mulInsAss.hideKnowledgeArticleTab);
        System.assertEquals(ec[0].Hide_Save_Button__c, mulInsAss.hideSaveBtn);
    }
       
    public Static testMethod void testFetchRelatedAssignmentManagers() {
       
       List<Main_questionaire__c> asstempList = [SELECT Id,Name FROM Main_questionaire__c];
        List<IssueRequest_Life_Cycle__c> amList = [SELECT Id,name FROM IssueRequest_Life_Cycle__c];
        List<Account> acList = [SELECT Id,Name FROM Account];  
        
        //Case 1 : Launching from Unit Template
        
        ApexPages.currentPage().getParameters().put('amid', amList[5].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss5 = new MultipleInspectionAssessmentViewCtrller();
        
        System.assertEquals(amList[5].Id, mulInsAss5.currentASMId);
        System.assertEquals(amList[5].Name, mulInsAss5.currentASMNameString);
        System.assertEquals(assTempList[5].Name, mulInsAss5.currentASMAssessmentTemplateName);
        System.assertEquals('Primary_Assessment_Type', mulInsAss5.template_type);
        System.assertEquals('ExAM__Facility_Name__c', mulInsAss5.assessableField_API);
        System.assertEquals(acList[0].Id, mulInsAss5.assessableRecordId);
        System.assertEquals(acList[0].Name, mulInsAss5.assessableRecordName);
        System.assertEquals(false, mulInsAss5.isRelatedAM);
        List<IssueRequest_Life_Cycle__c> amList1 = [SELECT Id, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id]; 
        System.assertEquals(null, amList1[0].Related_Assignment_Manager1__c);
        System.assertEquals(null, amList1[0].Related_Assignment_Manager2__c);
        System.assertEquals(null, amList1[0].Related_Assignment_Manager3__c);
        System.assertEquals(null, amList1[0].Related_Assignment_Manager4__c);
        
        
        List<ExAMUtilClass.AssessableRecordsClass> assClslist = new List<ExAMUtilClass.AssessableRecordsClass>(); 
        ExAMUtilClass.AssessableRecordsClass assCls = new ExAMUtilClass.AssessableRecordsClass();
        assCls.recordId = acList[0].Id;
        assCls.recordName = acList[0].Name;
        assCls.sObjectRecord = acList[0];
        assClslist.add(assCls);
        String str = JSON.serialize(assClslist);
        
        //System.assertEquals(str , mulInsAss5.assRecClsListJSON);
        
        MultipleInspectionAssessmentViewCtrller.MultipleInspectionViewerReqdInput mIView1 = MultipleInspectionAssessmentViewCtrller.fetchRelatedAssignmentManagers(mulInsAss5.currentASMId, mulInsAss5.assessableField_API, mulInsAss5.assRecClsListJSON);
        System.assert(mIView1.examConfigurationRecord != null);
        
        List<IssueRequest_Life_Cycle__c> currentAmList = [
                SELECT CreatedDate, Facility_Name__c, Facility_Name__r.Name, Id, InvestigationType__c,
                       InvestigationType__r.Name, Name, Assignment_Manager__c, Related_Assignment_Manager1__c,
                       Related_Assignment_Manager1__r.Name, Related_Assignment_Manager2__c,
                       Related_Assignment_Manager2__r.Name, Related_Assignment_Manager3__c,
                       Related_Assignment_Manager3__r.Name, Related_Assignment_Manager4__c,
                       Related_Assignment_Manager4__r.Name
                FROM   IssueRequest_Life_Cycle__c
                ];
            
        System.assertEquals(1, mIView1.ASMListForUnitAssessmentTemplate.size());
        List<IssueRequest_Life_Cycle__c> amListForUnit = mIView1.ASMListForUnitAssessmentTemplate;
        System.assertEquals(currentAmList[5], amListForUnit[0]); 
        
        System.assertEquals(1, mIView1.ASMListForSiteAssessmentTemplate.size());
        List<IssueRequest_Life_Cycle__c> amListForSite = mIView1.ASMListForSiteAssessmentTemplate;
        System.assertEquals(currentAmList[1], amListForSite[0]); 
       
        System.assertEquals(1, mIView1.ASMListForSystemsAssessmentTemplate.size());
        List<IssueRequest_Life_Cycle__c> amListForSystem = mIView1.ASMListForSystemsAssessmentTemplate;
        System.assertEquals(currentAmList[2], amListForSystem[0]); 
        
        System.assertEquals(1, mIView1.ASMListForCommonAreasAssessmentTemplate.size());
        List<IssueRequest_Life_Cycle__c> amListForcommonArea = mIView1.ASMListForCommonAreasAssessmentTemplate;
        System.assertEquals(currentAmList[3], amListForcommonArea[0]); 
        
        System.assertEquals(1, mIView1.ASMListForExteriorAssessmentTemplate.size());
        List<IssueRequest_Life_Cycle__c> amListForExterior = mIView1.ASMListForExteriorAssessmentTemplate;
        System.assertEquals(currentAmList[4], amListForExterior[0]);
        
        System.assertEquals('', mIView1.exceptionMsg); 
        System.assert(mIView1.examConfigurationRecord != null);
    }
    
    //Case 2: Create New AM
    public static testMethod void testCreateNewAMLaunchedFromPrimaryAM() {
        
        List<Main_questionaire__c> asstempList = [SELECT Id,Name FROM Main_questionaire__c];
        List<IssueRequest_Life_Cycle__c> amList = [SELECT Id, Name FROM IssueRequest_Life_Cycle__c];
        List<Account> acList = [SELECT Id,Name FROM Account]; 
        List<ExAM_Configuration__c> ec = [SELECT Id, Primary_Assessment_Type_Template__c, Hide_Related_Assignment_Manager1_Tab__c, Hide_Related_Assignment_Manager2_Tab__c, Hide_Related_Assignment_Manager3_Tab__c, Hide_Related_Assignment_Manager4_Tab__c,
           Hide_Data_Viewer_Tab__c, Hide_AM_List_Tab__c, Hide_Assessable_Record_Tab__c,Hide_Knowledge_Article_Tab__c, Hide_Save_Button__c  FROM ExAM_Configuration__c];   
    //Case 2(a) : Launch from Site
        
        ApexPages.currentPage().getParameters().put('amid', amList[1].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss6 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[1].Id, mulInsAss6.currentASMId);
        System.assertEquals(ec[0].Primary_Assessment_Type_Template__c, mulInsAss6.primaryTemplateId);
        System.assertEquals(assTempList[1].Id, mulInsAss6.currentASMAssessmentTemplateId);
        System.assertEquals(acList[0].Id, mulInsAss6.assessableRecordId);
        
        List<String> strList1 = new List<String> {amList[5].Id, mulInsAss6.assessableRecordId, mulInsAss6.currentASMAssessmentTemplateId, System.Label.Related_Assessment_Type_1,'Facility_Name__c' };
        String str4 = JSON.serialize(strList1);
        String str4a = MultipleInspectionAssessmentViewCtrller.createNewAssignmentManager(str4);
        MultipleInspectionAssessmentViewCtrller.SuccessClass retStr3 = (MultipleInspectionAssessmentViewCtrller.SuccessClass) JSON.deserialize(str4a, MultipleInspectionAssessmentViewCtrller.SuccessClass.class); 
        String rec3 = retstr3.msg;
        IssueRequest_Life_Cycle__c newManagerRecord3 =(IssueRequest_Life_Cycle__c) JSON.deserialize(rec3, IssueRequest_Life_Cycle__c.class);
        List<IssueRequest_Life_Cycle__c> amList2 = [SELECT Id, InvestigationType__c, Facility_Name__c, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id];
        
        System.assertEquals(newManagerRecord3.Id, amList2[0].Related_Assignment_Manager1__c); 
        System.assertEquals(asstempList[1].Id,newManagerRecord3.InvestigationType__c); 
        System.assertEquals('success', retstr3.code); 
        
        //Case 2(b) : Launch from System
        
        ApexPages.currentPage().getParameters().put('amid', amList[2].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss7 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[2].Id, mulInsAss7.currentASMId);
        System.assertEquals(ec[0].Primary_Assessment_Type_Template__c, mulInsAss7.primaryTemplateId);
        System.assertEquals(assTempList[2].Id, mulInsAss7.currentASMAssessmentTemplateId);
        System.assertEquals(acList[0].Id, mulInsAss7.assessableRecordId);
        
        List<String> strList2 = new List<String> {amList[5].Id, mulInsAss7.assessableRecordId, mulInsAss7.currentASMAssessmentTemplateId, System.Label.Related_Assessment_Type_2,'Facility_Name__c' };
        String str3 = JSON.serialize(strList2);
        String str3a = MultipleInspectionAssessmentViewCtrller.createNewAssignmentManager(str3);
        MultipleInspectionAssessmentViewCtrller.SuccessClass retStr2 = (MultipleInspectionAssessmentViewCtrller.SuccessClass) JSON.deserialize(str3a, MultipleInspectionAssessmentViewCtrller.SuccessClass.class); 
        String rec2 = retstr2.msg;
        IssueRequest_Life_Cycle__c newManagerRecord2 =(IssueRequest_Life_Cycle__c) JSON.deserialize(rec2, IssueRequest_Life_Cycle__c.class);
        List<IssueRequest_Life_Cycle__c> amList3 = [SELECT Id, InvestigationType__c, Facility_Name__c, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id];
        
        System.assertEquals(newManagerRecord2.Id, amList3[0].Related_Assignment_Manager2__c); 
        System.assertEquals(asstempList[2].Id,newManagerRecord2.InvestigationType__c); 
        System.assertEquals('success', retstr2.code); 

                
        //Case 2(c) : Launch from Common Area
        
        ApexPages.currentPage().getParameters().put('amid', amList[3].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss8 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[3].Id, mulInsAss8.currentASMId);
        System.assertEquals(ec[0].Primary_Assessment_Type_Template__c, mulInsAss8.primaryTemplateId);
        System.assertEquals(assTempList[3].Id, mulInsAss8.currentASMAssessmentTemplateId);
        System.assertEquals(acList[0].Id, mulInsAss8.assessableRecordId);
        
        List<String> strList3 = new List<String> {amList[5].Id, mulInsAss8.assessableRecordId, mulInsAss8.currentASMAssessmentTemplateId, System.Label.Related_Assessment_Type_3,'Facility_Name__c' };
        String str2 = JSON.serialize(strList3);
        String str2a = MultipleInspectionAssessmentViewCtrller.createNewAssignmentManager(str2);
        MultipleInspectionAssessmentViewCtrller.SuccessClass retStr1 = (MultipleInspectionAssessmentViewCtrller.SuccessClass) JSON.deserialize(str2a, MultipleInspectionAssessmentViewCtrller.SuccessClass.class); 
        String rec1 = retstr1.msg;
        IssueRequest_Life_Cycle__c newManagerRecord1 =(IssueRequest_Life_Cycle__c) JSON.deserialize(rec1, IssueRequest_Life_Cycle__c.class);
        List<IssueRequest_Life_Cycle__c> amList4 = [SELECT Id, InvestigationType__c, Facility_Name__c, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id];
       
        System.assertEquals(newManagerRecord1.Id, amList4[0].Related_Assignment_Manager3__c); 
        System.assertEquals(asstempList[3].Id,newManagerRecord1.InvestigationType__c); 
        System.assertEquals('success', retstr1.code); 
       
        //Case 2(d) : Launch From Exterior
        
        ApexPages.currentPage().getParameters().put('amid', amList[4].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss9 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[4].Id, mulInsAss9.currentASMId);
        System.assertEquals(ec[0].Primary_Assessment_Type_Template__c, mulInsAss9.primaryTemplateId);
        System.assertEquals(assTempList[4].Id, mulInsAss9.currentASMAssessmentTemplateId);
        System.assertEquals(acList[0].Id, mulInsAss9.assessableRecordId);
        
        List<String> strList4 = new List<String> {amList[5].Id, mulInsAss9.assessableRecordId, mulInsAss9.currentASMAssessmentTemplateId, System.Label.Related_Assessment_Type_4,'Facility_Name__c' };
        String str1a = JSON.serialize(strList4);
        String str1 = MultipleInspectionAssessmentViewCtrller.createNewAssignmentManager(str1a);
        MultipleInspectionAssessmentViewCtrller.SuccessClass retStr = (MultipleInspectionAssessmentViewCtrller.SuccessClass) JSON.deserialize(str1, MultipleInspectionAssessmentViewCtrller.SuccessClass.class); 
        String rec = retstr.msg;
        IssueRequest_Life_Cycle__c newManagerRecord =(IssueRequest_Life_Cycle__c) JSON.deserialize(rec, IssueRequest_Life_Cycle__c.class);
        List<IssueRequest_Life_Cycle__c> amList5 = [SELECT Id, InvestigationType__c, Facility_Name__c, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id];
        System.assertEquals(newManagerRecord.Id, amList5[0].Related_Assignment_Manager4__c); 
        System.assertEquals(asstempList[4].Id,newManagerRecord.InvestigationType__c); 
        System.assertEquals('success', retstr.code); 
    }
    
    //Case 3(a): Launched from related AM(Site,System,Common Area,Exterior) to link Primary AM - Proceed with existing record
    public static testMethod void testlinkCurrentAMwithPrimaryAM() { 
        
        List<Main_questionaire__c> asstempList = [SELECT Id, Name FROM Main_questionaire__c];
        List<IssueRequest_Life_Cycle__c> amList = [SELECT Id, Name FROM IssueRequest_Life_Cycle__c];
        List<Account> acList = [SELECT Id,Name FROM Account];    
        
        //case3a(i):launch from site
        
        List<IssueRequest_Life_Cycle__c> UnitTempList = [
                SELECT CreatedDate, Facility_Name__c, Facility_Name__r.Name, Id, InvestigationType__c,
                       InvestigationType__r.Name, Name, Assignment_Manager__c, Related_Assignment_Manager1__c,
                       Related_Assignment_Manager1__r.Name, Related_Assignment_Manager2__c,
                       Related_Assignment_Manager2__r.Name, Related_Assignment_Manager3__c,
                       Related_Assignment_Manager3__r.Name, Related_Assignment_Manager4__c,
                       Related_Assignment_Manager4__r.Name
                FROM   IssueRequest_Life_Cycle__c WHERE Id = : amList[5].Id];
                
        UnitTempList[0].Related_Assignment_Manager1__c = amList[1].Id;
        UnitTempList[0].Related_Assignment_Manager2__c = null;
        UnitTempList[0].Related_Assignment_Manager3__c = null;
        UnitTempList[0].Related_Assignment_Manager4__c = null;
        update UnitTempList;
        
        ApexPages.currentPage().getParameters().put('amid', amList[1].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss6 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[1].Id, mulInsAss6.currentASMId);
        List<IssueRequest_Life_Cycle__c> childAssignmentManagersList = (List<IssueRequest_Life_Cycle__c> )JSON.deserialize(mulInsAss6.primaryAMListStr, List<IssueRequest_Life_Cycle__c>.class);
        String Id = childAssignmentManagersList[0].Id;
        System.assertEquals(amList[5].Id, Id);
        
        List<String> strList = new list<String>();
            strList.add(Id);
            strList.add(mulInsAss6.currentASMId);
            strList.add('Site Demo');
            
            String stra = JSON.serialize(strList);
            String retStra =  MultipleInspectionAssessmentViewCtrller.linkSelectedASMWithCurrentAssignmentManager(stra);//It simply redirects the page.
        
            MultipleInspectionAssessmentViewCtrller.SuccessClass suc = (MultipleInspectionAssessmentViewCtrller.SuccessClass)JSON.deserialize(retStra, MultipleInspectionAssessmentViewCtrller.SuccessClass.class);
            List<IssueRequest_Life_Cycle__c> amList6 = [SELECT Id, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id]; 
            System.assertEquals(amList[1].id,amList6[0].Related_Assignment_Manager1__c); 
            System.assertEquals('success', suc.code);
            System.assertEquals('Related Assignment of this assignment manager updated successfully', suc.msg);
            
    // case3a(ii) :launch from System
    
        UnitTempList[0].Related_Assignment_Manager1__c = null;
        UnitTempList[0].Related_Assignment_Manager2__c = amList[2].Id;
        UnitTempList[0].Related_Assignment_Manager3__c = null;
        UnitTempList[0].Related_Assignment_Manager4__c = null;
        update UnitTempList;
        
        ApexPages.currentPage().getParameters().put('amid', amList[2].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss7 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[2].Id, mulInsAss7.currentASMId);
        List<IssueRequest_Life_Cycle__c> childAssignmentManagersList1 = (List<IssueRequest_Life_Cycle__c> )JSON.deserialize(mulInsAss7.primaryAMListStr, List<IssueRequest_Life_Cycle__c>.class);
        String Id1 = childAssignmentManagersList1[0].Id;
        System.assertEquals(amList[5].Id, Id1);
        
        List<String> strList1a = new list<String> {Id1, mulInsAss7.currentASMId, 'Systems'};
        String str1b = JSON.serialize(strList1a);
        String retStr1a =  MultipleInspectionAssessmentViewCtrller.linkSelectedASMWithCurrentAssignmentManager(str1b);
        
        MultipleInspectionAssessmentViewCtrller.SuccessClass suc1 = (MultipleInspectionAssessmentViewCtrller.SuccessClass)JSON.deserialize(retStr1a, MultipleInspectionAssessmentViewCtrller.SuccessClass.class);
        List<IssueRequest_Life_Cycle__c> amList7 = [SELECT Id, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id]; 
        System.assertEquals(amList[2].id,amList7[0].Related_Assignment_Manager2__c); 
        System.assertEquals('success', suc1.code);
        System.assertEquals( 'Related Assignment of this assignment manager updated successfully', suc1.msg);
        
        // case3a(iii) : Launch From Common Area
        
        UnitTempList[0].Related_Assignment_Manager1__c = null;
        UnitTempList[0].Related_Assignment_Manager2__c = null;
        UnitTempList[0].Related_Assignment_Manager3__c = amList[3].Id;
        UnitTempList[0].Related_Assignment_Manager4__c = null;
        update UnitTempList;
        
        ApexPages.currentPage().getParameters().put('amid', amList[3].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss8 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[3].Id, mulInsAss8.currentASMId);
        List<IssueRequest_Life_Cycle__c> childAssignmentManagersList2 = (List<IssueRequest_Life_Cycle__c> )JSON.deserialize(mulInsAss8.primaryAMListStr, List<IssueRequest_Life_Cycle__c>.class);
        String Id2 = childAssignmentManagersList2[0].Id;
        System.assertEquals(amList[5].Id, Id2);
        
        List<String> strList2a = new list<String> {Id2, mulInsAss8.currentASMId, 'Common Areas'};
        String str2b = JSON.serialize(strList2a);
        String retStr2a =  MultipleInspectionAssessmentViewCtrller.linkSelectedASMWithCurrentAssignmentManager(str2b);
        
        MultipleInspectionAssessmentViewCtrller.SuccessClass suc2 = (MultipleInspectionAssessmentViewCtrller.SuccessClass)JSON.deserialize(retStr2a, MultipleInspectionAssessmentViewCtrller.SuccessClass.class);
        List<IssueRequest_Life_Cycle__c> amList8 = [SELECT Id, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id]; 
        System.assertEquals(amList[3].id,amList8[0].Related_Assignment_Manager3__c); 
        System.assertEquals('success', suc2.code);
        System.assertEquals( 'Related Assignment of this assignment manager updated successfully', suc2.msg);
        
        //case3a(iv) : Launch From Exterior
        
        UnitTempList[0].Related_Assignment_Manager1__c = null;
        UnitTempList[0].Related_Assignment_Manager2__c = null;
        UnitTempList[0].Related_Assignment_Manager3__c = null;
        UnitTempList[0].Related_Assignment_Manager4__c = amList[4].Id;
        update UnitTempList;
        
        ApexPages.currentPage().getParameters().put('amid', amList[4].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss9 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[4].Id, mulInsAss9.currentASMId);
        List<IssueRequest_Life_Cycle__c> childAssignmentManagersList3 = (List<IssueRequest_Life_Cycle__c> )JSON.deserialize(mulInsAss9.primaryAMListStr, List<IssueRequest_Life_Cycle__c>.class);
        String Id3 = childAssignmentManagersList3[0].Id;
        System.assertEquals(amList[5].Id, Id3);
        
        List<String> strList3a = new list<String> {Id3, mulInsAss9.currentASMId, 'Exterior'};
        String str3b = JSON.serialize(strList3a);
        String retStr3a =  MultipleInspectionAssessmentViewCtrller.linkSelectedASMWithCurrentAssignmentManager(str3b);
        
        MultipleInspectionAssessmentViewCtrller.SuccessClass suc3 = (MultipleInspectionAssessmentViewCtrller.SuccessClass)JSON.deserialize(retStr3a, MultipleInspectionAssessmentViewCtrller.SuccessClass.class);
        List<IssueRequest_Life_Cycle__c> amList9 = [SELECT Id, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :amList[5].Id]; 
        System.assertEquals(amList[4].id,amList9[0].Related_Assignment_Manager4__c); 
        System.assertEquals('success', suc3.code);
        System.assertEquals( 'Related Assignment of this assignment manager updated successfully', suc3.msg);
        
    }
    //case 3(b): Launched from related AM(Site,System,Common Area,Exterior) to link Primary AM - Create New Primary AM
    public static testMethod void testCreateNewPrimaryAM() { 
    
        List<Main_questionaire__c> asstempList = [SELECT Id, Name FROM Main_questionaire__c];
        List<IssueRequest_Life_Cycle__c> amList = [SELECT Id, Name FROM IssueRequest_Life_Cycle__c];
        List<Account> acList = [SELECT Id,Name FROM Account];    
        List<IssueRequest_Life_Cycle__c> UnitTempList = [
                SELECT CreatedDate, Facility_Name__c, Facility_Name__r.Name, Id, InvestigationType__c,
                       InvestigationType__r.Name, Name, Assignment_Manager__c, Related_Assignment_Manager1__c,
                       Related_Assignment_Manager1__r.Name, Related_Assignment_Manager2__c,
                       Related_Assignment_Manager2__r.Name, Related_Assignment_Manager3__c,
                       Related_Assignment_Manager3__r.Name, Related_Assignment_Manager4__c,
                       Related_Assignment_Manager4__r.Name
                FROM   IssueRequest_Life_Cycle__c WHERE Id = : amList[5].Id];
              
        UnitTempList[0].Related_Assignment_Manager1__c = null;
        UnitTempList[0].Related_Assignment_Manager2__c = null;
        UnitTempList[0].Related_Assignment_Manager3__c = null;
        UnitTempList[0].Related_Assignment_Manager4__c = null;
        update UnitTempList;
        
        // case 3b(i): Launch from unit
        ApexPages.currentPage().getParameters().put('amid', amList[1].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss10 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[1].Id, mulInsAss10.currentASMId);
        System.assertEquals('', mulInsAss10.primaryAMListStr);
        System.assertEquals(acList[0].Id, mulInsAss10.assessableRecordId);
        System.assertEquals(acList[0].Name, mulInsAss10.assessableRecordName);
        System.assertEquals('ExAM__Facility_Name__c', mulInsAss10.assessableField_API);
        
        String str5 = MultipleInspectionAssessmentViewCtrller.createNewPrimaryAM(asstempList[5].Id, 'Related_Assessment_Type_1',mulInsAss10.currentASMId, mulInsAss10.assessableField_API, mulInsAss10.assessableRecordId ); 
        MultipleInspectionAssessmentViewCtrller.SuccessClass retStr4 = (MultipleInspectionAssessmentViewCtrller.SuccessClass) JSON.deserialize(str5, MultipleInspectionAssessmentViewCtrller.SuccessClass.class); 
        String newAmId = retStr4.msg;
        List<IssueRequest_Life_Cycle__c> amList10 = [SELECT Id, InvestigationType__c, Facility_Name__c, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :newAmId];
        
        System.assertEquals(amList[1].Id, amList10[0].Related_Assignment_Manager1__c);
        System.assertEquals(asstempList[5].Id,amList10[0].InvestigationType__c); 
        System.assertEquals(mulInsAss10.assessableRecordId,amList10[0].Facility_Name__c); 
        
        //case 3b(ii): System
       
        UnitTempList[0].Related_Assignment_Manager1__c = null;
        UnitTempList[0].Related_Assignment_Manager2__c = null;
        UnitTempList[0].Related_Assignment_Manager3__c = null;
        UnitTempList[0].Related_Assignment_Manager4__c = null;
        update UnitTempList;
        
        ApexPages.currentPage().getParameters().put('amid', amList[2].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss11 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[2].Id, mulInsAss11.currentASMId);
        System.assertEquals('', mulInsAss11.primaryAMListStr);
        System.assertEquals(acList[0].Id, mulInsAss11.assessableRecordId);
        System.assertEquals(acList[0].Name, mulInsAss11.assessableRecordName);
        System.assertEquals('ExAM__Facility_Name__c', mulInsAss11.assessableField_API);
        
        String str6 = MultipleInspectionAssessmentViewCtrller.createNewPrimaryAM(asstempList[5].Id, 'Related_Assessment_Type_2',mulInsAss11.currentASMId, mulInsAss11.assessableField_API, mulInsAss11.assessableRecordId ); 
        MultipleInspectionAssessmentViewCtrller.SuccessClass retStr5 = (MultipleInspectionAssessmentViewCtrller.SuccessClass) JSON.deserialize(str6, MultipleInspectionAssessmentViewCtrller.SuccessClass.class); 
        String newAmId1 = retStr5.msg;
        List<IssueRequest_Life_Cycle__c> amList11 = [SELECT Id, InvestigationType__c,  Facility_Name__c, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :newAmId1];
        
        System.assertEquals(amList[2].Id, amList11[0].Related_Assignment_Manager2__c);
        System.assertEquals(asstempList[5].Id,amList11[0].InvestigationType__c); 
        System.assertEquals(mulInsAss11.assessableRecordId,amList11[0].Facility_Name__c); 
        
        //case 3b(iii) common Area
        
        ApexPages.currentPage().getParameters().put('amid', amList[3].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss12 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[3].Id, mulInsAss12.currentASMId);
        System.assertEquals('', mulInsAss12.primaryAMListStr);
        System.assertEquals(acList[0].Id, mulInsAss12.assessableRecordId);
        System.assertEquals(acList[0].Name, mulInsAss12.assessableRecordName);
        System.assertEquals('ExAM__Facility_Name__c', mulInsAss12.assessableField_API);
        
        String str7 = MultipleInspectionAssessmentViewCtrller.createNewPrimaryAM(asstempList[5].Id, 'Related_Assessment_Type_3',mulInsAss12.currentASMId, mulInsAss12.assessableField_API, mulInsAss12.assessableRecordId ); 
        MultipleInspectionAssessmentViewCtrller.SuccessClass retStr6 = (MultipleInspectionAssessmentViewCtrller.SuccessClass) JSON.deserialize(str7, MultipleInspectionAssessmentViewCtrller.SuccessClass.class); 
        String newAmId2 = retStr6.msg;
        List<IssueRequest_Life_Cycle__c> amList12 = [SELECT Id, InvestigationType__c, Facility_Name__c, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :newAmId2];
        
        System.assertEquals(amList[3].Id, amList12[0].Related_Assignment_Manager3__c);
        System.assertEquals(asstempList[5].Id,amList12[0].InvestigationType__c); 
        System.assertEquals(mulInsAss12.assessableRecordId,amList12[0].Facility_Name__c);  
        
        //case 3b(iv) Exterior
        ApexPages.currentPage().getParameters().put('amid', amList[4].Id);
        MultipleInspectionAssessmentViewCtrller  mulInsAss13 = new MultipleInspectionAssessmentViewCtrller();
        System.assertEquals(amList[4].Id, mulInsAss13.currentASMId);
        System.assertEquals('', mulInsAss13.primaryAMListStr);
        System.assertEquals(acList[0].Id, mulInsAss13.assessableRecordId);
        System.assertEquals(acList[0].Name, mulInsAss13.assessableRecordName);
        System.assertEquals('ExAM__Facility_Name__c', mulInsAss13.assessableField_API);
        
        String str8 = MultipleInspectionAssessmentViewCtrller.createNewPrimaryAM(asstempList[5].Id, 'Related_Assessment_Type_4',mulInsAss13.currentASMId, mulInsAss13.assessableField_API, mulInsAss13.assessableRecordId ); 
        MultipleInspectionAssessmentViewCtrller.SuccessClass retStr7 = (MultipleInspectionAssessmentViewCtrller.SuccessClass) JSON.deserialize(str8, MultipleInspectionAssessmentViewCtrller.SuccessClass.class); 
        String newAmId3 = retStr7.msg;
        List<IssueRequest_Life_Cycle__c> amList13 = [SELECT Id, InvestigationType__c, Facility_Name__c, Related_Assignment_Manager1__c, Related_Assignment_Manager2__c, Related_Assignment_Manager3__c, Related_Assignment_Manager4__c FROM IssueRequest_Life_Cycle__c WHERE Id = :newAmId3];
        
        System.assertEquals(amList[4].Id, amList13[0].Related_Assignment_Manager4__c);
        System.assertEquals(asstempList[5].Id,amList13[0].InvestigationType__c); 
        System.assertEquals(mulInsAss13.assessableRecordId,amList13[0].Facility_Name__c);  
    }
}