src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>One_Time_Assessment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Z-One Time Assessment (DO NOT USE)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree Result Page Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>One_Time_Assessment__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When One Time Assessment is checked answered provided during a previous submission will be displayed in the viewer. Without it checked they will not see any previously submitted answers and new answers can be added.</inlineHelpText>
        <label>One Time Assessment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewer_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enables you select a specific configuration of the Standard Viewer to be used for the specified Assessment Template. You can create Standard Viewer configurations that include or exclude specific tabs in the ExAM Configuration tab.</inlineHelpText>
        <label>Viewer Configuration</label>
        <referenceTo>Viewer_Custom_Configuration__c</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Assessment_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree Result Page Fields Default</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAssessmentViewerController.cls
@isTest 
public class TestAssessmentViewerController {
    @testSetup
    public static void testSetUp() {
        
        List<Account> aclist = new List<Account> {
                               new Account(Name = 'TestAcc1')};
        insert acList;
        
        Viewer_Custom_Configuration__c viewerRec = new Viewer_Custom_Configuration__c();
        insert viewerRec;  
        
        List<Main_questionaire__c> asstempList = new List<Main_questionaire__c> {
                                                 new Main_questionaire__c (Template_name__c = 'Unit Template',Viewer_Configuration__c = viewerRec.Id, 
                                                     Decision_Tree__c = 'Pictures:true:false:1~External_Id__c:false:false:2~Priority__c:true:false:3~Comment__c:true:false:4~Response__c:true:false:5~Test_text_field__c:true:false:6~deficiency_status__c:true:false:7', One_Time_Assessment__c = true)};
        insert asstempList;
         
        List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c>{
                                                  new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[0].Id, Facility_Name__c = acList[0].Id, Status__c = 'Open' )};
        insert amList;
        
        List<Section_Template__c> secTempList = new List<Section_Template__c>{
                                                new Section_Template__c(Questionnaire_Section__c = asstempList[0].id, Section_label__c = 'UT Section')};
        insert secTempList;
        
        List<Question_Template__c> quesTempList = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Test Question4', Question_Order_No__c = 1,
                Question_Type__c = 'Text',Subquestion_Label__c='optD1~optD2',Weight_of_Answer__c ='100~50', Is_Dependent__c = false),
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Test Question4', Question_Order_No__c = 2,
                Question_Type__c = 'Text',Subquestion_Label__c='optD1~optD2',Weight_of_Answer__c ='100~50', Is_Dependent__c = false),
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Test Question4', Question_Order_No__c = 3,
                Question_Type__c = 'Text',Subquestion_Label__c='optD1~optD2',Weight_of_Answer__c ='100~50', Is_Dependent__c = false)};
       insert quesTempList;
        
        List<Question_Template__c> quesTempList1 = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Test Question4', Question_Order_No__c = 4,
                Question_Type__c = 'Text',Subquestion_Label__c='optD1~optD2',Weight_of_Answer__c ='100~50', Is_Dependent__c = false,Single_Next_Question__c = quesTempList[0].Id),
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Test Question4', Question_Order_No__c = 5,
                Question_Type__c = 'Email',Subquestion_Label__c='optD1~optD2',Weight_of_Answer__c ='100~50', Is_Dependent__c = false, Next_Question__c = 'What is ur code coverage'),
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Test Question4', Question_Order_No__c = 6,
                Question_Type__c = 'RadioPicklist',Subquestion_Label__c='optD1~optD2',Weight_of_Answer__c ='100~50', Is_Dependent__c = false, Next_Question__c = '~What is ur code coverage'),
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Test Question4', Question_Order_No__c = 7,
                Question_Type__c = 'Image',Subquestion_Label__c='optD1~optD2',Weight_of_Answer__c ='100~50', Is_Dependent__c = false)};
        insert quesTempList1;
                
        List<Answer_Option__c> ansoptions1 = new List<Answer_Option__c> {
                                             new Answer_Option__c(Question_Template__c = quesTempList1[3].Id, Order_No__c = 1, Name = 'optA', Weight__c = 50, Next_Question__c = quesTempList[1].Id ), 
                                             new Answer_Option__c(Question_Template__c = quesTempList1[3].Id, Order_No__c = 2, Name = 'optB', Weight__c = 50, Next_Question__c = quesTempList[2].Id )};
        insert ansoptions1;
       
        List<Attachment> attachList = new List<Attachment> {
            new Attachment(ParentId = quesTempList1[3].Id, ContentType = 'Image', Name = String.valueof('Question-image'), Body = Blob.valueof('attached')),
            new Attachment(ParentId = quesTempList1[0].Id, ContentType = 'Image', Name = String.valueof('Question-image'), Body = Blob.valueof('attached')),
            new Attachment(ParentId = assTempList[0].Id, ContentType = 'Image', Name = String.valueof('banner'), Body = Blob.valueof('attached'))};
       insert attachList;               
    }
    public static testMethod void testAssessmentViewerController() {
        String selectedViewerConfigJSON = '';
        Boolean Show_Configuration_Options_in_Viewer = false;
        Boolean show_Question_Name_on_Decision_Tree = false;
        
        List<Main_questionaire__c> asstempList = [SELECT Id FROM Main_questionaire__c];
        List<IssueRequest_Life_Cycle__c> amList = [SELECT Id, Name, Facility_Name__c, Status__c, InvestigationType__c, Assessment_Form_Completion__c,
                                                     Assessment_Date_Time__c, Show_Configuration_Options_in_Viewer__c 
                                                     FROM IssueRequest_Life_Cycle__c];
        List<Viewer_Custom_Configuration__c> vccList = [SELECT Id, Answer_Options__c, Data_Management__c, Hierarchical_Object__c, Single_Question_Mode__c, Assignment_Manager__c, Assignment_Manager_List__c 
                                                          FROM Viewer_Custom_Configuration__c];
        
        Show_Configuration_Options_in_Viewer = amList[0].Show_Configuration_Options_in_Viewer__c;
        
        Admin_Configuration__c adminConf = Admin_Configuration__c.getInstance(UserInfo.getUserId());
        if ( adminConf != null && adminConf.Show_Question_Name_on_Decision_Tree__c != null ) {
            show_Question_Name_on_Decision_Tree = adminConf.Show_Question_Name_on_Decision_Tree__c;
        }
        
        List<Attachment> attList = [SELECT Id FROM Attachment WHERE Name like 'banner%' AND ParentId = :asstempList[0].Id LIMIT 1];
        String bannerId = attList[0].Id;
        apexPages.currentPage().getParameters().put('amid',amList[0].Id);
        apexPages.currentPage().getParameters().put('asstempid',asstempList[0].Id);
        AssessmentViewerController avc = new AssessmentViewerController();
        Viewer_Custom_Configuration__c view1 = (Viewer_Custom_Configuration__c)JSON.deserialize(avc.selectedViewerConfigJSON, Viewer_Custom_Configuration__c.class);
        
        System.debug('::avc.selectedViewerConfigJSON::'+avc.selectedViewerConfigJSON);
        System.assertEquals(vccList[0].Id, view1.Id); 
        System.assert(avc.selectedViewerConfigJSON != null);
        selectedViewerConfigJSON = JSON.serialize(vccList[0]);
        
        List<ExAMUtilClass.AssessableRecordsClass> AssessableRecords = new List<ExAMUtilClass.AssessableRecordsClass>();
        Boolean hasAssessableObj = false;
        AssessableRecords = ExAMUtilClass.getAssessableRecords(amList, true);
        if( AssessableRecords != null && AssessableRecords.size() > 0 ){
            hasAssessableObj = true;
        }
        
        String hierarchicalListJSON = JSON.serialize( AssessableRecords );
        system.assertEquals(avc.hierarchicalListJSON ,hierarchicalListJSON);
        system.assertEquals(avc.hasAssessableObj ,hasAssessableObj);
        system.assertEquals(avc.bannerId ,bannerId);
        system.assertEquals(avc.selectedViewerConfigJSON ,selectedViewerConfigJSON);
        system.assertEquals(avc.Show_Configuration_Options_in_Viewer ,Show_Configuration_Options_in_Viewer); 
        system.assertEquals(avc.show_Question_Name_on_Decision_Tree ,show_Question_Name_on_Decision_Tree);
     }
}