src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessment_Date_Time__c</fullName>
        <label>Assessment Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Assessment_Form_Completion__c</fullName>
        <inlineHelpText>The for the team needs to fill for each investigation type</inlineHelpText>
        <label>Assessment Form Completion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Date_Assigned__c</fullName>
        <defaultValue>Now()</defaultValue>
        <inlineHelpText>The date and time the Assignment Manager was created.</inlineHelpText>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <inlineHelpText>Use this field to support additional metadata and reporting requirements around assessed accounts.</inlineHelpText>
        <label>Account Classification</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>School</fullName>
                </value>
                <value>
                    <fullName>Administrative</fullName>
                </value>
                <value>
                    <fullName>Parking Lot</fullName>
                </value>
                <value>
                    <fullName>Playground</fullName>
                </value>
                <value>
                    <fullName>Park</fullName>
                </value>
                <value>
                    <fullName>Learning Area</fullName>
                </value>
                <value>
                    <fullName>Multiple Rooms</fullName>
                </value>
                <value>
                    <fullName>Office Area</fullName>
                </value>
                <value>
                    <fullName>Unclassified</fullName>
                </value>
                <value>
                    <fullName>All</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The accounts for vendors, partners and other service providers that you may need in order to accomplish your assignments.</inlineHelpText>
        <label>Service Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager List (Service Organization)</relationshipLabel>
        <relationshipName>Assignment_Manager_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Services_Required__c</fullName>
        <inlineHelpText>Use this field to provide additional metadata around the assessment being performed.</inlineHelpText>
        <label>Assessment Classification</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual/Routine</fullName>
                </value>
                <value>
                    <fullName>Complaint Investigation</fullName>
                </value>
                <value>
                    <fullName>Re-inspection</fullName>
                </value>
                <value>
                    <fullName>2nd re-inspection</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>Call In</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Asbestos</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Mold</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Waste</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Site Contact</inlineHelpText>
        <label>Site Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Issue_Request_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAssignmentManagerDetailController.cls
@isTest 
public class TestAssignmentManagerDetailController {
    static testMethod void method1() {
                
        Account acc = new Account();
        acc.Name ='TestAcc';
        insert acc;
        
        contact con = new contact();
        con.AccountId=acc.id;
        con.LastName ='testCon';
        insert con;
        
        Main_questionaire__c asstemp = new Main_questionaire__c();
        asstemp.Template_name__c = 'testTemplate';
        insert asstemp;
        
        IssueRequest_Life_Cycle__c am = new IssueRequest_Life_Cycle__c();
        am.Facility_Name__c = acc.id;
        am.Site_Contact__c = con.id;
        am.Date_Assigned__c = system.today();
        am.Status__c='open';
        am.Priority__c = 'high';
        am.InvestigationType__c =asstemp.id;
        am.Assessment_Form_Completion__c = 'complete';
        am.Assessment_Date_Time__c = system.today();
        am.Location__c ='testloc';
        am.Services_Required__c = 'fitness';
        am.Service_Organization__c =acc.id;
        insert am;
        
        List<IssueRequest_Life_Cycle__c> amList = [Select Id from IssueRequest_Life_Cycle__c]; 
        System.assertEquals(1,amList.size());
       
        ApexPages.currentPage().getParameters().put('amid', am.id);
        
        AssignmentManagerDetailController amd = new AssignmentManagerDetailController();
        
    }
}