src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessment_Template_Type__c</fullName>
        <formula>if((InvestigationType__c==&apos;&apos;),&apos;&apos;, InvestigationType__r.Template_name__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The name of the Assessment Template in use by the Assignment Manager.</inlineHelpText>
        <label>Assessment Template Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Date__c</fullName>
        <inlineHelpText>This is the date and time that the Assignment is scheduled to take place.</inlineHelpText>
        <label>Scheduled Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Report_Builder_Configuration__c.object
<CustomObject>
    <description>Used to support individual report configurations so that ExAM reports can be saved for future use.</description>
    <fields>
        <fullName>Assessable_Object_Field_Position__c</fullName>
        <label>Assessable Object Field Position</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assessment_Data_Config__c</fullName>
        <label>Assessment Data Config</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Report Builder Configurations</relationshipLabel>
        <relationshipName>Report_Builder_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Manager_position__c</fullName>
        <label>Assignment Manager position</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Choosed_Assignment_manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Choosed Assignment manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Report Builder Configurations</relationshipLabel>
        <relationshipName>Report_Builder_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Range__c</fullName>
        <label>End Date Range</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Temporary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Temporary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Output_Format__c</fullName>
        <label>Output Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PDF</fullName>
                </value>
                <value>
                    <fullName>HTML</fullName>
                </value>
                <value>
                    <fullName>JSON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Overall_Status__c</fullName>
        <label>Overall Status</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Sections__c</fullName>
        <label>Selected Sections</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date_Range__c</fullName>
        <label>Start Date Range</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Report Builder Configuration</label>
    <nameField>
        <label>Report Builder Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Builder Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReportBuilderConfigController.cls
public with sharing class ReportBuilderConfigController {
    
    public String savedReportsJSON { get; set; }
    public String assessmentTemplateJSON { get; set; }
    public String reportBuilderListJSON { get; set; }
    public String amPositionJSON { get; set; }
    public String dataConfigJSON { get; set; }
    public String assessibleFieldDetailsJSON { get; set; }
    
    public String assObswithFieldsJSON { get; set; }

    public class assignmentManagerPositionCls {
        public String apiName;
        public String labelName;
        public Integer position;
        public assignmentManagerPositionCls(String api1, String label1, Integer position1) {
            apiName = api1;
            labelName = label1;
            position = position1;
        } 
    }
    
    //Start Assessable Object field select functionality.
    public class assessableObjFieldPositionCls {
        public String apiName;
        public String labelName;
        public Integer position;
        public assessableObjFieldPositionCls(String api1, String label1, Integer position1) {
            apiName = api1;
            labelName = label1;
            position = position1;
        } 
    }

    public List<assessableobjectwithFieldsClass> assessableObjNamewithFieldsList ; 

    public class assessableobjectwithFieldsClass {
        public String assessableObjectLabel;
        public String assessableObjectAPI;
        public String assignmentManagerApi;
        public List<assessableObjFieldPositionCls> assessablefields;
    }
    //End Assessable Object field select functionality.

    public List<AssessibleFieldDetails> assessibleFieldDtls;

    public class AssessibleFieldDetails {
        public string assessibleFieldApiName;
        public string assessibleFieldLabel;

        public AssessibleFieldDetails(String fieldApi, String fieldLabel) {
            this.assessibleFieldApiName = fieldApi;
            this.assessibleFieldLabel = fieldLabel;
        }
    }

    public class responseClass {
        public string resultMsg;
        public string recordId; 
    }

    public ReportBuilderConfigController() {

        try {

            savedReportsJSON = '';
            assessmentTemplateJSON = '';
            amPositionJSON = '';
            assessibleFieldDetailsJSON = '';
            dataConfigJSON = '';
            assessibleFieldDtls = new List<AssessibleFieldDetails>();
            List<assignmentManagerPositionCls> amPositionList = new List<assignmentManagerPositionCls>();
            List<Main_questionaire__c> templateList = new List<Main_questionaire__c>();
        
            assessableObjNamewithFieldsList = new List<assessableobjectwithFieldsClass> ();
            assObswithFieldsJSON = '';

            SFDCAccessController accessForAT = ExAMUtilClass.AccessController;
            List<String> fieldsListAT = new List<String>{'ExAM__Template_name__c'};
            accessForAT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Main_questionaire__c'), fieldsListAT);

            templateList = [SELECT CreatedDate, Id, Name, Template_name__c FROM Main_questionaire__c ORDER BY CreatedDate DESC LIMIT 1000];
            if (templateList != null && templateList.size() > 0) {
                assessmentTemplateJSON = JSON.serialize(templateList);
            }

            SFDCAccessController accessForRBC = ExAMUtilClass.AccessController;
            List<String> fieldsListRBC = new List<String>{'ExAM__Assessment_Data_Config__c', 'ExAM__Assessable_Object_Field_Position__c', 'ExAM__Assessment_Template__c', 'ExAM__Assignment_Manager_position__c',
                                                            'ExAM__End_Date_Range__c', 'ExAM__Is_Temporary__c', 'ExAM__Output_Format__c', 'ExAM__Overall_Status__c', 'ExAM__Selected_Sections__c', 'ExAM__Start_Date_Range__c', 'ExAM__Choosed_Assignment_manager__c'};
            accessForRBC.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Report_Builder_Configuration__c'), fieldsListRBC);

            List<Report_Builder_Configuration__c> reportBuilderList = new List<Report_Builder_Configuration__c> ();
            reportBuilderList = [
                SELECT   Assessment_Data_Config__c, Assessable_Object_Field_Position__c, Assessment_Template__c,
                         Assignment_Manager_position__c, Choosed_Assignment_manager__c, End_Date_Range__c, Id, Is_Temporary__c,
                         Name, Output_Format__c, Overall_Status__c, Selected_Sections__c, Start_Date_Range__c
                FROM     Report_Builder_Configuration__c
                WHERE    Is_Temporary__c = false
                ORDER BY Createddate ASC LIMIT 1000
            ];
            if (reportBuilderList != null && reportBuilderList.size() > 0) {
                reportBuilderListJSON = JSON.serialize(reportBuilderList);
            }

            for (Schema.SObjectField amfield : ExAMUtilClass.getSObjectFieldsMap('ExAM__IssueRequest_Life_Cycle__c').values()) {
            
                Schema.DescribeFieldResult res = amfield.getdescribe();
                System.debug('::::Name::::'+res.getName());
                if (res.isCustom() || res.getName().equalsIgnoreCase('Name') || res.getName().equalsIgnoreCase('Id')) {
                    amPositionList.add(new assignmentManagerPositionCls(res.getName(), res.getLabel(),null));

                    if (res.getName().equalsIgnoreCase('ExAM__Status__c')) {

                        for(Schema.PickListEntry pklstentry : res.getPicklistValues()) {
                            assessibleFieldDtls.add( new AssessibleFieldDetails(pklstentry.getValue(), pklstentry.getLabel()) );
                        }
                    }

                    if (res.getType() == Schema.DisplayType.REFERENCE && ( res.getLocalName().startsWithIgnoreCase('AM_') || res.getLocalName().equalsIgnoreCase('Facility_Name__c')) ) {
                        List<Schema.SObjectType> s = res.getReferenceTo();
                        Schema.DescribeSObjectResult objResult = s[0].getDescribe();
                        assessableobjectwithFieldsClass assessableObj = new assessableobjectwithFieldsClass();
                        assessableObj.assessableObjectLabel = objResult.getLabel();
                        assessableObj.assessableObjectAPI = objResult.getName();
                        assessableObj.assignmentManagerApi = res.getName();
                        Map<string, Schema.SObjectField> assessableObjectFieldApiMap = Schema.getGlobalDescribe().get(objResult.getName()).getDescribe().fields.getMap();
                    
                        assessableObj.assessablefields = new List<assessableObjFieldPositionCls>();
                        for (Schema.SObjectField assfield : assessableObjectFieldApiMap.values()) {
                            Schema.DescribeFieldResult assDesfldRes = assfield.getdescribe();
                            System.debug('::::Name::::'+assDesfldRes.getName());
                            if (assDesfldRes.isCustom() || assDesfldRes.getName().equalsIgnoreCase('Name') || assDesfldRes.getName().equalsIgnoreCase('Id')) {
                                assessableObj.assessablefields.add(new assessableObjFieldPositionCls(assDesfldRes.getName(), assDesfldRes.getLabel(),null));
                            }
                        }
                        assessableObjNamewithFieldsList.add(assessableObj);
                        System.debug('::::assessableObjNamewithFieldsList::::'+assessableObjNamewithFieldsList);
                        assObswithFieldsJSON = JSON.serialize(assessableObjNamewithFieldsList);
                    }
                }            
            }
            System.debug(':::::amPositionList:::::'+amPositionList);
            if (amPositionList != null && amPositionList.size() > 0) {
                amPositionJSON = JSON.serialize(amPositionList);
            }

            System.debug(':::::assessibleFieldDtls:::::'+assessibleFieldDtls);
            if (assessibleFieldDtls != null && assessibleFieldDtls.size() > 0) {
                assessibleFieldDetailsJSON = JSON.serialize(assessibleFieldDtls);
            }
        
            List<String> dataConfigList = new List<String>();
            //dataConfigList.add('Questions');
            //dataConfigList.add('Answers');
            dataConfigList.add('Comments');
            dataConfigList.add('Pictures'); 
            dataConfigJSON  = JSON.serialize(dataConfigList);
        }
        catch(Exception e) {
            ApexPages.addMessage( new Apexpages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    }

    @RemoteAction
    public static String queryAssignmentManagers(String searchName, String assTempId, String startDate, String endDate) {

        system.debug('::::::assTempId:::::'+assTempId);
        Date startTime;
        Date endTime ;
        string queryString = '';
        string response = '';

        try {

            List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c> ();
            if (searchName != null && searchName != '') {

                SFDCAccessController accessForAM = ExAMUtilClass.AccessController;
                List<String> fieldsListAM = new List<String>{'ExAM__Assessment_Template_Type__c', 'ExAM__Facility_Name__c', 'ExAM__InvestigationType__c', 'ExAM__Priority__c', 'ExAM__Scheduled_Start_Date__c', 'ExAM__Status__c'};
                accessForAM.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__IssueRequest_Life_Cycle__c'), fieldsListAM);

                queryString += 'SELECT Assessment_Template_Type__c, Facility_Name__c, Facility_Name__r.Name, Id, InvestigationType__c, Name, Priority__c, Scheduled_Start_Date__c, Status__c';
                queryString += ' FROM IssueRequest_Life_Cycle__c ';
                queryString += ' WHERE Name Like \''+searchName+'%\'';
                if (assTempId != null && assTempId != '') {
                    queryString += ' AND InvestigationType__c =:assTempId ';
                }
                if (startDate != null && startDate != '') {
                    List<String> dateStr = startDate.split('/');
                    if (dateStr != null && dateStr.size() >= 3) {
                        startTime = date.newinstance( Integer.valueOf(dateStr[2]), Integer.valueOf(dateStr[0]), Integer.valueOf(dateStr[1]) );
                        queryString += ' AND Scheduled_Start_Date__c >= :startTime';
                    }
                }
                if (endDate != null && endDate != '') {
                    List<String> dateStr = endDate.split('/');
                    
                    if (dateStr != null && dateStr.size() >= 3) {
                        endTime = date.newinstance( Integer.valueOf(dateStr[2]), Integer.valueOf(dateStr[0]), Integer.valueOf(dateStr[1]) );            
                        queryString += ' AND Scheduled_Start_Date__c <= :endTime';
                    }
                }
                queryString += ' ORDER BY CreatedDate DESC LIMIT 1000';
                System.debug(':::::queryString:::::'+queryString);
                amList = Database.query(queryString); //permission checked above            
                
            }
            response = JSON.serialize( amList );
        }
        catch(Exception e) {
            response = JSON.serialize( e.getMessage() );
        }
        return response;
    }
    @RemoteAction
    public static String querySectionTemplate(String assTempId) {

        string response = '';

        try {
            system.debug('::::::assTempId:::::'+assTempId);
        
            SFDCAccessController accessForST = ExAMUtilClass.AccessController;
            List<String> fieldsListST = new List<String>{'ExAM__Order_No__c', 'ExAM__Questionnaire_Section__c', 'ExAM__Section_label__c'};
            accessForST.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Section_Template__c'), fieldsListST);

            List<Section_Template__c> secList = new List<Section_Template__c> ();
            if (assTempId != null && assTempId != '') {
                secList = [
                    SELECT Id, Name, Order_No__c, Questionnaire_Section__c, Section_label__c
                    FROM   Section_Template__c 
                    WHERE  Questionnaire_Section__c =:assTempId ORDER BY Order_No__c ASC LIMIT 1000
                ]; 
            }
            response = JSON.serialize(secList);
        }
        catch(Exception e) {
            response = JSON.serialize( e.getMessage() );
        }
        return response;
    }
    
    @RemoteAction
    public static String saveReportBuilderConfig(String selectedReportValue, String selectedTemp, String reportBuilderName, String startdate, 
                            String enddate, String selectFormat,  String selectedAssignmentManager, String positionResult, 
                            String sectionSelectResult, Boolean isTemporary, String dataConfigResult, String assessableFieldConfig, String status) {
                    
        system.debug('::reportBuilderName:::'+reportBuilderName);
        system.debug('::startdate:::'+startdate);
        system.debug('::enddate:::'+enddate);
        system.debug('::selectFormat:::'+selectFormat);
        system.debug('::selectedAssignmentManager:::'+selectedAssignmentManager);
        system.debug('::positionResult:::'+positionResult);
        system.debug('::sectionSelectResult::'+sectionSelectResult);
        system.debug('::dataConfigResult::'+dataConfigResult);
        system.debug('::status::'+status);
        
        String resultMsg = '';
        
        try {

            if ( reportBuilderName != null && reportBuilderName != '') {

                SFDCAccessController access = ExAMUtilClass.AccessController;
                List<String> fieldsList = new List<String>{'ExAM__Is_Temporary__c', 'ExAM__Assessment_Template__c', 'ExAM__Output_Format__c', 'ExAM__Start_Date_Range__c', 'ExAM__End_Date_Range__c', 'ExAM__Choosed_Assignment_manager__c', 'ExAM__Assignment_Manager_position__c', 'ExAM__Selected_Sections__c', 'ExAM__Assessment_Data_Config__c', 'ExAM__Assessable_Object_Field_Position__c', 'ExAM__Overall_Status__c'};
                access.assertAuthorizedToCreate(Schema.getGlobalDescribe().get('exam__Report_Builder_Configuration__c'), fieldsList);
                access.assertAuthorizedToUpdate(Schema.getGlobalDescribe().get('exam__Report_Builder_Configuration__c'), fieldsList);

                Report_Builder_Configuration__c reportBuilderInsert = new Report_Builder_Configuration__c();
                if (selectedReportValue != null && selectedReportValue != '') {
                    reportBuilderInsert.Id = Id.valueOf(selectedReportValue);
                } else {
                    reportBuilderInsert.Name = reportBuilderName;
                    reportBuilderInsert.Is_Temporary__c = isTemporary;
                }
                reportBuilderInsert.Assessment_Template__c = selectedTemp != null && selectedTemp != '' ? Id.valueOf(selectedTemp) : null;
                reportBuilderInsert.Output_Format__c = selectFormat; 
                reportBuilderInsert.Start_Date_Range__c = startdate;
                reportBuilderInsert.End_Date_Range__c = enddate;
                reportBuilderInsert.Choosed_Assignment_manager__c = selectedAssignmentManager != null && selectedAssignmentManager != '' ? Id.valueof(selectedAssignmentManager) : null;
                reportBuilderInsert.Assignment_Manager_position__c = positionResult;
                reportBuilderInsert.Selected_Sections__c = sectionSelectResult; 
                reportBuilderInsert.Assessment_Data_Config__c = dataConfigResult;
                if (assessableFieldConfig != null && assessableFieldConfig != '') {
                    reportBuilderInsert.Assessable_Object_Field_Position__c = assessableFieldConfig;
                }
                reportBuilderInsert.Overall_Status__c = status;
                upsert reportBuilderInsert;

                responseClass res = new responseClass();
                res.resultMsg = 'success';
                res.recordId = reportBuilderInsert.Id; 
                resultMsg = JSON.serialize(res);
            }
            else {
                responseClass res = new responseClass();
                res.resultMsg = 'Please enter a name to save record';
                res.recordId = ''; 
                resultMsg = JSON.serialize(res);
            }
        } catch (Exception ex) {
            system.debug(':::::ex::::'+ex.getMessage());
            responseClass res = new responseClass();
            res.resultMsg = 'Error : '+ex.getMessage();
            res.recordId = ''; 

            resultMsg = JSON.serialize(res);
        }
        return resultMsg;
    } 
    
    @RemoteAction
    public static String queryAssignmentManager(String amId) {

        string response = '';

        try {
            SFDCAccessController accessForAM = ExAMUtilClass.AccessController;
            if (amId != null && amId != 'null' && amId != '') {

                List<String> fieldsListAM = new List<String>{'ExAM__Assessment_Template_Type__c', 'ExAM__Facility_Name__c', 'ExAM__InvestigationType__c', 'ExAM__Priority__c', 'ExAM__Status__c', 'ExAM__Scheduled_Start_Date__c'};
                accessForAM.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__IssueRequest_Life_Cycle__c'), fieldsListAM);

                List<IssueRequest_Life_Cycle__c> amList = [
                    SELECT Assessment_Template_Type__c, Facility_Name__c, Facility_Name__r.Name, Id, InvestigationType__c,
                           Name, Priority__c, Status__c, Scheduled_Start_Date__c
                    FROM   IssueRequest_Life_Cycle__c
                    WHERE  Id = :amId LIMIT 1
                ];
                if (amList != null && amList.size() > 0) {
                    response = JSON.serialize( amList[0] );
                }
            }
            else {
                response = JSON.serialize( 'Please provide a valid assignment manager id' );
            }
        }
        catch(Exception e) {
            response = JSON.serialize( e.getMessage() );
        }
        return response;
    }   

    @RemoteAction
    public static string deleteReportBuilderConfig(String deletedIdJSON) {

        string response = '';

        try {

            system.debug(':::::deletedIdJSON::::'+deletedIdJSON);
            Map<String, Boolean> deleteReportIdwithIsSelectedMap = (Map<String, Boolean>)System.JSON.deserialize(deletedIdJSON,Map<String, Boolean>.class);
            List<Report_Builder_Configuration__c> deleteList = new List<Report_Builder_Configuration__c>();
            SFDCAccessController accessForRBCDel = ExAMUtilClass.AccessController;
            for (string idval : deleteReportIdwithIsSelectedMap.keySet()) {
                if (deleteReportIdwithIsSelectedMap.get(idval)) {
                    deleteList.add(new Report_Builder_Configuration__c(Id = idval));
                }
            }
            if (deleteList != null && deleteList.size() > 0) {
                
                if ( accessForRBCDel.isAuthorizedToDelete(Schema.getGlobalDescribe().get('exam__Report_Builder_Configuration__c')) ) {

                    delete deleteList;

                    List<String> fieldsListRBC = new List<String>{'ExAM__Assignment_Manager_position__c', 'ExAM__Assessment_Template__c', 'ExAM__Assessment_Data_Config__c', 'ExAM__Choosed_Assignment_manager__c', 'ExAM__End_Date_Range__c', 'ExAM__Is_Temporary__c', 'ExAM__Output_Format__c', 'ExAM__Selected_Sections__c', 'ExAM__Start_Date_Range__c'};
                    accessForRBCDel.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Report_Builder_Configuration__c'), fieldsListRBC);

                    List<Report_Builder_Configuration__c> reportBuilderList = new List<Report_Builder_Configuration__c>();
                    reportBuilderList = [
                        SELECT Assignment_Manager_position__c, Assessment_Template__c, Assessment_Data_Config__c,
                               Choosed_Assignment_manager__c, End_Date_Range__c, Id, Is_Temporary__c, Name,
                               Output_Format__c, Selected_Sections__c, Start_Date_Range__c
                        FROM   Report_Builder_Configuration__c WHERE Is_Temporary__c = false ORDER BY Createddate ASC LIMIT 1000
                    ];
                    if (reportBuilderList != null && reportBuilderList.size() > 0) {
                        response = JSON.serialize(reportBuilderList);
                    }
                }
                else {
                    response = JSON.serialize( 'You do not have access to delete Report Builder Configuration records' );
                }
            }
        }
        catch(Exception e) {
            response = JSON.serialize( e.getMessage() );
        }
        return response;
    }
}