src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessable_Fields_Mapping__c.object
<CustomObject>
    <description>Where ExAM stores information about how to map Answer data to Assessable Object Fields.</description>
    <fields>
        <fullName>Assessable_Object_API__c</fullName>
        <label>Assessable Object API</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessable_Object_Field_API__c</fullName>
        <label>Assessable Object Field API</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assessable Fields Mappings</relationshipLabel>
        <relationshipName>Assessable_Fields_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Assessable Fields Mappings</relationshipLabel>
        <relationshipName>Assessable_Fields_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessable Fields Mapping</label>
    <nameField>
        <displayFormat>AFM-{0000}</displayFormat>
        <label>Assessable Fields Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessable Fields Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Field_Mapping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Field Mapping</label>
        <type>Checkbox</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Date__c</fullName>
        <inlineHelpText>This is the date and time that the Assignment is scheduled to take place.</inlineHelpText>
        <label>Scheduled Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the organization for which the template is created</description>
        <inlineHelpText>This is the main organization for which the template is created e.g. DOI etc.This has child accounts for each school and school has child accounts of facility or surveys</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Main_Questionnaire_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the organization that is responsible for maintaining the Assessment Template.</inlineHelpText>
        <label>Contact Organization</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Main_questionnaire_template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree Result Page Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree Result Page Fields Default</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAssignmentManagerTrigger.cls
@isTest
private class TestAssignmentManagerTrigger {

    @isTest static void protectMorethenOneCustomLookupValuePopulate() {
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        contact con = new contact();
        con.AccountId=acc.id;
        con.LastName ='testCon';
        insert con;
        
        ExAM_Configuration__c config = new ExAM_Configuration__c();
        config.Name ='Configuration';
        config.Decision_Tree__c='TestFiels';
        config.Is_Field_Mapping__c = true;
        insert config;
        
        List<Main_questionaire__c> assTempList = new List<Main_questionaire__c>{
            new Main_questionaire__c(Account__c = acc.Id,ContactOrganization__c = con.Id,Template_name__c='Test1'),
            new Main_questionaire__c(Account__c = acc.Id,ContactOrganization__c = con.Id,Template_name__c='test2')
        };
        insert assTempList;
        
        List<Section_Template__c> secTempList = new List<Section_Template__c>{
            new Section_Template__c(Questionnaire_Section__c = assTempList[0].Id),
            new Section_Template__c(Questionnaire_Section__c = assTempList[0].Id),
            new Section_Template__c(Questionnaire_Section__c = assTempList[1].Id),
            new Section_Template__c(Questionnaire_Section__c = assTempList[1].Id)
        };
        insert secTempList;
        
        List<Question_Template__c> quesTemplList = new List<Question_Template__c>{
            new Question_Template__c(Section_Question__c = secTempList[0].Id),
            new Question_Template__c(Section_Question__c = secTempList[0].Id),
            new Question_Template__c(Section_Question__c = secTempList[1].Id),
            new Question_Template__c(Section_Question__c = secTempList[1].Id),
            new Question_Template__c(Section_Question__c = secTempList[2].Id),
            new Question_Template__c(Section_Question__c = secTempList[2].Id),
            new Question_Template__c(Section_Question__c = secTempList[3].Id),
            new Question_Template__c(Section_Question__c = secTempList[3].Id)
        };
        insert quesTemplList;
        
        List<IssueRequest_Life_Cycle__c> assManagerList = new List<IssueRequest_Life_Cycle__c>{
            new IssueRequest_Life_Cycle__c(InvestigationType__c= assTempList[0].Id,Scheduled_Start_Date__c = Date.today()),
            new IssueRequest_Life_Cycle__c(InvestigationType__c= assTempList[1].Id,Scheduled_Start_Date__c = Date.today())
        };
        insert assManagerList;
        
        List<Questionnaire_Response__c> quesTemp = new List<Questionnaire_Response__c>{
            new Questionnaire_Response__c(Question_Template__c = quesTemplList[0].Id,Issue_Request__c = assManagerList[0].Id, Response__c = 'test2'),
            new Questionnaire_Response__c(Question_Template__c = quesTemplList[0].Id,Issue_Request__c = assManagerList[0].Id, Response__c = 'test3'),
            new Questionnaire_Response__c(Question_Template__c = quesTemplList[1].Id,Issue_Request__c = assManagerList[0].Id, Response__c = 'test4'),
            new Questionnaire_Response__c(Question_Template__c = quesTemplList[1].Id,Issue_Request__c = assManagerList[0].Id, Response__c = 'test5'),
            new Questionnaire_Response__c(Question_Template__c = quesTemplList[2].Id,Issue_Request__c = assManagerList[1].Id, Response__c = 'test6'),
            new Questionnaire_Response__c(Question_Template__c = quesTemplList[2].Id,Issue_Request__c = assManagerList[1].Id, Response__c = 'test7'),
            new Questionnaire_Response__c(Question_Template__c = quesTemplList[3].Id,Issue_Request__c = assManagerList[1].Id, Response__c = 'test8'),
            new Questionnaire_Response__c(Question_Template__c = quesTemplList[3].Id,Issue_Request__c = assManagerList[1].Id, Response__c = 'test9')
        };
        insert quesTemp; 
        
        List<Questionnaire_Response__c> quesTempUpdate = new List<Questionnaire_Response__c>{
            new Questionnaire_Response__c(Id = quesTemp[0].Id, Question_Template__c = quesTemplList[0].Id,Issue_Request__c = assManagerList[0].Id, Response__c = 'test2'),
            new Questionnaire_Response__c(Id = quesTemp[1].Id, Question_Template__c = quesTemplList[0].Id,Issue_Request__c = assManagerList[0].Id, Response__c = 'test3'),
            new Questionnaire_Response__c(Id = quesTemp[2].Id, Question_Template__c = quesTemplList[1].Id,Issue_Request__c = assManagerList[0].Id, Response__c = 'test4'),
            new Questionnaire_Response__c(Id = quesTemp[3].Id, Question_Template__c = quesTemplList[1].Id,Issue_Request__c = assManagerList[0].Id, Response__c = 'test5'),
            new Questionnaire_Response__c(Id = quesTemp[4].Id, Question_Template__c = quesTemplList[2].Id,Issue_Request__c = assManagerList[1].Id, Response__c = 'test6'),
            new Questionnaire_Response__c(Id = quesTemp[5].Id, Question_Template__c = quesTemplList[2].Id,Issue_Request__c = assManagerList[1].Id, Response__c = 'test7'),
            new Questionnaire_Response__c(Id = quesTemp[6].Id, Question_Template__c = quesTemplList[3].Id,Issue_Request__c = assManagerList[1].Id, Response__c = 'test8'),
            new Questionnaire_Response__c(Id = quesTemp[7].Id, Question_Template__c = quesTemplList[3].Id,Issue_Request__c = assManagerList[1].Id, Response__c = 'test9')
        };
        update quesTemp; 
        List<Assessable_Fields_Mapping__c> afmList = new List<Assessable_Fields_Mapping__c> {
            new Assessable_Fields_Mapping__c(Assessable_Object_API__c = 'Account', Assessable_Object_Field_API__c = 'Name', Assessment_Template__c = assTempList[0].Id , Question_Template__c = quesTemplList[0].Id)
        };
        insert afmList;
        
        List<IssueRequest_Life_Cycle__c> updateassManagerList = new List<IssueRequest_Life_Cycle__c>{
            new IssueRequest_Life_Cycle__c(Id = assManagerList[0].Id, Facility_Name__c = acc.Id, InvestigationType__c= assTempList[0].Id,Scheduled_Start_Date__c = Date.today(), Status__c = 'Completed'),
            new IssueRequest_Life_Cycle__c(Id = assManagerList[1].Id, Facility_Name__c = acc.Id, InvestigationType__c= assTempList[1].Id,Scheduled_Start_Date__c = Date.today(), Status__c = 'Completed')
        };
        update updateassManagerList;

        List<Account> acctList = new List<Account>([SELECT Id, Name FROM Account WHERE Id = :acc.Id LIMIT 1]);
        system.assertEquals(acctList[0].Name, 'Test');
    }    
}