src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>HelpText__c</fullName>
        <description>This is the text which we want to shown on mouse hover</description>
        <inlineHelpText>This is the text which we want to shown on mouse hover</inlineHelpText>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Account_to_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup object that will be used in a survey.So we are not using user but accounts to create number of surveys.The no of surveys would be same as no of accounts whose craete_survey field(on Account object) is set to true</description>
        <inlineHelpText>If the response is related to a specific account it will be listed here.</inlineHelpText>
        <label>Account to Response</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Group__c.object
<CustomObject>
    <description>Used to group multiple sections in order to support complex assessments that require sections from multiple ExAM Assessment Templates.</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Section Group</label>
    <nameField>
        <displayFormat>SG-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>Section Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Group_Section_Relation__c.object
<CustomObject>
    <description>Used to support relationships between sections.</description>
    <fields>
        <fullName>Section_Group__c</fullName>
        <description>Junction object to Section Group</description>
        <inlineHelpText>Section Group</inlineHelpText>
        <label>Section Group</label>
        <referenceTo>Section_Group__c</referenceTo>
        <relationshipLabel>Section Group Section Relation</relationshipLabel>
        <relationshipName>Section_Group_Relation</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_Template__c</fullName>
        <description>Junction object to Section master detail</description>
        <inlineHelpText>Master is section</inlineHelpText>
        <label>Section Template</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipLabel>Section Group Section Relation</relationshipLabel>
        <relationshipName>Section_Template_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Section Group Section Relation</label>
    <nameField>
        <displayFormat>SGR-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>Section Group Section Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Group Section Relation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SectionStatus__c.object
<CustomObject>
    <description>Used to support the evaluation of the completeness of sections within an Assessment Template.</description>
    <fields>
        <fullName>Section_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>section table id in section status table</inlineHelpText>
        <label>Section Template</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipLabel>SectionStatus</relationshipLabel>
        <relationshipName>SectionStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Incomplete&quot;</defaultValue>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>SectionStatus</label>
    <nameField>
        <displayFormat>Status-{0}</displayFormat>
        <label>SectionStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SectionStatus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuestionnaireFieldsReport.cls
public with sharing class QuestionnaireFieldsReport{

    public string templateName { get; set; }
    public string sectionId { get; set; }
    public string templateId { get; set; }
    public string groupId { get; set; }
    public string groupName { get; set; }
    public string accountName { get; set; }

    public List<Section_Group__c> secgrpList { get; set; }
    public List<Section_Group_Section_Relation__c> group_sectionlist { get; set; }
    public List<Section_Template__c> sectionsLists { get; set; }
    public List<Question_Template__c> questionsLists { get; set; }
    public List<Questionnaire_Response__c> responseLists { get; set; }
    public List<Main_questionaire__c> templateLists { get; set; }
    public List<SectionStatus__c> sectionsStatusLists { get; set; }
    public List<Section> sectionList { get; set; } 

    public Map<Id, List<Question_Template__c>> sectionTemplateIdQuestionsTemplatesMap;

    public Account acc { get; set; }

    public QuestionnaireFieldsReport(ApexPages.StandardSetController controller){}

    public class Section
    {
        public string name {get; set;} 
        public List<Question> questionList {get; set;}
        public Section() {}
    } 

    public class Question 
    {
        public Question() {}
        public string name {get; set;} 
        public string subquestionname {get; set;} 
    }

    public QuestionnaireFieldsReport(){ 

        try {
            templateId=System.currentPageReference().getParameters().get('templateid');//to get the school or account id
            groupId=System.currentPageReference().getParameters().get('groupid');
            sectionList = new List<Section>(); 
            sectionTemplateIdQuestionsTemplatesMap = new Map<Id, List<Question_Template__c>>();
            //System.debug('!!!!!!!!!!!!!!!!~~~~~~~~~~~~~acct id from diff page :'+accountid);
            if(templateId!=null)
            {

                SFDCAccessController accessForAT = ExAMUtilClass.AccessController;
                List<string> fieldsListAT = new List<string>{'ExAM__Template_name__c'};
                accessForAT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Main_questionaire__c'), fieldsListAT);

                templateLists = [SELECT Id, Name, Template_name__c FROM Main_questionaire__c WHERE id = :templateId];
                if(templateLists!=NULL && templateLists.size()>=1)
                {
                    templateName = templateLists.get(0).Template_name__c ;   

                    SFDCAccessController accessForST = ExAMUtilClass.AccessController;
                    List<string> fieldsListST = new List<string>{'ExAM__Order_No__c', 'ExAM__Section_label__c'};
                    accessForST.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Section_Template__c'), fieldsListST);

                    sectionsLists = [
                        SELECT Id, Section_label__c, Order_No__c
                        FROM   Section_Template__c
                        WHERE  Questionnaire_Section__c = :templateLists.get(0).Id ORDER BY Order_No__c
                    ];

                    SFDCAccessController accessForQT = ExAMUtilClass.AccessController;
                    List<string> fieldsListQT = new List<string>{'ExAM__HelpText__c', 'ExAM__Question_Label__c', 'ExAM__Question_Order_No__c', 'ExAM__Question_Type__c', 'ExAM__Section_Question__c', 'ExAM__Subquestion_Label__c'};
                    accessForQT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Question_Template__c'), fieldsListQT);

                    SFDCAccessController accessForAO = ExAMUtilClass.AccessController;
                    List<string> fieldsListAO = new List<string>{'ExAM__Help_Text__c', 'ExAM__Weight__c'};
                    accessForAO.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Answer_Option__c'), fieldsListAO);

                    Map<Id, List<Question_Template__c>> sectionTemplateIdQuestionsTemplatesMap = new Map<Id, List<Question_Template__c>>();
                    questionsLists = new List<Question_Template__c>();
                    questionsLists = [
                        SELECT  HelpText__c, Id, Question_Label__c, Question_Order_No__c, Question_Type__c,
                                Section_Question__c, Subquestion_Label__c,
                                (SELECT Help_Text__c, Id, Name, Weight__c FROM Answer_Options__r) 
                        FROM    Question_Template__c 
                        WHERE   Section_Question__c IN :sectionsLists ORDER BY Question_Order_No__c
                    ];
                    if (questionsLists != null && questionsLists.size() > 0) {
                        for (Question_Template__c qt : questionsLists) {
                            if (!sectionTemplateIdQuestionsTemplatesMap.containsKey(qt.Section_Question__c)) {
                                sectionTemplateIdQuestionsTemplatesMap.put(qt.Section_Question__c, new List<Question_Template__c>());
                            }
                            sectionTemplateIdQuestionsTemplatesMap.get(qt.Section_Question__c).add( qt );
                        }
                    }

                    //responseLists=[Select id,Response__c,Question_Template__c,Account_to_Response__c from Questionnaire_Response__c where Account_to_Response__c= :accountId] ;                 
                    //System.debug('!!!!!!!!!!!!!!!!~~~~~~~~~~~~~acct id from diff page :'+accountid+'lllllll'+responseLists);
                    for(Section_Template__c sec: sectionsLists ) 
                    {
                        Section s=new Section();
                        s.name=sec.Section_label__c;
                        s.questionList =new List<Question>(); 
                        if( sectionTemplateIdQuestionsTemplatesMap.containsKey(sec.Id) ){
                            for(Question_Template__c quest : sectionTemplateIdQuestionsTemplatesMap.get(sec.Id) ) 
                            {
                                Question q=new Question();
                                q.name=quest.Question_Label__c;
                                if ( quest.Answer_Options__r.size() == 0 ){
                                    q.subquestionname =quest.Subquestion_Label__c;
                                } else {
                                    List<string> optList = new List<string>();
                                    for( Answer_Option__c ansRec :quest.Answer_Options__r ){
                                        if ( ansRec != null && ansRec.Name != null && ansRec.Name != '' ){
                                            optList.add(ansRec.Name);
                                        }
                                    }
                                    q.subquestionname = string.join(optList,'~');
                                }
                                s.questionList.add(q);
                            }
                        }
                        sectionList.add(s);
                    }
                }
            }
            else
            {
                if(groupId!=null)
                {

                    SFDCAccessController accessForSG = ExAMUtilClass.AccessController;
                    List<string> fieldsListSG = new List<string>{'ExAM__Group_Name__c'};
                    accessForSG.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Section_Group__c'), fieldsListSG);

                    secgrpList = [SELECT Group_Name__c, Id, Name FROM Section_Group__c WHERE Id = :groupId];
                    if(secgrpList !=NULL && secgrpList.size()>0)
                    {
                        groupName=secgrpList[0].Group_Name__c;

                        SFDCAccessController accessForSGSR = ExAMUtilClass.AccessController;

                        List<string> fieldsListSGSRST = new List<string>{'ExAM__Section_label__c'};
                        accessForSGSR.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Section_Template__c'), fieldsListSGSRST);

                        List<string> fieldsListSGSR = new List<string>{'ExAM__Default_Section__c', 'ExAM__Section_Active__c', 'ExAM__Section_Group__c', 'ExAM__Section_Template__c'};
                        accessForSGSR.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Section_Group_Section_Relation__c'), fieldsListSGSR);

                        Set<Id> sectionTemplateIdSet = new Set<Id>();
                        group_sectionlist = new List<Section_Group_Section_Relation__c>();

                        for(Section_Group_Section_Relation__c  res : [SELECT Default_Section__c, Id, Section_Active__c, Section_Group__c, Section_Template__c,
                                                                             Section_Template__r.Section_label__c
                                                                      FROM   Section_Group_Section_Relation__c
                                                                      WHERE  Section_Group__c = :secgrpList[0].id AND Section_Active__c = true]) {


                            sectionTemplateIdSet.add( res.Section_Template__c );
                            group_sectionlist.add( res );
                        }

                        SFDCAccessController accessForQT = ExAMUtilClass.AccessController;
                        List<string> fieldsListQT = new List<string>{'ExAM__HelpText__c', 'ExAM__Question_Label__c', 'ExAM__Question_Order_No__c', 'ExAM__Question_Type__c', 'ExAM__Section_Question__c', 'ExAM__Subquestion_Label__c'};
                        accessForQT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Question_Template__c'), fieldsListQT);

                        SFDCAccessController accessForAO = ExAMUtilClass.AccessController;
                        List<string> fieldsListAO = new List<string>{'ExAM__Help_Text__c', 'ExAM__Weight__c'};
                        accessForAO.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Answer_Option__c'), fieldsListAO);

                        for(Question_Template__c  qt : [SELECT  HelpText__c, Id, Question_Label__c, Question_Order_No__c, Question_Type__c,
                                                                Section_Question__c, Subquestion_Label__c,
                                                                (SELECT Help_Text__c, Id, Name, Weight__c FROM Answer_Options__r) 
                                                        FROM    Question_Template__c
                                                        WHERE   Section_Question__c IN :sectionTemplateIdSet ORDER BY Question_Order_No__c]) {

                            if (!sectionTemplateIdQuestionsTemplatesMap.containsKey(qt.Section_Question__c)) {
                                sectionTemplateIdQuestionsTemplatesMap.put(qt.Section_Question__c, new List<Question_Template__c>());
                            }
                            sectionTemplateIdQuestionsTemplatesMap.get(qt.Section_Question__c).add( qt );
                        }

                        System.debug('!!!!!group_sectionlist '+group_sectionlist.size());
                        for(Section_Group_Section_Relation__c  res: group_sectionlist ) 
                        {
                            Section s=new Section();System.debug('11!!!!!sec');
                            s.name=res.Section_Template__r.Section_label__c;System.debug('222!!!!!sec'+s.name);
                            s.questionList =new List<Question>(); 
                            System.debug('!!!!!sec'+res.Section_Template__r.Section_label__c);

                            if ((sectionTemplateIdQuestionsTemplatesMap.containsKey(res.Section_Template__c))
                                && (sectionTemplateIdQuestionsTemplatesMap.get(res.Section_Template__c) != null
                                    && sectionTemplateIdQuestionsTemplatesMap.get(res.Section_Template__c).size() > 0)
                            ) {

                                for(Question_Template__c quest : sectionTemplateIdQuestionsTemplatesMap.get(res.Section_Template__c) ) 
                                {
                                    Question q=new Question();
                                    q.name=quest.Question_Label__c;
                                    if ( quest.Answer_Options__r.size() == 0 ){
                                        q.subquestionname =quest.Subquestion_Label__c;
                                    } else {
                                        List<string> optList = new List<string>();
                                        for( Answer_Option__c ansRec :quest.Answer_Options__r ){
                                            if ( ansRec != null && ansRec.Name != null && ansRec.Name != '' ){
                                                optList.add(ansRec.Name);
                                            }
                                        }
                                        q.subquestionname = string.join(optList,'~');
                                    }
                                    s.questionList.add(q);
                                }
                            }
                            System.debug('1111!!!!!question'+s);
                            sectionList.add(s);System.debug('222!!!!!question');
                        }
                    }
                }
            }
            //FROM the force.com site if we want to update data in Account for CCTV etc scores I am adding the code here, as here the responses would be given and data would be added to Main Report DAta object for reports 
            // To set the focus category scores for the account
            //sectionsStatusLists=[Select id,Section_Template__c,Section_Template__r.id,Section_Template__r.Section_Label__c,Section_Template__r.Order_No__c,Account_to_SectionStatus__c,Status__c,User__c from SectionStatus__c where Account_to_SectionStatus__c= :accountId AND (Section_Template__c!=null) order by Section_Template__r.Order_No__c] ;
            System.debug('---sectionList'+sectionList);
        }
        catch(Exception e) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    }

    public static testMethod void testgetSections()
    {

        Test.setCurrentPageReference(new PageReference('Page.QuestionnaireViewReport'));
        Main_questionaire__c maintest=new Main_questionaire__c (Template_name__c ='DOI');
        insert maintest; 
        Section_Group__c maintestg=new Section_Group__c(Group_Name__c ='test');
        upsert maintestg;
        System.currentPageReference().getParameters().put('templateid', maintest.id ); 

        Section_Template__c sc= new Section_Template__c(Questionnaire_Section__c=maintest.id,Section_label__c='test section'); 
        insert sc;
        Section_Template__c sc1= new Section_Template__c(Questionnaire_Section__c=maintest.id,Section_label__c='test section 2'); 
        insert sc1;
        Question_Template__c scq= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your name?',Question_Order_No__c=1,Question_Type__c='Text',Focus_category__c='CCTV');     
        Question_Template__c scqp= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=2,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Perimeter');     
        Question_Template__c scqm= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your qualification?',Question_Order_No__c=3,Question_Type__c='MultiselectPicklist',Subquestion_Label__c='High School~Bachelors~Masters',Focus_category__c='Emergency Response Plan');     
        Question_Template__c scqp1= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=4,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Adequate Lighting');     
        Question_Template__c scqm1= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your qualification?',Question_Order_No__c=5,Question_Type__c='MultiselectPicklist',Subquestion_Label__c='High School~Bachelors~Masters',Focus_category__c='Adequate Locking System');     
        Question_Template__c scqp2= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=6,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Mail Handling');     
  
        insert scq;insert scqp;insert scqm;insert scqp1;insert scqm1;insert scqp2;
        Section_Group_Section_Relation__c  sgrelation=new Section_Group_Section_Relation__c (Section_Group__c=maintestg.id,Default_Section__c=true,Section_Active__c=true,Section_Template__c=sc.id);
        upsert sgrelation;
            
        List<Section> scAlls=new List<Section>();  
        QuestionnaireFieldsReport d= new QuestionnaireFieldsReport();
        System.currentPageReference().getParameters().put('templateid',null ); 
        System.currentPageReference().getParameters().put('groupid', maintestg.id );

        Test.startTest();
        QuestionnaireFieldsReport d1= new QuestionnaireFieldsReport();
        System.assert(d!=null,'Response data with questions not found');
        Test.stopTest();
    }   
}//end main class