src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessable_Fields_Mapping__c.object
<CustomObject>
    <description>Where ExAM stores information about how to map Answer data to Assessable Object Fields.</description>
    <fields>
        <fullName>Assessable_Object_API__c</fullName>
        <label>Assessable Object API</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessable_Object_Field_API__c</fullName>
        <label>Assessable Object Field API</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Assessable Fields Mappings</relationshipLabel>
        <relationshipName>Assessable_Fields_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessable Fields Mapping</label>
    <nameField>
        <displayFormat>AFM-{0000}</displayFormat>
        <label>Assessable Fields Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessable Fields Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_Of_Question__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is the question weight</inlineHelpText>
        <label>Question Weight</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestLoadScoreForExistingAM.cls
@isTest
public class TestLoadScoreForExistingAM {
    
    @testSetup static void dataforTest() {
        
        Account acct = new Account(Name = 'Test Account');
        insert acct;
        
        Main_questionaire__c assessmentTemplate = new Main_questionaire__c(Template_name__c = 'Test Template');     
        insert assessmentTemplate;
        
        List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c>{
            new IssueRequest_Life_Cycle__c(Facility_Name__c = acct.Id, InvestigationType__c = assessmentTemplate.Id, Status__c = 'Completed'),
            new IssueRequest_Life_Cycle__c(Facility_Name__c = acct.Id, InvestigationType__c = assessmentTemplate.Id, Status__c = 'Completed')
        };
        insert amList;        
        
        Section_Template__c sectionTemplate = new Section_Template__c(Questionnaire_Section__c = assessmentTemplate.Id, Section_label__c = 'Test Section');
        insert sectionTemplate;
        
        List<Question_Template__c> qtList = new List<Question_Template__c>{
            new Question_Template__c(Question_Label__c = 'How can you rate our service?', Question_Type__c = 'Button', Section_Question__c = sectionTemplate.Id, 
                Subquestion_Label__c = 'Bad~Good~Excellent', Weight_of_Answer__c = '0~30~70', Weight_Of_Question__c = 10),
            new Question_Template__c(Question_Label__c = 'How can you rate our service?', Question_Type__c = 'Button', Section_Question__c = sectionTemplate.Id, Weight_Of_Question__c = 10),
            new Question_Template__c(Question_Label__c = 'How much experience do you have in this domain?', Question_Type__c = 'Dropdown Picklist', Section_Question__c = sectionTemplate.Id, 
                Subquestion_Label__c = 'Beginner~Intermediate~Advanced', Weight_of_Answer__c = '10~40~50', Weight_Of_Question__c = 10),
            new Question_Template__c(Question_Label__c = 'How fast you can do this work?', Question_Type__c = 'MultiselectPicklist', Section_Question__c = sectionTemplate.Id, 
                Subquestion_Label__c = 'Less than 1 day~1 day~2 days', Weight_of_Answer__c = '60~25~15', Weight_Of_Question__c = 10),
            new Question_Template__c(Question_Label__c = 'How easy is our service?', Question_Type__c = 'RadioPicklist', Section_Question__c = sectionTemplate.Id,            
                Subquestion_Label__c = 'Difficult~Flexible', Weight_of_Answer__c = '45~55', Weight_Of_Question__c = 10),
            new Question_Template__c(Question_Label__c = 'When did you started learning salesforce?', Question_Type__c = 'Date', Section_Question__c = sectionTemplate.Id)
        };
        insert qtList;
        
        Answer_Option__c[] options = new Answer_Option__c[]{
            new Answer_Option__c(Name = 'Bad', Order_No__c = 1, Question_Template__c  = qtList[1].Id, Weight__c = 0),
            new Answer_Option__c (Name = 'Good', Order_No__c = 2, Question_Template__c  = qtList[1].Id, Weight__c = 30),
            new Answer_Option__c(Name = 'Excellent', Order_No__c = 3, Question_Template__c  = qtList[1].Id, Weight__c = 70)
        };
        insert options;
                
        Assessable_Fields_Mapping__c[] fieldsMapping = new Assessable_Fields_Mapping__c[] {
            new Assessable_Fields_Mapping__c(Assessable_Object_API__c = 'Account', Assessable_Object_Field_API__c = 'Description', Assessment_Template__c = assessmentTemplate.Id, Question_Template__c = qtList[0].Id, Store_Answer_Response_Or_Score__c = 'Response'),
            new Assessable_Fields_Mapping__c(Assessable_Object_API__c = 'Account', Assessable_Object_Field_API__c = 'Overall_Score__c', Assessment_Template__c = assessmentTemplate.Id, Question_Template__c = qtList[0].Id, Store_Answer_Response_Or_Score__c = 'Score'),
            new Assessable_Fields_Mapping__c(Assessable_Object_API__c = 'Account', Assessable_Object_Field_API__c = 'Type', Assessment_Template__c = assessmentTemplate.Id, Assignment_Manager_Field_API__c = 'Status__c'),
            new Assessable_Fields_Mapping__c(Assessable_Object_API__c = 'Account', Assessable_Object_Field_API__c = 'SLAExpirationDate__c', Assessment_Template__c = assessmentTemplate.Id, Question_Template__c = qtList[5].Id, Store_Answer_Response_Or_Score__c = 'Response')
        };
        insert fieldsMapping;        
        
        Questionnaire_Response__c[] answers = new Questionnaire_Response__c[] {
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[0].Id, Question_Template__c = qtList[0].Id, Response__c = 'Good'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[0].Id, Question_Template__c = qtList[1].Id, Response__c = 'Good'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[0].Id, Question_Template__c = qtList[2].Id, Response__c = 'Advanced'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[0].Id, Question_Template__c = qtList[3].Id, Response__c = 'Less than 1 day'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[0].Id, Question_Template__c = qtList[4].Id, Response__c = 'Difficult'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[0].Id, Question_Template__c = qtList[4].Id, Response__c = 'Difficult', Weight_Response__c = 45),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[1].Id, Question_Template__c = qtList[0].Id, Response__c = 'Good'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[1].Id, Question_Template__c = qtList[1].Id, Response__c = 'Good'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[1].Id, Question_Template__c = qtList[2].Id, Response__c = 'Advanced'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[1].Id, Question_Template__c = qtList[3].Id, Response__c = 'Less than 1 day'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[1].Id, Question_Template__c = qtList[4].Id, Response__c = 'Difficult'),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[1].Id, Question_Template__c = qtList[4].Id, Response__c = 'Difficult', Weight_Response__c = 45),
            new Questionnaire_Response__c(Account_to_Response__c = acct.Id, Issue_Request__c = amList[1].Id, Question_Template__c = qtList[5].Id, Response__c = Date.today().format())
        };
        insert answers;
    }

    /**
    static testmethod void testGetTemplate() {
       
        ExAM_Configuration__c econ = new ExAM_Configuration__c();
        econ.Name = 'Configuration';
        insert econ;
        
        LoadScoreAndMapFieldValueInAMController amScoreUpdateClass = new LoadScoreAndMapFieldValueInAMController();
        
        LoadScoreAndMapFieldValueInAMController.TemplateDetail tempdetail = new LoadScoreAndMapFieldValueInAMController.TemplateDetail();
        tempdetail = LoadScoreAndMapFieldValueInAMController.getTemplates('Test Template');
        
        System.assertEquals(1, tempdetail.templatelist.size());
        System.assertEquals('Completed',tempdetail.amStatus);
    }
    **/   

    static testmethod void testGetAssignmentManager() {
               
        List<Main_questionaire__c> assTempList = new List<Main_questionaire__c>([SELECT Id, Name FROM Main_questionaire__c ORDER BY CreatedDate ASC]);

        Map<String, String> amMap = new Map<String, String>{'templateId'=> assTempList[0].Id, 'status' => 'Completed'};
        String searchCriteria = Json.serialize( amMap );

        LoadScoreAndMapFieldValueInAMController.AMDetail amd = new LoadScoreAndMapFieldValueInAMController.AMDetail();
        
        amd = LoadScoreAndMapFieldValueInAMController.getAssignmentManagers(searchCriteria);

        String updateresponse = LoadScoreAndMapFieldValueInAMController.loadScoreInSelectedAssignmentManagers( amd.assmanlist );
        LoadScoreAndMapFieldValueInAMController.ScoreUpdateResponse responseInstance = (LoadScoreAndMapFieldValueInAMController.ScoreUpdateResponse)Json.deserialize(updateresponse, LoadScoreAndMapFieldValueInAMController.ScoreUpdateResponse.class);
        system.assertEquals(responseInstance.isSuccess, true);
        system.assertEquals(responseInstance.message, 'Assignment Manager(s) updated successfully');

        List<Account> acctListAfter = new List<Account>([SELECT Id, Name, Description, Overall_Score__c, Type, SLAExpirationDate__c FROM Account]);
        if (acctListAfter != null && acctListAfter.size() > 0) {
            system.assertEquals('Good', acctListAfter[0].Description);
            system.assertEquals('Completed', acctListAfter[0].Type);
        }
    }
}