src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment_Event__c.object
<CustomObject>
    <description>Where ExAM stores data about Assessment Events including Date, Start and Finish Times.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Finish_Time__c</fullName>
        <label>Event Finish Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Start_Time__c</fullName>
        <label>Event Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Assessment Event</label>
    <nameField>
        <label>Assessment Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment_Group__c.object
<CustomObject>
    <description>Stores the name and type of Assessment Group. This helps support things like the batch generation of Public Assessment Links.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Group</label>
    <nameField>
        <label>Assessment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessment_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Event</label>
        <referenceTo>Assessment_Event__c</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Form_Completion__c</fullName>
        <inlineHelpText>The for the team needs to fill for each investigation type</inlineHelpText>
        <label>Assessment Form Completion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Assessment_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Group</label>
        <referenceTo>Assessment_Group__c</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the organization for which the template is created</description>
        <inlineHelpText>This is the main organization for which the template is created e.g. DOI etc.This has child accounts for each school and school has child accounts of facility or surveys</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Main_Questionnaire_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>This is a description of the Assessment Template.</inlineHelpText>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Map_Anything_Address_Configuration__c.object
<CustomObject>
    <description>Maps fields to into addresses so that ExAM can display them on a map.</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Field_Name__c</fullName>
        <label>City Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Field_Name__c</fullName>
        <label>Country Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code_Field_Name__c</fullName>
        <label>Postal Code Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Field_Name__c</fullName>
        <label>Street Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Map Anything Address Configuration</label>
    <nameField>
        <label>Map Anything Address Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Anything Address Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAssessmentMapUserImplementorCtlr.cls
@isTest
private class TestAssessmentMapUserImplementorCtlr {

    static testMethod void method1() {
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.BillingCity = 'test City';
        acc.BillingCountry = 'test country';
        acc.BillingState = 'test state';
        acc.BillingStreet = 'test Street';
        acc.BillingLatitude = 74.6;
        acc.BillingLongitude = 76.7;
        insert acc;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Template_name__c = 'Unit Template';
        assTemp.Account__c = acc.Id;
        insert assTemp;
        
        Assessment_Group__c assGrp = new Assessment_Group__c();
        assGrp.Type__c = 'Account';
        insert assGrp;
        
        Assessment_Event__c assEvent = new Assessment_Event__c();
        assEvent.Description__c = 'Test Description';
        assEvent.Event_Date__c = System.today();
        assEvent.Event_Start_Time__c = System.now().addHours(-4);
        assEvent.Event_Finish_Time__c = System.now().addHours(1);
        insert assEvent;
        
        Map_Anything_Address_Configuration__c mapConfig = new Map_Anything_Address_Configuration__c();
        mapConfig.Name = 'Account';
        mapConfig.Address__c = 'BillingStreet';
        insert mapConfig;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.Facility_Name__c = acc.Id;
        assManager.Assessment_Form_Completion__c = 'Complete';
        assManager.Assessment_Event__c = assEvent.Id;
        assManager.Assessment_Group__c = assGrp.Id;
        assManager.Status__c = 'Completed';
        assManager.Priority__c = 'High';
        assManager.InvestigationType__c = assTemp.Id;
        insert assManager;
        
        date tt = system.today()-1;
        string ss = tt.format();
        date t = system.today() +1;
        String s = t.format();
        apexpages.currentpage().getparameters().put('AssessableObj','Account');
        apexpages.currentpage().getparameters().put('AssessmentGrp',assGrp.Id);
        apexpages.currentpage().getparameters().put('AssessmentEvt',assEvent.Id);

        apexpages.currentpage().getparameters().put('scheduledFrom',ss);
        apexpages.currentpage().getparameters().put('scheduledTo',s);
        
        apexpages.currentpage().getparameters().put('AMStatus',assManager.Status__c);
        apexpages.currentpage().getparameters().put('AMpriority',assManager.Priority__c);
        apexpages.currentpage().getparameters().put('AMassessmentCompletion',assManager.Assessment_Form_Completion__c);
        apexpages.currentpage().getparameters().put('AMassessmentType',assTemp.Id);
        system.currentPageReference().getParameters().put('showUsers','true');
        system.currentPageReference().getParameters().put('ColorBy','Name');
        AssessmentMapUserImplementorController mapCtlr = new AssessmentMapUserImplementorController();
        
        List<AssessmentMapUserImplementorController.AddressToLatLongConversion> latAndLangList = new List<AssessmentMapUserImplementorController.AddressToLatLongConversion>();
        AssessmentMapUserImplementorController.AddressToLatLongConversion latlang = new AssessmentMapUserImplementorController.AddressToLatLongConversion(acc.Id,'33.3','32.3');
        latAndLangList.add(latlang);
        List<AssessmentMapUserImplementorController.Locations> locList = new List<AssessmentMapUserImplementorController.Locations>();
        locList = mapCtlr.getlistacc();
        String latLangStr = JSON.serialize(latAndLangList);
        string response = AssessmentMapUserImplementorController.updateAssessibleObjectLatLng(latLangStr,'Account');
        system.assertEquals(response, 'Geolocation field in Account updated successfully');
        string response1 = AssessmentMapUserImplementorController.updateAssessibleObjectLatLng(latLangStr,'Case');
        
    }
    static testMethod void method2() {
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.BillingCity = 'test City';
        acc.BillingCountry = 'test country';
        acc.BillingState = 'test state';
        acc.BillingStreet = 'test Street';
        acc.BillingLatitude = 74.6;
        acc.BillingLongitude = 76.7;
        insert acc;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Template_name__c = 'Unit Template';
        assTemp.Account__c = acc.Id;
        insert assTemp;
        
        Assessment_Group__c assGrp = new Assessment_Group__c();
        assGrp.Type__c = 'Account';
        insert assGrp;
        
        Assessment_Event__c assEvent = new Assessment_Event__c();
        assEvent.Description__c = 'Test Description';
        assEvent.Event_Date__c = System.today();
        assEvent.Event_Start_Time__c = System.now().addHours(-4);
        assEvent.Event_Finish_Time__c = System.now().addHours(1);
        insert assEvent;
        
        Map_Anything_Address_Configuration__c mapConfig = new Map_Anything_Address_Configuration__c();
        mapConfig.Name = 'Case';
        mapConfig.Street_Field_Name__c = 'Street';
        mapConfig.City_Field_Name__c = 'City';
        mapConfig.Postal_Code_Field_Name__c = 'PostalCode';
        mapConfig.Country_Field_Name__c = 'Country';
        insert mapConfig;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.Facility_Name__c = acc.Id;
        assManager.Assessment_Form_Completion__c = 'Complete';
        assManager.Assessment_Event__c = assEvent.Id;
        assManager.Assessment_Group__c = assGrp.Id;
        assManager.Status__c = 'Completed';
        assManager.Priority__c = 'High';
        assManager.InvestigationType__c = assTemp.Id;
        insert assManager;
        
        date tt = system.today()-1;
        string ss = tt.format();
        date t = system.today() +1;
        String s = t.format();
        apexpages.currentpage().getparameters().put('AssessableObj','Case');
        apexpages.currentpage().getparameters().put('AssessmentGrp',assGrp.Id);
        apexpages.currentpage().getparameters().put('AssessmentEvt',assEvent.Id);

        apexpages.currentpage().getparameters().put('scheduledFrom',ss);
        apexpages.currentpage().getparameters().put('scheduledTo',s);
        
        apexpages.currentpage().getparameters().put('AMStatus',assManager.Status__c);
        apexpages.currentpage().getparameters().put('AMpriority',assManager.Priority__c);
        apexpages.currentpage().getparameters().put('AMassessmentCompletion',assManager.Assessment_Form_Completion__c);
        apexpages.currentpage().getparameters().put('AMassessmentType',assTemp.Id);
        system.currentPageReference().getParameters().put('showUsers','true');
        system.currentPageReference().getParameters().put('ColorBy','Name');
        AssessmentMapUserImplementorController mapCtlr = new AssessmentMapUserImplementorController();
        
        List<AssessmentMapUserImplementorController.AddressToLatLongConversion> latAndLangList = new List<AssessmentMapUserImplementorController.AddressToLatLongConversion>();
        AssessmentMapUserImplementorController.AddressToLatLongConversion latlang = new AssessmentMapUserImplementorController.AddressToLatLongConversion(acc.Id,'33.3','32.3');
        latAndLangList.add(latlang);
        List<AssessmentMapUserImplementorController.Locations> locList = new List<AssessmentMapUserImplementorController.Locations>();
        locList = mapCtlr.getlistacc();
        String latLangStr = JSON.serialize(latAndLangList);
        string response = AssessmentMapUserImplementorController.updateAssessibleObjectLatLng(latLangStr,'Account');
        system.assertEquals(response, 'Geolocation field in Account updated successfully');
        string response1 = AssessmentMapUserImplementorController.updateAssessibleObjectLatLng(latLangStr,'User');
        
    }
}