src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Create_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</description>
        <inlineHelpText>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</inlineHelpText>
        <label>Create Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Questionnaire_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Each account should be related to a Template</inlineHelpText>
        <label>Main_Questionnaire_Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>PublishPlace__c</fullName>
        <description>This field specifies whether the template is for access through external site or internal salesforce login</description>
        <inlineHelpText>This field specifies whether the template is accessable through external site or internal salesforce login</inlineHelpText>
        <label>PublishPlace</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Internal to salesforce</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>External Site</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_Of_Question__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is the question weight</inlineHelpText>
        <label>Question Weight</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Group__c.object
<CustomObject>
    <description>Used to group multiple sections in order to support complex assessments that require sections from multiple ExAM Assessment Templates.</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Section Group</label>
    <nameField>
        <displayFormat>SG-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>Section Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAssessmentTemplateUIController.cls
@isTest
public class TestAssessmentTemplateUIController {
    static TestMethod void method1(){
        Main_questionaire__c[] templateList = new Main_questionaire__c[]{
            new Main_questionaire__c(Template_name__c = 'test template',
                                    PublishPlace__c = 'Internal to salesforce'
                                    )
        };
        insert templateList;
        Section_Template__c[] secList = new Section_Template__c[]{
            new Section_Template__c(Questionnaire_Section__c = templateList[0].Id)
        };
        insert secList;
        Question_Template__c[] qt = new Question_Template__c[]{
            new Question_Template__c(Question_Order_No__c = 1,Question_Label__c = 'test question',
                                    Question_Type__c = 'Text',Subquestion_Label__c = 'tst sub question',
                                    Weight_Of_Question__c = 100,Section_Question__c = secList[0].Id                                   )
        };
        insert qt;
        Section_Group__c sg =  new Section_Group__c();
        sg.Group_Name__c = 'test sg name';
        insert sg;
        
        ApexPages.currentPage().getParameters().put('templateid',templateList[0].Id);
        
        AssessmentTemplateUIController atuic = new AssessmentTemplateUIController();
        
        Account[] newAccount = new Account[] {
            new Account(name='XYZ Organization',Create_Survey__c = FALSE,
                        Main_Questionnaire_Template__c = NULL
                       )
                };
        insert newAccount;
        atuic.selectedAccountId=newAccount[0].id;
        atuic.AccountList = new List<SelectOption>{
            new SelectOption(templateList[0].Id, templateList[0].Id)
        };

        atuic.save();
        List<Account> acctList = new List<Account>([SELECT Id, Name FROM Account LIMIT 1]);
        if ( acctList != null && acctList.size() > 0 ) {
            system.assertEquals(acctList[0].Name, 'XYZ Organization');
        }

        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(newAccount);
        new AssessmentTemplateUIController(sc);
        atuic.getsecgrouplist();
        atuic.gettemplatesList();
        atuic.cloneTemp();
        atuic.EditSurvey();
        atuic.save();
        atuic.cancel();
        atuic.saveMulti();
        atuic.selectedAccountId = NULL;
        atuic.AccName = 'test acc';
    }
}