src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Date_Assigned__c</fullName>
        <defaultValue>Now()</defaultValue>
        <inlineHelpText>The date and time the Assignment Manager was created.</inlineHelpText>
        <label>Date Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Site Contact</inlineHelpText>
        <label>Site Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Issue_Request_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visitor_Register__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Salesforce ID of the Visitor record associated with this Assignment Manager. This field is only populated when the data collection effort takes place outside of Salesforce for example when a public assessment link is being used.</inlineHelpText>
        <label>Visitor Register</label>
        <referenceTo>Visitor_Register__c</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment__c.object
<CustomObject>
    <description>Used to support the collection of information necessary to perform data collections that primarily occur outside of Salesforce.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <inlineHelpText>If you are using our Twillio integration to support SMS interactions over Public Assessments this code is what your end user will text in order to fire start engaging with this template.</inlineHelpText>
        <label>Short Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Public Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Public Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Site_URL__c</fullName>
        <label>Site URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Public Assessment Configuration</label>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Visitor_Register__c.object
<CustomObject>
    <description>Used to collect information on ExAM Assessment participants. Enables analysis against visitors and participants in ExAM data collections.</description>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Public Assessment</label>
        <referenceTo>Public_Assessment__c</referenceTo>
        <relationshipLabel>Visitor Register</relationshipLabel>
        <relationshipName>Visitor_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Visitor Register</relationshipLabel>
        <relationshipName>Visitor_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visitor_Last_Name__c</fullName>
        <label>Visitor Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor__c</fullName>
        <label>Visitor First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Visitor Register</label>
    <nameField>
        <label>Visitor Register Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitor Register</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSMSSupportController.cls
@isTest
public class TestSMSSupportController {
    
    static testmethod void smssurvey() {
        Public_Assessment__c pa = new Public_Assessment__c(Short_Code__c = 'xyz123');
        insert pa;
        
        String siteurl ='';
        Public_Assessment_Configuration__c pac = Public_Assessment_Configuration__c.getInstance( UserInfo.getOrganizationId() );
        if (pac != null) {

            siteurl = pac.Site_URL__c;
        } else {
            siteurl = 'https://test12345.com/customerFeedback';
            pac.Site_URL__c = siteurl;
            upsert pac;
        }
        
        
        Account acc = new Account();
        acc.Name = 'TestAcc';
        insert acc;
        
        contact con = new contact();
        con.AccountId=acc.id;
        con.LastName ='testCon';
        insert con;
        
        Main_questionaire__c[] templateList = new Main_questionaire__c[] {
            new Main_questionaire__c(Template_name__c = 'General Safety'),
            new Main_questionaire__c(Template_name__c = 'Fire Safety')
        };
        insert templateList;

        Section_Template__c[] sectionTemplateList = new Section_Template__c[] {
            new Section_Template__c(Questionnaire_Section__c = templateList[0].Id, Section_label__c = 'Section Template 1'),
            new Section_Template__c(Questionnaire_Section__c = templateList[0].Id, Section_label__c = 'Section Template 2'),
            new Section_Template__c(Questionnaire_Section__c = templateList[1].Id, Section_label__c = 'Section Template 3'),
            new Section_Template__c(Questionnaire_Section__c = templateList[1].Id, Section_label__c = 'Section Template 4')
        };
        insert sectionTemplateList; 

        Question_Template__c[] qtList = new Question_Template__c[] {
            new Question_Template__c(Question_Type__c = 'Text', Question_Label__c = 'What is your name?', Section_Question__c = sectionTemplateList[0].Id, Question_Order_No__c = 4),
            new Question_Template__c(Question_Type__c = 'Date', Question_Label__c = 'Your DOB?', Section_Question__c = sectionTemplateList[0].Id, Question_Order_No__c = 3),
            new Question_Template__c(Subquestion_Label__c = 'Cricket~Basket ball~Volley ball', Question_Type__c = 'MultiselectPicklist', Question_Label__c = 'What are your hobbies?', Section_Question__c = sectionTemplateList[1].Id, Question_Order_No__c = 2),
            new Question_Template__c(Subquestion_Label__c = 'Male~Female', Question_Type__c = 'RadioPicklist', Question_Label__c = 'Gender?', Section_Question__c = sectionTemplateList[1].Id,Question_Order_No__c = 1),
            new Question_Template__c(Subquestion_Label__c = 'before 5 years~before 10 years', Question_Type__c = 'RadioPicklist', Question_Label__c = 'When did you joined this company?', Section_Question__c = sectionTemplateList[1].Id,Next_question__c='Q-1~Q-2'),
            new Question_Template__c(Subquestion_Label__c = 'before 1 year~before 2 years', Question_Type__c = 'RadioPicklist', Question_Label__c = 'When did you joined this project?', Section_Question__c = sectionTemplateList[1].Id),
            new Question_Template__c(Subquestion_Label__c = 'result', Question_Type__c = 'Result', Question_Label__c = 'Result Question?', Section_Question__c = sectionTemplateList[1].Id),
            new Question_Template__c(Subquestion_Label__c = '< 5~> 5 but < 10~> 10', Question_Type__c = 'RadioPicklist', Question_Label__c = 'How many years of IT experience do you have?', Section_Question__c = sectionTemplateList[1].Id),
            new Question_Template__c(Subquestion_Label__c = '1~2~3~4~5', Question_Type__c = 'Dropdown Picklist', Question_Label__c = 'How satisfield you are with our service?', Section_Question__c = sectionTemplateList[2].Id, Question_Order_No__c = 5),
            new Question_Template__c(Subquestion_Label__c = '1~2~3~4~5', Question_Type__c = 'RadioPicklist', Question_Label__c = 'How is your overall experience?', Section_Question__c = sectionTemplateList[3].Id),
            new Question_Template__c(Question_Type__c = 'Text', Question_Label__c = 'Where did you completed your schooling', Section_Question__c = sectionTemplateList[3].Id),
            new Question_Template__c(Question_Type__c = 'Text', Question_Label__c = 'Where did you completed your schooling', Section_Question__c = sectionTemplateList[3].Id,Question_Order_No__c = 12),
            new Question_Template__c(Subquestion_Label__c = '1~2~3~4~5', Question_Type__c = 'RadioPicklist', Question_Label__c = 'How is your overall experience?', Section_Question__c = sectionTemplateList[3].Id,Question_Order_No__c = 13)
        };
        insert qtList;
        
        List<Question_Template__c> queryList1 = [SELECT id, Name FROM Question_Template__c WHERE Id IN (:qtList[0].Id,:qtList[2].Id)];
        System.debug(':::queryList1:::'+queryList1);
        if (queryList1 != null && queryList1.size() > 1) {
            Question_Template__c q = new Question_Template__c(id = qtList[5].Id, Next_question__c=queryList1[0].Name+'~'+queryList1[1].Name);
            upsert q;        
        }
        RestRequest req1 = new RestRequest(); 
        RestResponse res1 = new RestResponse();
        
        req1.requestURI = siteurl+'/services/apexrest/smssupport';  
        req1.httpMethod = 'GET';
        req1.params.put('From','1234567890');
        req1.params.put('Body','ABCD123');
        
        RestContext.request = req1;
        RestContext.response = res1;
        SMSSupportController.processRequest();
        
        
        Visitor_Register__c vReg = new Visitor_Register__c();
        //vReg.Visitor__c = 'John';
        //vReg.Visitor_Last_Name__c = 'Honnay';
        vReg.Mobile_Number__c = '1234567890';
        vReg.Status__c = 'started';
        vReg.Question_Template__c = qtList[3].Id;
        insert vReg;
        
        
        IssueRequest_Life_Cycle__c am = new IssueRequest_Life_Cycle__c();
        am.OwnerId = UserInfo.getUserId();
        am.Facility_Name__c = acc.id;
        am.Site_Contact__c = con.id;
        am.Date_Assigned__c = system.today();
        am.Status__c='open';
        am.Priority__c = 'high';
        am.InvestigationType__c =templateList[0].id;
        am.Assessment_Form_Completion__c = 'complete';
        am.Assessment_Date_Time__c = system.today();
        am.Visitor_Register__c = vReg.Id;
        insert am;
        
        
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = siteurl+'/services/apexrest/smssupport';  
        req.httpMethod = 'GET';
        req.params.put('From','1234567890');
        req.params.put('Body','1');
        RestContext.request = req;
        RestContext.response = res;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg3 = new Visitor_Register__c();
        //vReg3.Visitor__c = 'Chris';
        //vReg3.Visitor_Last_Name__c = 'Harrison';
        vReg3.Mobile_Number__c = '123456';
        vReg3.Status__c = 'started';
        vReg3.Question_Template__c = qtList[3].Id;
        insert vReg3;
        
        RestRequest req2 = new RestRequest(); 
        RestResponse res2 = new RestResponse();
        req2.requestURI = siteurl+'/services/apexrest/smssupport';  
        req2.httpMethod = 'GET';
        req2.params.put('From','123456');
        req2.params.put('Body','1');
        RestContext.request = req2;
        RestContext.response = res2;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg4 = new Visitor_Register__c(Mobile_Number__c = '123456', Status__c = 'started', Question_Template__c = qtList[4].Id);//, Visitor__c = 'George', Visitor_Last_Name__c = 'Bailey'
        insert vReg4;
        
        RestRequest req4 = new RestRequest(); 
        RestResponse res4 = new RestResponse();
        req4.requestURI = siteurl+'/services/apexrest/smssupport';  
        req4.httpMethod = 'GET';
        req4.params.put('From','123456');
        req4.params.put('Body','2');
        RestContext.request = req4;
        RestContext.response = res4;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg5 = new Visitor_Register__c(Mobile_Number__c = '123456', Status__c = 'started', Question_Template__c = qtList[5].Id);//, Visitor__c = 'Peter', Visitor_Last_Name__c = 'Shankar'
        insert vReg5;
        
        RestRequest req5 = new RestRequest(); 
        RestResponse res5 = new RestResponse();
        req5.requestURI = siteurl+'/services/apexrest/smssupport';  
        req5.httpMethod = 'GET';
        req5.params.put('From','123456');
        req5.params.put('Body','2');
        RestContext.request = req5;
        RestContext.response = res5;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg6 = new Visitor_Register__c(Mobile_Number__c = '1234567', Status__c = 'started', Question_Template__c = qtList[7].Id);//, Visitor__c = 'Kevin', Visitor_Last_Name__c = 'Peterson'
        insert vReg6;
        
        RestRequest req6 = new RestRequest(); 
        RestResponse res6 = new RestResponse();
        req6.requestURI = siteurl+'/services/apexrest/smssupport';  
        req6.httpMethod = 'GET';
        req6.params.put('From','1234567');
        req6.params.put('Body','3');
        RestContext.request = req6;
        RestContext.response = res6;
        SMSSupportController.processRequest();
        
        
        Visitor_Register__c vReg7 = new Visitor_Register__c(Mobile_Number__c = '1234567', Status__c = 'started', Question_Template__c = qtList[8].Id);//, Visitor__c = 'Simon', Visitor_Last_Name__c = 'Jones'
        insert vReg7;
        
        RestRequest req7 = new RestRequest(); 
        RestResponse res7 = new RestResponse();
        req7.requestURI = siteurl+'/services/apexrest/smssupport';  
        req7.httpMethod = 'GET';
        req7.params.put('From','1234567');
        req7.params.put('Body','5');
        RestContext.request = req7;
        RestContext.response = res7;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg8 = new Visitor_Register__c(Mobile_Number__c = '1234567', Status__c = 'started', Question_Template__c = qtList[0].Id);//, Visitor__c = 'Ian', Visitor_Last_Name__c = 'Bishop'
        insert vReg8;
        
        RestRequest req8 = new RestRequest(); 
        RestResponse res8 = new RestResponse();
        req8.requestURI = siteurl+'/services/apexrest/smssupport';  
        req8.httpMethod = 'GET';
        req8.params.put('From','1234567');
        req8.params.put('Body','5');
        RestContext.request = req8;
        RestContext.response = res8;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg9 = new Visitor_Register__c(Mobile_Number__c = '1234567', Status__c = 'started', Question_Template__c = qtList[1].Id);//, Visitor__c = 'Mohammed', Visitor_Last_Name__c = 'Adams'
        insert vReg9;
        
        RestRequest req9 = new RestRequest(); 
        RestResponse res9 = new RestResponse();
        req9.requestURI = siteurl+'/services/apexrest/smssupport';  
        req9.httpMethod = 'GET';
        req9.params.put('From','1234567');
        req9.params.put('Body','5');
        RestContext.request = req9;
        RestContext.response = res9;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg10 = new Visitor_Register__c(Mobile_Number__c = '1234567', Status__c = 'started', Question_Template__c = qtList[10].Id);//, Visitor__c = 'Test', Visitor_Last_Name__c = 'Visitor'
        insert vReg10;
        
        RestRequest req10 = new RestRequest(); 
        RestResponse res10 = new RestResponse();
        req10.requestURI = siteurl+'/services/apexrest/smssupport';  
        req10.httpMethod = 'GET';
        req10.params.put('From','1234567');
        req10.params.put('Body','5');
        RestContext.request = req10;
        RestContext.response = res10;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg11 = new Visitor_Register__c(Mobile_Number__c = '1234567', Status__c = 'started', Question_Template__c = qtList[11].Id);//, Visitor__c = 'Test', Visitor_Last_Name__c = 'Visitor 1'
        insert vReg11;
        
        RestRequest req11 = new RestRequest(); 
        RestResponse res11 = new RestResponse();
        req11.requestURI = siteurl+'/services/apexrest/smssupport';  
        req11.httpMethod = 'GET';
        req11.params.put('From','1234567');
        req11.params.put('Body','5');
        RestContext.request = req11;
        RestContext.response = res11;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg12 = new Visitor_Register__c(Mobile_Number__c = '1234567', Status__c = 'started', Question_Template__c = qtList[12].Id);//, Visitor__c = 'Test', Visitor_Last_Name__c = 'Visitor 2'
        insert vReg12;
        
        RestRequest req12 = new RestRequest(); 
        RestResponse res12 = new RestResponse();
        req12.requestURI = siteurl+'/services/apexrest/smssupport';  
        req12.httpMethod = 'GET';
        req12.params.put('From','1234567');
        req12.params.put('Body','5');
        RestContext.request = req12;
        RestContext.response = res12;
        SMSSupportController.processRequest();
        
        Visitor_Register__c vReg13 = new Visitor_Register__c(Mobile_Number__c = '1234567', Status__c = 'started');//, Visitor__c = 'Test', Visitor_Last_Name__c = 'Visitor 3'
        insert vReg13;
        
        RestRequest req13 = new RestRequest(); 
        RestResponse res13 = new RestResponse();
        req13.requestURI = siteurl+'/services/apexrest/smssupport';  
        req13.httpMethod = 'GET';
        req13.params.put('From','1234567');
        req13.params.put('Body','5');
        RestContext.request = req13;
        RestContext.response = res13;
        SMSSupportController.processRequest();
        
        Public_Assessment__c pa2 = new Public_Assessment__c(Short_Code__c = 'Shortxyz123',Facility_Name__c = acc.Id,Assessment_Template__c = templateList[0].Id, Assessible_Object_ID__c = ''+acc.Id);
        insert pa2;
        RestRequest req14 = new RestRequest(); 
        RestResponse res14 = new RestResponse();
        req14.requestURI = siteurl+'/services/apexrest/smssupport';  
        req14.httpMethod = 'GET';
        req14.params.put('From','100000123');
        req14.params.put('Body','Shortxyz123');
        RestContext.request = req14;
        RestContext.response = res14;
        SMSSupportController.processRequest();
        system.assertNotEquals(RestContext.response.responseBody, Blob.valueOf('test'));
    }
    static testmethod void smssupport() {
        
        Public_Assessment__c pa = new Public_Assessment__c(Short_Code__c = 'xyz123');
        insert pa;
        
        String siteurl ='';
        Public_Assessment_Configuration__c pac = Public_Assessment_Configuration__c.getInstance( UserInfo.getOrganizationId() );
        if (pac != null) {

            siteurl = pac.Site_URL__c;
        } else {
            siteurl = 'https://test12345.com/customerFeedback';
            pac.Site_URL__c = siteurl;
            upsert pac;
        }
        
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = siteurl+'/services/apexrest/smssupport';  
        req.httpMethod = 'GET';
        req.params.put('From','1234567890');
        req.params.put('Body','xyz123');
        
        RestContext.request = req;
        RestContext.response = res;
        SMSSupportController.processRequest();
        
        List<Public_Assessment__c> palist = [SELECT id, name, Short_Code__c, Public_Assessment_URL__c 
                                                FROM Public_Assessment__c 
                                                WHERE Short_Code__c = 'xyz123' 
                                                LIMIT 1];
        system.assert(palist[0].Public_Assessment_URL__c != null);
        
        
        RestRequest req2 = new RestRequest(); 
        RestResponse res2 = new RestResponse();
        
        req2.params.put('From','1234567890');
        req2.params.put('Body','x');
        
        RestContext.request = req2;
        RestContext.response = res2;
        
        SMSSupportController.processRequest();
        
        RestRequest req3 = new RestRequest(); 
        RestResponse res3 = new RestResponse();
        
        req3.params.put('From','1234567890');
        req3.params.put('Body','');
        
        RestContext.request = req3;
        RestContext.response = res3;
        
        SMSSupportController.processRequest();
        
        system.assertEquals(palist.size(), 1);
    }
    static testmethod void smssupport2() {
        
        Public_Assessment__c pa = new Public_Assessment__c(Short_Code__c = 'xyz123');
        insert pa;
        
        String siteurl ='';
        Public_Assessment_Configuration__c pac = Public_Assessment_Configuration__c.getInstance( UserInfo.getOrganizationId() );
        if (pac != null) {

            siteurl = pac.Site_URL__c;
        } else {
            siteurl = 'https://test12345.com/customerFeedback';
            pac.Site_URL__c = siteurl;
            upsert pac;
        }
        
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        
        req.requestURI = siteurl+'/services/apexrest/smssupport';  
        req.httpMethod = 'GET';
        req.params.put('From','1234567890');
        req.params.put('Body','get xyz123');
        
        RestContext.request = req;
        RestContext.response = res;
        SMSSupportController.processRequest();
        
        List<Public_Assessment__c> palist = [SELECT id, name, Short_Code__c, Public_Assessment_URL__c 
                                                FROM Public_Assessment__c 
                                                WHERE Short_Code__c = 'xyz123' 
                                                LIMIT 1];
        system.assert(palist[0].Public_Assessment_URL__c != null);
        
        
        RestRequest req2 = new RestRequest(); 
        RestResponse res2 = new RestResponse();
        
        req2.requestURI = siteurl+'/services/apexrest/smssupport';  
        req2.httpMethod = 'GET';
        req2.params.put('From','1234567890');
        req2.params.put('Body','get x');
        
        RestContext.request = req2;
        RestContext.response = res2;
        
        SMSSupportController.processRequest();
        
        RestRequest req3 = new RestRequest(); 
        RestResponse res3 = new RestResponse();
        
        req3.requestURI = siteurl+'/services/apexrest/smssupport';  
        req3.httpMethod = 'GET';
        req3.params.put('From','1234567890');
        req3.params.put('Body','get ');
        
        RestContext.request = req3;
        RestContext.response = res3;
        
        SMSSupportController.processRequest();
        system.assertEquals(palist.size(), 1);
    }
}