src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Create_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</description>
        <inlineHelpText>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</inlineHelpText>
        <label>Create Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>TemplateFlag__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Flag to include the template in creating deficiency in Multi Assessment Manager</inlineHelpText>
        <label>Multi Assessment Mode?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Focus_category__c</fullName>
        <description>Group which will have questions from different sections</description>
        <inlineHelpText>Group which will have questions from different sections</inlineHelpText>
        <label>Focus category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Single_Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to next question in decision tree</description>
        <inlineHelpText>Lookup to next question in decision tree</inlineHelpText>
        <label>Single Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_Of_Question__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is the question weight</inlineHelpText>
        <label>Question Weight</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Account_to_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup object that will be used in a survey.So we are not using user but accounts to create number of surveys.The no of surveys would be same as no of accounts whose craete_survey field(on Account object) is set to true</description>
        <inlineHelpText>If the response is related to a specific account it will be listed here.</inlineHelpText>
        <label>Account to Response</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Taker_user__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the user that provided the answer if this is known.</inlineHelpText>
        <label>Questionnaire Taker(user)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>0 to 100%</inlineHelpText>
        <label>Section Weight (%)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Procedurecontroller.cls
public with sharing class Procedurecontroller {
    public List<Account> childAccountLists { get; set; }
    public List<SelectOption> childAccOptionLists { get; set; }
    public List<Question_Template__c> questionsLists { get; set; }
    
    public List<SelectOption> questionOptionLists { get; set; }
    public String questionid{get;set;}
    public Question_Template__c selectedQuestion{get;set;}
    public List<SelectOption> ansOptionLists { get; set; }
    public List<Questionnaire_Response__c> ansLists{ get; set; }
    public List<Section_Template__c > sectionsLists{ get; set; }
    public List<SelectOption> sectionOptionLists { get; set; }
    public String sectionid{get;set;}
    public List<Main_questionaire__c> alltemplateLists { get; set; }
    public List<SelectOption> templateLists { get; set; }
    public String templateName{get;set;}
    public String templateid{get;set;}
    
    public String accountId{get;set;}
    public String accountName{get;set;}
    public Questionnaire_Response__c response{get;set;}
    public String[] multi{get;set;}
    public List<Attachment> allFileList {get; set;} //max 5
   //public Account  acc{ get; set; }//this is the child account of the main school i.e room1,room2,play area etc   
   
    public Procedurecontroller (ApexPages.StandardController controller){
        try{
            SFDCAccessController accessForAT = ExAMUtilClass.AccessController;
            List<String> fieldsListAT = new List<String>{'ExAM__Template_name__c','ExAM__TemplateFlag__c'};
            accessForAT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Main_questionaire__c'), fieldsListAT);
                
            response=new Questionnaire_Response__c();
            sectionOptionLists =new List<SelectOption>();
            questionOptionLists =new List<SelectOption>();
            sectionOptionLists =new List<SelectOption>();
            questionOptionLists =new List<SelectOption>();
            childAccOptionLists =new List<SelectOption>();
            allFileList = new List<Attachment>() ;
            accountName ='Emergency Procedures';
            multi= new String[]{};
            childAccountLists =[select id,name from account where name=:accountName ];
            System.debug('~~1~~'+accountId+','+accountName+',,,'+childAccountLists );
            templateName='Emergency Procedures';  
            ansOptionLists  = new List<SelectOption>();   
            alltemplateLists = [Select Id, Name,Template_name__c,TemplateFlag__c  from Main_questionaire__c where Template_name__c=:templateName order by Template_name__c ];
            if((alltemplateLists!=null) &&(alltemplateLists.size()>0))
            {
                templateid=alltemplateLists[0].id;
            }
            multi= new String[]{};
            if((templateid!=null)&&(templateid!='None'))
                { if(sectionOptionLists!=null){sectionOptionLists =new List<SelectOption>();}
            //Get all the sections list
            
            List<String> fieldsListST = new List<String>{'ExAM__status__c','ExAM__Section_Weight__c','ExAM__Section_label__c','ExAM__Order_No__c','ExAM__Questionnaire_Section__c'};
            accessForAT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Section_Template__c'), fieldsListST);
            
            sectionsLists = [Select Id, Name,status__c,Section_Weight__c,Section_label__c,Order_No__c from Section_Template__c where Questionnaire_Section__c=:templateid order by Order_No__c];
            sectionOptionLists.add(new SelectOption('None','None'));
            for(Section_Template__c res: sectionsLists ) 
                {
                    sectionOptionLists.add(new SelectOption(res.id,res.Section_label__c));
                }    
                System.debug('~~~section list'+  sectionsLists.size());                
            }
            questionsLists=null;  
        } catch(Exception e){
             ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    }
    
    public void setQuestions()
    {
        try{
            System.debug('~~~Template'+templateid+',sectionid'+sectionid);questionsLists =null;
            questionOptionLists =new List<SelectOption>();
            ansOptionLists  = new List<SelectOption>();  
            multi= new String[]{};
            
            SFDCAccessController accessForQT = ExAMUtilClass.AccessController;
            
            List<String> fieldsListOpT = new List<String>{'ExAM__Help_Text__c','ExAM__Weight__c'};
            accessForQT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Answer_Option__c'), fieldsListOpT);
            
            List<String> fieldsListQT = new List<String>{'ExAM__Section_Question__c','ExAM__Question_Label__c','ExAM__Weight_of_Answer__c','ExAM__Subquestion_Label__c','ExAM__Question_Order_No__c','ExAM__Question_Type__c'};
            accessForQT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Question_Template__c'), fieldsListQT);
            
            if((templateid!=null)&&(sectionid!=null)&&(sectionid!='None')&&(templateid!='None'))
            {
              //Get all the sections list
               questionsLists = [SELECT  Id,Section_Question__c,Question_Label__c,Weight_of_Answer__c,Subquestion_Label__c,Question_Order_No__c,Question_Type__c,
                                 (SELECT Id,Name,Help_Text__c,Weight__c FROM Answer_Options__r)
                                 FROM Question_Template__c 
                                 WHERE (Section_Question__c=:sectionid ) ORDER BY Question_Order_No__c]; 
               questionOptionLists.add(new SelectOption('None','None'));
               for(Question_Template__c res: questionsLists ) 
                  {
                     questionOptionLists.add(new SelectOption(res.id,res.Question_Label__c));
                  }                  
             }  System.debug('~~~question list'+  questionsLists .size());  
         }     
         catch(Exception e){
             ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
         }
    }
    
    public void setAnswers()
    {System.debug('~~~~s'+templateid+',sec'+sectionid);System.debug('~~~questionid'+questionid);
        if((templateid!=null)&&(sectionid!=null)&&(questionid!=null)&&(questionid!='None')&&(sectionid!='None')&&(templateid!='None'))
        {
            //assuming always new record is created for edit we will provide separate functionality
            /*ansLists = [Select id,Response__c,Question_Template__r.Section_Question__r.id,Question_Template__c,Account_to_Response__c,Issue_Request__c,Questionnaire_Taker_user__c,(SELECT Id,Title,body,CreatedDate,Owner.FirstName,Owner.LastName FROM Notes order by CreatedDate)  from Questionnaire_Response__c where Issue_Request__c=:issueId AND Question_Template__r.Section_Question__r.id=:questionid]; 
            
            if(ansLists.size()==0)
            {*/
                ansOptionLists  = new List<SelectOption>();  
                
                //response.Account_to_Response__c=accountId;
                System.debug('~~~'+questionid+'~~~~');
                if(questionsLists.size()>0)
                {
                 for(Question_Template__c res: questionsLists ) 
                  {System.debug('~~~'+questionid+'~~~~'+res.id);
                   if(questionid==res.id)
                   {response.Question_Template__c=res.id; selectedQuestion=res;
                     if(res.Question_Type__c.equalsIgnoreCase('RadioPicklist') 
                        || res.Question_Type__c.equalsIgnoreCase('Horizontal Radiopicklist') )
                         {
                                String qoptionValues = '';
                                List<String> ls = new List<String>();
                                if ( res.Answer_Options__r.size() == 0 ){
                                    qoptionValues = res.Subquestion_Label__c;
                                    if ( qoptionValues != null ){
                                        ls = qoptionValues.split('~');
                                    }
                                } else {
                                    for( Answer_Option__c ansOpt :res.Answer_Options__r ){
                                        if ( ansOpt != null && ansOpt.Name != null && ansOpt.Name != '' ){
                                            ls.add(ansOpt.Name);
                                        }
                                    }
                                }  
                                if ( ls.size() > 0 ){
                                    for(String s: ls) 
                                    {                   
                                        ansOptionLists.add(new SelectOption(s,s));                   
                                    }   
                                }
                                System.debug('-----radio picklist:'+qoptionValues); 
                                //response.Question_Template__r.Question_Type__c='RadioPicklist';
                                     
                         } 
                          else if(res.Question_Type__c.equalsIgnoreCase('Text'))
                         {
                                 System.debug('-----text:'); 
                                 if (res.Subquestion_Label__c != null && res.Answer_Options__r.size() == 0 ) {
                                     response.Response__c = res.Subquestion_Label__c;
                                 } else if( res.Answer_Options__r.size() > 0 ) {
                                     response.Response__c = res.Answer_Options__r[0].Name;
                                 }   
                                // response.Question_Template__r.Question_Type__c='Text';         
                         }
                          else if(res.Question_Type__c.equalsIgnoreCase('MultiselectPicklist'))
                         {
                                String[] multilist = new String[]{};
                                String qoptionValues = '';
                                List<String> ls = new List<String>();
                                if ( res.Answer_Options__r.size() == 0 ){
                                    qoptionValues = res.Subquestion_Label__c;
                                    if ( qoptionValues != null ){
                                        ls = qoptionValues.split('~');
                                    }
                                } else {
                                    for( Answer_Option__c ansOpt :res.Answer_Options__r ){
                                        if ( ansOpt != null && ansOpt.Name != null && ansOpt.Name != '' ){
                                            ls.add(ansOpt.Name);
                                        }
                                    }
                                } 
                                if ( ls.size() > 0 ){ 
                                    for(String s: ls) {                   
                                        ansOptionLists.add(new SelectOption(s,s));                   
                                    }  
                                }
                                System.debug('-----multi:'+   qoptionValues); 
                                           
                         }       
                    break;
                   }
                   
                  }//for(Question_Template__c res: questionsLists ) 
                }//if(questionsLists .size()>0)
                
          /*  }
            else
            {
             //record already exists
             response=ansLists[0];
            
            }*/
            
           //return options;
        }
        else
        {//return null;
        }
    }
     public PageReference cancel()
     {
        PageReference cancelClicked=new PageReference(ApexPages.currentPage().getUrl());
        cancelClicked.setRedirect(true);
        return cancelClicked;
     }
    

    
 
        public static testMethod void Procedurecontroller_Test()
        {
            //Test converage for the visualforce page
            PageReference pageRef = Page.Procedures ;
            Test.setCurrentPageReference(pageRef);
            Test.startTest();
            Main_questionaire__c maintest=new Main_questionaire__c (Template_name__c ='Emergency Procedures',TemplateFlag__c=true);
            upsert maintest;
            Account acc=new Account(name='Emergency Procedures',Create_Survey__c=true); upsert acc; 
           
            Section_Template__c sc= new Section_Template__c(Questionnaire_Section__c=maintest.id,Section_label__c='test section'); 
             insert sc;
             Section_Template__c sc1= new Section_Template__c(Questionnaire_Section__c=maintest.id,Section_label__c='test section 2'); 
             insert sc1;
             
             Question_Template__c scq= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your name?',Question_Order_No__c=1,Question_Type__c='Text',Focus_category__c='CCTV',Subquestion_Label__c='text value',Weight_of_Answer__c='4');     
             Question_Template__c scqp= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=2,Weight_Of_Question__c=2,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Perimeter',Weight_of_Answer__c='2~3');     
             Question_Template__c scqm= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your qualification?',Question_Order_No__c=3,Question_Type__c='MultiselectPicklist',Subquestion_Label__c='High School~Bachelors~Masters',Focus_category__c='Emergency Response Plan',Weight_of_Answer__c='2~3~4');     
             Question_Template__c scqp1= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=4,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Adequate Lighting',Weight_of_Answer__c='2~3');     
             Question_Template__c scqm1= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your qualification?',Question_Order_No__c=5,Question_Type__c='MultiselectPicklist',Subquestion_Label__c='High School~Bachelors~Masters',Focus_category__c='Adequate Locking System');     
             Question_Template__c scqp2= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=6,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Mail Handling');     
          
             insert scq;insert scqp;insert scqm;insert scqp1;insert scqm1;insert scqp2;
            
            ApexPages.StandardController scont = new ApexPages.StandardController(maintest);
            Procedurecontroller d= new Procedurecontroller(scont ); 
            d.alltemplateLists.add(maintest);
            d.accountId=acc.id;
            d.accountName=acc.name;
            d.templateid=maintest.id;
            
            d.sectionid=sc.id;
            d.sectionsLists=new List<Section_Template__c>();
            d.childAccountLists =new List<Account>();
            d.childAccountLists.add(acc);
            //d.childAccountLists[1] =[select id,name,parent.id,parent.name from account where parent.id=:acc.id];
           
            //d.childAccountLists[0].parent.id=acc.id;d.childAccountLists[0].parent.name=acc.name;
            d.questionsLists=new List<Question_Template__c >();
            d.sectionsLists.add(sc);d.sectionsLists.add(sc1);
            d.questionsLists.add(scq);d.questionsLists.add(scqp);d.questionsLists.add(scqm);
            d.selectedQuestion=scqp;
            d.questionid=d.selectedQuestion.id;
            System.assert(d.questionid!=null);
            d.setQuestions();d.setAnswers();
            d.response.Response__c='10-30';
            d.response.Question_Template__c=d.selectedQuestion.id;
           d.cancel();
            
            
            //System.assert(d.setwtTemplate()==null,'sectionslist returns  null');
            Test.stopTest();
     
}
 
 
 
 }