src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adequate_Lighting_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adequate Lighting Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Adequate_Locking_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adequate Locking Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCTV_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is the total CCTV</inlineHelpText>
        <label>CCTV Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Create_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</description>
        <inlineHelpText>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</inlineHelpText>
        <label>Create Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Questionnaire_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Each account should be related to a Template</inlineHelpText>
        <label>Main_Questionnaire_Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Overall Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mobile_Incident_Report_Form__c.object
<CustomObject>
    <description>Used to support event and incident reporting.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Drug/Alcohol Offenses</fullName>
                </value>
                <value>
                    <fullName>Crimes Against Persons</fullName>
                </value>
                <value>
                    <fullName>Crimes Against Property</fullName>
                </value>
                <value>
                    <fullName>Security Threats</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Incident_Location__c</fullName>
        <label>Incident Location Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Incident_Score__c</fullName>
        <label>Incident Score</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mobile Incident Report</label>
    <nameField>
        <label>Mobile Incidence Reporting Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Incident Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncidentLocationMAPController.cls
public with sharing class IncidentLocationMAPController {

//not needed this class
    public List<Mobile_Incident_Report_Form__c> incidents{get;set;}//=new List<Mobile_Incident_Report_Form__c>();
    public String ErrorMsg {get; set;}
       
    public String getincidentslist()
    {    
        try{
            SFDCAccessController accessForobj = ExAMUtilClass.AccessController;
            List<String> fieldsList = new List<String>{'ExAM__Category__c','ExAM__Incident_Location__c','ExAM__Location__Latitude__s','ExAM__Location__Longitude__s','ExAM__Incident_Score__c'};
            accessForobj.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Mobile_Incident_Report_Form__c'), fieldsList);
            incidents=[SELECT id,name,Category__c,Incident_Location__c,Location__Latitude__s,Location__Longitude__s,Incident_Score__c from Mobile_Incident_Report_Form__c];
        
           // return JSON.serialize(incidents);
        }catch(Exception ex)
        {
            ErrorMsg = ex.getmessage();
            
        }
        return JSON.serialize(incidents);
    }

 /*public static testMethod void testlistacc()
 {
    DisplayLocationMapT2 d= new DisplayLocationMapT2();
    Test.startTest();
    Main_questionaire__c maintest=new Main_questionaire__c (Template_name__c ='test');
    upsert maintest;
    Account acc=new Account(BillingStreet='2425 Wilson Blvd',BillingCity='arlington',BillingPostalCode='22209',BillingCountry='USA',name='test account',Adequate_Lighting_Score__c=0,Adequate_Locking_Score__c=8,CCTV_Score__c=8,Overall_Score__c=16,Create_Survey__c=true);
    acc.Main_Questionnaire_Template__c=maintest.id;
    upsert acc;
    List<Locations> accountstest=new List<Locations>();
    
    accountstest=d.getlistacc();
    Test.stopTest();
     
     
     System.assert(accountstest!=null,'Account is null');
     
 }*/
}