src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adequate_Lighting_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adequate Lighting Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Adequate_Locking_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adequate Locking Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CCTV_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is the total CCTV</inlineHelpText>
        <label>CCTV Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Create_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</description>
        <inlineHelpText>This field would be used in the code to create a survey for an account or not, so System Admin has to check this field to create a survey</inlineHelpText>
        <label>Create Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Emergency_Response_Plan__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Emergency Response Plan Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mail_Handling_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Mail Handling Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Main_Questionnaire_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Each account should be related to a Template</inlineHelpText>
        <label>Main_Questionnaire_Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Overall Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Perimeter_Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Perimeter Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessment_Form_Completion__c</fullName>
        <inlineHelpText>The for the team needs to fill for each investigation type</inlineHelpText>
        <label>Assessment Form Completion</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <inlineHelpText>If scoring has been implemented for this Assessment the total score achieved in the Assignment will be recorded here.</inlineHelpText>
        <label>Total Score</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the organization for which the template is created</description>
        <inlineHelpText>This is the main organization for which the template is created e.g. DOI etc.This has child accounts for each school and school has child accounts of facility or surveys</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Main_Questionnaire_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_Report_Data__c.object
<CustomObject>
    <description>Used to support the consolidation of data for ExAM to Wave automation.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is for what we are taking survey its a school or facility within a school.They have hierarchical relationship</inlineHelpText>
        <label>School or Facility</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Main Report Data</relationshipLabel>
        <relationshipName>Main_Report_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Main Report Data</relationshipLabel>
        <relationshipName>Main_Report_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questionnaire Response</label>
        <referenceTo>Questionnaire_Response__c</referenceTo>
        <relationshipLabel>Main Report Data</relationshipLabel>
        <relationshipName>Main_Report_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Main Report Data</label>
    <nameField>
        <label>Main Report Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Main Report Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Focus_category__c</fullName>
        <description>Group which will have questions from different sections</description>
        <inlineHelpText>Group which will have questions from different sections</inlineHelpText>
        <label>Focus category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Single_Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to next question in decision tree</description>
        <inlineHelpText>Lookup to next question in decision tree</inlineHelpText>
        <label>Single Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Account_to_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup object that will be used in a survey.So we are not using user but accounts to create number of surveys.The no of surveys would be same as no of accounts whose craete_survey field(on Account object) is set to true</description>
        <inlineHelpText>If the response is related to a specific account it will be listed here.</inlineHelpText>
        <label>Account to Response</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>This is the priority of the Answer being provided.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <description>For responses which are negative i.e like N/A or for any response which u do not want to put negative and this question would not be counted in total question score and max score.this is user score or issue score</description>
        <formula>if( Weight_Response__c&lt;0,0,((Weight_Response__c/100)* Question_Template__r.Weight_Of_Question__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total number of points achieved by a specific Answer record.</inlineHelpText>
        <label>Total Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DisplayLocationMapT2.cls
public with sharing class DisplayLocationMapT2
{
     public List<Locations> accounts;
     public Account[] accLists { get; set; }
    
     public List<Account> allaccounts=new List<Account>();
     public List<Main_Report_Data__c> allreportdata=new List<Main_Report_Data__c>();
     public integer MailHandlingScore=0;
     public integer CCTVScore=0;
     public integer PerimeterScore=0;
     public integer AdequateLightingScore=0;
     public integer AdequateLockingScore=0;
     public integer EmergencyResponsePlanScore=0;
     public integer OverallScore=0;
    //public = new QuestionDisplay[]{};
  
/*public List<Locations> getlistacc()
    {
       accounts=[SELECT id,BillingStreet,BillingCity,BillingPostalCode,BillingCountry,name From Account where BillingStreet <>NULL and BillingPostalCode<>NULL];
       System.debug('!!!!!!!!!!!!!!!!! accoount-'+accounts);
       //System.debug('!!!!!!!!!!!!!!!!! acoount-'+accounts);
       return accounts;
    }


public void EditScores()
{
 accLists=new Account[]{};
 accounts= new Locations[]{};
 List<aggregateResult> aggr=[
   Select Account__c, Question_Template__r.Focus_category__c focus, SUM(Questionnaire_Response__r.Total_Score__c)total
   from Main_Report_Data__c
   GROUP BY Account__c, Question_Template__r.Focus_category__c];
    for (Account acc : [SELECT id,BillingStreet,BillingCity,BillingPostalCode,BillingCountry,name,Adequate_Lighting_Score__c,Adequate_Locking_Score__c,CCTV_Score__c,Emergency_Response_Plan__c,Mail_Handling_Score__c,Overall_Score__c,Perimeter_Score__c,Create_Survey__c From Account where Create_Survey__c=:true])
       {  
           acc.Overall_Score__c=0;
           for (AggregateResult ar : aggr)
           {
             
             String accid=String.valueOf(ar.get('Account__c'));
            
              if(accid.equalsIgnoreCase(acc.id))
              {
              String focuscat=String.valueOf(ar.get('focus')); 
              System.debug('account id:'+acc.id+'focus category:'+focuscat);
              acc.Overall_Score__c+=Integer.valueOf(ar.get('total'));
                  if(focuscat.equalsIgnoreCase('CCTV'))
                  {
                  System.debug('ccccccccccctvfocuscat'+focuscat);
                    acc.CCTV_Score__c=Integer.valueOf(ar.get('total'));
                  
                  }
                  else if(focuscat.equalsIgnoreCase('Perimeter'))
                  {
                 
                    acc.Perimeter_Score__c=Integer.valueOf(ar.get('total'));
                  
                  }
                   else if(focuscat.equalsIgnoreCase('Adequate Lighting'))
                  {
                 
                    acc.Adequate_Lighting_Score__c=Integer.valueOf(ar.get('total'));
                  
                  }
                   else if(focuscat.equalsIgnoreCase('Adequate Locking System'))
                  {
                  
                    acc.Adequate_Locking_Score__c=Integer.valueOf(ar.get('total'));
                  
                  }
                   else if(focuscat.equalsIgnoreCase('Emergency Response Plan'))
                  {
                 
                    acc.Emergency_Response_Plan__c=Integer.valueOf(ar.get('total'));
                  
                  }
                   else if(focuscat.equalsIgnoreCase('Mail Handling'))
                  {
                 
                    acc.Mail_Handling_Score__c=Integer.valueOf(ar.get('total'));
                  
                  }
                  
                   
                 
                   
             */ 
             
          //    }//if stmt
              
      //     }//for inner of aggr
     //   accounts.add(new Locations(acc));
     //   accLists.add(acc); 

//}
 // Creates section List
public List<Locations> getlistacc()
{
    
   try{
       SFDCAccessController accessForobj = ExAMUtilClass.AccessController;
       List<String> fieldsList = new List<String>{'ExAM__Main_Questionnaire_Template__c','ExAM__Adequate_Lighting_Score__c','ExAM__Adequate_Locking_Score__c','ExAM__CCTV_Score__c','ExAM__Emergency_Response_Plan__c','ExAM__Mail_Handling_Score__c','ExAM__Overall_Score__c','ExAM__Perimeter_Score__c','ExAM__Create_Survey__c'};
       accessForobj.assertAuthorizedToView(Schema.getGlobalDescribe().get('Account'), fieldsList);
       
       List<String> fieldsList1 = new List<String>{'ExAM__Priority__c','ExAM__InvestigationType__c','ExAM__Assessment_Form_Completion__c'};
       accessForobj.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__IssueRequest_Life_Cycle__c'), fieldsList1);
       
       List<String> fieldsList2 = new List<String>{'ExAM__Template_name__c'};
       accessForobj.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Main_questionaire__c'), fieldsList2);
       
       accLists=[SELECT id,Main_Questionnaire_Template__r.Template_name__c,Main_Questionnaire_Template__c,BillingStreet,BillingCity,BillingPostalCode,BillingCountry,name,Adequate_Lighting_Score__c,Adequate_Locking_Score__c,CCTV_Score__c,Emergency_Response_Plan__c,Mail_Handling_Score__c,Overall_Score__c,Perimeter_Score__c,Create_Survey__c,(SELECT Id,Facility_Name__c,Priority__c,InvestigationType__c,Assessment_Form_Completion__c,CreatedDate FROM Issue_Request_Life_Cycles__r) From Account where (BillingStreet <>NULL OR BillingCity<>NULL)and BillingPostalCode<>NULL];
       accounts= new Locations[]{};
      
       for (Account a :accLists )
           {  
             String addr=a.BillingStreet+','+a.BillingCity+','+a.BillingPostalCode+','+a.BillingCountry;
             System.debug('----'+   a.id+','+a.name+','+a.Issue_Request_Life_Cycles__r);
             accounts.add(new Locations(a.id,a.name,addr,a.Adequate_Lighting_Score__c,a.Adequate_Locking_Score__c,a.CCTV_Score__c,a.Emergency_Response_Plan__c,a.Mail_Handling_Score__c,a.Overall_Score__c,a.Perimeter_Score__c,a.Issue_Request_Life_Cycles__r));
            
            }
            System.debug('----'+accounts);
             // Add Question Records
          /*  for (Account a : [SELECT id,color__c,Adequate_Lighting_Score__c,Adequate_Locking_Score__c,CCTV_Score__c,Emergency_Response_Plan__c,Mail_Handling_Score__c,Overall_Score__c,Perimeter_Score__c,BillingStreet,BillingCity,BillingPostalCode,BillingCountry,name From Account where BillingStreet <>NULL and BillingPostalCode<>NULL]){
                String addr=a.BillingStreet+','+a.BillingCity+','+a.BillingPostalCode+','+a.BillingCountry;
                
                
                accounts.add(new Locations(a.id,a.name,addr,a.color__c) ); 
            }*/
          
            
          return accounts;
      }catch(Exception e){
          accounts= new Locations[]{};
          String ErrorMsg = e.getMessage();
          accounts.add(new Locations(ErrorMsg));
          return accounts;
      }
    }
    
    // Create an inner class
    public class Locations{
        public String accountid {get; set;}
        public String accountname {get; set;}
        public String accountaddress {get; set;}
        public String accountcolor{get;set;}
        public Decimal accountLightingScore {get; set;}
        public Decimal accountLockingScore {get; set;}
        public Decimal accountCCTVScore {get; set;}
        public Decimal accountEResponseScore{get;set;}   
        public Decimal accountMailHandlingScore{get;set;}
        public Decimal accountOverallScore{get;set;}
        public Decimal accountPerimeterScore{get;set;}   
        public Account accountobj{get;set;}
        public List<IssueRequest_Life_Cycle__c> issueLists { get; set; }
        public String ErrorMsg{get;set;}
        public  Locations(String aid,String aname,String aaddress,Decimal Lighting_Score,Decimal Locking_Score,Decimal CCTV_Score,Decimal Emergency_Response_Score,Decimal Mail_Handling_Score,Decimal Overall_Score,Decimal Perimeter_Score,list<IssueRequest_Life_Cycle__c> ilist)
        {
            accountid=aid;
            accountname=aname;
            accountaddress=aaddress;
            accountLightingScore =Lighting_Score;  
            accountLockingScore=Locking_Score;
            accountCCTVScore =CCTV_Score;
            accountEResponseScore=Emergency_Response_Score;
            accountMailHandlingScore=Mail_Handling_Score;  
            accountOverallScore           =Overall_Score;
            accountPerimeterScore           =Perimeter_Score;
            issueLists =new List<IssueRequest_Life_Cycle__c>();
            issueLists =ilist;
                     
        }
        public  Locations(String errmsg){
            ErrorMsg = errmsg;
        }
        /* public  Locations(Account accnt)
         {
         accountobj=accnt;
         }*/
    }

 public static testMethod void testlistacc()
 {
    DisplayLocationMapT2 d= new DisplayLocationMapT2();
    Test.startTest();
    Main_questionaire__c maintest=new Main_questionaire__c (Template_name__c ='test');
    upsert maintest;
    Account acc=new Account(BillingStreet='2425 Wilson Blvd',BillingCity='arlington',BillingPostalCode='22209',BillingCountry='USA',name='test account',Adequate_Lighting_Score__c=0,Adequate_Locking_Score__c=8,CCTV_Score__c=8,Overall_Score__c=16,Create_Survey__c=true);
    acc.Main_Questionnaire_Template__c=maintest.id;
    upsert acc;
    List<Locations> accountstest=new List<Locations>();
    
    accountstest=d.getlistacc();
    Test.stopTest();
     
     //assert results
     System.assert(accountstest!=null,'Account is null');
     
 }
}