src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public_Assessment_URL__c</fullName>
        <label>Public Assessment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visitor_Register__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Salesforce ID of the Visitor record associated with this Assignment Manager. This field is only populated when the data collection effort takes place outside of Salesforce for example when a public assessment link is being used.</inlineHelpText>
        <label>Visitor Register</label>
        <referenceTo>Visitor_Register__c</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment__c.object
<CustomObject>
    <description>Used to support the collection of information necessary to perform data collections that primarily occur outside of Salesforce.</description>
    <fields>
        <fullName>Assessible_Object_ID__c</fullName>
        <inlineHelpText>This is the Salesforce record ID of the Assessable Object.</inlineHelpText>
        <label>Assessable Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assessment Template ID that is being used for the Assessment.</inlineHelpText>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public_Assessment_URL__c</fullName>
        <formula>$Setup.Public_Assessment_Configuration__c.Site_URL__c + &apos;/ExAM__AMAndAnswerCreationPage?paId=&apos;+ Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the full URL that can be used to access this Public Assessment.</inlineHelpText>
        <label>Public Assessment URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <inlineHelpText>If you are using our Twillio integration to support SMS interactions over Public Assessments this code is what your end user will text in order to fire start engaging with this template.</inlineHelpText>
        <label>Short Code</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Public Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Public Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Single_Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to next question in decision tree</description>
        <inlineHelpText>Lookup to next question in decision tree</inlineHelpText>
        <label>Single Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Visitor_Register__c.object
<CustomObject>
    <description>Used to collect information on ExAM Assessment participants. Enables analysis against visitors and participants in ExAM data collections.</description>
    <fields>
        <fullName>Mobile_Number__c</fullName>
        <label>Mobile Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Public_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Public Assessment</label>
        <referenceTo>Public_Assessment__c</referenceTo>
        <relationshipLabel>Visitor Register</relationshipLabel>
        <relationshipName>Visitor_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Visitor Register</relationshipLabel>
        <relationshipName>Visitor_Register</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Visitor Register</label>
    <nameField>
        <label>Visitor Register Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitor Register</pluralLabel>
    <recordTypes>
        <fullName>SMS_Survey</fullName>
        <active>true</active>
        <label>SMS Survey</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SMSSupportController.cls
@RestResource(urlMapping='/smssupport')
global class SMSSupportController {

    @HttpGET
    global static void processRequest() {
        
        String inputCode='', mobileNumber='';
        
        String responseString = '';
        
        RestRequest req = RestContext.request;
        RestResponse restResp = RestContext.response;
        
        mobileNumber = req.params.get('From');
        inputCode = req.params.get('Body');    // send public assessable Id value ie. 'PA'
        
        system.debug('::mobileNumber:::'+mobileNumber);
        system.debug('::inputCode:::'+inputCode);
        try {

            if (String.isNotBlank(inputCode)) {            
                if (String.isNotBlank(mobileNumber)) {                
                    if (inputCode.startswithIgnoreCase('get ')) {
                        inputCode = inputCode.removeStartIgnoreCase('get ');
                        inputCode = inputCode.trim();
                        System.debug(':::inputCod:::'+inputCode);
                        if (inputCode != null && inputCode != '') {

                            List<Public_Assessment__c> pubAssList = [
                                SELECT Assessible_Object_ID__c, Assessment_Template__c, Facility_Name__c, ID, Public_Assessment_URL__c, Short_Code__c
                                FROM   Public_Assessment__c
                                WHERE  Public_Assessment_URL__c != null AND Public_Assessment_URL__c != '' AND Short_Code__c = :inputCode LIMIT 1
                            ];
                    
                            if (pubAssList != null && pubAssList.size() > 0) {
                                responseString = pubAssList[0].Public_Assessment_URL__c;
                            } else {
                                responseString = 'Invalid code';
                            }
                        } else {
                            responseString = 'Please send valid format';// <get> <code> 
                        }
                    } else {

                        //Start IVR SMS
                        List<RecordType> reportTypeList = [
                            SELECT DeveloperName, Id, SObjectType 
                            FROM   RecordType
                            WHERE  SObjectType = 'ExAM__Visitor_Register__c' AND DeveloperName ='SMS_Survey' LIMIT 1
                        ];
                        inputCode = inputCode.trim();
                        string amid = '';

                        List<Visitor_Register__c> visRegList = [
                            SELECT Id, Mobile_Number__c,Question_Template__c, //mobile, question
                                   Question_Template__r.Question_Label__c, Question_Template__r.Subquestion_Label__c,
                                   Question_Template__r.Next_Question__c, Question_Template__r.Section_Question__c,
                                   Question_Template__r.Section_Question__r.Questionnaire_Section__c,
                                   Question_Template__r.Question_Order_No__c, Status__c
                            FROM   Visitor_Register__c 
                            WHERE  Mobile_Number__c = :mobileNumber ORDER BY createddate DESC LIMIT 1                        
                        ];
                        if (visRegList != null && !visRegList.isEmpty() && visRegList[0].Status__c != 'Completed' ) {

                            List<IssueRequest_Life_Cycle__c> queryAMList = [SELECT Id, Visitor_Register__c FROM IssueRequest_Life_Cycle__c WHERE Visitor_Register__c = :visRegList[0].Id LIMIT 1];

                            Map<Id,Question_Template__c> quesIdWithRecMap = new Map<Id,Question_Template__c>([
                                SELECT Id, Next_Question__c, Subquestion_Label__c,
                                       (SELECT Dependent_Question__c, Dependent_Question__r.Name, Help_Text__c, Id, Name, Next_Question__c, Next_Question__r.Name, Weight__c FROM Answer_Options__r)
                                FROM   Question_Template__c
                                WHERE  Id = :visRegList[0].Question_Template__c]);

                            if (queryAMList != NULL && queryAMList.size() > 0) {
                                amid = queryAMList[0].Id; 
                            } else {
                                if (visRegList[0].Question_Template__c != null) {

                                    IssueRequest_Life_Cycle__c newAssignManager = new IssueRequest_Life_Cycle__c();
                                    newAssignManager.Visitor_Register__c = visRegList[0].Id;
                                    newAssignManager.InvestigationType__c = visRegList[0].Question_Template__r.Section_Question__r.Questionnaire_Section__c;
                                    insert newAssignManager;
                                    amid = newAssignManager.Id;
                                }
                            }
                            if ( (visRegList[0].Question_Template__c != NULL && visRegList[0].Question_Template__r.Subquestion_Label__c != null)
                                 || (quesIdWithRecMap != NULL && visRegList[0].Question_Template__c != NULL && 
                                     quesIdWithRecMap.containsKey(visRegList[0].Question_Template__c) && 
                                     quesIdWithRecMap.get(visRegList[0].Question_Template__c).Answer_Options__r.size() > 0)
                            ) {
                                if (inputCode.isNumeric()) {
                                    integer inputVal = integer.valueOf(inputCode);
                                    List<String> answerOptionList = new List<String>();
                                    if( quesIdWithRecMap.values().size() > 0 ){
                                        if ( quesIdWithRecMap.get(visRegList[0].Question_Template__c).Answer_Options__r.size() == 0 ){
                                            answerOptionList = visRegList[0].Question_Template__r.Subquestion_Label__c.split('~');
                                        }
                                        else {
                                            for( Answer_Option__c ansOpt :quesIdWithRecMap.get(visRegList[0].Question_Template__c).Answer_Options__r ){
                                                if ( ansOpt != null && ansOpt.Name != null && ansOpt.Name != '' ){
                                                    answerOptionList.add(ansOpt.Name);
                                                }
                                            }
                                        }
                                    }
                                    if (inputVal > 0 && answerOptionList.size() >= inputVal) {

                                        List<Questionnaire_Response__c> answerInsert = new List<Questionnaire_Response__c> {
                                            new Questionnaire_Response__c(Issue_Request__c = amid, Question_Template__c = visRegList[0].Question_Template__c, Response__c = answerOptionList.get(inputVal - 1))
                                        };
                                        insert answerInsert;
                                        if (visRegList[0].Question_Template__r.Next_Question__c != null || quesIdWithRecMap.get(visRegList[0].Question_Template__c).Answer_Options__r.size() > 0 ) {
                                            String questionName = '';
                                            if ( quesIdWithRecMap.get(visRegList[0].Question_Template__c).Answer_Options__r.size() == 0 ){
                                                if (visRegList[0].Question_Template__r.Next_Question__c.split('~').size() >= inputVal) {
                                                    
                                                    questionName = visRegList[0].Question_Template__r.Next_Question__c.split('~').get(inputVal-1);
                                                } else {
                                                    questionName = visRegList[0].Question_Template__r.Next_Question__c.split('~').get(0);
                                                }
                                            } else {
                                                List<String> nextList = new List<String>();
                                                for( Answer_Option__c ansOpt :quesIdWithRecMap.get(visRegList[0].Question_Template__c).Answer_Options__r ){
                                                    if ( ansOpt != null ){
                                                        nextList.add(ansOpt.Next_Question__r.Name);
                                                    }
                                                }
                                                if ( nextList.size() >= inputVal ){
                                                    questionName = nextList.get(inputVal-1);
                                                } else {
                                                    questionName = nextList.get(0);
                                                }
                                            }

                                            List<Question_Template__c> qustionList = [
                                                SELECT Id, Name, Question_Label__c, Question_Order_No__c, Subquestion_Label__c, Next_Question__c,
                                                       Section_Question__c, Section_Question__r.Questionnaire_Section__c,
                                                       (SELECT Id,Name,Help_Text__c,Weight__c FROM Answer_Options__r)
                                                FROM   Question_Template__c
                                                WHERE  Name = :questionName LIMIT 1
                                            ];
        
                                            if (qustionList != null && !qustionList.isEmpty()) {
                                                responseString = qustionList[0].Question_Label__c;
                                                if ( (qustionList[0].Subquestion_Label__c != null && qustionList[0].Answer_Options__r.size() == 0) 
                                                     || qustionList[0].Answer_Options__r.size() > 0 ) {
                                                    integer i = 1;
                                                    List<String> optlist = new List<String>();
                                                    if ( qustionList[0].Answer_Options__r.size() == 0 ){
                                                        optlist = qustionList[0].Subquestion_Label__c.split('~');
                                                    } else {
                                                        for( Answer_Option__c ansOpt :qustionList[0].Answer_Options__r ){
                                                            if ( ansOpt != null && ansOpt.Name != null && ansOpt.Name != '' ){
                                                                optList.add(ansOpt.Name);
                                                            }
                                                        }
                                                    }
                                                    if ( optlist.size() > 0 ){
                                                        for (String question :optlist ) {
                                                            responseString += '\n'+i+'. '+question;
                                                            i++;
                                                        }
                                                    }
                                                    responseString += '\n(Please type only the number)';
                                                }

                                                List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                                    new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'In Progress', Mobile_Number__c = mobileNumber, Question_Template__c = qustionList[0].Id )
                                                };
                                                if (reportTypeList != null && reportTypeList.size() > 0) {
                                                    vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                                }
                                                upsert vrlist;
                                            } else {
                                                responseString = 'Thank you'; //Do not have next question.

                                                List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                                    new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'Completed', Mobile_Number__c = mobileNumber)
                                                };
                                                if (reportTypeList != null && reportTypeList.size() > 0) {
                                                    vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                                }
                                                upsert vrlist;
                                            }

                                        } else if( visRegList[0].Question_Template__r.Question_Order_No__c != null) {

                                            List<Question_Template__c> qustionList = [
                                                SELECT   Id, Next_Question__c, Question_Label__c, Question_Order_No__c, 
                                                         Subquestion_Label__c, Section_Question__c, Section_Question__r.Questionnaire_Section__c,
                                                         (SELECT Id,Name,Help_Text__c,Weight__c FROM Answer_Options__r)
                                                FROM     Question_Template__c
                                                WHERE    Section_Question__r.Questionnaire_Section__c =:visRegList[0].Question_Template__r.Section_Question__r.Questionnaire_Section__c            
                                                         AND Question_Order_No__c >:visRegList[0].Question_Template__r.Question_Order_No__c
                                                ORDER BY Question_Order_No__c ASC NULLS LAST LIMIT 1
                                            ];
        
                                            if (qustionList != null && !qustionList.isEmpty()) {
                                                responseString = qustionList[0].Question_Label__c;
                                                if ( (qustionList[0].Subquestion_Label__c != null && qustionList[0].Answer_Options__r.size() == 0) 
                                                     || qustionList[0].Answer_Options__r.size() > 0 ) {
                                                    integer i = 1;
                                                    List<String> optlist = new List<String>();
                                                    if ( qustionList[0].Answer_Options__r.size() == 0 ){
                                                        optlist = qustionList[0].Subquestion_Label__c.split('~');
                                                    } else {
                                                        for( Answer_Option__c ansOpt :qustionList[0].Answer_Options__r ){
                                                            if ( ansOpt != null && ansOpt.Name != null && ansOpt.Name != '' ){
                                                                optList.add(ansOpt.Name);
                                                            }
                                                        }
                                                    }
                                                    if ( optlist.size() > 0 ){
                                                        for (String question :optlist ) {
                                                            responseString += '\n'+i+'. '+question;        
                                                            i++;
                                                        }
                                                    }
                                                    responseString += '\n(Please type only the number)';

                                                }

                                                List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                                    new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'In Progress', Mobile_Number__c = mobileNumber,Question_Template__c = qustionList[0].Id )
                                                };
                                                if (reportTypeList != null && reportTypeList.size() > 0) {
                                                    vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                                }
                                                upsert vrlist;
                                            } else { // Do not have next question complete the survey

                                                List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                                    new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'Completed', Mobile_Number__c = mobileNumber)
                                                };
                                                if (reportTypeList != null && reportTypeList.size() > 0) {
                                                    vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                                }
                                                upsert vrlist;
                                                responseString = 'Thank you';
                                            }

                                        } else {

                                            List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                                new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'Completed', Mobile_Number__c = mobileNumber)
                                            };
                                            if (reportTypeList != null && reportTypeList.size() > 0) {
                                                vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                            }
                                            upsert vrlist;
                                            responseString = 'Thank you';
                                        }  
                                    } else {
                                        responseString = 'Please send correct answer';
                                    }
                                } else {
                                    responseString = 'Please type only the number';
                                }
                            //Do not have question's answer option but sent the next ordered question.
                            } else if( (visRegList[0].Question_Template__c != NULL && visRegList[0].Question_Template__r.Subquestion_Label__c == null) || 
                                        (visRegList[0].Question_Template__c != NULL && visRegList[0].Question_Template__r.Answer_Options__r.size() == 0) ) {          

                                List<Questionnaire_Response__c> answerInsert = new List<Questionnaire_Response__c> {
                                         new Questionnaire_Response__c(Issue_Request__c = amid, Question_Template__c = visRegList[0].Question_Template__c,
                                                                         Response__c = inputCode)
                                 };
                                insert answerInsert;
                                if (visRegList[0].Question_Template__r.Question_Order_No__c != null) {

                                    List<Question_Template__c> qustionList = [
                                        SELECT   Id, Question_Label__c, Question_Order_No__c, 
                                                 Subquestion_Label__c, Next_Question__c,
                                                 Section_Question__c, Section_Question__r.Questionnaire_Section__c,
                                                 (SELECT Id,Name,Help_Text__c,Weight__c FROM Answer_Options__r)
                                        FROM     Question_Template__c
                                        WHERE    Section_Question__r.Questionnaire_Section__c =:visRegList[0].Question_Template__r.Section_Question__r.Questionnaire_Section__c
                                                 AND Question_Order_No__c >:visRegList[0].Question_Template__r.Question_Order_No__c
                                        ORDER BY Question_Order_No__c ASC NULLS LAST LIMIT 1
                                    ];
                                
                                    if (qustionList != null && !qustionList.isEmpty()) {
                                        responseString = qustionList[0].Question_Label__c;
                                        if ( (qustionList[0].Subquestion_Label__c != null && qustionList[0].Answer_Options__r.size() == 0)
                                             || qustionList[0].Answer_Options__r.size() > 0 ) {
                                            integer i = 1;
                                            List<String> optlist = new List<String>();
                                            if ( qustionList[0].Answer_Options__r.size() == 0 ){
                                                optlist = qustionList[0].Subquestion_Label__c.split('~');
                                            } else {
                                                for( Answer_Option__c ansOpt :qustionList[0].Answer_Options__r ){
                                                    if ( ansOpt != null && ansOpt.Name != null && ansOpt.Name != '' ){
                                                        optList.add(ansOpt.Name);
                                                    }
                                                }
                                            }
                                            if ( optlist.size() > 0 ){
                                                for (String question :optlist ) {
                                                    responseString += '\n'+i+'. '+question;        
                                                    i++;
                                                }
                                            }
                                            responseString += '\n(Please type only the number)';
                                         }

                                        List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                            new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'In Progress', Mobile_Number__c = mobileNumber,Question_Template__c = qustionList[0].Id )
                                        };
                                        if (reportTypeList != null && reportTypeList.size() > 0) {
                                            vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                        }
                                        upsert vrlist;
                                    } else { // Do not have next question complete the survey

                                        List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                            new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'Completed', Mobile_Number__c = mobileNumber)
                                        };
                                        if (reportTypeList != null && reportTypeList.size() > 0) {
                                            vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                        }
                                        upsert vrlist;
                                        responseString = 'Thank you';
                                    }
                                
                                } else {

                                    List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                        new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'Completed', Mobile_Number__c = mobileNumber)
                                    };
                                    if (reportTypeList != null && reportTypeList.size() > 0) {
                                        vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                    }
                                    upsert vrlist;
                                    responseString = 'Thank you';
                                }
                            } else {

                                responseString = 'Mismatch your answer please retake survey from first';

                                List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                    new Visitor_Register__c(Id = visRegList[0].Id, Status__c = 'Completed', Mobile_Number__c = mobileNumber)
                                };
                                if (reportTypeList != null && reportTypeList.size() > 0) {
                                    vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                }
                                upsert vrlist;
                            }
    
                        } else {   // find the assessment template using template short code

                            Map<string,string> objectAPIInPAAndAMMap = new Map<string,string>();

                            string queryStr = 'SELECT Assessible_Object_ID__c, Assessment_Template__c, ID, Public_Assessment_URL__c, Short_Code__c';

                            ExAMUtilClass.AssessableObjectDetails objectDetail = ExAMUtilClass.getAssessableObjectDetails('ExAM__Public_Assessment__c');
                            Map<string, string> fieldsAPIMap = objectDetail.assessableObjectAPIMap;
                            if (fieldsAPIMap != null && fieldsAPIMap.size() > 0) {

                                for (string referenceFieldAPIInPA : fieldsAPIMap.keySet()) {
                                    string referenceFieldAPIInAM = (referenceFieldAPIInPA != 'ExAM__Facility_Name__c') ? referenceFieldAPIInPA.replaceFirst('PA_', 'AM_') : referenceFieldAPIInPA;
                                    objectAPIInPAAndAMMap.put(referenceFieldAPIInPA, referenceFieldAPIInAM);
                                }

                                List<string> referenceFieldsList = new List<string>();
                                referenceFieldsList.addAll( fieldsAPIMap.keySet() );

                                queryStr += ', ';
                                queryStr += string.join(referenceFieldsList, ', ');
                            }
                            queryStr += ' FROM Public_Assessment__c WHERE Short_Code__c =:inputCode LIMIT 1';

                            List<Public_Assessment__c> queryPublicAssList = Database.query(queryStr);

                            if ( queryPublicAssList != null && queryPublicAssList.size() > 0) {
                                if (queryPublicAssList[0].Assessment_Template__c != null) {

                                    List<Question_Template__c> qustionList = [
                                        SELECT      Id, Question_Label__c, Question_Order_No__c, 
                                                    Subquestion_Label__c, Next_Question__c,
                                                    Section_Question__c, Section_Question__r.Questionnaire_Section__c,
                                                    (SELECT Id,Name,Help_Text__c,Weight__c FROM Answer_Options__r)
                                        FROM        Question_Template__c
                                        WHERE       Section_Question__r.Questionnaire_Section__c =:queryPublicAssList[0].Assessment_Template__c
                                        ORDER BY    Question_Order_No__c ASC NULLS LAST LIMIT 1
                                    ];
                                                
                                    if (qustionList != null && !qustionList.isEmpty()) {
                                        responseString = qustionList[0].Question_Label__c;
                                        if ( (qustionList[0].Subquestion_Label__c != null && qustionList[0].Answer_Options__r.size() == 0)
                                             || qustionList[0].Answer_Options__r.size() > 0 ) {
                                            integer i = 1;
                                            List<String> optlist = new List<String>();
                                            if ( qustionList[0].Answer_Options__r.size() == 0 ){
                                                optlist = qustionList[0].Subquestion_Label__c.split('~');
                                            } else {
                                                for( Answer_Option__c ansOpt :qustionList[0].Answer_Options__r ){
                                                    if ( ansOpt != null && ansOpt.Name != null && ansOpt.Name != '' ){
                                                        optList.add(ansOpt.Name);
                                                    }
                                                }
                                            }
                                            if ( optlist.size() > 0 ){
                                                for (String question :optlist ) {
                                                    responseString += '\n'+i+'. '+question;        
                                                    i++;
                                                }
                                            }
                                            responseString += '\n(Please type only the number)';
                                        }   

                                        List<Visitor_Register__c> vrlist = new List<Visitor_Register__c> {
                                                new Visitor_Register__c(Name = mobileNumber, Status__c = 'Started',  Mobile_Number__c = mobileNumber, 
                                                                        Question_Template__c = qustionList[0].Id )
                                        };
                                        if (reportTypeList != null && reportTypeList.size() > 0) {
                                            vrlist[0].RecordTypeId = reportTypeList[0].Id;
                                        }
                                        Savepoint sp = Database.setSavepoint();
                                        try {
                                            insert vrlist;

                                            IssueRequest_Life_Cycle__c AMRecord = new IssueRequest_Life_Cycle__c(InvestigationType__c = queryPublicAssList[0].Assessment_Template__c, Visitor_Register__c = vrList[0].Id);

                                            for (string fd : objectAPIInPAAndAMMap.keySet()) {
                                                if (queryPublicAssList[0].get(fd) != null && queryPublicAssList[0].Assessible_Object_ID__c != null
                                                    && (queryPublicAssList[0].get(fd) == queryPublicAssList[0].Assessible_Object_ID__c)) {
                                                
                                                    AMRecord.put(objectAPIInPAAndAMMap.get(fd), queryPublicAssList[0].get(fd));
                                                }
                                            }
                                            insert AMRecord;

                                        } catch(Exception ex) {
                                            responseString = ex.getMessage();
                                            Database.rollback(sp);
                                        }
                                    }

                                } else {
                                    responseString = 'The "' +inputCode +'" does not have any question'; //'Do not have assessment template'
                                }
                            } else {
                                responseString = 'Please send valid code';
                            }
                        }
                        //End IVR SMS
                    }
                } else {
                    responseString = 'Mobile number empty';
                }
            } else {
            
                responseString = 'Please send correct code';
            }
        }
        catch(Exception e) {
            responseString = e.getMessage();
        }
        
        DOM.Document doc = new DOM.Document();
        dom.XmlNode envelope = doc.createRootElement('Response',null,null);
        dom.XmlNode body = envelope.addChildElement('Message',null,null).addTextNode(responseString);
        
        System.debug(':::'+responseString);
        
        restResp.addHeader('Content-Type', 'text/xml');
        restResp.responseBody = Blob.valueOf(doc.toXmlString());
        restResp.statusCode = 200;
    }
}