src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Is_Dependent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dependent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestExamManager.cls
@isTest
private class TestExamManager {
    
    static testMethod void validateExamManager() {
        
        Main_questionaire__c assessment = new Main_questionaire__c();
        assessment.Template_name__c = 'Food Survey';
        insert assessment;
        
        List<Section_Template__c> sectionList = new List<Section_Template__c>{
            new Section_Template__c(
                Questionnaire_Section__c = assessment.Id,
                Section_label__c = 'Starters',
                Order_No__c = 1
            ),
            new Section_Template__c(
                Questionnaire_Section__c = assessment.Id,
                Section_label__c = 'Main Course',
                Order_No__c = 2
            ),
            new Section_Template__c(
                Questionnaire_Section__c = assessment.Id,
                Section_label__c = 'Desserts',
                Order_No__c = 3
            ) 
        };
                    
        insert sectionList;
        Map<Id,Section_Template__c> oldIdWthSection = new Map<Id,Section_Template__c>(sectionList);
        List<Question_Template__c> questionList = new List<Question_Template__c>{
            new Question_Template__c(
                Question_Label__c = 'Which type of starters do you prefer mostly?',
                Question_Type__c = 'RadioPicklist',
                Question_Order_No__c = 1,
                Section_Question__c = sectionList[0].Id
            ),
            new Question_Template__c(
                Question_Label__c = 'Which category do you like most?',
                Question_Type__c = 'Button',
                Question_Order_No__c = 2,
                Section_Question__c = sectionList[0].Id
            ),
            new Question_Template__c(
                Question_Label__c = 'Which category do you like most?',
                Question_Type__c = 'Button',
                Question_Order_No__c = 3,
                Section_Question__c = sectionList[0].Id,
                Is_Dependent__c = true
            ),
            new Question_Template__c(
                Question_Label__c = 'Which type of Main Course do you choose mostly?',
                Question_Type__c = 'Button',
                Question_Order_No__c = 1,
                Section_Question__c = sectionList[1].Id
            ),
            new Question_Template__c(
                Question_Label__c = 'Which category do you like most?',
                Question_Type__c = 'Button',
                Question_Order_No__c = 2,
                Subquestion_Label__c = 'Sea Food~Others',
                Weight_of_Answer__c = '20~10',
                Section_Question__c = sectionList[1].Id
            ),
            new Question_Template__c(
                Question_Label__c = 'Which category do you like most?',
                Question_Type__c = 'Button',
                Question_Order_No__c = 3,
                Section_Question__c = sectionList[1].Id
            ),
            new Question_Template__c(
                Question_Label__c = 'Which category do you prefer mostly?',
                Question_Type__c = 'RadioPicklist',
                Question_Order_No__c = 4,
                Subquestion_Label__c = 'Meals~Biriyani~Others',
                Weight_of_Answer__c = '20~10~15',
                Is_Dependent__c = true,
                Section_Question__c = sectionList[1].Id
            ),
            new Question_Template__c(
                Question_Label__c = 'Which flavor do you like the most?',
                Question_Type__c = 'Image',
                Question_Order_No__c = 1,
                Section_Question__c = sectionList[2].Id
            )
                
        };
                    
        insert questionList;
        
        Map<Id,Question_Template__c> IdWithQuestion = new Map<Id,Question_Template__c>(questionList);
        
        questionList = [SELECT Id,Name,Next_Question__c,Dependent_Question__c,Subquestion_Label__c FROM Question_Template__c WHERE Id IN:IdWithQuestion.keySet()];
        questionList[4].Next_Question__c = questionList[3].Name+'~'+questionList[5].Name;
        questionList[6].Dependent_Question__c = questionList[3].Name+'~'+questionList[5].Name;
        update questionList;
        
        Map<Id,Question_Template__c> oldIdWthquestion = new Map<Id,Question_Template__c>(questionList);
        
        List<Answer_Option__c> answerOptionsList = new List<Answer_Option__c>{
            new Answer_Option__c(
                Name = 'Veg',
                Order_No__c = 1,
                Question_Template__c = questionList[0].Id
            ), 
            new Answer_Option__c(
                Name = 'Non-Veg',
                Order_No__c = 2,
                Question_Template__c = questionList[0].Id,
                Next_Question__c = questionList[1].Id
            ),
            new Answer_Option__c(
                Name = 'Sea Food',
                Order_No__c = 1,
                Question_Template__c = questionList[1].Id
            ),
            new Answer_Option__c(
                Name = 'Others',
                Order_No__c = 2,
                Question_Template__c = questionList[1].Id                    
            ),
            new Answer_Option__c(
                Name = 'Meals',
                Order_No__c = 1,
                Question_Template__c = questionList[2].Id,
                Dependent_Question__c =  questionList[1].Id
            ),
            new Answer_Option__c(
                Name = 'Veg',
                Order_No__c = 1,
                Question_Template__c = questionList[3].Id
            ), 
            new Answer_Option__c(
                Name = 'Non-Veg',
                Order_No__c = 2,
                Question_Template__c = questionList[3].Id
            ), 
            new Answer_Option__c(
                Name = 'Veg',
                Order_No__c = 1,
                Question_Template__c = questionList[5].Id
            ), 
            new Answer_Option__c(
                Name = 'Non-Veg',
                Order_No__c = 2,
                Question_Template__c = questionList[5].Id
            ), 
            new Answer_Option__c(
                Name = 'Chocolate',
                Order_No__c = 1,
                Question_Template__c = questionList[7].Id
            ),
            new Answer_Option__c(
                Name = 'Strawberry',
                Order_No__c = 2,
                Question_Template__c = questionList[7].Id
            )
                
        };
        insert answerOptionsList;
        set<Id> questionHasAnswers = new Set<Id>();
        for(Answer_Option__c answer : answerOptionsList){
            questionHasAnswers.add(answer.Question_Template__c);
        }
        
        Integer count = 0;
        
        for(Question_Template__c question : questionList){
            
            if(!questionHasAnswers.contains(question.Id)){
                
                if(question.Subquestion_Label__c != null){
                    List<String> answers = question.Subquestion_Label__c.split('~');
                    count += answers.size();
                }
                
            }
        }
        
        count += answerOptionsList.size();
        
        Map<Id,Answer_Option__c> oldIdWthAnswer = new Map<Id,Answer_Option__c>(answerOptionsList);
        
        
        List<Attachment> attach = new List<Attachment>{
            new Attachment(
                ParentId = answerOptionsList[9].Id,
                Name = 'kk',
                ContentType = 'jpg',
                Body = EncodingUtil.base64Decode('sfkjdhkjd')
            ),
            new Attachment(
                ParentId = answerOptionsList[10].Id,
                Name = 'kk1',
                ContentType = 'jpg',
                Body = EncodingUtil.base64Decode('sfkjdhkjd')
            )
                
        };
                    
        insert attach;
        
        List<Attachment> attachByQuestion = new List<Attachment>{
            
            new Attachment(
                ParentId = questionList[4].Id,
                Name = '1',
                ContentType = 'jpg',
                Body = EncodingUtil.base64Decode('sfkjdhkjd')
            ),
            new Attachment(
                ParentId = questionList[4].Id,
                Name = '2',
                ContentType = 'jpg',
                Body = EncodingUtil.base64Decode('sfkjdhkjhhd')
            )
                
        };
                    
        insert attachByQuestion;
        
        Map<Id,String> assessmentIdWthTempName = new Map<Id,String>{assessment.Id => 'test Food Survey'};
        ExamManager.clone(assessmentIdWthTempName);
        
        Map<Id,Id> oldWthNewId = new Map<Id,Id>();
        Map<Id,Id> questionOldWthNewId = new Map<Id,Id>();
        List<Question_Template__c> newQuestionList = [SELECT Id,Name FROM Question_Template__c WHERE Id NOT IN:oldIdWthquestion.keySet()];
        List<Answer_Option__c> newAnswerOptionsList = [SELECT Id,Name FROM Answer_Option__c WHERE Id NOT IN:oldIdWthAnswer.keySet()];
        
        
        for(Integer i = 0; i < newAnswerOptionsList.size(); i++){
            
            if(answerOptionsList.size() > i){
                oldWthNewId.put(answerOptionsList[i].Id, newAnswerOptionsList[i].Id); 
            }
            
        }
        
        for(Integer i = 0; i < newQuestionList.size(); i++){
            questionOldWthNewId.put(questionList[i].Id, newQuestionList[i].Id);
        }
        
        
        List<Main_questionaire__c> assessmentList = [SELECT Id, Template_name__c FROM Main_questionaire__c WHERE Template_name__c = 'test Food Survey'];
        System.assertEquals(1,assessmentList.size());
        
        
        List<Section_Template__c> cloneSectionList = [SELECT Id,Questionnaire_Section__c FROM Section_Template__c WHERE Questionnaire_Section__c =:assessmentList[0].Id];
        System.assertEquals(sectionList.size(), cloneSectionList.size());
        
        List<Question_Template__c> cloneQuestionList = [SELECT Id,Name,Section_Question__c FROM Question_Template__c WHERE Section_Question__c NOT IN:oldIdWthSection.keySet()];
       	System.assertEquals(questionList.size(), cloneQuestionList.size());
        
        System.assertEquals(count, newAnswerOptionsList.size());
        
        BatchAttachmentClone cloneAttachment = new BatchAttachmentClone(oldWthNewId,false);
        BatchAttachmentClone cloneAttachmentByQuestion = new BatchAttachmentClone(questionOldWthNewId,true);
        Test.StartTest();
        Database.executeBatch(cloneAttachment);
        Database.executeBatch(cloneAttachmentByQuestion);
        Test.StopTest();
        
        List<Attachment> attachmentListByAnswer = [SELECT Id,ParentId FROM Attachment WHERE ParentId =:oldWthNewId.values()];
        System.assertEquals(attach.size(), attachmentListByAnswer.size());
    }
    
}