src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Likert__c</fullName>
        <label>Likert</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                </value>
                <value>
                    <fullName>Frequency</fullName>
                </value>
                <value>
                    <fullName>Importance</fullName>
                </value>
                <value>
                    <fullName>Likelihood</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Single_Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to next question in decision tree</description>
        <inlineHelpText>Lookup to next question in decision tree</inlineHelpText>
        <label>Single Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionTemplateTriggerHandler.cls
public with sharing class QuestionTemplateTriggerHandler {

    public void beforeUpdate(Map<Id,Question_Template__c> quesTempOldMap, Map<Id,Question_Template__c> quesTempNewMap, List<Question_Template__c> newQuestTempList) {

        validateMultiSelectQuestionUpdate(quesTempOldMap, quesTempNewMap, newQuestTempList);
    }

    public void afterInsert(List<Question_Template__c> questions) {

        createAnswerOptionForLikertQtnType(new Map<Id, Question_Template__c>(), new Map<Id, Question_Template__c>(), questions, true, false);
    }

    public void afterUpdate(Map<Id, Question_Template__c> oldQuestionsMap, Map<Id, Question_Template__c> newQuestionsMap, List<Question_Template__c> questions) {

        createAnswerOptionForLikertQtnType(oldQuestionsMap, newQuestionsMap, questions, false, true);
    }

    public void validateMultiSelectQuestionUpdate(Map<Id,Question_Template__c> quesTempOldMap, Map<Id,Question_Template__c> quesTempNewMap, List<Question_Template__c> newQuestTempList) {
        
        Set<Id> multiselectQTSet = new Set<Id>();
        Map<Id,Set<String>> AnsOptquesIdWithNextQuesMap = new Map<Id,Set<String>>();
        Map<Id,List<String>> quesIdWithNextQuesMap = new Map<Id,List<String>>();
        
        if ( quesTempOldMap != null && quesTempOldMap.size() > 0 &&
             quesTempNewMap != null && quesTempNewMap.size() > 0 ) {
            
            for (Question_Template__c qtn : newQuestTempList) {
            
                if ( quesTempNewMap.get(qtn.Id).Question_Type__c == 'MultiselectPicklist' ) {
                    multiselectQTSet.add( qtn.Id );
                }
                if ((quesTempOldMap.get(qtn.Id).Question_Type__c != qtn.Question_Type__c)
                    && (quesTempOldMap.get(qtn.Id).Question_Type__c == 'Likert' &&  qtn.Question_Type__c != 'Likert')) {

                    qtn.Likert__c = '';
                }
            }

            if ( multiselectQTSet.size() > 0 ) {
                 
                 for( Answer_Option__c ansOption :[SELECT Id,Name,Help_Text__c,Weight__c,Dependent_Question__c,Next_Question__c,
                                            Question_Template__r.Question_Type__c,Question_Template__c
                                            FROM Answer_Option__c
                                            WHERE Question_Template__c IN :multiselectQTSet AND 
                                            Next_Question__c != null] ) {                   
                
                    if ( !AnsOptquesIdWithNextQuesMap.containsKey(ansOption.Question_Template__c ) ) {
                        AnsOptquesIdWithNextQuesMap.put(ansOption.Question_Template__c,new Set<string>());
                    }
                    AnsOptquesIdWithNextQuesMap.get(ansOption.Question_Template__c).add(ansOption.Next_Question__c);                        
                }
                
                // Question template not have a answer option records
                for(Id multiSelectQT : multiselectQTSet) {
                    if(!AnsOptquesIdWithNextQuesMap.containsKey(multiSelectQT) 
                        && quesTempNewMap.get(multiSelectQT).Next_Question__c != null && quesTempNewMap.get(multiSelectQT).Next_Question__c != '') {
                        
                        List<string> splitOfoptionList = new List<string>();
                        String nextQues = quesTempNewMap.get(multiSelectQT).Next_Question__c;
                        if( nextQues.indexOf('~') > 0 ) {
                            splitOfoptionList = nextQues.split('~');
                        } else {
                            splitOfoptionList.add(nextQues);
                        }
                        quesIdWithNextQuesMap.put(multiSelectQT,splitOfoptionList);
                    }
                }

                if ( AnsOptquesIdWithNextQuesMap.size() > 0 || quesIdWithNextQuesMap.size() > 0) {
                    for ( Id qid : multiselectQTSet) {
                        if (AnsOptquesIdWithNextQuesMap.containsKey(qid) && AnsOptquesIdWithNextQuesMap.get(qid).size() > 1 ) {
                            quesTempNewMap.get(qid).adderror('All Answer Options should point to the same Next Question for MultiselectPicklist question type');
                        } else if (quesIdWithNextQuesMap.containsKey(qid) && quesIdWithNextQuesMap.get(qid).size() > 1 ) {
                            quesTempNewMap.get(qid).adderror('Please set only one Next Question for MultiselectPicklist question type');
                        }
                    }
                }
            }
        }
    }

    public void createAnswerOptionForLikertQtnType(Map<Id, Question_Template__c> oldQuestionsMap, Map<Id, Question_Template__c> newQuestionsMap, List<Question_Template__c> questions, Boolean isAfterInsert, Boolean isAfterUpdate) {

        Integer counter = 1;

        List<Question_Template__c> likertQtns = new List<Question_Template__c>();
        List<Answer_Option__c> answerOptionsList = new List<Answer_Option__c>();

        Set<Id> qtnIdSet = new Set<Id>();

        Map<string, List<string>> likertKeyAndValuesMap = new Map<string, List<string>>{
            'agreement' => new List<string>{'Strongly Agree', 'Agree', 'Undecided', 'Disagree', 'Strongly Disagree'},
            'frequency' => new List<string>{'Very Frequently', 'Frequently', 'Occasionally', 'Rarely', 'Never'},
            'importance' => new List<string>{'Very Important', 'Important', 'Moderately Important', 'Of Little Importance', 'Unimportant'},
            'likelihood' => new List<string>{'Almost Always True', 'Usually True', 'Occasionally True', 'Usually Not True', 'Almost Never True'}
        };

        if (isAfterInsert) {

            for (Question_Template__c qtn : questions) {

                if (qtn.Question_Type__c == 'Likert' && string.isNotBlank(qtn.Likert__c)) {

                    likertQtns.add( qtn );
                }
            }
        }
        else if (isAfterUpdate) {

            for (Question_Template__c qtn : questions) {

                if (oldQuestionsMap.get(qtn.Id).Question_Type__c != qtn.Question_Type__c) {

                    if (qtn.Question_Type__c == 'Likert' && string.isNotBlank(qtn.Likert__c)) {

                        likertQtns.add( qtn );
                    }
                    else if ((oldQuestionsMap.get(qtn.Id).Question_Type__c == 'Likert') && (qtn.Question_Type__c != 'Likert')) {

                        qtnIdSet.add( qtn.Id );
                    }
                }
                else if ((qtn.Question_Type__c == 'Likert') && (oldQuestionsMap.get(qtn.Id).Likert__c != qtn.Likert__c)) {

                    qtnIdSet.add( qtn.Id );
                    likertQtns.add( qtn );
                }
            }
        }

        if (qtnIdSet.size() > 0) {
            delete [SELECT Id, Name, Question_Template__c FROM Answer_Option__c WHERE Question_Template__c IN :qtnIdSet];
        }
        if (likertQtns != null && likertQtns.size() > 0) {

            for (Question_Template__c qtn : likertQtns) {

                string likertKey = qtn.Likert__c.toLowerCase();

                if (likertKeyAndValuesMap.containsKey(likertKey) && likertKeyAndValuesMap.get(likertKey) != null && likertKeyAndValuesMap.get(likertKey).size() > 0) {

                    counter = 1;
                    for (string likertValue : likertKeyAndValuesMap.get(likertKey)) {

                        Answer_Option__c newAO = new Answer_Option__c();
                        newAO.Name = likertValue;
                        newAO.Order_No__c = counter;
                        newAO.Question_Template__c = qtn.Id;
                        answerOptionsList.add( newAO );
                        counter++;
                    }
                }
            }
            if (answerOptionsList != null && answerOptionsList.size() > 0) {
                insert answerOptionsList;
            }   
        }
    }
}