src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Exam.cls
public with sharing class Exam {
    //AssessmentWrapper class
    public class AssessmentWrapper{
        public Main_questionaire__c assessmentRecord;
        public List<SectionWrapper> sections;
        
        //clone Assessment
        public  Main_questionaire__c cloneAssessment(){
            assessmentRecord = assessmentRecord.clone(false,true,false,false);
            return assessmentRecord;
        }
        
        // constructor  for AssessmentWrapper class
        public AssessmentWrapper(Main_questionaire__c assessment, Map<Id,List<Section_Template__c>> assessmentIdWthSections, Map<Id,List<Question_Template__c>> sectionIdWthQuestions, Map<Id,List<Answer_Option__c>> questionIdWthAnswers){
            this.assessmentRecord = assessment;            
            List<SectionWrapper> sectionWrapperList = new List<SectionWrapper>();
            
            if(assessmentIdWthSections.containsKey(assessment.Id)){
                for(Section_Template__c section : assessmentIdWthSections.get(assessment.Id)){
                    sectionWrapperList.add(new Exam.SectionWrapper(section,sectionIdWthQuestions,questionIdWthAnswers));
                }
                this.sections = sectionWrapperList;
            }
            
        }
    }
    
    //SectionWrapper class
    public class SectionWrapper{
        public Section_Template__c sectionRecord;
        public List<QuestionWrapper> questions;
        
        // cloneSection
        public Section_Template__c cloneSection(Exam.AssessmentWrapper assessment){
            sectionRecord = sectionRecord.clone(false,true,false,false);
            sectionRecord.Questionnaire_Section__c = assessment.assessmentRecord.Id;
            return sectionRecord;
        }
        
        // constructor for SectionWrapper class
        public SectionWrapper(Section_Template__c section, Map<Id,List<Question_Template__c>> sectionIdWthQuestions, Map<Id,List<Answer_Option__c>> questionIdWthAnswers){
            this.sectionRecord = section;
            List<QuestionWrapper> questionWrapperList = new List<QuestionWrapper>();
            
            if(sectionIdWthQuestions.containsKey(section.Id)){
                for(Question_Template__c question : sectionIdWthQuestions.get(section.Id)){
                    questionWrapperList.add(new Exam.QuestionWrapper(question,questionIdWthAnswers));
                }
                this.questions = questionWrapperList;
            }
            
        }
    }
    
    // QuestionWrapper class
    public class QuestionWrapper{
        public Question_Template__c questionRecord;
        public List<AnswerOptionsWrapper> answerOptions;
        
        // CloneQuestion
        public Question_Template__c cloneQuestion(Exam.SectionWrapper section){
            questionRecord = questionRecord.clone(false,true,false,false);
            questionRecord.Section_Question__c = section.sectionRecord.Id;
            return questionRecord;
        }
        
        // constructor for QuestionWrapper class
        public QuestionWrapper(Question_Template__c question, Map<Id,List<Answer_Option__c>> questionIdWthAnswers){
            this.questionRecord = question;
            List<AnswerOptionsWrapper> answerOptionsWrapperList = new List<AnswerOptionsWrapper>();
            
            if(questionIdWthAnswers.containsKey(question.Id)){
                for(Answer_Option__c answer : questionIdWthAnswers.get(question.Id)){
                    answerOptionsWrapperList.add(new Exam.AnswerOptionsWrapper(answer));
                }
                this.answerOptions = answerOptionsWrapperList;
            }  
            
        }
    }
    
    // AnswerOptionsWrapper class
    public class AnswerOptionsWrapper{
        public Answer_Option__c answerOptionRecord;
        
        // clone AnswerOption
        public Answer_Option__c cloneAnswerOption(Exam.QuestionWrapper question,Id nextQuestion, Id dependentQuestion){
            answerOptionRecord = answerOptionRecord.clone(false,true,false,false);
            answerOptionRecord.Question_Template__c = question.questionRecord.Id;
            if(nextQuestion != null){
                answerOptionRecord.Next_Question__c = nextQuestion;
            }else if(dependentQuestion != null){
                answerOptionRecord.Dependent_Question__c = dependentQuestion;
            }
            return answerOptionRecord;
        }
        
        //Constructor for AnswerOptionsWrapper class
        public AnswerOptionsWrapper(Answer_Option__c answerOption){
            this.answerOptionRecord = answerOption;
            
        }
    }
}