src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestQuestionResponseAnalyticsController.cls
@isTest
private class TestQuestionResponseAnalyticsController {
    static testMethod void validateGetAnswerResponseWithCount(){
        
        Main_questionaire__c assessment = new Main_questionaire__c();
        assessment.Template_name__c = 'ExAM';
        insert assessment;
        
        Section_Template__c section = new Section_Template__c();
        section.Section_label__c = 'Section1';
        section.Questionnaire_Section__c = assessment.Id;
        insert section;

        List<Question_Template__c> quesTempList = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c = section.id, Question_Label__c = 'Radio Question', 
                Question_Order_No__c = 1, Question_Type__c = 'RadioPicklist', Weight_of_Answer__c  = '10'),       
            new Question_Template__c(Section_Question__c = section.id, Question_Label__c = 'MultiSelect Question', 
                Question_Order_No__c = 2, Question_Type__c = 'MultiselectPicklist', Weight_of_Answer__c  = '10'),  
            new Question_Template__c(Section_Question__c = section.id, Question_Label__c = 'Button Question', 
                Question_Order_No__c = 3, Question_Type__c = 'Button', Weight_of_Answer__c  = '10'),
            new Question_Template__c(Section_Question__c = section.id, Question_Label__c = 'Text Question', 
                Question_Order_No__c = 4, Question_Type__c = 'Text', Weight_of_Answer__c  = '10'),       
            new Question_Template__c(Section_Question__c = section.id, Question_Label__c = 'TextArea Question', 
                Question_Order_No__c = 5, Question_Type__c = 'Textarea', Weight_of_Answer__c  = '10'),  
            new Question_Template__c(Section_Question__c = section.id, Question_Label__c = 'Email Question', 
                Question_Order_No__c = 6, Question_Type__c = 'Email', Weight_of_Answer__c  = '10')
        };
        insert quesTempList;

        List<Answer_Option__c> ansoptions1 = new List<Answer_Option__c> {
            new Answer_Option__c(Question_Template__c = quesTempList[0].Id, Order_No__c = 1, Name = 'RadiooptA'),
            new Answer_Option__c(Question_Template__c = quesTempList[0].Id, Order_No__c = 2, Name = 'RadiooptB'),
            new Answer_Option__c(Question_Template__c = quesTempList[1].Id, Order_No__c = 3, Name = 'MultioptA'),
            new Answer_Option__c(Question_Template__c = quesTempList[1].Id, Order_No__c = 4, Name = 'MultioptB'),
            new Answer_Option__c(Question_Template__c = quesTempList[2].Id, Order_No__c = 5, Name = 'ButtonoptA'),
            new Answer_Option__c(Question_Template__c = quesTempList[2].Id, Order_No__c = 6, Name = 'ButtonoptB'),
            new Answer_Option__c(Question_Template__c = quesTempList[2].Id, Order_No__c = 7, Name = 'ButtonoptC')
           
        };
        insert ansoptions1;
        
        List<Questionnaire_Response__c> dependAnsList = new  list<Questionnaire_Response__c>{
            new Questionnaire_Response__c(Question_Template__c = quesTempList[0].Id,Response__c='RadiooptA'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[0].Id,Response__c='RadiooptA'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[0].Id,Response__c='RadiooptB'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[0].Id,Response__c='RadiooptB'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[0].Id,Response__c='RadiooptB'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[0].Id,Response__c='RadiooptB'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[1].Id,Response__c='MultioptA'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[1].Id,Response__c='MultioptA'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[1].Id,Response__c='MultioptA'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[1].Id,Response__c='MultioptB'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[1].Id,Response__c='MultioptB'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[2].Id,Response__c='ButtonoptA'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[2].Id,Response__c='ButtonoptB'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[2].Id,Response__c='ButtonoptB'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[2].Id,Response__c='ButtonoptC'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[2].Id,Response__c='ButtonoptC'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[2].Id,Response__c='ButtonoptC'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[3].Id,Response__c='Text Ans'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[3].Id,Response__c='Text'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[4].Id,Response__c='TextAreaResp'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[4].Id,Response__c='TextAreaResp'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[5].Id,Response__c='ss@gmail.com'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[5].Id,Response__c='ss2@gmail.com'),
            new Questionnaire_Response__c(Question_Template__c = quesTempList[5].Id,Response__c='ss2@gmail.com')
            
        };
        
        Integer noOfRec = 5;
        for(Integer i = 1; i <= 30; i++){
            
            for(Integer j = 0; j < noOfRec; j++){
                Questionnaire_Response__c answerResponse = new Questionnaire_Response__c();
                answerResponse.Response__c = 'opt'+i;
                answerResponse.Question_Template__c = quesTempList[3].Id;
                dependAnsList.add(answerResponse);
            }
            noOfRec += 5;
        }
        
        insert dependAnsList;
        
        QuestionResponseAnalyticsController.QuestionAnalyticInfo response = QuestionResponseAnalyticsController.getAnswerResponseWithCount(assessment.Id, 0);
        
        Integer noOfQuestions = response.noOfQuestions;
        System.assertEquals(6, noOfQuestions);
        
        List<QuestionResponseAnalyticsController.QuestionAnalytic> QuestionAnalyticResponse = response.questions;
        System.assertEquals(6, QuestionAnalyticResponse.size());
        
        //(Option based) CASE 1 : RadioPicklist question 
        
        String questionLable = QuestionAnalyticResponse[0].questionLablel;
        System.assertEquals('Radio Question', questionLable);
        
        List<QuestionResponseAnalyticsController.AnswerAnalytic> answer = QuestionAnalyticResponse[0].answer;
        System.assertEquals('RadiooptA', answer[0].name);
        System.assertEquals(2, answer[0].weight);
        
        System.assertEquals('RadiooptB', answer[1].name);
        System.assertEquals(4, answer[1].weight);
        
        // CASE 2 : MultiselectPicklist question 
        
        questionLable = QuestionAnalyticResponse[1].questionLablel;
        System.assertEquals('MultiSelect Question', questionLable);
        
        answer = QuestionAnalyticResponse[1].answer;
        System.assertEquals('MultioptA', answer[0].name);
        System.assertEquals(3, answer[0].weight);
        
        System.assertEquals('MultioptB', answer[1].name);
        System.assertEquals(2, answer[1].weight);
        
        // CASE 3 : Button Question 
        
        questionLable = QuestionAnalyticResponse[2].questionLablel;
        System.assertEquals('Button Question', questionLable);
        
        answer = QuestionAnalyticResponse[2].answer;
        System.assertEquals('ButtonoptA', answer[0].name);
        System.assertEquals(1, answer[0].weight);
        
        System.assertEquals('ButtonoptB', answer[1].name);
        System.assertEquals(2, answer[1].weight);
        
        System.assertEquals('ButtonoptC', answer[2].name);
        System.assertEquals(3, answer[2].weight);
        
        //(Non option based) CASE 4 : text question 
        
        questionLable = QuestionAnalyticResponse[3].questionLablel;
        System.assertEquals('Text Question', questionLable);
        
        answer = QuestionAnalyticResponse[3].answer;
        System.assertEquals(15, answer.size());
        
        System.assertEquals('opt30', answer[0].name);
        System.assertEquals(150, answer[0].weight);
        
        System.assertEquals('opt16', answer[14].name);
        System.assertEquals(80, answer[14].weight);
        
        // CASE 5 : textArea question 
        
        questionLable = QuestionAnalyticResponse[4].questionLablel;
        System.assertEquals('TextArea Question', questionLable);
        
        answer = QuestionAnalyticResponse[4].answer;
        System.assertEquals('TextAreaResp', answer[0].name);
        System.assertEquals(2, answer[0].weight);
        
        // CASE 6 : Email Question 
        
        questionLable = QuestionAnalyticResponse[5].questionLablel;
        System.assertEquals('Email Question', questionLable);
        
        answer = QuestionAnalyticResponse[5].answer;
        System.assertEquals('ss@gmail.com', answer[0].name);
        System.assertEquals(1, answer[0].weight);   
        
        System.assertEquals('ss2@gmail.com', answer[1].name);
        System.assertEquals(2, answer[1].weight);     
    }
}