src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Context_Questions_Mapping__c</fullName>
        <label>Context Questions Mapping</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContextQuestionMappingConfigCtlr.cls
public with sharing class ContextQuestionMappingConfigCtlr {
    
    public string answerFieldsStr {get;set;}
    public string questionListStr {get;set;}
    public string quesAndAnsFieldStr {get;set;}
    
    public ContextQuestionMappingConfigCtlr() {
       
        SFDCAccessController accessObj = ExAMUtilClass.AccessController;
        String assTempId = '';
        assTempId = ApexPages.currentPage().getParameters().get('assTempId');
        List<FieldClass> fieldClassList = new List<FieldClass>();
        
        Map <String, Schema.SObjectField> fieldMap = ExAMUtilClass.getSObjectFieldsMap('ExAM__Questionnaire_Response__c');
        List<String> Fieldlist = new List<String>();
        for (Schema.SObjectField ansField : fieldMap.Values()) {
            Schema.DescribeFieldResult fieldDesc = ansField.getDescribe();
            if ( !fieldDesc.isCalculated() && String.ValueOf(fieldDesc.getType()).touppercase() != 'REFERENCE' && fieldDesc.isCreateable() && fieldDesc.isUpdateable() ) {
                if(fieldDesc.isCustom()){
                    Fieldlist.add(fieldDesc.getName());
                }
                FieldClass fcls = new FieldClass();
                fcls.fieldApi = fieldDesc.getName();
                fcls.fieldLabel = fieldDesc.getLabel();
                fcls.fieldType = String.valueOf(fieldDesc.getType()).touppercase();
                fieldClassList.add(fcls);
            }        
        }
        system.debug('****Fieldlist'+Fieldlist);
        System.debug('***fieldClassList'+fieldClassList);
        try{
            accessObj.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Questionnaire_Response__c'), Fieldlist);
            accessObj.assertAuthorizedToCreate(Schema.getGlobalDescribe().get('exam__Questionnaire_Response__c'), Fieldlist);
            accessObj.assertAuthorizedToUpdate(Schema.getGlobalDescribe().get('exam__Questionnaire_Response__c'), Fieldlist);
            answerFieldsStr = JSON.serialize(fieldClassList);
            System.debug('***answerFieldsStr'+answerFieldsStr);
            if(assTempId !='') {
            
                List<Main_questionaire__c> assTempList =  new List<Main_questionaire__c>();
                List<Question_Template__c> quesTempList = new List<Question_Template__c>();
                List<QuestionAndAnswerFieldClass> quesAndAnsFieldList = new List<QuestionAndAnswerFieldClass>();
                Map<String,String> quesIdAndAnsFieldMap = new Map<String,String>();
                
                
                List<String> fieldsListAT = new List<String>{'ExAM__Context_Questions_Mapping__c'};
                accessObj.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Main_questionaire__c'), fieldsListAT);
                assTempList = [SELECT Id,Context_Questions_Mapping__c 
                                FROM Main_questionaire__c 
                                WHERE Id = :assTempId];
                system.debug(':::assTempList:::'+assTempList);
                if(assTempList != null && assTempList.size() > 0 ) {
                    if(assTempList[0].Context_Questions_Mapping__c != null && assTempList[0].Context_Questions_Mapping__c != '' ) {
                        List<String> mappedValues = new List<String>();
                        if(assTempList[0].Context_Questions_Mapping__c.contains(':')) {
                            mappedValues = assTempList[0].Context_Questions_Mapping__c.split(':');
                        } else {
                            mappedValues.add(assTempList[0].Context_Questions_Mapping__c);
                        }
                        if(mappedValues.size()> 0) {
                            for(String mv : mappedValues) {
                                List<String> splitVal = new List<String>();
                                splitVal = mv.split('~');
                                quesIdAndAnsFieldMap.put(splitVal[0],splitVal[1]);
                            }
                        }
                    }
                }
                List<String> fieldsList = new List<String>{'ExAM__Question_Label__c','ExAM__Next_Question__c','ExAM__Dependent_Question__c','ExAM__Question_Type__c'};
                accessObj.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Question_Template__c'), fieldsList);
                
                List<String> fieldsList1 = new List<String>{'ExAM__Help_Text__c','ExAM__Weight__c','ExAM__Dependent_Question__c','ExAM__Next_Question__c'};
                accessObj.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Answer_Option__c'), fieldsList1);
                       
                Set<String> qNameSet = new Set<String>();
                
                quesTempList = [SELECT Id,Name,Question_Label__c,Next_Question__c,Dependent_Question__c,Question_Type__c,
                                (SELECT Id,Name,Help_Text__c,Weight__c,Dependent_Question__r.Name,Next_Question__r.Name FROM Answer_Options__r)
                                FROM Question_Template__c 
                                WHERE Section_Question__r.Questionnaire_Section__c = :assTempId AND Question_Type__c != 'Hidden'
                                ];
                if(quesTempList.size() > 0) {  
                    for(Question_Template__c ques : quesTempList) {
                        List<string> tempList = new List<string>();
                        if(((ques.Next_Question__c != null && ques.Next_Question__c != '') || (ques.Dependent_Question__c != null && ques.Dependent_Question__c != '') ) && ques.Answer_Options__r.size() == 0 ) {
                            if(ques.Next_Question__c != null && ques.Next_Question__c != '') {
                                if(ques.Next_Question__c.contains('~')) {
                                    tempList = ques.Next_Question__c.split('~');
                                    for(string quesName : tempList) {
                                        qNameSet.add(quesName);
                                    }
                                } else {
                                    qNameSet.add(ques.Next_Question__c);
                                }
                            }
                            if (ques.Dependent_Question__c != null && ques.Dependent_Question__c != '') {
                                if(ques.Dependent_Question__c.contains('~')) {
                                    tempList = ques.Dependent_Question__c.split('~');
                                    for(string quesName : tempList) {
                                        qNameSet.add(quesName);
                                    }
                                } else {
                                    qNameSet.add(ques.Dependent_Question__c);
                                }
                            }
                        } else {
                        
                            for( Answer_Option__c ansOpt :ques.Answer_Options__r ){
                                if ( ansOpt != null && ansOpt.Next_Question__r.Name != null && ansOpt.Next_Question__r.Name != '' ){
                                    tempList.add(ansOpt.Next_Question__r.Name);
                                } 
                                if (ansOpt != null && ansOpt.Dependent_Question__r.Name != null && ansOpt.Dependent_Question__r.Name != '' ) {
                                    tempList.add(ansOpt.Dependent_Question__r.Name);
                                }
                            }
                            if ( tempList.size() > 0 ){
                                for(string quesName : tempList) {
                                    qNameSet.add(quesName);
                                }
                            }
                        }
                    }
                    if(qNameSet.size() > 0) {
                        Integer i = 0;
                        while(i < quesTempList.size()) {
                            for(String dtques : qNameSet) {
                                if(dtques == quesTempList[i].Name) {
                                    quesTempList.remove(i);
                                    qNameSet.remove(dtques);
                                    i--;
                                    break;
                                } 
                            }
                            i++;
                        }
                    }
                    questionListStr = JSON.serialize(quesTempList);
                    
                    for(Question_Template__c ques : quesTempList) {
                        if(quesIdAndAnsFieldMap.containsKey(ques.Id)) {
                            for(FieldClass fields : fieldClassList) {
                                if(fields.fieldApi == quesIdAndAnsFieldMap.get(ques.Id)) {
                                    QuestionAndAnswerFieldClass qa = new QuestionAndAnswerFieldClass();
                                    qa.questionId = ques.Id;
                                    qa.answerFieldApi = fields.fieldApi;
                                    quesAndAnsFieldList.add(qa);
                                    break;
                                }
                            }
                        }
                    }
                }
                if(quesAndAnsFieldList.size() > 0) {
                    quesAndAnsFieldStr = JSON.serialize(quesAndAnsFieldList);
                } else {
                    QuestionAndAnswerFieldClass qa = new QuestionAndAnswerFieldClass();
                    qa.questionId = '';
                    qa.answerFieldApi = '';
                    quesAndAnsFieldList.add(qa);
                    quesAndAnsFieldStr = JSON.serialize(quesAndAnsFieldList);
                }
                
            }
        }catch(Exception ex){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
        }
               
    }
    
    @RemoteAction
    public static string saveMappingFieldsFunc(List<QuestionAndAnswerFieldClass> quesAndAnsFieldsList,String assTempId,Boolean isReqForUpdation) {
        system.debug('::::quesAndAnsFieldsList::::'+quesAndAnsFieldsList);
        
        String contextQuestionsStr = '';
        String resultMsg = '';
        SFDCAccessController accessObj = ExAMUtilClass.AccessController;
        
        try {    
        
            List<String> fieldsListAT = new List<String>{'ExAM__Context_Questions_Mapping__c'};
            accessObj.assertAuthorizedToUpdate(Schema.getGlobalDescribe().get('exam__Main_questionaire__c'), fieldsListAT);
            if(quesAndAnsFieldsList != null && quesAndAnsFieldsList.size()> 0) {
                for(QuestionAndAnswerFieldClass quesAndAns : quesAndAnsFieldsList) {
                    contextQuestionsStr += quesAndAns.questionId+'~'+quesAndAns.answerFieldApi+':';
                }
                if(contextQuestionsStr.endsWith(':')) {
                    contextQuestionsStr = contextQuestionsStr.removeEnd(':');
                }
                
                Main_questionaire__c assTemplate = new Main_questionaire__c();
                assTemplate.Id = assTempId;
                assTemplate.Context_Questions_Mapping__c = contextQuestionsStr;
                update assTemplate;
                resultMsg = 'success';
                
            } else if(quesAndAnsFieldsList.size()== 0 && isReqForUpdation) {
            
                Main_questionaire__c assTemplate = new Main_questionaire__c();
                assTemplate.Id = assTempId;
                assTemplate.Context_Questions_Mapping__c = '';
                update assTemplate;
                resultMsg = 'success';
            }
            return resultMsg;
        } catch(exception e) {
            resultMsg = e.getMessage();
            return resultMsg;
        }
    }
    
    public class FieldClass {
        public String fieldApi;
        public String fieldLabel;
        public String fieldType;
    }
    
    public class QuestionAndAnswerFieldClass {
        public string questionId;
        public String answerFieldApi;
    }
}