src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Single_Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to next question in decision tree</description>
        <inlineHelpText>Lookup to next question in decision tree</inlineHelpText>
        <label>Single Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AnswerOptionHandler.cls
public with sharing class AnswerOptionHandler {
    
    Set<Id> questionIdSet = new Set<Id>();
    Set<Id> quesIdWithDependentQuesSet = new Set<Id>();
    Set<Id> quesIdWithNextQuesSet = new Set<Id>();
    Set<Id> multiselectQTSet = new Set<Id>();
    Map<Id,Set<String>> AnsOptquesIdWithNextQuesMap = new Map<Id,Set<String>>();
    Map<Id,List<Answer_Option__c>> quesIdWithAnsOptListMap = new Map<Id,List<Answer_Option__c>>();
    Map<Id,Id> quesIdWithAssTempIdMap = new Map<Id,Id>();
    
    public void insertValidation(List<Answer_Option__c> ansOptNewList){
        
        Map<Id,List<Answer_Option__c>> quesIdWithAnswerOptListMap = new Map<Id,List<Answer_Option__c>>();
        Set<Id> depenQuesIdSet = new Set<Id>();
        Set<Id> nextQuesIdSet = new Set<Id>();
        for( Answer_Option__c ansOpt :ansOptNewList ){
            if ( ansOpt.Question_Template__c != null ){
                questionIdSet.add(ansOpt.Question_Template__c);
            }
            if ( ansOpt.Next_Question__c != null ){
                questionIdSet.add(ansOpt.Next_Question__c);
                
                if ( !AnsOptquesIdWithNextQuesMap.containsKey(ansOpt.Question_Template__c ) ) {
                    AnsOptquesIdWithNextQuesMap.put(ansOpt.Question_Template__c,new Set<string>());
                }
                AnsOptquesIdWithNextQuesMap.get(ansOpt.Question_Template__c).add(ansOpt.Next_Question__c);
            }
            if ( ansOpt.Dependent_Question__c != null ){
                questionIdSet.add(ansOpt.Dependent_Question__c);
            }
            if ( ansOpt.Dependent_Question__c != null && !depenQuesIdSet.contains(ansOpt.Question_Template__c) ){
                depenQuesIdSet.add(ansOpt.Question_Template__c);
            }
            if ( ansOpt.Next_Question__c != null && !nextQuesIdSet.contains(ansOpt.Question_Template__c) ){
                nextQuesIdSet.add(ansOpt.Question_Template__c);
            }
            if ( ansOpt.Question_Template__c != null && 
                ( ansOpt.Next_Question__c != null || ansOpt.Dependent_Question__c != null )){
                if ( ansOpt.Next_Question__c != null && ansOpt.Dependent_Question__c != null ){
                    ansOpt.adderror('Please provide either dependent question or Next Question for answer Option Record: '+ansOpt.Name);
                } else if ( ((ansOpt.Next_Question__c != null && depenQuesIdSet.contains(ansOpt.Question_Template__c)) || 
                     (ansOpt.Dependent_Question__c != null && nextQuesIdSet.contains(ansOpt.Question_Template__c))) ){
                    ansOpt.adderror('Please provide next question or dependent question for this question Template '+ansOpt.Question_Template__c);
                } else {
                    if ( !quesIdWithAnsOptListMap.containsKey(ansOpt.Question_Template__c) ){
                        quesIdWithAnsOptListMap.put(ansOpt.Question_Template__c,new List<Answer_Option__c>());
                        quesIdWithAnsOptListMap.get(ansOpt.Question_Template__c).add(ansOpt);
                    } else {
                        quesIdWithAnsOptListMap.get(ansOpt.Question_Template__c).add(ansOpt);
                    }
                }
            }
        }
        if ( questionIdSet != null && questionIdSet.size() > 0 ){
            for( Question_Template__c ques :[SELECT Id,Name,Question_Type__c,Section_Question__r.Questionnaire_Section__c
                                            FROM Question_Template__c WHERE Id IN :questionIdSet] ){
                if ( !quesIdWithAssTempIdMap.containsKey(ques.Id) ){
                    quesIdWithAssTempIdMap.put(ques.Id,ques.Section_Question__r.Questionnaire_Section__c);
                }
                if ( ques.Question_Type__c == 'MultiselectPicklist' ) {
                    multiselectQTSet.add(ques.Id);
                }
            }
        }
        // pre validated (both != null) and question modal change(one opt has nextQues and another ques has depenQues under same quesTemp).
        if ( quesIdWithAnsOptListMap != null && quesIdWithAnsOptListMap.size() > 0 ){
            for( List<Answer_Option__c> answerOptList :quesIdWithAnsOptListMap.values() ){
                for( Answer_Option__c ansOption :answerOptList ){
                    if ( multiselectQTSet.contains(ansOption.Question_Template__c) && AnsOptquesIdWithNextQuesMap.containsKey(ansOption.Question_Template__c) &&
                         AnsOptquesIdWithNextQuesMap.get(ansOption.Question_Template__c).size() > 1 ) {
                        ansOption.adderror('Please select same question for Next Question field when question template’s question type is "MultiselectPicklist"');  
                    } else if ( ansOption.Next_Question__c != null && 
                        quesIdWithAssTempIdMap.get(ansOption.Question_Template__c) != quesIdWithAssTempIdMap.get(ansOption.Next_Question__c) ){
                        ansOption.adderror('Please provide same template\'s next question for Answer Option Record: '+ansOption.Name);
                    } else if ( ansOption.Dependent_Question__c != null && 
                        quesIdWithAssTempIdMap.get(ansOption.Question_Template__c) != quesIdWithAssTempIdMap.get(ansOption.Dependent_Question__c) ){
                        ansOption.adderror('Please provide same template\'s dependent question for Answer Option Record: '+ansOption.Name);
                    } else { 
                        if ( !quesIdWithAnswerOptListMap.containsKey(ansOption.Question_Template__c) ){
                            quesIdWithAnswerOptListMap.put(ansOption.Question_Template__c,new List<Answer_Option__c>());
                            quesIdWithAnswerOptListMap.get(ansOption.Question_Template__c).add(ansOption);
                        } else {
                            quesIdWithAnswerOptListMap.get(ansOption.Question_Template__c).add(ansOption);
                        }
                    }
                }
            }
        }
        //here records reached, when that records(trigger.New) meets is true on pre validation(within trigger.New records).
        //here this map contains pre validated records for post validation with existing records.
        if ( quesIdWithAnswerOptListMap != null && quesIdWithAnswerOptListMap.size() > 0 ){
        
            for( Answer_Option__c ansOption :[SELECT Id,Name,Help_Text__c,Weight__c,Dependent_Question__c,Next_Question__c,
                                            Question_Template__r.Question_Type__c,Question_Template__c
                                            FROM Answer_Option__c
                                            WHERE Question_Template__c IN :quesIdWithAnswerOptListMap.keySet() AND 
                                            (Dependent_Question__c != null OR Next_Question__c != null)] ){
                if ( ansOption.Dependent_Question__c != null && !quesIdWithDependentQuesSet.contains(ansOption.Question_Template__c)){
                    quesIdWithDependentQuesSet.add(ansOption.Question_Template__c);
                } else if ( ansOption.Next_Question__c != null && !quesIdWithNextQuesSet.contains(ansOption.Question_Template__c)){
                    quesIdWithNextQuesSet.add(ansOption.Question_Template__c);
                } 
                if ( ansOption.Question_Template__r.Question_Type__c == 'MultiselectPicklist' ) {
                    if ( !AnsOptquesIdWithNextQuesMap.containsKey(ansOption.Question_Template__c ) ) {
                        AnsOptquesIdWithNextQuesMap.put(ansOption.Question_Template__c,new Set<string>());
                    }
                    AnsOptquesIdWithNextQuesMap.get(ansOption.Question_Template__c).add(ansOption.Next_Question__c);
                }
                
            }
            for( List<Answer_Option__c> ansOptRecList :quesIdWithAnswerOptListMap.values() ){
                for( Answer_Option__c ansOptRec :ansOptRecList ){
                    if ( ((ansOptRec.Next_Question__c != null && quesIdWithDependentQuesSet.contains(ansOptRec.Question_Template__c)) || 
                         (ansOptRec.Dependent_Question__c != null && quesIdWithNextQuesSet.contains(ansOptRec.Question_Template__c))) ){
                        ansOptRec.adderror('Please provide next question or dependent question for this Question Template '+ansOptRec.Question_Template__c);
                    } else if ( multiselectQTSet.contains(ansOptRec.Question_Template__c) && AnsOptquesIdWithNextQuesMap.containsKey(ansOptRec.Question_Template__c) && 
                                AnsOptquesIdWithNextQuesMap.get(ansOptRec.Question_Template__c).size() > 1 ) {
                        ansOptRec.adderror('All Answer Options should point to the same Next Question for MultiselectPicklist question type');  
                    } 
                }
            }
        }
    }
    
    public void updateValidation(List<Answer_Option__c> ansOptNewList, Map<Id,Answer_Option__c> ansOptOldMap){
        for( Answer_Option__c ansOpt :ansOptNewList ){
            if ( ansOpt.Next_Question__c != null && ansOpt.Dependent_Question__c != null ){
                ansOpt.adderror('Please provide either dependent question or Next Question for Answer Option Record: '+ansOpt.Name);
            } else {
                if ( ansOpt.Question_Template__c != null ){
                    questionIdSet.add(ansOpt.Question_Template__c);
                }
                if ( ansOpt.Next_Question__c != null ){
                    questionIdSet.add(ansOpt.Next_Question__c);
                    
                    if ( !AnsOptquesIdWithNextQuesMap.containsKey(ansOpt.Question_Template__c ) ) {
                        AnsOptquesIdWithNextQuesMap.put(ansOpt.Question_Template__c,new Set<string>());
                    }
                    AnsOptquesIdWithNextQuesMap.get(ansOpt.Question_Template__c).add(ansOpt.Next_Question__c);
                }
                if ( ansOpt.Dependent_Question__c != null ){
                    questionIdSet.add(ansOpt.Dependent_Question__c);
                }
                if ( ansOpt.Dependent_Question__c != ansOptOldMap.get(ansOpt.Id).Dependent_Question__c || 
                     ansOpt.Next_Question__c != ansOptOldMap.get(ansOpt.Id).Next_Question__c ){
                     if ( ansOpt.Question_Template__c != null && 
                        ( ansOpt.Next_Question__c != null || ansOpt.Dependent_Question__c != null )){
                        if ( !quesIdWithAnsOptListMap.containsKey(ansOpt.Question_Template__c) ){
                            quesIdWithAnsOptListMap.put(ansOpt.Question_Template__c,new List<Answer_Option__c>());
                            quesIdWithAnsOptListMap.get(ansOpt.Question_Template__c).add(ansOpt);
                        } else {
                            quesIdWithAnsOptListMap.get(ansOpt.Question_Template__c).add(ansOpt);
                        }
                    }
                     
                }
            }
        }
        if ( questionIdSet != null && questionIdSet.size() > 0 ){
            for( Question_Template__c ques :[SELECT Id,Name,Question_Type__c,Section_Question__r.Questionnaire_Section__c
                                            FROM Question_Template__c WHERE Id IN :questionIdSet] ){
                if ( !quesIdWithAssTempIdMap.containsKey(ques.Id) ){
                    quesIdWithAssTempIdMap.put(ques.Id,ques.Section_Question__r.Questionnaire_Section__c);
                }
                if ( ques.Question_Type__c == 'MultiselectPicklist' ) {
                    multiselectQTSet.add(ques.Id);
                }
            }
        }
        
        if ( quesIdWithAnsOptListMap != null && quesIdWithAnsOptListMap.size() > 0 ){
        
            for( Answer_Option__c ansOption :[SELECT Id,Name,Help_Text__c,Weight__c,Dependent_Question__c,Next_Question__c,
                                            Question_Template__r.Question_Type__c,Question_Template__c
                                            FROM Answer_Option__c
                                            WHERE Question_Template__c IN :quesIdWithAnsOptListMap.keySet() AND 
                                            (Dependent_Question__c != null OR Next_Question__c != null) AND Id NOT IN :ansOptNewList ] ){
                
                if ( ansOption.Dependent_Question__c != null && !quesIdWithDependentQuesSet.contains(ansOption.Question_Template__c)){
                    quesIdWithDependentQuesSet.add(ansOption.Question_Template__c);
                } else if ( ansOption.Next_Question__c != null && !quesIdWithNextQuesSet.contains(ansOption.Question_Template__c)){
                    quesIdWithNextQuesSet.add(ansOption.Question_Template__c);
                }
                if ( ansOption.Question_Template__r.Question_Type__c == 'MultiselectPicklist' ) {
                    if ( !AnsOptquesIdWithNextQuesMap.containsKey(ansOption.Question_Template__c ) ) {
                        AnsOptquesIdWithNextQuesMap.put(ansOption.Question_Template__c,new Set<string>());
                    }
                    AnsOptquesIdWithNextQuesMap.get(ansOption.Question_Template__c).add(ansOption.Next_Question__c);
                }
            }
            for( List<Answer_Option__c> ansOptRecList :quesIdWithAnsOptListMap.values() ){
                for( Answer_Option__c ansOptRec :ansOptRecList ){
                    if ( ansOptRec.Next_Question__c != null && 
                        quesIdWithAssTempIdMap.get(ansOptRec.Question_Template__c) != quesIdWithAssTempIdMap.get(ansOptRec.Next_Question__c) ){
                        ansOptRec.adderror('Please provide same template\'s next question for Answer Option Record: '+ansOptRec.Name);
                    } else if ( ansOptRec.Dependent_Question__c != null && 
                        quesIdWithAssTempIdMap.get(ansOptRec.Question_Template__c) != quesIdWithAssTempIdMap.get(ansOptRec.Dependent_Question__c) ){
                        ansOptRec.adderror('Please provide same template\'s dependent question for Answer Option Record: '+ansOptRec.Name);
                    } else if ( (ansOptRec.Next_Question__c != null && quesIdWithDependentQuesSet.contains(ansOptRec.Question_Template__c)) || 
                         (ansOptRec.Dependent_Question__c != null && quesIdWithNextQuesSet.contains(ansOptRec.Question_Template__c)) ){
                        ansOptRec.adderror('Please provide next question or dependent question for this Question Template '+ansOptRec.Question_Template__c);
                    } else if ( multiselectQTSet.contains(ansOptRec.Question_Template__c) && AnsOptquesIdWithNextQuesMap.containsKey(ansOptRec.Question_Template__c) && 
                                AnsOptquesIdWithNextQuesMap.get(ansOptRec.Question_Template__c).size() > 1 ) {
                        ansOptRec.adderror('All Answer Options should point to the same Next Question for MultiselectPicklist question type');  
                    } 
                }
            }
        }
    }
}