src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAnswerOptionHandler.cls
@isTest
public class TestAnswerOptionHandler {
    @testSetup static void methodName() {
        List<Main_questionaire__c> assTempList = new List<Main_questionaire__c>{
            new Main_questionaire__c(Template_name__c = 'testTemp1'),
                new Main_questionaire__c(Template_name__c = 'testTemp2')
                };
                    insert assTempList;
        List<Section_Template__c> secList = new List<Section_Template__c>{
            new Section_Template__c(Section_label__c = 'test sec1',Questionnaire_Section__c = assTempList[0].Id ),
                new Section_Template__c(Section_label__c = 'test sec2',Questionnaire_Section__c = assTempList[1].Id)
                };
                    insert secList;
        List<Question_Template__c> quesList = new List<Question_Template__c>{
            new Question_Template__c(Question_Label__c = 'test ques1',Section_Question__c = secList[0].Id),
                new Question_Template__c(Question_Label__c = 'test ques2',Section_Question__c = secList[0].Id),
                new Question_Template__c(Question_Label__c = 'test ques3',Section_Question__c = secList[0].Id),
                new Question_Template__c(Question_Label__c = 'test ques4',Section_Question__c = secList[1].Id),
                new Question_Template__c(Question_Label__c = 'test ques5',Section_Question__c = secList[1].Id),
                new Question_Template__c(Question_Label__c = 'test ques6',Section_Question__c = secList[1].Id)
                };
                    insert quesList;
        List<Answer_Option__c> ansOptList1= new List<Answer_Option__c>{
            new Answer_Option__c(Question_Template__c =quesList[0].Id,Order_No__c=1,
                                 Name = 'test1'),
                new Answer_Option__c(Question_Template__c =quesList[0].Id,Order_No__c=1,
                                     Name ='test2',Dependent_Question__c = quesList[1].Id),
                new Answer_Option__c(Question_Template__c =quesList[1].Id,Order_No__c=1,
                                     Name = 'test3',Next_Question__c = quesList[2].Id),
                new Answer_Option__c(Question_Template__c =quesList[1].Id,Order_No__c=1,
                                     Name = 'test1',Next_Question__c = quesList[1].Id)
                };
                    Test.startTest();
                    insert ansOptList1;
              Test.stopTest();
        List<Answer_Option__c> ansOptList2= new List<Answer_Option__c>{
            new Answer_Option__c(Question_Template__c =quesList[0].Id,Order_No__c=1,
                                 Name = 'test1'),
                new Answer_Option__c(Question_Template__c =quesList[0].Id,Order_No__c=1,
                                     Name ='test2',Dependent_Question__c = quesList[1].Id),
                new Answer_Option__c(Question_Template__c =quesList[1].Id,Order_No__c=1,
                                     Name = 'test3',Next_Question__c = quesList[2].Id)
                
                };
                    
                    insert ansOptList2;
        List<Answer_Option__c> ansOptList= new List<Answer_Option__c>{
            new Answer_Option__c(Question_Template__c =quesList[0].Id,Order_No__c=1,
                                 Name = 'test1',Dependent_Question__c = quesList[1].Id,Next_Question__c = quesList[1].Id)
                };
                    try{
                        insert ansOptList;
                    } catch (Exception e){
                        String ex= e.getMessage();
                        System.debug('mess1'+ex);
                        System.assert(ex.contains('Please provide either dependent question or Next Question for answer Option Record'));
                    }    
    }
    static testmethod void method1(){
        List<Question_Template__c> quesList = [SELECT Id FROM Question_Template__c LIMIT 20];
        List<Answer_Option__c> ansOptionlist =[SELECT Id, Name, Order_No__c, Dependent_Question__c, 
                                               Next_Question__c, Weight__c, Question_Template__c, Help_Text__c 
                                               FROM Answer_Option__c
                                               WHERE Question_Template__c =:quesList[0].Id];
        ansOptionlist[0].Dependent_Question__c = null;
        ansOptionlist[0].Next_Question__c = quesList[3].Id;
        try{
            update ansOptionlist;
        } catch (Exception e){
            String ex= e.getMessage();
            System.debug('mess2'+ex);    
            System.assert(ex.contains('Please provide same template\'s next question for Answer Option Record:'));
        }   
        List<Answer_Option__c> ansOptionlist1=[SELECT Id, Name, Order_No__c, Dependent_Question__c, 
                                               Next_Question__c, Weight__c, Question_Template__c, Help_Text__c 
                                               FROM Answer_Option__c
                                               WHERE Question_Template__c =:quesList[0].Id];
        ansOptionlist1[0].Dependent_Question__c = quesList[3].Id;
        try{
            update ansOptionlist1;
        } catch (Exception e){
            String ex= e.getMessage();
            System.debug('mess3'+ex);    
            System.assert(ex.contains('Please provide same template\'s dependent question for Answer Option Record:'));
        }   
        List<Answer_Option__c> ansOptionlist2=[SELECT Id, Name, Order_No__c, Dependent_Question__c, 
                                               Next_Question__c, Weight__c, Question_Template__c, Help_Text__c 
                                               FROM Answer_Option__c
                                               WHERE Question_Template__c =:quesList[0].Id];
        ansOptionlist2[0].Dependent_Question__c = quesList[3].Id;
        ansOptionlist2[0].Next_Question__c = quesList[3].Id;
        try{
            update ansOptionlist2;
        } catch (Exception e){
            String ex= e.getMessage();
            System.debug('mess4'+ex);    
            System.assert(ex.contains('Please provide either dependent question or Next Question for Answer Option Record:'));
        } 
    }
}