src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Context_Questions_Mapping__c</fullName>
        <label>Context Questions Mapping</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestImportAssessmentTemplateController.cls
@isTest 
public class TestImportAssessmentTemplateController {

    static testMethod void method1() {
       
        Test.startTest();
        Main_questionaire__c[] templateList = new Main_questionaire__c[] {
            new Main_questionaire__c(Template_name__c = 'General Safety',Context_Questions_Mapping__c='Q-4~ExAM__Answer_Text__c:Q-0~ExAM__Comment__c'),
            new Main_questionaire__c(Template_name__c = 'Fire Safety'),
            new Main_questionaire__c(Template_name__c = 'Accident Safety'),
            new Main_questionaire__c(Template_name__c = 'General Instructions')
        };
        List<String> oldTempIdList = new List<String> {'id1','id2','id3','id4'};
        List<String> oldSecIdList = new List<String> {'id1','id2','id3','id4'};
        List<String> oldQusIdList = new List<String> {'Q-1','Q-2','Q-3','Q-4','Q-5','Q-6','Q-7'};
        List<String>oldAnsOptIdList = new List<String> {'Ans- opt1','Ans- opt2','Ans- opt3' };
        Map<String, String> responseTemplateInsert = ImportAssessmentTemplateController.saveAssessmentTemplate(templateList, oldTempIdList);
        //insert templateList;
        if (responseTemplateInsert != null && responseTemplateInsert.size() > 0) {
            List<Section_Template__c> secTemp = new List<Section_Template__c> {
                    new Section_Template__c(Section_label__c = 'Section1',Questionnaire_Section__c = responseTemplateInsert.get('id1')),
                    new Section_Template__c(Section_label__c = 'Section2',Questionnaire_Section__c = responseTemplateInsert.get('id1')),
                    new Section_Template__c(Section_label__c = 'Section3',Questionnaire_Section__c = responseTemplateInsert.get('id1')),
                    new Section_Template__c(Section_label__c = 'Section4',Questionnaire_Section__c = responseTemplateInsert.get('id1'))
            };
            Map<String, String> responseSec = ImportAssessmentTemplateController.saveSectionTemplate(secTemp,oldSecIdList);
            
            if (responseSec != null && responseSec.size() > 0) {

                List<Question_Template__c> quesTemp = new List<Question_Template__c> {
                    new Question_Template__c(Question_Label__c = 'question1', Next_Question__c = 'Q-1', Section_Question__c = responseSec.get('id1'), Question_Type__c = 'RadioPicklist'),
                    new Question_Template__c(Question_Label__c = 'question2', Next_Question__c = 'Q-2~Q-3', Section_Question__c = responseSec.get('id1')),
                    new Question_Template__c(Question_Label__c = 'question3', Section_Question__c = responseSec.get('id1')),
                    new Question_Template__c(Question_Label__c = 'question4', Section_Question__c = responseSec.get('id1')),
                    new Question_Template__c(Question_Label__c = 'question5', Dependent_Question__c = 'Q-5~Q-6', Section_Question__c = responseSec.get('id1')),
                    new Question_Template__c(Question_Label__c = 'question6', Section_Question__c = responseSec.get('id1')),
                    new Question_Template__c(Question_Label__c = 'question7', Section_Question__c = responseSec.get('id1'))
                };
                Map<String, Map<String, String>> responseQuestion = ImportAssessmentTemplateController.saveQuestionTemplate(quesTemp,oldQusIdList);
                System.assertEquals(null,responseQuestion.get('error'));
                if (responseQuestion != null && responseQuestion.size() > 0) {
                    if (!responseQuestion.containsKey('error')) {

                        String responseDecisionTreepopulate = ImportAssessmentTemplateController.decisionTreeQuestionUpdate(responseTemplateInsert.values(), responseQuestion.get('newQuesNameMap'), responseQuestion.get('newQuesIdMap'));
                        system.assertEquals('success',responseDecisionTreepopulate);

                        List<String> oldTempValue = new List<String>();
                        oldTempValue.addAll(responseTemplateInsert.keySet());
                        String responseDependentQues = ImportAssessmentTemplateController.contextQuestionMapFieldsUpdate(oldTempValue, responseQuestion.get('newQuesNameMap'), responseTemplateInsert);
                        system.assertEquals('success',responseDependentQues);
                        
                        List<Answer_Option__c> ansoptions1 = new List<Answer_Option__c> {
                            new Answer_Option__c(Question_Template__c = quesTemp[0].Id, Order_No__c = 1, Name = 'optA', Weight__c = 50), 
                            new Answer_Option__c(Question_Template__c = quesTemp[0].Id, Order_No__c = 2, Name = 'optB', Weight__c = 50), 
                            new Answer_Option__c(Question_Template__c = quesTemp[0].Id, Order_No__c = 3, Name = 'optC', Weight__c = 50)
                        };    
                        Map<string, string> ansOptMap = ImportAssessmentTemplateController.saveAnswerOptions(ansoptions1 ,oldAnsOptIdList);
                        System.assert(ansOptMap != Null);
                    }
                }
            }
            ImportAssessmentTemplateController.deleteTemplate(responseTemplateInsert);
        }
           
        Test.stopTest();
        
    }
}