src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Score_By_Section_Weight__c</fullName>
        <inlineHelpText>calculate based on section weights</inlineHelpText>
        <label>Score By Section Weight?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight_Template__c</fullName>
        <description>template to choose for the assessment</description>
        <inlineHelpText>template to choose for the assessment</inlineHelpText>
        <label>Weight Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non Weighted Section</fullName>
                </value>
                <value>
                    <fullName>Non Weighted Section with N/A</fullName>
                </value>
                <value>
                    <fullName>Weighted Section</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Focus_category__c</fullName>
        <description>Group which will have questions from different sections</description>
        <inlineHelpText>Group which will have questions from different sections</inlineHelpText>
        <label>Focus category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_Of_Question__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is the question weight</inlineHelpText>
        <label>Question Weight</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_Weight__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>0 to 100%</inlineHelpText>
        <label>Section Weight (%)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssessmentWeightMgmtController.cls
public with sharing class AssessmentWeightMgmtController {

    public string wtTemplate{get;set;}
    public string sectionScore{get;set;}
    public string templateName{get;set;}
    public string templateid{get;set;}
    public string sectionid{get;set;}

    public List<Question_Template__c> questionsLists { get; set; }
    public List<Section_Template__c > sectionsLists{ get; set; }
    public List<SelectOption> templateLists { get; set; }
    public List<SelectOption> sectionOptionLists { get; set; }
    public List<Main_questionaire__c> alltemplateLists { get; set; }

    public Map<Id, string> quesIdwithTempMap;
    
    public AssessmentWeightMgmtController(ApexPages.StandardController controller) {

        try {

            templateLists =new List<SelectOption>();
            sectionOptionLists =new List<SelectOption>();
            /*
            Schema.DescribeFieldResult wttemplates = Main_questionaire__c.Weight_Template__c.getDescribe();
            List<Schema.PicklistEntry> wttemplatesValues = wttemplates.getPicklistValues();
            System.debug('~~~4 '+wttemplatesValues);
            wttemplateLists.add(new SelectOption('None','None'));
            for (Schema.PicklistEntry a : wttemplatesValues)
            {
                System.debug('~~~3 '+a.getLabel()+ a.getValue());
                wttemplateLists.add(new SelectOption(a.getLabel(), a.getValue()));
            }
            */

            SFDCAccessController accessAT = ExAMUtilClass.AccessController;
            List<String> fieldsListAT = new List<String>{'ExAM__Template_name__c', 'ExAM__Score_By_Section_Weight__c', 'ExAM__Weight_Template__c'};
            accessAT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Main_questionaire__c'), fieldsListAT);

            alltemplateLists = [SELECT Id, Name, Template_name__c, Score_By_Section_Weight__c, Weight_Template__c FROM Main_questionaire__c ORDER BY Template_name__c LIMIT 1000];
            templateLists.add(new SelectOption('None','None'));
            for(Main_questionaire__c res: alltemplateLists ) 
            {
                System.debug('~~~1 res.Weight_Template__c'+res.Weight_Template__c );
                if ( res.Template_name__c != null ){
                    templateLists.add(new SelectOption(res.id,res.Template_name__c ));
                } else {
                    templateLists.add(new SelectOption(res.id,res.Name ));
                }
                //wttemplateLists.add(new SelectOption(res.id,res.Weight_Template__c ));
                //System.debug('~~~2 res.Weight_Template__c'+res.Weight_Template__c );
            }
        }
        catch(Exception e) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    }

    /*public string getwtTemplate () {
        return wtTemplate ;
    }*/

    public void setwtTemplate() {
        try {
            System.debug('~~~setwtTemplate'+templateid);
            if(templateid!=null)
            {
                if(sectionOptionLists!=null){ sectionOptionLists =new List<SelectOption>();}
                /*
                for(Main_questionaire__c res: alltemplateLists ) 
                {
                    string ids=(string)res.id;
                    if(ids.equalsIgnoreCase(templateid))
                    {
                        wtTemplate  = res.Weight_Template__c;
                        System.debug('~~~setwtTemplate '+wtTemplate   );break;
                    }
                }
                */

                SFDCAccessController accessST = ExAMUtilClass.AccessController;
                List<String> fieldsListST = new List<String>{'ExAM__Order_No__c', 'ExAM__status__c', 'ExAM__Section_label__c', 'ExAM__Section_Weight__c'};
                accessST.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Section_Template__c'), fieldsListST);

                //Get all the sections list
                sectionsLists = [SELECT Id, Name, Order_No__c, status__c, Section_label__c, Section_Weight__c FROM Section_Template__c where Questionnaire_Section__c=:templateid ORDER BY Order_No__c];
                sectionOptionLists.add(new SelectOption('None','None'));
                for(Section_Template__c res: sectionsLists )
                {
                    if ( res.Section_label__c != null ){
                        sectionOptionLists.add(new SelectOption(res.id,res.Section_label__c));
                    } else {
                        sectionOptionLists.add(new SelectOption(res.id,res.Name));
                    }
                }
            }
            questionsLists=null;
        }
        catch(Exception e) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    }

    public void setquestionList() {

        try {
            System.debug('~~~setwtTemplate'+templateid);questionsLists =null;
            if((templateid!=null)&&(sectionid!=null))
            {
                //Get all the sections list
                //questionsLists = [SELECT  Id,Section_Question__c,Question_Label__c,Subquestion_Label__c,Weight_Of_Question__c,Question_Order_No__c,Question_Type__c,Weight_of_Answer__c FROM Question_Template__c where (Section_Question__c=:sectionid AND Question_Type__c='RadioPicklist') ORDER BY Question_Order_No__c]; 
                questionsLists = new List<Question_Template__c>();
                quesIdwithTempMap = new Map<Id,string>();

                SFDCAccessController accessQT = ExAMUtilClass.AccessController;
                List<String> fieldsListQT = new List<String>{'ExAM__Question_Label__c', 'ExAM__Question_Order_No__c', 'ExAM__Question_Type__c', 'ExAM__Section_Question__c', 'ExAM__Subquestion_Label__c', 'ExAM__Weight_of_Answer__c', 'ExAM__Weight_Of_Question__c'};
                accessQT.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Question_Template__c'), fieldsListQT);

                SFDCAccessController accessAO = ExAMUtilClass.AccessController;
                List<String> fieldsListAO = new List<String>{'ExAM__Help_Text__c', 'ExAM__Weight__c'};
                accessAO.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Answer_Option__c'), fieldsListAO);

                for(Question_Template__c quesTemp :[SELECT Id,Section_Question__c,Question_Label__c,Subquestion_Label__c,Weight_Of_Question__c,
                                                    Question_Order_No__c,Question_Type__c,Weight_of_Answer__c,
                                                    (SELECT Id,Name,Help_Text__c,Weight__c FROM Answer_Options__r) 
                                                    FROM Question_Template__c 
                                                    WHERE (Section_Question__c=:sectionid AND Question_Type__c='RadioPicklist') 
                                                    ORDER BY Question_Order_No__c]){ 
                    if( quesTemp.Answer_Options__r.size() > 0 ){
                        List<string> optList = new List<string>();
                        List<string> wtList = new List<string>();
                        for( Answer_Option__c ansOpt :quesTemp.Answer_Options__r ){
                            if( ansOpt != null ){
                                if( ansOpt.Name != null && ansOpt.Name != '' ) {
                                    optList.add(ansOpt.Name);
                                }
                                if( ansOpt.Weight__c != null ){
                                    wtList.add(string.valueOf(ansOpt.Weight__c));
                                }
                            }
                        }
                        if(  optList.size() > 0 ){
                            quesTemp.Subquestion_Label__c = string.join(optList,'~');
                        }
                        if(  wtList.size() > 0 ){
                            quesTemp.Weight_of_Answer__c = string.join(wtList,'~');
                        }
                    } else {
                       //questionsLists.add(quesTemp);
                    }
                    questionsLists.add(quesTemp);
                    string weight = quesTemp.Weight_of_Answer__c+'='+quesTemp.Weight_Of_Question__c;
                    System.debug('weight:::'+weight);
                    quesIdwithTempMap.put(quesTemp.Id,weight);
                }                 
            }
        }
        catch(Exception e) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    }

    public PageReference savesections()
    {
        try {
            if(sectionsLists!=null)
            {
                System.debug('~~~sectionsLists '+sectionsLists );
                Decimal totalsections=0;
                for(Section_Template__c res: sectionsLists ) 
                {
                    if(res.Section_Weight__c!=null)
                    {
                        totalsections+=res.Section_Weight__c;
                    }
                }  
                if(totalsections==100)
                {
                    SFDCAccessController accessST = ExAMUtilClass.AccessController;
                    List<string> fieldsListST = new List<string>{'ExAM__Section_Weight__c'};
                    accessST.assertAuthorizedToUpdate(Schema.getGlobalDescribe().get('exam__Section_Template__c'), fieldsListST);

                    upsert sectionsLists;
                }
                else
                {
                    ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Total Section score is not 100%');//Same old drama 
                    ApexPages.addMessage(myMsg);
                    // Return null so the page won't redirect
                    return null;
                }
            } 
            //string urlform='/apex/AssessmentWeightManagement';
            //PageReference saveClicked=new PageReference(urlform);
            //saveClicked.setRedirect(true); return saveClicked;
        }
        catch(Exception e) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
        return null;
    }

    public PageReference savequestions()
    {
        try {

            if((templateid!=null)&&(sectionid!=null))
            {
                if(questionsLists!=null)
                {
                    //added on 19-05-2017
                    List<Question_Template__c> updateQuesList = new List<Question_Template__c>();
                    for( Question_Template__c q :questionsLists ){
                        System.debug('map values'+quesIdwithTempMap.get(q.Id)+':::'+q.Weight_of_Answer__c);
                        string weight = q.Weight_of_Answer__c+'='+q.Weight_Of_Question__c;
                        System.debug('weight in save:::'+weight);
                        if ( weight != quesIdwithTempMap.get(q.Id) ) {
                            updateQuesList.add(q);
                        }
                    }
                    System.debug('to be update ques list:::'+updateQuesList);
                    System.debug('size of updat list:::'+updateQuesList.size());
                    List<Answer_Option__c> ansOptRecList = new List<Answer_Option__c>();     
                    for( Question_Template__c ques :updateQuesList ){
                        System.debug('ques template:::::'+ques.Answer_Options__r);
                        List<string> optList = new List<string>();
                        List<string> wtList = new List<string>();
                        System.debug('ans rec size:::'+ques.Answer_Options__r.size());
                        if( ques.Answer_Options__r.size() > 0 ){
                            System.debug('ans rec size:::>0');          
                            if( ques.Subquestion_Label__c != null && ques.Subquestion_Label__c != '' ){        
                                optList = ques.Subquestion_Label__c.split('~');
                            }
                            if( ques.Weight_of_Answer__c != null && ques.Weight_of_Answer__c != '' ){
                                wtList = ques.Weight_of_Answer__c.split('~');
                            }
                            System.debug('optList:::'+optList);
                            System.debug('wtList:::'+wtList);
                            Integer optLen = 0;
                            if( optList.size() > 0 ){
                                optLen = optList.size();
                                System.debug('len of opt list:::::'+optLen);
                            }
                            for( Integer i = 0; i < optLen; i++ ){
                                System.debug('i:::'+i);
                                System.debug('option:::'+optList[i]);
                                for( Answer_Option__c ansOpt :ques.Answer_Options__r ){
                                    System.debug('ansOpt:::'+ansOpt.Name+':::'+optList[i]);
                                    if ( ansOpt != null && ansOpt.Name == optList[i] ){
                                        System.debug('equal:::');
                                        if( wtList.size() > 0 && wtList[i] != null ){
                                            ansOpt.Weight__c = Decimal.valueOf(  wtList[i] );
                                            System.debug('ansOpt:::'+ansOpt);
                                        } else {
                                            System.debug('else ansOpt:::'+ansOpt);
                                            ansOpt.Weight__c = 0;
                                        }
                                        ansOptRecList.add(ansOpt);
                                        System.debug('added ansOptRecList:::'+ansOptRecList);
                                        //break;
                                    }
                                }
                            }
                            System.debug('ansOptRecList:::'+ansOptRecList);
                            //ques.Subquestion_Label__c = '';
                            //ques.Weight_of_Answer__c = '';
                        }
                    }
                    System.debug('~~~ update questionsLists'+updateQuesList);

                    SFDCAccessController accessQT = ExAMUtilClass.AccessController;
                    List<string> fieldsListQT = new List<string>{'ExAM__Weight_of_Answer__c', 'ExAM__Weight_Of_Question__c'};
                    accessQT.assertAuthorizedToUpdate(Schema.getGlobalDescribe().get('exam__Question_Template__c'), fieldsListQT);

                    upsert updateQuesList;

                    for ( Question_Template__c ques :updateQuesList ){
                        string weight = ques.Weight_of_Answer__c+'='+ques.Weight_Of_Question__c;
                        System.debug('weight in save:::'+weight);
                        quesIdwithTempMap.put(ques.Id,weight);
                    }
                    System.debug('quesIdwithTempMap=='+quesIdwithTempMap);
                    if( ansOptRecList.size() > 0 ){

                        SFDCAccessController accessAO = ExAMUtilClass.AccessController;
                        List<string> fieldsListAO = new List<string>{'ExAM__Weight__c'};
                        accessAO.assertAuthorizedToUpdate(Schema.getGlobalDescribe().get('exam__Answer_Option__c'), fieldsListAO);

                        update ansOptRecList;
                        /*
                        PageReference tempPage = ApexPages.currentPage();            
                        tempPage.setRedirect(true);
                        return tempPage;
                        */
                    }
                }
            } 
            //string urlform='/apex/AssessmentWeightManagement';
            //PageReference saveClicked=new PageReference(urlform);
            //saveClicked.setRedirect(true); return saveClicked;
        }
        catch(Exception e) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
        return null;
    }

    public PageReference cancel()
    { 
        string urlform='/apex/AssessmentWeightManagement';
        //'/apex/QuestionnaireCustomIssue?accid='+accountId+'&issueid='+issueId+'&templatename='+templateName;
        PageReference saveClicked=new PageReference(urlform);
        saveClicked.setRedirect(true);
        return saveClicked;
    }

    public PageReference exit()
    {
        PageReference cancelClicked;
        /*
        string userAgent =ApexPages.currentPage().getHeaders().get('USER-AGENT');
        if(userAgent.contains('iPhone')) {
            cancelClicked=new PageReference('/one/one.app');
        }
        else {
        */
        cancelClicked=new PageReference('/home/home.jsp');
        //}
        cancelClicked.setRedirect(true);
        return cancelClicked;  
    }

    public static testMethod void AssessmentWeightManagement_Test()
    {

        //Test converage for the visualforce page
        PageReference pageRef = Page.AssessmentWeightManagement;
        Test.setCurrentPageReference(pageRef);
        Test.startTest();
        Main_questionaire__c maintest=new Main_questionaire__c (Template_name__c ='test');
        upsert maintest;
        Section_Template__c sc= new Section_Template__c(Questionnaire_Section__c=maintest.id,Section_Weight__c=50,Section_label__c='test section'); 
        insert sc;
        Section_Template__c sc1= new Section_Template__c(Questionnaire_Section__c=maintest.id,Section_label__c='test section 2'); 
        insert sc1;
        System.currentPageReference().getParameters().put('templateid', maintest.id);

        Question_Template__c scq= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your name?',Question_Order_No__c=1,Question_Type__c='Text',Focus_category__c='CCTV',Weight_of_Answer__c='4');     
        Question_Template__c scqp= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=2,Weight_Of_Question__c=2,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Perimeter',Weight_of_Answer__c='2~3');     
        Question_Template__c scqm= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your qualification?',Question_Order_No__c=3,Question_Type__c='MultiselectPicklist',Subquestion_Label__c='High School~Bachelors~Masters',Focus_category__c='Emergency Response Plan',Weight_of_Answer__c='2~3~4');     
        Question_Template__c scqp1= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=4,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Adequate Lighting',Weight_of_Answer__c='2~3');     
        Question_Template__c scqm1= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your qualification?',Question_Order_No__c=5,Question_Type__c='MultiselectPicklist',Subquestion_Label__c='High School~Bachelors~Masters',Focus_category__c='Adequate Locking System');     
        Question_Template__c scqp2= new Question_Template__c(Section_Question__c=sc.id,Question_Label__c='What is your age?',Question_Order_No__c=6,Question_Type__c='RadioPicklist',Subquestion_Label__c='10-30~31-50',Focus_category__c='Mail Handling');     

        insert scq;insert scqp;insert scqm;insert scqp1;insert scqm1;insert scqp2;

        ApexPages.StandardController scont = new ApexPages.StandardController(maintest);
        AssessmentWeightMgmtController d= new AssessmentWeightMgmtController(scont ); 
        d.alltemplateLists.add(maintest);

        System.currentPageReference().getParameters().put('templateid', maintest.id);
        System.currentPageReference().getParameters().put('sectionid', sc.id);
        d.sectionsLists=new List<Section_Template__c>();
        d.sectionsLists.add(sc);d.sectionsLists.add(sc1);
        d.setwtTemplate();d.setquestionList();d.savesections();d.savequestions();
        d.cancel();d.exit();
        System.assert(d.setquestionList()==null,'questionslist returns null');

        System.assert(d.setwtTemplate()==null,'sectionslist returns  null');
        Test.stopTest();
    }
}