src/objects/Answer_Option__c.object
<CustomObject>
    <description>Where ExAM stores information about potential Answers to Questions.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Help_Text__c</fullName>
        <label>Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options (Next Question)</relationshipLabel>
        <relationshipName>Answer_Options1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_No__c</fullName>
        <label>Order No</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answer Options</relationshipLabel>
        <relationshipName>Answer_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight(%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer Option</label>
    <nameField>
        <label>Answer Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answer Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distributions</relationshipLabel>
        <relationshipName>Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Distribution</label>
    <nameField>
        <label>Distribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Distribution_Group__c.object
<CustomObject>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isArchive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isArchive</label>
        <type>Checkbox</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <label>Dependent Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Order_No__c</fullName>
        <description>This is to order the sections from lowest to greatest no</description>
        <label>Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>isArchive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isArchive</label>
        <type>Checkbox</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssessmentTemplateController.cls
public with sharing class AssessmentTemplateController {
    
    
    @AuraEnabled
    public static List<Main_questionaire__c> fetchAssessment(String selectView) {
        
        List<Main_questionaire__c> assessmentTemp = AssessmentService.getAssessmentsByCurrentUser(selectView);
        
        return assessmentTemp; 
    }
    
    @AuraEnabled
    public static Main_questionaire__c archiveAssessment(Main_questionaire__c selAssessment){
        
        selAssessment = AssessmentService.archieveAssessment(selAssessment);
        return selAssessment;
    }
    
    @AuraEnabled
    public static Main_questionaire__c cloneAssessmentTemp(String recordId, String temp_name) {   
        Map<Id,String> assessmentIdWthTempName = new Map<Id,String>{recordId => temp_name};
        List<Main_questionaire__c> assessmentList = ExamManager.clone(assessmentIdWthTempName);
        String assessmentId = assessmentList[0].Id;
        AssessmentService.updateAssessmentDueToChildUpdates(assessmentId);
        String fields = 'Template_name__c, isArchive__c';
        FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'view', 'Main_questionaire__c');
        assessmentList = [SELECT Id, Template_name__c, CreatedDate, LastModifiedDate FROM Main_questionaire__c WHERE Id =:assessmentId]; 
        return assessmentList[0];
    }
    
    
    @AuraEnabled
    public static List<Section_Template__c> fetchSecTemplate(String assessementId) {
        
        List<Section_Template__c> sectionTemplates = SectionService.getSectionsByAssessmentId(assessementId);
        return sectionTemplates;
    }
    
    @AuraEnabled
    public static String fetchSecTemplateWthSectionFieldSetValue(String sObjectName, List<String> fieldSets, String sObjectId) {
        
        Map<String,Object> containWrapObject = new Map<String,Object>();
        if(!fieldSets.isEmpty()){
            Map<String,List<WrapperFieldSet>> WrapperFieldSetList = new Map<String,List<WrapperFieldSet>>();
            for(String fieldSet : fieldSets){
                WrapperFieldSetList.put(fieldSet,ExamDescribeHelper.getFieldSetByRecord(fieldSet,sObjectName));
            }
            containWrapObject.put('fields',WrapperFieldSetList);
        }
        
        
        List<sObject> objList = ExamDescribeHelper.getRecordByFieldSet(sObjectName,fieldSets,sObjectId);
        
        List<Section_Template__c> sectionTemplates = (List<Section_Template__c>)objList;
        containWrapObject.put('sobject',sectionTemplates);
        return JSON.serialize(containWrapObject);
    }
    
    @AuraEnabled
    public static String fetchQuesTemplateWthQuestionFieldSetValue(String sObjectName, List<String> fieldSets, String sObjectId) {
        
        
        Map<String,Object> containWrapObject = new Map<String,Object>();
        if(!fieldSets.isEmpty()){
            Map<String,List<WrapperFieldSet>> WrapperFieldSetList = new Map<String,List<WrapperFieldSet>>();
            for(String fieldSet : fieldSets){
                WrapperFieldSetList.put(fieldSet,ExamDescribeHelper.getFieldSetByRecord(fieldSet,sObjectName));
            }
            containWrapObject.put('fields',WrapperFieldSetList);
        }
        
        
        List<sObject> objList = ExamDescribeHelper.getRecordByFieldSet(sObjectName,fieldSets,sObjectId);
        
        List<Question_Template__c> questionTemplates = (List<Question_Template__c>)objList;
        questionTemplates = QuestionService.filterGetNonDependentQuestions(questionTemplates);
        containWrapObject.put('sobject', questionTemplates);
        
        Map<Id, Question_Template__c> idWthQuestions = new Map<Id, Question_Template__c>(questionTemplates);
        Set<Id> questionIds = idWthQuestions.keySet();
        containWrapObject.put('attachment', AttachmentService.getAttachmentsByQuestionIds(questionIds));
        
        return JSON.serialize(containWrapObject);
    }
    
    @AuraEnabled
    public static List<String> getQuestionType(){
        
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Question_Template__c.Question_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }
        
        return options;
    }
    
    @AuraEnabled
    public static Map<String, List<Object>> createQuestionWthAnswer(Question_Template__c QuestionTemplate, Integer orderNo, List<Answer_Option__c> answerOptions){
        
        Map<String, List<Object>> QuestionWthAnswer = new Map<String, List<Object>>();
        Set<String> answerOptionIds = new Set<String>();
        List<Question_Template__c> questionTemplates = QuestionService.createQuestion(QuestionTemplate, orderNo);
        String questionId = questionTemplates[0].Id; // get Assessment Id
        Question_Template__c question = QuestionService.getQuestion(questionId);
        String assessmentId = question.Section_Question__r.Questionnaire_Section__c;
        questionId = questionTemplates[orderNo].Id;
        for(Answer_Option__c answer : answerOptions){
            answer.Question_Template__c = questionId;
        }
        try{
            String fields = 'Name, Dependent_Question__c, Order_No__c, Weight__c, Question_Template__c, Next_Question__c, Help_Text__c';
            FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'create', 'Answer_Option__c');
            insert answerOptions;                               
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        
        // update Assessment
        AssessmentService.updateAssessmentDueToChildUpdates(assessmentId);
        
        QuestionWthAnswer.put('questions', QuestionService.filterGetNonDependentQuestions(questionTemplates));
        
        for(Answer_Option__c ans : answerOptions){
            answerOptionIds.add(ans.Id);
        }
        List<Answer_Option__c> questionOptions = AnswerOptionService.getAnswerOptionsWthRef(answerOptionIds);
        
        QuestionWthAnswer.put('answers', questionOptions);
        List<String> newQuestionId = new List<String>{questionId};
        QuestionWthAnswer.put('newQuestionId',newQuestionId);
        
        return QuestionWthAnswer;
    }
    
    @AuraEnabled
    public static List<Section_Template__c> createSection(Section_Template__c SectionTemplate, Integer orderNo){
        List<Section_Template__c> sectionTemplates = SectionService.createSection(SectionTemplate, orderNo);
        return sectionTemplates;
    }
    
    @AuraEnabled
    public static Main_questionaire__c createAssessment(Main_questionaire__c AssessmentTemplate, String selectView) {
        AssessmentTemplate = AssessmentService.createNewAssessment(AssessmentTemplate, selectView);
        return AssessmentTemplate;
    }
    
    
    @AuraEnabled
    public static Attachment saveFile(String attachmentId, String parentId, String fileName, String base64Data, String contentType) {
        
        Attachment attch = AttachmentService.saveAttachment(attachmentId, parentId, fileName, base64Data, contentType);
        attch.Body = null;
        String assessmentId = AnswerOptionService.getGrandParentsRef(attch.ParentId);
        AssessmentService.updateAssessmentDueToChildUpdates(assessmentId);
        return attch;
    }
    
    @AuraEnabled
    public static String updateAttachFile(String parentId, String fileName, String base64Data, String contentType){
        String attch = AttachmentService.saveFile(parentId, fileName, base64Data, contentType);
        AssessmentService.updateAssessmentDueToChildUpdates(parentId);
        return attch;
    }
    
    @AuraEnabled
    public static List<Attachment> fetchAttachment(String QuesId, List<String> answerOptionsId) { 
        List<Attachment> attachments;
        
        if(!answerOptionsId.isEmpty()){
            try{
                String fields = 'Name, ContentType, ParentId';
                FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'view', 'Attachment');
                attachments =  [SELECT Id, Name, ContentType, ParentId FROM Attachment WHERE ParentId IN :answerOptionsId];
            }
            catch(Exception e){
                throw new AuraHandledException(e.getMessage());
            }
            
        }else if(QuesId != null){
            attachments = AttachmentService.getAttachmentsByParentId(QuesId);
            
        }
        
        return attachments;
    }
    
    @AuraEnabled
    public static String getRecordById(String sObjectName, List<String> fieldSets, String sObjectId) {   
        
        Map<String,List<WrapperFieldSet>> WrapperFieldSetList = new Map<String,List<WrapperFieldSet>>();
        
        Map<String,Object> containWrapObject = new Map<String,Object>();
        
        for(String fieldSet : fieldSets){
            WrapperFieldSetList.put(fieldSet,ExamDescribeHelper.getFieldSetByRecord(fieldSet,sObjectName));
        }
        
        List<sObject> objList = ExamDescribeHelper.getRecordByFieldSet(sObjectName,fieldSets,sObjectId);
        List<WrapperAttachment> attachments = AttachmentService.getAttachmentById(sObjectId);                       
        
        containWrapObject.put('fields',WrapperFieldSetList);
        containWrapObject.put('sobject',objList);
        containWrapObject.put('attachment',attachments);
        
        return JSON.serialize(containWrapObject);
    }
    
    @AuraEnabled
    public static String getFieldSet(String sObjectName, List<String> fieldSets, String sObjectId) { 
        
        Map<String,List<WrapperFieldSet>> WrapperFieldSetList = new Map<String,List<WrapperFieldSet>>();
        
        Map<String,Object> containWrapObject = new Map<String,Object>();
        
        for(String fieldSet : fieldSets){
            WrapperFieldSetList.put(fieldSet,ExamDescribeHelper.getFieldSetByRecord(fieldSet,sObjectName));             
        }
        containWrapObject.put('fields',WrapperFieldSetList);
        return JSON.serialize(containWrapObject);
    }
    
    public class WrapperFieldSet{
        
        @AuraEnabled
        public String fieldApi;
        @AuraEnabled
        public String fieldDataType;
        @AuraEnabled
        public String fieldLabel;
        @AuraEnabled
        public String sObjectApi;
        @AuraEnabled
        public List<String> options;
        @AuraEnabled
        public String inLineHelpText;
        
        public WrapperFieldSet(String fieldApi, String fieldDataType, List<String> options, String fieldLabel, String sObjectApi, String helpText){
            this.fieldApi = fieldApi;
            this.fieldDataType = fieldDataType;
            this.options = options;
            this.fieldLabel = fieldLabel;
            this.sObjectApi = sObjectApi;
            this.inLineHelpText = helpText;
        }
        
    }
    
    
    public class WrapperAttachment{
        @AuraEnabled
        public String Name;
        @AuraEnabled
        public String Id;
        @AuraEnabled
        public String ContentType;
        public WrapperAttachment(String Name, String Id, String ContentType){
            this.Name = Name;
            this.Id = Id;
            this.ContentType = ContentType;
        }
        
    }
    
    
    @AuraEnabled
    public static String getRecord(String sObjectName, List<String> fieldSets, String sObjectId) {   
        
        Map<String,Object> containWrapObject = new Map<String,Object>();
        
        List<sObject> objList = ExamDescribeHelper.getRecordByFieldSet(sObjectName,fieldSets,sObjectId);
        List<WrapperAttachment> attachments = AttachmentService.getAttachmentById(sObjectId);
        
        containWrapObject.put('sobject',objList);
        containWrapObject.put('attachment',attachments);
        
        return JSON.serialize(containWrapObject);
    }
    
    @AuraEnabled
    public static List<Section_Template__c> moveSectionUpOrDwn(String assessmentId, Decimal index, String direction){
        
        List<Section_Template__c> sectionTemplates = SectionService.moveSectionUpOrDown(assessmentId, index, direction);
        
        return sectionTemplates;
    }
    
    @AuraEnabled
    public static Map<String, List<Question_Template__c>> moveQuestionToSection(String oldSectionId, String newSectionId, String direction, Decimal index, String recordId){
        
        Map<String, List<Question_Template__c>> oldToNewQuestion = QuestionService.moveQuestion(oldSectionId, newSectionId, direction, index, recordId);
        return oldToNewQuestion;
    }
    
    
    @AuraEnabled
    public static Map<String,List<Object>> copyQuestionTemplate(String questionId, String sectionId, String direction, Decimal index){
        Map<String,List<Object>> copyQuesAndAnswers = new Map<String,List<Object>>();
        Map<String,object> responseMap = QuestionService.copyQuestion(questionId, sectionId, direction, index);
        object objectId =  responseMap.get('newQuestionId');
        String newQuestionId =  String.valueOf(objectId);
        Boolean withInSection = Boolean.valueOf(responseMap.get('withInSec')); 
        Map<String,Answer_Option__c> answerOldIdWthNewAnswer = AnswerOptionService.cloneAnswerOptions(questionId,newQuestionId,withInSection);
        List<Question_Template__c> questionTemplates =  (List<Question_Template__c>)responseMap.get('updateRecords');
        
        Map<String,String> questionOldIdWthNewId = new Map<String,String>();
        questionOldIdWthNewId.put(questionId,newQuestionId);
        List<Attachment> copyQuestionImage = AttachmentService.copyQuestionImage(questionOldIdWthNewId);
        
        
        //update Assessment 
        String assessmentId = questionTemplates[0].Section_Question__r.Questionnaire_Section__c;
        AssessmentService.updateAssessmentDueToChildUpdates(assessmentId);
        
        copyQuesAndAnswers.put('copyQuestion',questionTemplates);
        copyQuesAndAnswers.put('copyAnswerOptions',(List<object>)answerOldIdWthNewAnswer.values());
        copyQuesAndAnswers.put('questionImage',copyQuestionImage); // new
        
        return copyQuesAndAnswers;
    }
    /*
    @AuraEnabled
    public static sObject updateRecord(String ObjectName, String id, String fieldName, String fieldVal){
        sObject obj = ExamFieldEditorController.updateRecord(ObjectName, id, fieldName, fieldVal);
        return obj;
    }*/
    @AuraEnabled
    public static sObject updateRecord(String ObjectName, String JSONStr){
        System.debug('JSONStr::::'+JSONStr);
        sObject obj = ExamFieldEditorController.updateRecord(ObjectName, JSONStr);
        return obj;
    }
    
    @AuraEnabled
    public static Map<String,List<object>> upsertAnswer(String answerOptions, List<String> removeOptionIds, Boolean derivedFromQuestion, List<Integer> removedOptionIndices){
        Map<String,List<object>> answerOptionList = AnswerOptionService.upsertAnswerOptions(answerOptions, removeOptionIds, derivedFromQuestion, removedOptionIndices);
        List<Answer_Option__c> upsertAnswerOptions = (List<Answer_Option__c>)answerOptionList.get('AnswerOptions');
        String answerOptionId = (String)upsertAnswerOptions[0].Id;
        String assessmentId = AnswerOptionService.getGrandParentsRef(answerOptionId);
        AssessmentService.updateAssessmentDueToChildUpdates(assessmentId);
        return answerOptionList;
    }
    
    @AuraEnabled
    public static Map<String,List<Object>> copyQuestionWithAttachment(String questionId, String sectionId, String direction, Decimal index){
        Map<String,List<Object>> copyQuesAndAnswerWithAttachment = new Map<String,List<Object>>();
        Map<String,String> questionOldIdWthNewId;
        List<Attachment> cloneAttachments, copyQuestionImage;
        Map<String,object> responseMap = QuestionService.copyQuestion(questionId, sectionId, direction, index);
        object objectId =  responseMap.get('newQuestionId');
        String newQuestionId =  String.valueOf(objectId);
        Boolean withInSection = Boolean.valueOf(responseMap.get('withInSec')); 
        Map<String,Answer_Option__c> answerOldIdWthNewAnswer = AnswerOptionService.cloneAnswerOptions(questionId,newQuestionId,withInSection);
        
        questionOldIdWthNewId = new Map<String,String>();
        questionOldIdWthNewId.put(questionId,newQuestionId);
        
        if(answerOldIdWthNewAnswer.isEmpty()){
            
            cloneAttachments = AttachmentService.cloneAttachmentByQuestionIds(questionOldIdWthNewId);
        }else{
            cloneAttachments = AttachmentService.cloneAttachment(answerOldIdWthNewAnswer);
        }
        copyQuestionImage = AttachmentService.copyQuestionImage(questionOldIdWthNewId);
        
        List<Question_Template__c> questionTemplates =  (List<Question_Template__c>)responseMap.get('updateRecords');
        
        //update Assessment 
        String assessmentId = questionTemplates[0].Section_Question__r.Questionnaire_Section__c;
        AssessmentService.updateAssessmentDueToChildUpdates(assessmentId);
        
        copyQuesAndAnswerWithAttachment.put('copyQuestion',questionTemplates);
        copyQuesAndAnswerWithAttachment.put('copyAnswerOptions',(List<object>)answerOldIdWthNewAnswer.values());
        copyQuesAndAnswerWithAttachment.put('copyAttachment',cloneAttachments);
        copyQuesAndAnswerWithAttachment.put('questionImage',copyQuestionImage);
        
        return copyQuesAndAnswerWithAttachment;
    }
    
    @AuraEnabled
    public static List<Question_Template__c> deleteQuestionTemplate(String questionId){
        List<Question_Template__c> questionTemplate= QuestionService.deleteQuestion(questionId);
        return questionTemplate;
    }
    
    @AuraEnabled
    public static Section_Template__c archiveSection(String sectionId, String assessmentId){
        
        Section_Template__c sectionTemp = SectionService.archiveSection(sectionId, assessmentId);
        return sectionTemp;
    }
    
    @AuraEnabled
    public static Map<String, List<Section_Template__c>> moveSection(String oldAssessmentId, String newAssessmentId, String direction, Integer index, String recordId){
        
        Map<String, List<Section_Template__c>> oldToNewSection = SectionService.moveSection(oldAssessmentId, newAssessmentId, direction, index, recordId);
        return oldToNewSection;
    }
    
    @AuraEnabled
    public static Map<String, List<Object>> copySection(String toassessmentId, String direction, Integer index, String recordId){
        Map<String, List<Object>> copySectionWithQuestionAndAttachment = SectionService.copySectionWithRelatedQuestions(toassessmentId, direction, index, recordId);
        return copySectionWithQuestionAndAttachment;
    }
    
     @AuraEnabled
    public static Main_questionaire__c getLastModifiedOfCurrentAssessment(String assessmentId){
        try{
            String fields = 'Template_name__c, isArchive__c';
            FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'view', 'Main_questionaire__c');
            Main_questionaire__c assessment = [SELECT Id, Template_name__c, CreatedDate, LastModifiedDate, isArchive__c FROM Main_questionaire__c WHERE Id =:assessmentId];
            return assessment;  
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled 
    public static List<Question_Template__c> getQuestions(String sectionId){
        try{
            String fields = 'Name, Question_Label__c, Question_Order_No__c';
            FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'view', 'Question_Template__c');
            List<Question_Template__c> questions = [SELECT Id, Name, Question_Label__c, Question_Order_No__c FROM Question_Template__c 
                                                    WHERE Section_Question__c = :sectionId ORDER BY Question_Order_No__c];
            return questions;   
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled 
    public static Attachment upsertQuestionImage(String attachmentId, String parentId, String fileName, String base64Data, String contentType){
        Attachment attch = AttachmentService.saveAttachment(attachmentId, parentId, fileName, base64Data, contentType);
        String questionId = attch.ParentId;
        
        try{
            String fields = 'Section_Question__c';
            FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'view', 'Question_Template__c');
            fields = 'Questionnaire_Section__c';
            FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'view', 'Section_Template__c');
            Question_Template__c question = [SELECT Section_Question__r.Questionnaire_Section__c FROM Question_Template__c WHERE Id =:questionId];
            AssessmentService.updateAssessmentDueToChildUpdates(question.Section_Question__r.Questionnaire_Section__c);
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        
        attch.Body = null;
        return attch;
        
    }
    @AuraEnabled
    public static List<Question_Template__c> getdependencyQuestionsLabel(List<String> dependencyQuestions){
        List<Question_Template__c> questions = [SELECT Id, Question_Label__c FROM Question_Template__c WHERE Name IN :dependencyQuestions];
        return questions;
    }
    
    @AuraEnabled 
    public static List<Distribution__c> fetchDistribution(String assessmentId){
        List<Distribution__c> distributions = DistributionService.fetchDistribution(assessmentId);
        return distributions;
    }
    @AuraEnabled
    public static void archiveDistribution(String distributionId){
        DistributionService.archiveDistribution(distributionId);
    }
    @AuraEnabled
    public static void deleteDistribution(String distributionId){
       DistributionService.deleteDistribution(distributionId);    
    }
    @AuraEnabled
    public static List<DistributionService.AssessableObjectWrapper> getAssessableObjectDetails(String sObjectApiName){
        return DistributionService.getAssessableObjectDetails(sObjectApiName);
    }
    @AuraEnabled
    public static DistributionService.DistributionsDetails getDistributionsWthFieldSet(String assessmentId, List<String> fieldSets, String sObjectName){
        return DistributionService.getDistributionsWthFieldSet(assessmentId, fieldSets, sObjectName);
    }
    @AuraEnabled
    public static void createDistributionWthPALink(Distribution__c distributionObj, Distribution_Group__c distributionGroupObj, Integer countOfPALinks){
        DistributionService.createDistributionWthPALink(distributionObj, distributionGroupObj, countOfPALinks);
    }
    @AuraEnabled 
    public static DistributionGroupService.TargetObjectsOperatorsClass fetchTargetObjectsWthOperators(){
        DistributionGroupService.TargetObjectsOperatorsClass targetObjects = DistributionGroupService.fetchTargetObjectsWthOperators();
        return targetObjects;
    }
    @AuraEnabled 
    public static DistributionGroupService.DistributionGroupClass fetchSelectedObjectGroup(String objectName){
        DistributionGroupService.DistributionGroupClass selectedObjectGroup = DistributionGroupService.fetchSelectedObjectGroup(objectName);
        return selectedObjectGroup;
    }
    @AuraEnabled 
    public static DistributionGroupService.DistributionCountClass fetchCriteriaWthCountOfRd(String groupId){
        DistributionGroupService.DistributionCountClass distRecordDetails = DistributionGroupService.queryDistRecord(groupId);
        return distRecordDetails;
    }
    @AuraEnabled 
    public static List<EmailTemplate> fetchEmailTemplates(){
        List<EmailTemplate> emailTemplates = EmailTemplateService.fetchEmailTemplates();
        return emailTemplates;
    }
    @AuraEnabled 
    public static DistributionGroupService.AvailableDistribtionGroupClass checkCriteriaMet(String sObjectName, String JSONStr, String groupName, String selGrpId){
        DistributionGroupService.AvailableDistribtionGroupClass distGroupStatus = DistributionGroupService.checkFilterIsAvailable(sObjectName, JSONStr, groupName, selGrpId);
        return distGroupStatus;
    }
    @AuraEnabled
    public static ExamUtilClass.LimitClass getDailyEmailLimit() {
        return ExAMUtilClass.getDailyEmailLimit();
    } 
}