src/objects/Assessment_Group__c.object
<CustomObject>
    <description>Stores the name and type of Assessment Group. This helps support things like the batch generation of Public Assessment Links.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Group</label>
    <nameField>
        <label>Assessment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment_Group_Junction__c.object
<CustomObject>
    <description>Where ExAM stores the grouping of Assessable Records. This helps support things like the batch generation of Public Assessment Links.</description>
    <fields>
        <fullName>Assessment_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Group</label>
        <referenceTo>Assessment_Group__c</referenceTo>
        <relationshipLabel>Assessment Group Junctions</relationshipLabel>
        <relationshipName>Assessment_Group_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessment Group Junctions</relationshipLabel>
        <relationshipName>Assessment_Group_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Group Junction</label>
    <nameField>
        <label>Assessment Group Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Group Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessment_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Group</label>
        <referenceTo>Assessment_Group__c</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_Configuration_Options_in_Viewer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this box enables the end user to configure the Standard Viewer for the purposes of this specific Assignment Manager. For example, adding and removing tabs.</inlineHelpText>
        <label>Show Configuration Options in Viewer</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewer_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enables you select a specific configuration of the Standard Viewer to be used for the specified Assessment Template. You can create Standard Viewer configurations that include or exclude specific tabs in the ExAM Configuration tab.</inlineHelpText>
        <label>Viewer Configuration</label>
        <referenceTo>Viewer_Custom_Configuration__c</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Assessment_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Viewer_Custom_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the standard viewer on an Assessment Template by Assessment Template basis. This configuration is done in the ExAM Configuration tab.</description>
    <label>Viewer Custom Configuration</label>
    <nameField>
        <label>Viewer Custom Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewer Custom Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAssignmentGroupController.cls
@isTest
public class TestAssignmentGroupController {

    static testMethod void method1() {
    
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Viewer_Custom_Configuration__c viewerRec = new Viewer_Custom_Configuration__c();
        insert viewerRec;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Viewer_Configuration__c = viewerRec.Id;
        assTemp.Template_name__c = 'testTemplate';
        insert assTemp;
        
        Section_Template__c secTemp = new Section_Template__c();
        secTemp.Questionnaire_Section__c = assTemp.Id;
        insert secTemp;
        
        Question_Template__c quesTemp = new Question_Template__c();
        quesTemp.Section_Question__c = secTemp.Id;
        insert quesTemp;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.investigationType__c = assTemp.Id;
        assManager.Facility_Name__c = acc.Id;
        assManager.Show_Configuration_Options_in_Viewer__c = True;
        insert assManager;
        
        Assessment_Group__c assGrpIns = new Assessment_Group__c();
        assGrpIns.Type__c = 'Account';
        assGrpIns.Name = 'ass group';
        insert assGrpIns;
        
        Assessment_Group_Junction__c assGrpJun = new Assessment_Group_Junction__c();
        assGrpJun.Facility_Name__c = acc.Id;
        assGrpJun.Assessment_Group__c = assGrpIns.Id;
        
        insert assGrpJun;
        
        Id assGrpJuncId = assGrpJun.Id;
        Map<String,String> objNameAndFieldNameMap = new Map<String,String>();
        objNameAndFieldNameMap.put('Account','Facility_Name__c');
        //String testObj = objNameAndFieldNameMap;
        
        ApexPages.currentPage().getParameters().put('idsVal','assGrpJuncId');
        ApexPages.currentPage().getParameters().put('totelRec','1');
        ApexPages.currentPage().getParameters().put('selectedObjectAPIName','Account');
        
        AssignmentGroupController  assGrp = new AssignmentGroupController();
        
        assGrp.selectedObj = 'Account';
        assGrp.assGroup.Name = 'Account one';
        assGrp.selectedRecords = 1;
        assGrp.totalRecords =1;
        assGrp.selectedGroup = 'Account One';
       
        assGrp.insertAssignmentManager();
        assGrp.saveSelectedRecords();
        assGrp.processSelected();
        assGrp.saveAssessmentGroup();
        assGrp.refreshFn();
        assGrp.changeObject();
    
        String recRes =  AssignmentGroupController.getRecords('Account one','all','Account','Account=ExAM__Facility_Name__c');
        AssignmentGroupController.getCreatedRecords('Account', 'Account one', 'Account=ExAM__Facility_Name__c');
        AssignmentGroupController.deleteAssessmentJunctionRecord(assGrpJuncId);

        List<Assessment_Group_Junction__c> deletedAGJList = new List<Assessment_Group_Junction__c>([SELECT Id FROM Assessment_Group_Junction__c WHERE Id = :assGrpJuncId LIMIT 1]);
        if (deletedAGJList.size() == 0) {
            system.assertEquals(deletedAGJList.size(), 0, 'Record was not deleted');
        }

        AssignmentGroupController.innerCls innerIns = new AssignmentGroupController.innerCls(acc);        
    }
    
    static testMethod void method2() {
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Viewer_Custom_Configuration__c viewerRec = new Viewer_Custom_Configuration__c();
        insert viewerRec;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Viewer_Configuration__c = viewerRec.Id;
        assTemp.Template_name__c = 'testTemplate';
        insert assTemp;
        
        Section_Template__c secTemp = new Section_Template__c();
        secTemp.Questionnaire_Section__c = assTemp.Id;
        insert secTemp;
        
        Question_Template__c quesTemp = new Question_Template__c();
        quesTemp.Section_Question__c = secTemp.Id;
        insert quesTemp;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.investigationType__c = assTemp.Id;
        assManager.Facility_Name__c = acc.Id;
        assManager.Show_Configuration_Options_in_Viewer__c = True;
        insert assManager;
        
        Assessment_Group__c assGrpIns = new Assessment_Group__c();
        assGrpIns.Name = 'Account one';
        assGrpIns.Type__c = 'Account';
        insert assGrpIns;
        
        Assessment_Group_Junction__c assGrpJun = new Assessment_Group_Junction__c();
        assGrpJun.Facility_Name__c = acc.Id;
        assGrpJun.Assessment_Group__c = assGrpIns.Id;
        
        insert assGrpJun;
        
        Id assGrpJuncId = assGrpJun.Id;
        Map<String,String> objNameAndFieldNameMap = new Map<String,String>();
        objNameAndFieldNameMap.put('Account','Facility_Name__c');
        //String testObj = '+objNameAndFieldNameMap+';
        
        ApexPages.currentPage().getParameters().put('idsVal', acc.Id);
        ApexPages.currentPage().getParameters().put('totelRec','1');
        
        AssignmentGroupController  assGrp = new AssignmentGroupController();
        
        assGrp.selectedObj = 'Account';
        assGrp.assGroup.Name = 'Account one';
        assGrp.selectedRecords = 1;
        assGrp.totalRecords =1;
        assGrp.selectedGroup = assGrpIns.Id;
        assGrp.selectedGroupId2 = assGrpIns.Id;
        
        assGrp.insertAssignmentManager();
        assGrp.processSelected();
        assGrp.saveSelectedRecords();

        List<ApexPages.Message> msgList = ApexPages.getMessages();
        if (msgList.size() > 0) {
            system.assertEquals(msgList[0].getSeverity(), ApexPages.Severity.CONFIRM);
            system.assertEquals(msgList[0].getDetail(), 'Record saved successfully');
        }

        List<Assessment_Group_Junction__c> insertedAGJList = new List<Assessment_Group_Junction__c>([SELECT ExAM__Assessment_Group__c, ExAM__Assessment_Group__r.ExAM__Type__c, ExAM__Facility_Name__c, ExAM__Facility_Name__r.Name, Id, Name FROM Assessment_Group_Junction__c LIMIT 1]); 
        if (insertedAGJList != null && insertedAGJList.size() > 0) {
            system.assertEquals(insertedAGJList[0].ExAM__Assessment_Group__r.ExAM__Type__c, 'Account');
            system.assertEquals(insertedAGJList[0].ExAM__Facility_Name__c, acc.Id);
            system.assertEquals(insertedAGJList[0].ExAM__Facility_Name__r.Name, 'Test');
        }

        assGrp.saveAssessmentGroup();
        assGrp.refreshFn();
        assGrp.changeObject();
    
        String recRes =  AssignmentGroupController.getRecords('Account one','all','Account','Account=ExAM__Facility_Name__c');
        AssignmentGroupController.getCreatedRecords('Account', 'Account one', 'Account=ExAM__Facility_Name__c');
        AssignmentGroupController.deleteAssessmentJunctionRecord(assGrpJuncId);
        
        AssignmentGroupController.innerCls innerIns = new AssignmentGroupController.innerCls(acc);
        
    }
    
    static testMethod void method3() {
    
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Assessment_Group__c assGrpIns = new Assessment_Group__c();
        assGrpIns.Name = 'Account one';
        assGrpIns.Type__c = 'Account';
        insert assGrpIns;
        
        Assessment_Group_Junction__c assGrpJun = new Assessment_Group_Junction__c();
        assGrpJun.Facility_Name__c = acc.Id;
        assGrpJun.Assessment_Group__c = assGrpIns.Id;
        insert assGrpJun;
        
        AssignmentGroupController.getRecords('Account','all',assGrpIns.Id,'Account=ExAM__Facility_Name__c');
        AssignmentGroupController.getRecords('Case','Case',assGrpIns.Id,'Account=ExAM__Facility_Name__c');
        AssignmentGroupController.getRecords('Account','Case',assGrpIns.Id,'Account=ExAM__Facility_Name__c');
        AssignmentGroupController.getRecords('Case','#',assGrpIns.Id,'Account=ExAM__Facility_Name__c');
        AssignmentGroupController.getRecords('Account','#',assGrpIns.Id,'Account=ExAM__Facility_Name__c');
        AssignmentGroupController.getRecords('User','User',assGrpIns.Id,'Account=ExAM__Facility_Name__c');
        
        AssignmentGroupController.getCreatedRecords('Account', assGrpIns.Id, 'Account=ExAM__Facility_Name__c');
        
        String blobCsv = '\r\n'+acc.Id+'\r\n';
        blob b = Blob.valueOf(blobCsv);
    
        blobCsv = EncodingUtil.base64Encode(b);
        ApexPages.currentPage().getParameters().put('attBlob',blobCsv);
        AssignmentGroupController assignmentGroup = new AssignmentGroupController();
        assignmentGroup.saveRecordwithUploadAssessment();
        
        
        Account acc1 = new Account(Name = 'Test 1');
        insert acc1;
        Account acc2 = new Account(Name = 'Test 12');
        insert acc2;
        blobCsv = '\r\n'+acc1.Id+'\r\n'+'\r\n'+acc.Id+'\r\n'+'\r\n'+acc2.Id+'\r\n';
        b = Blob.valueOf(blobCsv);
    
        blobCsv = EncodingUtil.base64Encode(b);
        ApexPages.currentPage().getParameters().put('attBlob',blobCsv);
        assignmentGroup = new AssignmentGroupController();
        assignmentGroup.saveRecordwithUploadAssessment();
        
        blobCsv = 'Id,Name\r\n'+acc1.Id+',Test1\r\n'+'\r\n'+acc.Id+',Test 2\r\n'+'\r\n'+acc2.Id+',Test 12\r';
        b = Blob.valueOf(blobCsv);
    
        blobCsv = EncodingUtil.base64Encode(b);
        ApexPages.currentPage().getParameters().put('attBlob',blobCsv);
        assignmentGroup = new AssignmentGroupController();
        assignmentGroup.saveRecordwithUploadAssessment();

        List<ApexPages.Message> msgList = ApexPages.getMessages();
        if (msgList.size() > 0) {
            system.assertEquals(msgList[0].getSeverity(), ApexPages.Severity.ERROR);
            system.assertEquals(msgList[0].getDetail(), 'File does not have data. Please upload a file with data or confirm if it is a valid csv file.');
        }
    }
}