src/objects/Assessment_Group__c.object
<CustomObject>
    <description>Stores the name and type of Assessment Group. This helps support things like the batch generation of Public Assessment Links.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Group</label>
    <nameField>
        <label>Assessment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment_Group_Junction__c.object
<CustomObject>
    <description>Where ExAM stores the grouping of Assessable Records. This helps support things like the batch generation of Public Assessment Links.</description>
    <fields>
        <fullName>Assessment_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Group</label>
        <referenceTo>Assessment_Group__c</referenceTo>
        <relationshipLabel>Assessment Group Junctions</relationshipLabel>
        <relationshipName>Assessment_Group_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessment Group Junctions</relationshipLabel>
        <relationshipName>Assessment_Group_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Group Junction</label>
    <nameField>
        <label>Assessment Group Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Group Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewer_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enables you select a specific configuration of the Standard Viewer to be used for the specified Assessment Template. You can create Standard Viewer configurations that include or exclude specific tabs in the ExAM Configuration tab.</inlineHelpText>
        <label>Viewer Configuration</label>
        <referenceTo>Viewer_Custom_Configuration__c</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Assessment_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Viewer_Custom_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the standard viewer on an Assessment Template by Assessment Template basis. This configuration is done in the ExAM Configuration tab.</description>
    <label>Viewer Custom Configuration</label>
    <nameField>
        <label>Viewer Custom Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewer Custom Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAssignmentManagerGeneratorController.cls
@isTest
private class TestAssignmentManagerGeneratorController {

    @isTest static void AMgenerator1() {
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        Account acc2 = new Account();
        acc2.Name = 'Account Label1';
        insert acc2;
        
        Viewer_Custom_Configuration__c viewerRec = new Viewer_Custom_Configuration__c();
        insert viewerRec;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Viewer_Configuration__c = viewerRec.Id;
        assTemp.Template_name__c = 'testTemplate';
        insert assTemp;
        
        Section_Template__c secTemp = new Section_Template__c();
        secTemp.Questionnaire_Section__c = assTemp.Id;
        insert secTemp;
        
        Question_Template__c quesTemp = new Question_Template__c();
        quesTemp.Section_Question__c = secTemp.Id;
        insert quesTemp;
        
        Assessment_Group__c assGrpIns = new Assessment_Group__c();
        assGrpIns.Name = 'Account one';
        assGrpIns.Type__c = 'Account';
        insert assGrpIns;
        
        Assessment_Group_Junction__c assGrpJun = new Assessment_Group_Junction__c();
        assGrpJun.Facility_Name__c = acc.Id;
        assGrpJun.Assessment_Group__c = assGrpIns.Id;
        
        insert assGrpJun;
        
        test.startTest();
        
            AssignmentManagerGeneratorController amg = new AssignmentManagerGeneratorController();
            String getAssGrp = AssignmentManagerGeneratorController.getAssessmentGroups('Account');
            String saveAssManList = AssignmentManagerGeneratorController.saveAssignmentmanagerList('ExAM__Facility_Name__c', 'ExAM__Facility_Name__c', assGrpIns.Id, assTemp.Id, '', 'Account', 'Account Label','');
            String saveAssManList2 = AssignmentManagerGeneratorController.saveAssignmentmanagerList('ExAM__Facility_Name__c', 'ExAM__Facility_Name__c', '', assTemp.Id, '2', 'Account', 'Account Label','');
            String saveAssManList3 = AssignmentManagerGeneratorController.saveAssignmentmanagerList('ExAM__Facility_Name__c', 'ExAM__Facility_Name__c', '', assTemp.Id, '2', 'Account', 'Account Label',acc2.Id);

            AssignmentManagerGeneratorController.AssessableRecordClass recordClass;            
            List<AssignmentManagerGeneratorController.AssessableRecordClass> recordClassList;            

            String accStr1 = AssignmentManagerGeneratorController.queryAssessableRecords('Test','Account');
            Contact con = new Contact(LastName = 'Contact1');
            insert con;

            recordClass = new AssignmentManagerGeneratorController.AssessableRecordClass();
            recordClass.RecordName = con.LastName;
            recordClass.RecordId = con.Id;
            recordClassList = new List<AssignmentManagerGeneratorController.AssessableRecordClass>();
            recordClassList.add( recordClass );
            String conStr1 = AssignmentManagerGeneratorController.queryAssessableRecords('Contact1','Contact');
            system.assertEquals(conStr1, Json.serialize(recordClassList));

            Case case1 = new Case();
            insert case1;     
            List<Case> caseQuery = [SELECT Id, CaseNumber FROM Case WHERE Id =:case1.Id];   

            recordClass = new AssignmentManagerGeneratorController.AssessableRecordClass();
            recordClass.RecordName = caseQuery[0].CaseNumber;
            recordClass.RecordId = caseQuery[0].Id;
            recordClassList = new List<AssignmentManagerGeneratorController.AssessableRecordClass>();
            recordClassList.add( recordClass );
            String caseStr1 = AssignmentManagerGeneratorController.queryAssessableRecords(''+caseQuery[0].CaseNumber,'Case');
            system.assertEquals(caseStr1, Json.serialize(recordClassList));
            
            Lead lead1 = new Lead(LastName = 'lead1', Company = 'company1');
            insert lead1;        

            recordClass = new AssignmentManagerGeneratorController.AssessableRecordClass();
            recordClass.RecordName = lead1.LastName;
            recordClass.RecordId = lead1.Id;
            recordClassList = new List<AssignmentManagerGeneratorController.AssessableRecordClass>();
            recordClassList.add( recordClass );

            String leadStr1 = AssignmentManagerGeneratorController.queryAssessableRecords('lead1','Lead');
            system.assertEquals(leadStr1, Json.serialize(recordClassList));
        test.stopTest();
    }
    
    @isTest static void AMgenerator2() {
        
        test.startTest();
            AssignmentManagerGeneratorController amg = new AssignmentManagerGeneratorController();
        test.stopTest();
        system.assertEquals(amg.assessmentTemplateJSON, '[]');
    }
}