src/objects/Assessable_Fields_Mapping__c.object
<CustomObject>
    <description>Where ExAM stores information about how to map Answer data to Assessable Object Fields.</description>
    <fields>
        <fullName>Question_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Template</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Assessable Fields Mappings</relationshipLabel>
        <relationshipName>Assessable_Fields_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessable Fields Mapping</label>
    <nameField>
        <displayFormat>AFM-{0000}</displayFormat>
        <label>Assessable Fields Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessable Fields Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Is_Field_Mapping__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Field Mapping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Overall_Status_on_Submit__c</fullName>
        <label>Overall Status on Submit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessor_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Assigned Resource is typically the Salesforce user assigned with gathering the data or ensuring the gathering of the data.</inlineHelpText>
        <label>Assigned Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <inlineHelpText>This field is updated with the most recent time the Assignment Manager was submitted.</inlineHelpText>
        <label>Date/Time Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Max_Score__c</fullName>
        <inlineHelpText>The total score possible given the possible point values of the questions answered and the total points scored as determined by the Answer Option selected. Scoring is configured in the ExAM Console on a question by question basis.</inlineHelpText>
        <label>Max Score</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <inlineHelpText>If scoring has been implemented for this Assessment the total score achieved in the Assignment will be recorded here.</inlineHelpText>
        <label>Total Score</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Single_Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to next question in decision tree</description>
        <inlineHelpText>Lookup to next question in decision tree</inlineHelpText>
        <label>Single Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Score__c</fullName>
        <description>For responses which are negative i.e like N/A or for any response which u do not want to score put negative value and this question would not be counted in total question score and max score</description>
        <formula>if( Weight_Response__c&lt;0,0,Question_Template__r.Weight_Of_Question__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total number of points that the Answer record could have scored.</inlineHelpText>
        <label>Max Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <description>For responses which are negative i.e like N/A or for any response which u do not want to put negative and this question would not be counted in total question score and max score.this is user score or issue score</description>
        <formula>if( Weight_Response__c&lt;0,0,((Weight_Response__c/100)* Question_Template__r.Weight_Of_Question__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total number of points achieved by a specific Answer record.</inlineHelpText>
        <label>Total Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight_Response__c</fullName>
        <description>This is score that user gets .It is in percentages from 0-100%.For N/A the score as 0 and dont add it to numerator or denominator</description>
        <inlineHelpText>The percentage of the total possible score possible for the answer that was achieved by the Answer.</inlineHelpText>
        <label>Raw Response Score(%)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssignmentManagerTriggerHandler.cls
public class AssignmentManagerTriggerHandler {

    private Boolean m_isExecuting = false;
    private Integer BatchSize = 0;

    private static examConfigClass examConfig { //assingment manager submit status
        get {
            if (examConfig == null) {
                examConfig = new examConfigClass();
                examConfig.AMSubmitStatus = 'Completed';
                examConfig.isFieldMapping = false;
                try{

                    List<ExAM_Configuration__c> examConfigList = [
                        SELECT Id, Is_Field_Mapping__c, Overall_Status_on_Submit__c
                        FROM   ExAM_Configuration__c
                        WHERE  Name = 'Configuration' ORDER BY CreatedDate DESC LIMIT 1
                    ];                 
                    if (examConfigList != null && examConfigList.size() > 0) {
                        if (examConfigList[0].Overall_Status_on_Submit__c != null 
                            && examConfigList[0].Overall_Status_on_Submit__c != '') {
                                examConfig.AMSubmitStatus = examConfigList[0].Overall_Status_on_Submit__c;
                            }
                        if (examConfigList[0].Is_Field_Mapping__c) {
                            examConfig.isFieldMapping = examConfigList[0].Is_Field_Mapping__c;
                        }
                    }
                }catch(Exception e){
                    throw e;
                } 
            }
            return examConfig;
        }
        set;
    }

    public class examConfigClass {
        public string AMSubmitStatus;
        public Boolean isFieldMapping;
    }

    public AssignmentManagerTriggerHandler(boolean isExecuting, integer size){
        m_isExecuting = isExecuting;
        BatchSize = size;
    }
    
    //Before insert assignment Manager process 
    public void onBeforeInsert(List<IssueRequest_Life_Cycle__c> newAMList) {
        
        for (IssueRequest_Life_Cycle__c am :newAMList) {
            if (am.Assessor_Resource__c!= null) {
                am.OwnerId = am.Assessor_Resource__c;
            }            
        }
        protectMorethenOneCustomLookupValuePopulate(newAMList);
    }
    
    //After insert assignment Manager process
    public void onAfterInsert(List<IssueRequest_Life_Cycle__c> newAMList) {
        executeFieldMappingOnAMSave(newAMList, new Map<Id, IssueRequest_Life_Cycle__c>(), true);
    }

    //Before update assignment Manager process
    public void onBeforeUpdate( List<IssueRequest_Life_Cycle__c> oldAMList, 
                                List<IssueRequest_Life_Cycle__c> newAMList,
                                Map<ID, IssueRequest_Life_Cycle__c> newAssignmentManagerMap) {
        Map<ID, IssueRequest_Life_Cycle__c> scoreUpdateAssignmentManagerMap = new Map<ID, IssueRequest_Life_Cycle__c> ();
        for (IssueRequest_Life_Cycle__c oldAM :oldAMList) {
            if (newAssignmentManagerMap.get(oldAM.Id).Assessor_Resource__c != null 
                    && newAssignmentManagerMap.get(oldAM.Id).Assessor_Resource__c != oldAM.Assessor_Resource__c) {
                newAssignmentManagerMap.get(oldAM.Id).OwnerId = newAssignmentManagerMap.get(oldAM.Id).Assessor_Resource__c;
            } 
            if (newAssignmentManagerMap.get(oldAM.Id).Status__c == examConfig.AMSubmitStatus && oldAM.Status__c != examConfig.AMSubmitStatus ) {
                scoreUpdateAssignmentManagerMap.put(oldAM.Id, newAssignmentManagerMap.get(oldAM.Id));
                if( newAssignmentManagerMap.get(oldAM.Id).Date_Completed__c == null ){
                    newAssignmentManagerMap.get(oldAM.Id).Date_Completed__c = System.now();
                }
            }     
        }
        protectMorethenOneCustomLookupValuePopulate(newAMList);    
        if (scoreUpdateAssignmentManagerMap.size() > 0) {
            calculateScore(scoreUpdateAssignmentManagerMap);
        }    
    }
    
    public void onAfterUpdate(List<IssueRequest_Life_Cycle__c> oldAMList, 
                                List<IssueRequest_Life_Cycle__c> newAMList,
                                Map<ID, IssueRequest_Life_Cycle__c> oldAMMap,
                                Map<ID, IssueRequest_Life_Cycle__c> newAMMap) {
    
        //update assissable
        updateAssessableRecords(oldAMList, newAMList, newAMMap); 
        createCase(oldAMList, newAMMap);       
        generateCaseOrLead(oldAMList, newAMMap);
        executeFieldMappingOnAMSave(newAMList, oldAMMap, false);
    }
    
    public void protectMorethenOneCustomLookupValuePopulate(List<IssueRequest_Life_Cycle__c> newAMList) {
    
        Map<string, string> fieldAPIFieldLabelMap = new Map<string, string>();
        
        ExAMUtilClass.AssessableObjectDetails objectDetail = ExAMUtilClass.getAssessableObjectDetails('ExAM__IssueRequest_Life_Cycle__c');
        fieldAPIFieldLabelMap = objectDetail.assessableFieldInAMMap;

        for (IssueRequest_Life_Cycle__c assMang : newAMList) {
            Integer AMValueFieldcount = 0;
            List<string> fieldsLabel = new List<string>();
            for (string fieldApiName : fieldAPIFieldLabelMap.keySet()) {
                if (assMang.get(fieldApiName) != NULL) {
                    AMValueFieldcount++;
                    fieldsLabel.add(fieldAPIFieldLabelMap.get(fieldApiName));
                }                          
            }
            if ( AMValueFieldcount > 1 ) {
                assMang.addError('Can\'t do more than one inspection at a time. Inspection created for '+string.join(fieldsLabel,', ')+' fields.');
            } 
        }        
    }
    public static void calculateScore(Map<ID, IssueRequest_Life_Cycle__c> scoreAssignmentManagerMap) {
        
        Map<Id, Decimal> amIdwithTotalScoreMap = new Map<Id, Decimal>();
        Map<Id, Decimal> amIdwithMaxScoreMap = new Map<Id, Decimal>();
        
        try{
            for(Questionnaire_Response__c ans : [SELECT ID, Weight_Response__c, Total_Score__c, Max_Score__c, Issue_Request__c, 
                                                        Question_Template__c, Question_Template__r.Question_Type__c 
                                                    FROM Questionnaire_Response__c 
                                                    WHERE Issue_Request__c IN:scoreAssignmentManagerMap.keySet()
                                                    AND Total_Score__c != null 
                                                    AND Max_Score__c != null]) {
                                                    /* Total score and Max score in AM will be set to 0 when there is no answer record with total score/ Max score > 0. 
                                                       This is done to support score based redirection logic in Public Assessment*/
                                                    //AND Question_Template__r.Question_Type__c IN ('RadioPicklist','Dropdown Picklist','Button','Image','List','Horizontal Radiopicklist','Likert'
                
                if (!amIdwithTotalScoreMap.containsKey(ans.Issue_Request__c)) {
                    amIdwithTotalScoreMap.put(ans.Issue_Request__c, 0.00);
                }
                if (!amIdwithMaxScoreMap.containsKey(ans.Issue_Request__c)) {
                    amIdwithMaxScoreMap.put(ans.Issue_Request__c, 0.00);
                } 
             
                amIdwithTotalScoreMap.put(ans.Issue_Request__c, amIdwithTotalScoreMap.get(ans.Issue_Request__c) + ans.Total_Score__c);
                amIdwithMaxScoreMap.put(ans.Issue_Request__c, amIdwithMaxScoreMap.get(ans.Issue_Request__c) + ans.Max_Score__c);
            }
            for (Id amId : amIdwithTotalScoreMap.KeySet()) {
                if (amIdwithMaxScoreMap != null && amIdwithMaxScoreMap.containsKey(amId)) { //amIdwithTotalScoreMap.get(amId) != 0  && amIdwithMaxScoreMap.get(amId) != 0
                    scoreAssignmentManagerMap.get(amId).Total_Score__c = amIdwithTotalScoreMap.get(amId);
                    scoreAssignmentManagerMap.get(amId).Max_Score__c = amIdwithMaxScoreMap.get(amId);
                }
            }
        }catch(Exception e){
            throw e;
        }
    }
    
    public void updateAssessableRecords(List<IssueRequest_Life_Cycle__c> oldAMList, List<IssueRequest_Life_Cycle__c> newAMList, Map<ID, IssueRequest_Life_Cycle__c> newAMMap) {

        if (examConfig.isFieldMapping) {

            List<IssueRequest_Life_Cycle__c> filteredManagers = new List<IssueRequest_Life_Cycle__c>();

            ExAMUtilClass.AssessableObjectDetails objectDetail = ExAMUtilClass.getAssessableObjectDetails('ExAM__IssueRequest_Life_Cycle__c');
            Map<string, string> fieldsMap = objectDetail.assessableObjectAPIMap;
                
            for (IssueRequest_Life_Cycle__c oldAM : oldAMList) {
                if (newAMMap.get(oldAM.Id).Status__c == examConfig.AMSubmitStatus && newAMMap.get(oldAM.Id).InvestigationType__c != null) {
                    for (string assessablefld : fieldsMap.keySet()) {
                        if (newAMMap.get(oldAM.Id).get(assessablefld) != null 
                            && ((newAMMap.get(oldAM.Id).get(assessablefld) != oldAM.get(assessablefld))
                                || (newAMMap.get(oldAM.Id).Status__c != oldAM.Status__c))
                        ) {

                            filteredManagers.add( oldAM );           
                            break;
                        } 
                    }
                }
            }

            if (filteredManagers != null && filteredManagers.size() > 0) {
                ExAMUtilClass.updateAssessableObjectUsingFieldMapping(filteredManagers, false);          
            }
        }
    }

    public void createCase(List<IssueRequest_Life_Cycle__c> oldAMList, Map<ID, IssueRequest_Life_Cycle__c> newAMMap) {
        
        try {

            Set<Id> AMIdSet = new Set<Id>();
            List<Case> caseList = new List<Case>();
            string watchlisttext = '';
        
            for(IssueRequest_Life_Cycle__c am : oldAMList) {
                if(am.Status__c != newAMMap.get(am.Id).Status__c) {
                    if(newAMMap.get(am.Id).Status__c == examConfig.AMSubmitStatus) {
                        AMIdSet.add(am.Id);
                    }                 
                }
            }
            for(Questionnaire_Response__c ans : [SELECT Response__c, Issue_Request__c, Issue_Request__r.Name, 
                                                 Question_Template__r.Section_Question__r.Questionnaire_Section__r.Watchlist_Of_Words__c 
                                                 FROM Questionnaire_Response__c 
                                                 WHERE Issue_Request__c in :AMIdSet]) {
                List<string> checkStringList = new List<string>();
                if(ans.Response__c != NULL && ans.Question_Template__r.Section_Question__r.Questionnaire_Section__r.Watchlist_Of_Words__c != NULL) {
                
                    checkStringList = ans.Question_Template__r.Section_Question__r.Questionnaire_Section__r.Watchlist_Of_Words__c.split('~');
                    watchlisttext = '';
                
                    if(checkStringList.size() > 0) {
                        for(string st : checkStringList) {
                            if(ans.Response__c.indexOf(st) != -1) {
                                watchlisttext += st + ', ';
                            }
                        }                    
                        if(watchlisttext != '' && watchlisttext.lastIndexOf(',') != -1) {
                            watchlisttext = watchlisttext.substring(0, watchlisttext.lastIndexOf(','));
                            string sub = 'Watchlist - ' + watchlisttext + ' - '+ ans.Issue_Request__r.Name;
                            case cs = new Case(Description = ans.Response__c, Subject = sub);
                            caseList.add(cs);
                        }
                    }
                }
            }
            if(caseList != null && caseList.size() > 0) {
                insert caseList;
            }
        }       
        catch(Exception exp) {   
            throw exp;   
        }
    }
   
    public void generateCaseOrLead(List<IssueRequest_Life_Cycle__c> oldAMList, Map<ID, IssueRequest_Life_Cycle__c> newAMMap) {
       
        List<SObject> sObjList = new List<SObject>();       
        Set<Id> amIdSet = new Set<Id>();        
        Set<Id> templateIdSet = new Set<Id>();      
        Map<Id, string> templateIdEntityNameMap = new Map<Id, string>();        
        Map<string, Id> assessableFieldNameQtnTemplateIdMap = new Map<string, Id>();        
        Map<Id, string> qtnIdAnswerResponseMap = new Map<Id, string>();     
        Map<string, Schema.SObjectType> sObjectsMap = Schema.getGlobalDescribe();       
        try {       
            for(IssueRequest_Life_Cycle__c oldAM : oldAMList) {     
                IssueRequest_Life_Cycle__c newAM = newAMMap.get(oldAM.Id);      
                if((oldAM.Status__c != newAM.Status__c)     
                    && (examConfig.AMSubmitStatus == newAM.Status__c)       
                    && (newAM.InvestigationType__c != null)     
                ) {     
                    amIdSet.add( newAM.Id );        
                    templateIdSet.add( newAM.InvestigationType__c );        
                }       
            }   
            if (!templateIdSet.isEmpty()) {  
                for (Main_questionaire__c template : [SELECT Generate_Case_Or_Lead__c, Id, Name     
                                                      FROM   Main_questionaire__c       
                                                      WHERE  Id IN :templateIdSet AND Generate_Case_Or_Lead__c != null]) {      
                        templateIdEntityNameMap.put(template.Id, template.Generate_Case_Or_Lead__c);        
                }       
            }       
            if (templateIdEntityNameMap != null && templateIdEntityNameMap.size() > 0) {  

                for (Assessable_Fields_Mapping__c afm : [SELECT Assessable_Object_API__c, Assessable_Object_Field_API__c,       
                                                                Assessment_Template__c, Id, Is_Case_Response__c,        
                                                                Name, Question_Template__c      
                                                         FROM   Assessable_Fields_Mapping__c        
                                                         WHERE  Assessment_Template__c IN :templateIdEntityNameMap.KeySet()     
                                                                AND Assessable_Object_API__c IN :templateIdEntityNameMap.values()       
                                                                AND Is_Case_Response__c = true      
                                                                AND Assessable_Object_Field_API__c != null      
                                                                AND Question_Template__c != null]) {        
                        assessableFieldNameQtnTemplateIdMap.put(afm.Assessable_Object_Field_API__c, afm.Question_Template__c);      
                }  

                for (Questionnaire_Response__c ans : [SELECT CreatedDate, Issue_Request__c, Question_Template__c,       
                                                             Question_Template__r.Section_Question__c,      
                                                             Question_Template__r.Section_Question__r.Questionnaire_Section__c,     
                                                             Response__c        
                                                      FROM   Questionnaire_Response__c      
                                                      WHERE  Issue_Request__c IN :amIdSet       
                                                             AND Question_Template__r.Section_Question__r.Questionnaire_Section__c IN :templateIdEntityNameMap.KeySet() ORDER BY CreatedDate DESC]) {       
                        if (!qtnIdAnswerResponseMap.containsKey(ans.Question_Template__c) ) {       
                            qtnIdAnswerResponseMap.put(ans.Question_Template__c, ans.Response__c);      
                        }       
                }       
                string entity = '';
                List<string> fieldsListEntity = new List<string>();
                for (string templateId : templateIdEntityNameMap.keySet()) {        
                    entity = templateIdEntityNameMap.get(templateId);        
                    if ( (string.isNotBlank(entity)) && (sObjectsMap.containsKey(entity) && sObjectsMap.get(entity) != null) ) {        
                        Map<string, Schema.SObjectField> sObjFieldDescribeMap = sObjectsMap.get(entity).getDescribe().fields.getMap();      
                        if (assessableFieldNameQtnTemplateIdMap != null && assessableFieldNameQtnTemplateIdMap.size() > 0) {        
                            sObject sObj = sObjectsMap.get(entity).newSObject() ;       
                            for (string assessableObjectField : assessableFieldNameQtnTemplateIdMap.keySet()) {     
                                if (sObjFieldDescribeMap.containsKey(assessableObjectField) && sObjFieldDescribeMap.get(assessableObjectField) != null) {       
                                    Id qtnTemplateId = assessableFieldNameQtnTemplateIdMap.get(assessableObjectField);      
                                    if (qtnIdAnswerResponseMap.containsKey(qtnTemplateId) && qtnIdAnswerResponseMap.get(qtnTemplateId) != null) {       
                                        string ansRes = qtnIdAnswerResponseMap.get(qtnTemplateId);        
                                        fieldsListEntity.add(assessableObjectField); 
                                        Schema.DisplayType fieldType = sObjFieldDescribeMap.get(assessableObjectField).getDescribe().getType();
                                        if (fieldType == Schema.DisplayType.DATE) {
                                            string[] dateStr = (ansRes).split('/');
                                            Date response = date.newinstance( Integer.valueOf(dateStr[2]), Integer.valueOf(dateStr[1]), Integer.valueOf(dateStr[0]) );
                                            sObj.put(assessableObjectField, response);                                            
                                        } else if (fieldType == Schema.DisplayType.DATETIME) {
                                            string[] dateStr = (ansRes).split('/');
                                            Datetime response = dateTime.newinstance( Integer.valueOf(dateStr[2]), Integer.valueOf(dateStr[1]), Integer.valueOf(dateStr[0]) );
                                            sObj.put(assessableObjectField, response);
                                        } else if (fieldType == Schema.DisplayType.DOUBLE) {
                                            sObj.put(assessableObjectField, Decimal.valueOf(ansRes));
                                        } else if (fieldType == Schema.DisplayType.INTEGER) {
                                            sObj.put(assessableObjectField, Integer.valueOf(ansRes));
                                        } else {
                                            sObj.put(assessableObjectField, ansRes);
                                        } 
                                    }       
                                }       
                            }       
                            sObjList.add( sObj );       
                        }       
                    }       
                }
                if ((sObjList != null && sObjList.size() > 0)
                    && (string.isNotBlank(entity))
                    && (sObjectsMap.containsKey(entity) && sObjectsMap.get(entity) != null)
                ) {
                    insert sObjList;
                }       
            }       
        }       
        catch(Exception exp) {   
            throw exp;   
        }       
    }

    public static void executeFieldMappingOnAMSave(List<IssueRequest_Life_Cycle__c> newAMs, Map<ID, IssueRequest_Life_Cycle__c> oldAMMap, Boolean isCreateAM) {

        List<IssueRequest_Life_Cycle__c> contextAMs = new List<IssueRequest_Life_Cycle__c>();
        List<IssueRequest_Life_Cycle__c> filteredManagers = new List<IssueRequest_Life_Cycle__c>();
        Set<Id> templateIdSet = new Set<Id>();

        //Find which Reference field has value and prepare a map of Assignment Manager Id with Assessable Object Id{'a0H' => '001'}
        ExAMUtilClass.AssessableObjectInAMClass assessableObjectDetail = ExAMUtilClass.getAssessableObjectDetailsFromAM(newAMs);
        if (assessableObjectDetail != null) {

            Map<Id, Id> fieldsMap = assessableObjectDetail.managerIdWithAssessableObjectIdMap;                                    

            for (IssueRequest_Life_Cycle__c newAM : newAMs) {

                if (isCreateAM && newAM.InvestigationType__c != null
                    && (fieldsMap.containsKey(newAM.Id) && fieldsMap.get(newAM.Id) != null)
                ) {

                    templateIdSet.add( newAM.InvestigationType__c );
                    contextAMs.add( newAM );
                }
                else if (!isCreateAM) {

                    for (Schema.SObjectField amField : ExAMUtilClass.getSObjectFieldsMap('ExAM__IssueRequest_Life_Cycle__c').Values()) {

                        string amFieldAPI = amField.getDescribe().getName();
                        if (newAM.InvestigationType__c != null
                            && (fieldsMap.containsKey(newAM.Id) && fieldsMap.get(newAM.Id) != null)
                            && (oldAMMap.get(newAM.Id).get(amFieldAPI) != newAM.get(amFieldAPI))
                        ) {
    
                            templateIdSet.add( newAM.InvestigationType__c );
                            contextAMs.add( newAM );
                            break;
                        }
                    }
                }
            }
            if (contextAMs != null && contextAMs.size() > 0) {

                Map<Id, Main_questionaire__c> templateMap = new Map<Id, Main_questionaire__c>([SELECT Id, Execute_Field_Mapping_On_AM__c FROM Main_questionaire__c WHERE Id IN :templateIdSet AND Execute_Field_Mapping_On_AM__c = true]);

                for (IssueRequest_Life_Cycle__c newAM : contextAMs) {
                    if (templateMap.containsKey(newAM.InvestigationType__c) && templateMap.get(newAM.InvestigationType__c) != null ) {
                        filteredManagers.add( newAM );
                    }
                }
                if (filteredManagers != null && filteredManagers.size() > 0) {
                    ExAMUtilClass.updateAssessableObjectUsingFieldMapping(filteredManagers, true);
                }
            }
        }
    }
}