src/objects/Assessment_Event__c.object
<CustomObject>
    <description>Where ExAM stores data about Assessment Events including Date, Start and Finish Times.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Assessment Event</label>
    <nameField>
        <label>Assessment Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment_Group__c.object
<CustomObject>
    <description>Stores the name and type of Assessment Group. This helps support things like the batch generation of Public Assessment Links.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Group</label>
    <nameField>
        <label>Assessment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessment_Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Event</label>
        <referenceTo>Assessment_Event__c</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Group</label>
        <referenceTo>Assessment_Group__c</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Map_Pin_Color_Configuration__c.object
<CustomObject>
    <description>Maps pin color on the basis of fields selected as part of Map Builder Configuration.</description>
    <fields>
        <fullName>Assessible_Object__c</fullName>
        <label>Assessible Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Map Pin Color Configuration</label>
    <nameField>
        <label>Map Pin Color Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Map Pin Color Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAssessmentMapBuilderController.cls
@isTest
public class TestAssessmentMapBuilderController {
    static testMethod void method(){
        Assessment_Event__c ae = new Assessment_Event__c();
        ae.Description__c = 'test ae';
        ae.Name = 'test ae';
        insert ae;
        Assessment_Group__c ag = new Assessment_Group__c();
        ag.Name = 'test assessment group';
        ag.Type__c = 'Account';
        insert ag;
        IssueRequest_Life_Cycle__c[] am = new IssueRequest_Life_Cycle__c[]{
            new IssueRequest_Life_Cycle__c(Assessment_Group__c = ag.Id,
                                          Assessment_Event__c = ae.Id
                                          )  
        }; 
        insert am;
        Map_Pin_Color_Configuration__c mpcc = new Map_Pin_Color_Configuration__c();
        mpcc.Assessible_Object__c = 'Account';
        insert mpcc;
        AssessmentMapBuilderController ambc = new AssessmentMapBuilderController();
        ambc.assessmentGroup = ag.Id;
        
        //ambc.assessmentGroup = ag.Id;
        ambc.assessableObjectChanged();
        //ambc.assessmentGroup = ag.Id;
        ambc.assessmentGroupChanged();
        ApexPages.currentPage().getHeaders().put('USER-AGENT','USER-AGENT iphone');
        ambc.getshowhead();
        ambc.submitmap();
        ambc.getAMPriority();
        ambc.getMappingGroup();
        ambc.getAMStatus();
        ambc.getAMAssessmentCompletion();
        ambc.getAMAssessmentType();
        
        AssessmentMapBuilderController ambc1 = new AssessmentMapBuilderController();
        ambc1.assessmentGroup = null;
        new AssessmentMapBuilderController();
        ambc.assessmentGroup = 'not none';
        ambc.submitmap();
        List<Map_Pin_Color_Configuration__c> mpcclist = [SELECT ID FROM Map_Pin_Color_Configuration__c];
        delete mpcclist;
        new AssessmentMapBuilderController();
        ambc1.ColorBy = 'test';

        AssessmentMapBuilderController ambc2 = new AssessmentMapBuilderController();
        ambc2.submitmap();
        List<ApexPages.Message> msgs = ApexPages.getMessages();
        system.assertEquals(msgs[0].getDetail(), 'Please select a Assessment Group');
    }
}