src/objects/Assessment_Group__c.object
<CustomObject>
    <description>Stores the name and type of Assessment Group. This helps support things like the batch generation of Public Assessment Links.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Group</label>
    <nameField>
        <label>Assessment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assessment_Group_Junction__c.object
<CustomObject>
    <description>Where ExAM stores the grouping of Assessable Records. This helps support things like the batch generation of Public Assessment Links.</description>
    <fields>
        <fullName>Assessment_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Group</label>
        <referenceTo>Assessment_Group__c</referenceTo>
        <relationshipLabel>Assessment Group Junctions</relationshipLabel>
        <relationshipName>Assessment_Group_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessment Group Junctions</relationshipLabel>
        <relationshipName>Assessment_Group_Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Group Junction</label>
    <nameField>
        <label>Assessment Group Junction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Group Junctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessment_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Group</label>
        <referenceTo>Assessment_Group__c</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewer_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enables you select a specific configuration of the Standard Viewer to be used for the specified Assessment Template. You can create Standard Viewer configurations that include or exclude specific tabs in the ExAM Configuration tab.</inlineHelpText>
        <label>Viewer Configuration</label>
        <referenceTo>Viewer_Custom_Configuration__c</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Assessment_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Viewer_Custom_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the standard viewer on an Assessment Template by Assessment Template basis. This configuration is done in the ExAM Configuration tab.</description>
    <label>Viewer Custom Configuration</label>
    <nameField>
        <label>Viewer Custom Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewer Custom Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAssignmentManagerGenerator_Batch.cls
@isTest 
private class TestAssignmentManagerGenerator_Batch {
    @testSetup
    public static void testSetUp() {
    
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Viewer_Custom_Configuration__c viewerRec = new Viewer_Custom_Configuration__c();
        insert viewerRec;
        
        List<Main_questionaire__c> assTemp = new List<Main_questionaire__c> {
            new Main_questionaire__c(Viewer_Configuration__c =viewerRec.Id,Template_name__c= 'testTemplate1'),
            new Main_questionaire__c(Viewer_Configuration__c =viewerRec.Id,Template_name__c= 'testTemplate2'),
            new Main_questionaire__c(Viewer_Configuration__c =viewerRec.Id,Template_name__c= 'testTemplate3')
        };
        insert assTemp;
        
        List<Section_Template__c> secTemp = new List<Section_Template__c> {
            new Section_Template__c(Questionnaire_Section__c = assTemp[0].Id),
            new Section_Template__c(Questionnaire_Section__c = assTemp[1].Id),
            new Section_Template__c(Questionnaire_Section__c = assTemp[2].Id)
        };
        insert secTemp;
        
        List<Question_Template__c> quesTemp = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c = secTemp[0].Id)
        };
        insert quesTemp;
        
        Assessment_Group__c assGrpIns = new Assessment_Group__c();
        assGrpIns.Name = 'Account one';
        assGrpIns.Type__c = 'Account';
        insert assGrpIns;
        
        Assessment_Group_Junction__c assGrpJun = new Assessment_Group_Junction__c();
        assGrpJun.Facility_Name__c = acc.Id;
        assGrpJun.Assessment_Group__c = assGrpIns.Id;
        insert assGrpJun;
        
    }
            
    public static testMethod void testAmGeneratorWithAcc() {
    
        List<Main_questionaire__c> assTemp = [SELECT Id FROM Main_questionaire__c];
        List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c> {
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id)
        };
        System.debug('::::::amList.size():::::::::'+amList.size());
        
        Test.StartTest();
            AssignmentManagerGenerator_Batch AmGeneratorBatch = new AssignmentManagerGenerator_Batch();
            AmGeneratorBatch.assignmentManagerList = amList;
            AmGeneratorBatch.totalNoOfRecords = 15;
            AmGeneratorBatch.assessbleObjAPI = 'Account';
            AmGeneratorBatch.selectedobjectLabel = 'Account';
            AmGeneratorBatch.AMApi = 'Facility_Name__c';
            Database.executeBatch(AmGeneratorBatch,2000);
        Test.StopTest(); 
        
        List<IssueRequest_Life_Cycle__c> assManagerList = new List<IssueRequest_Life_Cycle__c>();
        assManagerList = [SELECT Id FROM IssueRequest_Life_Cycle__c WHERE InvestigationType__c = :assTemp[1].Id];
        System.assertEquals(5, assManagerList.size());
    }
    
    public static testMethod void testAmGeneratorWithLead() {
    
       List<Main_questionaire__c> assTemp = [SELECT Id FROM Main_questionaire__c];
       List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c> {
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[1].Id)
        };
        
        Test.StartTest();
            AssignmentManagerGenerator_Batch AmGeneratorBatch = new AssignmentManagerGenerator_Batch();
            AmGeneratorBatch.assignmentManagerList = amList;
            AmGeneratorBatch.totalNoOfRecords = 15;
            AmGeneratorBatch.assessbleObjAPI = 'Lead';
            AmGeneratorBatch.selectedobjectLabel = 'Lead';
            AmGeneratorBatch.AMApi ='Facility_Name__c';
            Database.executeBatch(AmGeneratorBatch,2000);
        Test.StopTest();
        
        List<IssueRequest_Life_Cycle__c> assManagerList = new List<IssueRequest_Life_Cycle__c>();
        assManagerList = [SELECT Id FROM IssueRequest_Life_Cycle__c WHERE InvestigationType__c = :assTemp[1].Id];
        System.assertEquals(0, assManagerList.size()); 
    }
    
    public static testMethod void testAmGeneratorWithCon() {
    
        List<Main_questionaire__c> assTemp = [SELECT Id FROM Main_questionaire__c];
        List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c> {
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id)
        };
        
        Test.StartTest();
            AssignmentManagerGenerator_Batch AmGeneratorBatch = new AssignmentManagerGenerator_Batch();
            AmGeneratorBatch.assignmentManagerList = amList;
            AmGeneratorBatch.totalNoOfRecords = 5;
            AmGeneratorBatch.assessbleObjAPI = 'Contact';
            AmGeneratorBatch.selectedobjectLabel = 'Contact';
            AmGeneratorBatch.AMApi ='Facility_Name__c';
            Database.executeBatch(AmGeneratorBatch,5);
        Test.StopTest(); 
        
        List<IssueRequest_Life_Cycle__c> assManagerList = new List<IssueRequest_Life_Cycle__c>();
        assManagerList = [SELECT Id FROM IssueRequest_Life_Cycle__c WHERE InvestigationType__c = :assTemp[0].Id];
        System.assertEquals(0, assManagerList.size()); 
    }
    
    static testMethod void testAmGeneratorWithoutObj() {
    
        List<Account> accList = [SELECT Id FROM Account];
        List<Main_questionaire__c> assTemp = [SELECT Id FROM Main_questionaire__c];
        List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c> {
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id,Facility_Name__c = accList[0].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id,Facility_Name__c = accList[0].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id,Facility_Name__c = accList[0].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id,Facility_Name__c = accList[0].Id),
            new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemp[0].Id,Facility_Name__c = accList[0].Id)
        };
        
        Test.StartTest();
            AssignmentManagerGenerator_Batch AmGeneratorBatch = new AssignmentManagerGenerator_Batch();
            AmGeneratorBatch.assignmentManagerList = amList ;
            AmGeneratorBatch.totalNoOfRecords = 5;
            AmGeneratorBatch.assessbleObjAPI = '';
            AmGeneratorBatch.AMApi = 'Facility_Name__c';
            Database.executeBatch(AmGeneratorBatch,5);
        Test.StopTest();
        
        List<IssueRequest_Life_Cycle__c> assManagerList = new List<IssueRequest_Life_Cycle__c>();
        assManagerList = [SELECT Id FROM IssueRequest_Life_Cycle__c WHERE InvestigationType__c = :assTemp[0].Id];
        System.assertEquals(5, assManagerList.size()); 
    }
}