src/objects/Assignment_Generator_Batch__c.object
<CustomObject>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Generator Batches</relationshipLabel>
        <relationshipName>Assignment_Generator_Batches</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_Of_Records__c</fullName>
        <label>No Of Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assignment Generator Batch</label>
    <nameField>
        <displayFormat>AGB-{0000}</displayFormat>
        <label>Assignment Generator Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Generator Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To create a hierarchy of sub issues or deficiencies</inlineHelpText>
        <label>Related Assignment</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Assignment Manager List</relationshipLabel>
        <relationshipName>Assignment_Manager_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewer_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enables you select a specific configuration of the Standard Viewer to be used for the specified Assessment Template. You can create Standard Viewer configurations that include or exclude specific tabs in the ExAM Configuration tab.</inlineHelpText>
        <label>Viewer Configuration</label>
        <referenceTo>Viewer_Custom_Configuration__c</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Assessment_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment__c.object
<CustomObject>
    <description>Used to support the collection of information necessary to perform data collections that primarily occur outside of Salesforce.</description>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assessment Template ID that is being used for the Assessment.</inlineHelpText>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Generator_Batch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If this Public Assessment was generated as part of a batch this is the Salesforce record Id of that batch.</inlineHelpText>
        <label>Assignment Generator Batch</label>
        <referenceTo>Assignment_Generator_Batch__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Assignment Manager record associated with the Public Assessment.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Public Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Public Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Viewer_Custom_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the standard viewer on an Assessment Template by Assessment Template basis. This configuration is done in the ExAM Configuration tab.</description>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assignment Manager</label>
        <type>Checkbox</type>
    </fields>
    <label>Viewer Custom Configuration</label>
    <nameField>
        <label>Viewer Custom Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewer Custom Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPublicAssessmentLinkCSVcontroller.cls
@isTest
private class TestPublicAssessmentLinkCSVcontroller {

    static testMethod void PAMethod() {
        
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Viewer_Custom_Configuration__c viewerRec = new Viewer_Custom_Configuration__c();
        insert viewerRec;
        
        List<Main_questionaire__c> assTemp = new List<Main_questionaire__c> {
            new Main_questionaire__c(Viewer_Configuration__c =viewerRec.Id,Template_name__c= 'testTemplate1'),
            new Main_questionaire__c(Viewer_Configuration__c =viewerRec.Id,Template_name__c= 'testTemplate2'),
            new Main_questionaire__c(Viewer_Configuration__c =viewerRec.Id,Template_name__c= 'testTemplate3')
        };
        insert assTemp;
        
        List<Section_Template__c> secTemp = new List<Section_Template__c> {
            new Section_Template__c(Questionnaire_Section__c = assTemp[0].Id),
            new Section_Template__c(Questionnaire_Section__c = assTemp[1].Id),
            new Section_Template__c(Questionnaire_Section__c = assTemp[2].Id)
        };
        insert secTemp;
        
        List<Question_Template__c> quesTemp = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c = secTemp[0].Id)
        };
        insert quesTemp;
        
        IssueRequest_Life_Cycle__c amList = new IssueRequest_Life_Cycle__c ();
        amList.InvestigationType__c = assTemp[0].Id;
        amList.Facility_Name__c = acc.Id;
        insert amList;
        
        Assignment_Generator_Batch__c assGen = new Assignment_Generator_Batch__c();
        assGen.Assessment_Template__c = assTemp[0].Id;
        assGen.No_Of_Records__c = 3;
        insert assGen;
        
        List<Public_Assessment__c> paList = new  List<Public_Assessment__c> {
            new Public_Assessment__c(Assessment_Template__c =assTemp[0].Id,Facility_Name__c= acc.Id,Assignment_Manager__c = amList.Id,Assignment_Generator_Batch__c =assGen.Id),
            new Public_Assessment__c(Assessment_Template__c =assTemp[0].Id,Facility_Name__c= acc.Id,Assignment_Manager__c = amList.Id,Assignment_Generator_Batch__c =assGen.Id),
            new Public_Assessment__c(Assessment_Template__c =assTemp[0].Id,Facility_Name__c= acc.Id,Assignment_Manager__c = amList.Id,Assignment_Generator_Batch__c =assGen.Id)
        };
        insert paList;
        
        ApexPages.currentPage().getParameters().put('agId',assGen.Id);
        String PAQueryFields = '';
        List<Schema.FieldSetMember> PAObjFieldsList = new List<Schema.FieldSetMember>();
        
        if(paList != null && paList.size() >0) {

             if(assGen.Id != null) {
        
                PAObjFieldsList = SObjectType.Public_Assessment__c.FieldSets.ExAM__Link_Generator.getFields();
                
                if( PAObjFieldsList != null && PAObjFieldsList.size() > 0) {
                
                    PAQueryFields += 'Id,Name,';
                    
                    for(Schema.FieldSetMember f : PAObjFieldsList) { 
                        if(!PAQueryFields.contains(f.getFieldPath())) {
                            PAQueryFields += f.getFieldPath() + ',';
                        }
                    }
                    
                } else {
                    PAQueryFields += 'Id,Name,ExAM__Public_Assessment_URL__c';
                }
                if (PAQueryFields.endsWith(',')) {
                    PAQueryFields = PAQueryFields.substring(0, PAQueryFields.length()-1);
                }
            }
        }
        
        String queryStr = 'SELECT '+PAQueryFields+' FROM ExAM__Public_Assessment__c WHERE';
        queryStr += ' ExAM__Assignment_Generator_Batch__c = \''+assGen.Id+'\'';
        PublicAssessmentLinkCSVcontroller PALink = new PublicAssessmentLinkCSVcontroller();
        PublicAssessmentLinkCSVcontroller.PARecordClass paRecs = PublicAssessmentLinkCSVcontroller.queryPArecords(queryStr,true,new List<String>());
        
        system.assertEquals(paRecs.statusMsg, 'Processing');
    }
}