src/objects/Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Assessable_Object_API__c</fullName>
        <label>Assessable Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessable_Record__c</fullName>
        <label>Assessable Record</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Distributions</relationshipLabel>
        <relationshipName>Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution_DateTime__c</fullName>
        <label>Distribution DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distributions</relationshipLabel>
        <relationshipName>Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Mode__c</fullName>
        <label>Send Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Anonymous Link</fullName>
                </value>
                <value>
                    <fullName>Download as CSV</fullName>
                </value>
                <value>
                    <fullName>Email with Salesforce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Distribution</label>
    <nameField>
        <label>Distribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Distribution_Group__c.object
<CustomObject>
    <fields>
        <fullName>Target_Object_Filter__c</fullName>
        <label>Target Object Filter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <label>Target Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment__c.object
<CustomObject>
    <description>Used to support the collection of information necessary to perform data collections that primarily occur outside of Salesforce.</description>
    <fields>
        <fullName>Assessable_Object_API__c</fullName>
        <inlineHelpText>This is the Salesforce API name of the Assessable Object.</inlineHelpText>
        <label>Assessable Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assessment Template ID that is being used for the Assessment.</inlineHelpText>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Distribution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution</label>
        <referenceTo>Distribution__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Public Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Public Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDistributionServiceClass.cls
@isTest
public class TestDistributionServiceClass {
    static Testmethod void method1(){
        Main_questionaire__c[] assesment = new Main_questionaire__c[]{
            new Main_questionaire__c(),
            new Main_questionaire__c()
        };
        insert assesment;
        
        Contact newContact = new Contact(LastName='testContact1', Email = 'selva@gmail.com');
        insert newContact;
        
        Account newAcc = new Account(Name = 'TestAcc');
        insert newAcc;
        
        Distribution_Group__c[] distGpList = new Distribution_Group__c[]{
            new Distribution_Group__c(Name = 'test distGp 1' , Target_Object__c = 'Contact', Target_Object_Filter__c = '[{"fieldApi":"LastName","fieldLabel":"Last Name","fieldType":"STRING","operator":"not equals","fieldValue":"testContact"}]'),
            new Distribution_Group__c(Name = 'test distGp 1' , Target_Object__c = 'Contact', Target_Object_Filter__c = '[]'),
            new Distribution_Group__c(Name = 'test distGp 1' , Target_Object__c = 'Contact')
        };
        insert distGpList;                              
        
        Distribution__c[] distributionList = new Distribution__c[]{
            new Distribution__c(Name='test Distribution1'),
            new Distribution__c(Name='test Distribution2'),
            new Distribution__c(Name='test Distribution3')
             
        };
        insert distributionList;
        
        Distribution__c[] distributionList1 = new Distribution__c[]{
            new Distribution__c(Name='test Distribution4', Assessment_Template__c = assesment[1].Id, Distribution_DateTime__c = System.now().addMinutes(2), Assessable_Object_API__c = 'Account', Send_Mode__c = 'Download as CSV'), 
            new Distribution__c(Name='test Distribution5', Assessment_Template__c = assesment[1].Id, Distribution_DateTime__c = System.now().addMinutes(4), Assessable_Record__c = newAcc.Id, Assessable_Object_API__c = 'Account', Send_Mode__c = 'Email with Salesforce'), 
            new Distribution__c(Name='test Distribution6', Assessment_Template__c = assesment[1].Id, Distribution_DateTime__c = System.now().addMinutes(6), Assessable_Object_API__c = 'Account', Send_Mode__c = 'Anonymous Link'),
            new Distribution__c(Name='test Distribution7', Assessment_Template__c = assesment[1].Id, Distribution_DateTime__c = System.now().addMinutes(10), Assessable_Record__c = newAcc.Id, Assessable_Object_API__c = 'Account', Send_Mode__c = 'Email with Salesforce')  
        };
        
        Distribution__c[] newList = [SELECT Name FROM Distribution__c];
        newList[0].Assessment_Template__c = assesment[0].Id;
        newList[1].Assessment_Template__c = assesment[0].Id;
        newList[2].Assessment_Template__c = assesment[0].Id;
        update newList;
        
        List<String> fieldSet = new List<String>();
        fieldSet.add('ExAM__LightningCmp_Distribution_FieldSet');
        
        List<Distribution__c> archivedList = new List<Distribution__c>(); 
        archivedList.add(distributionList[0]);
        archivedList.add(distributionList[1]);
        AssessmentTemplateController.fetchDistribution(assesment[0].Id);        
        System.assert(AssessmentTemplateController.fetchDistribution(assesment[0].Id).size() == 3);
        
        AssessmentTemplateController.archiveDistribution(distributionList[2].Id); 
        AssessmentTemplateController.fetchDistribution(assesment[0].Id);
        System.assert(AssessmentTemplateController.fetchDistribution(assesment[0].Id).size() == 2); 
        if(AssessmentTemplateController.getAssessableObjectDetails('ExAM__IssueRequest_Life_Cycle__c')[0].assObjApiName == 'Account'){
           System.assert(AssessmentTemplateController.getAssessableObjectDetails('ExAM__IssueRequest_Life_Cycle__c')[0].assObjApiName == 'Account'); 
        } else{
           System.assert(AssessmentTemplateController.getAssessableObjectDetails('ExAM__IssueRequest_Life_Cycle__c')[0].assObjFieldApi.startsWithIgnoreCase('AM_')); 
        }
        
        System.assert(AssessmentTemplateController.getDistributionsWthFieldSet(assesment[0].Id, fieldSet, 'ExAM__Distribution__c').distributions[0].Name =='test Distribution1');
        
        Test.startTest();
        try {
            AssessmentTemplateController.createDistributionWthPALink(distributionList1[0], distGpList[0], 3);
                List<Public_Assessment__c> paList = [SELECT Id , Distribution__c FROM Public_Assessment__c ];
               // System.assertEquals(1, paList.size());
               //System.assertEquals(distributionList1[1].Id , paList[0].Distribution__c);
        } catch(Exception e){
            System.assert(e.getMessage() != Null);
        }           
        try {
            AssessmentTemplateController.createDistributionWthPALink(distributionList1[1], distGpList[0], 3);
        } catch(Exception e){
            System.debug('e:::'+e.getMessage());
            System.assertNotEquals(e.getMessage(),'');
        }   
        try {   
            AssessmentTemplateController.createDistributionWthPALink(distributionList1[2], distGpList[0], 3);
        } catch(Exception e){
            System.assertNotEquals(e.getMessage(),'');
        }  
        try {
            AssessmentTemplateController.createDistributionWthPALink(distributionList1[3], distGpList[1], 3);
        } catch(Exception e){
            System.assertNotEquals(e.getMessage(),'');
        }  
        Test.stopTest();
       // AssessmentTemplateController.createDistributionWthPALink(distributionList1[1], distGpList[0], 3);
        
        AssessmentTemplateController.deleteDistribution(distributionList[1].Id);
        System.assert(AssessmentTemplateController.fetchDistribution(assesment[0].Id).size() == 1);
    }
}