src/objects/Distribution__c.object
<CustomObject>
    <fields>
        <fullName>Assessable_Object_API__c</fullName>
        <label>Assessable Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessable_Record__c</fullName>
        <label>Assessable Record</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_DateTime__c</fullName>
        <label>Distribution DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Distribution_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution Group</label>
        <referenceTo>Distribution_Group__c</referenceTo>
        <relationshipLabel>Distributions</relationshipLabel>
        <relationshipName>Distributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email_Template__c</fullName>
        <label>Email Template</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object_Ids__c</fullName>
        <label>Target Object Ids</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Distribution</label>
    <nameField>
        <label>Distribution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distributions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Distribution_Group__c.object
<CustomObject>
    <fields>
        <fullName>Target_Object_Filter__c</fullName>
        <label>Target Object Filter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <label>Target Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Distribution Group</label>
    <nameField>
        <label>Distribution Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Distribution Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment__c.object
<CustomObject>
    <description>Used to support the collection of information necessary to perform data collections that primarily occur outside of Salesforce.</description>
    <fields>
        <fullName>Assessable_Object_API__c</fullName>
        <inlineHelpText>This is the Salesforce API name of the Assessable Object.</inlineHelpText>
        <label>Assessable Object API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distribution</label>
        <referenceTo>Distribution__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public_Assessment_URL__c</fullName>
        <formula>$Setup.Public_Assessment_Configuration__c.Site_URL__c + &apos;/ExAM__AMAndAnswerCreationPage?paId=&apos;+ Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the full URL that can be used to access this Public Assessment.</inlineHelpText>
        <label>Public Assessment URL</label>
        <type>Text</type>
    </fields>
    <label>Public Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Public Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendDistributionScheduler.cls
public class SendDistributionScheduler implements Schedulable {

    public Id distId;

    public SendDistributionScheduler(Id recordId) {
        distId = recordId;
    }
    
    public void execute (SchedulableContext SC){ 
     
       List<Distribution__c> distList = new List<Distribution__c>([
            SELECT Assessable_Object_API__c, Assessable_Record__c, Distribution_Group__c, Distribution_Group__r.Target_Object__c,
                   Distribution_Group__r.Target_Object_Filter__c, Distribution_DateTime__c, Email_Template__c,
                   Id, Name, Target_Object_Ids__c,
                   (SELECT Id, Public_Assessment_URL__c FROM Public_Assessments__r)
            FROM   Distribution__c
            WHERE  Id = :distId AND Email_Template__c != null LIMIT 1]); 

        if( distList.size() > 0 ) {
            SendDistributionBatch dist = new SendDistributionBatch();
            dist.distribution = distList[0];
            Database.executeBatch(dist, 75);
        }
    }
}