src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Data_Management_Tab_Filter__c</fullName>
        <label>Data Management Tab Filter</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Knowledge_Article_Content_Field_Name__c</fullName>
        <label>Knowledge Article Content Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Knowledge_Article_Type_Name__c</fullName>
        <label>Knowledge Article Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Assignment_Manager1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Assignment Manager 1</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Assignment Manager (Related Assignment Manager 1)</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Assignment_Manager2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Assignment Manager 2</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Assignment Manager (Related Assignment Manager 2)</relationshipLabel>
        <relationshipName>Assignment_Manager1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Assignment_Manager3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Assignment Manager 3</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Assignment Manager (Related Assignment Manager 3)</relationshipLabel>
        <relationshipName>Assignment_Manager2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Account_to_Response__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup object that will be used in a survey.So we are not using user but accounts to create number of surveys.The no of surveys would be same as no of accounts whose craete_survey field(on Account object) is set to true</description>
        <inlineHelpText>If the response is related to a specific account it will be listed here.</inlineHelpText>
        <label>Account to Response</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <inlineHelpText>Any user comment associated with this specific Answer record.</inlineHelpText>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>This is the priority of the Answer being provided.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Responsible_Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Point of contact for the deficiency or the response</description>
        <inlineHelpText>If there is a person responsible for the Answer they will be listed here.</inlineHelpText>
        <label>Responsible Party</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Assessment_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight_Response__c</fullName>
        <description>This is score that user gets .It is in percentages from 0-100%.For N/A the score as 0 and dont add it to numerator or denominator</description>
        <inlineHelpText>The percentage of the total possible score possible for the answer that was achieved by the Answer.</inlineHelpText>
        <label>Raw Response Score(%)</label>
        <precision>15</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>deficiency_status__c</fullName>
        <description>For any question response this is the provides a mechanism to provide feedback on the status of this particular item.</description>
        <inlineHelpText>This is the current value associated with the lifecycle of the Answer object record.</inlineHelpText>
        <label>Answer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Self-Certified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestDataManagementController.cls
@isTest 
public class TestDataManagementController {

     static testMethod void method1() {
        ExAM_Configuration__c[] configList = new ExAM_Configuration__c[]{
        	new ExAM_Configuration__c(Name = 'test config',Knowledge_Article_Type_Name__c = 'test article type',
                                     Knowledge_Article_Content_Field_Name__c = 'test field name',
                                     Data_Management_Tab_Filter__c = 'test filter1,test filter2'
                                     )    
        };
        insert configList;
         
        Account acc = new Account();
        acc.Name ='Test';
        insert acc;
        
        contact con = new contact();
        con.AccountId = acc.Id;
        con.LastName = 'TestLastName';
        insert con;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        insert assTemp;
        
        IssueRequest_Life_Cycle__c assManager1 = new IssueRequest_Life_Cycle__c();
        assManager1.investigationType__c = assTemp.Id;
        insert assManager1;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.investigationType__c = assTemp.Id;
        assManager.Related_Assignment_Manager1__c = assManager1.Id;
        assManager.Related_Assignment_Manager2__c = assManager1.Id;
        assManager.Related_Assignment_Manager3__c = assManager1.Id;
        insert assManager;
        
        Section_Template__c secTemp = new Section_Template__c();
        secTemp.Questionnaire_Section__c = assTemp.Id;
        insert secTemp;
        
        Question_Template__c quesTemp = new Question_Template__c();
        quesTemp.Section_Question__c = secTemp.Id;
        insert quesTemp;
        
        Questionnaire_Response__c queRes = new Questionnaire_Response__c();
        queRes.Question_Template__c = quesTemp.Id;
        queRes.Account_to_Response__c = acc.Id;
        queRes.deficiency_status__c = 'Closed';
        queRes.Comment__c = 'Test';
        queRes.Issue_Request__c = assManager.Id;
        queRes.Weight_Response__c = 765629;
        queRes.Response__c = 'test';
        queRes.Responsible_Party__c = con.Id;
        queRes.Priority__c ='high';
        insert queRes;
        
        ApexPages.currentPage().getParameters().put('amid',assManager.Id);
        
        DataManagementController.queryAllAnswerRecords(assManager.Id,false);
        String deleteAnswerRecordResult = DataManagementController.deleteAnswerRecord(queRes.Id);
        
        System.assertEquals('success', deleteAnswerRecordResult);
        DataManagementController dataMngmt = new DataManagementController();
         
        ExAM_Configuration__c econfig = new ExAM_Configuration__c();
        econfig.Data_Management_Tab_Filter__c = 'test filter';
        econfig.Id = configList[0].Id;
        configList[0] = econfig;
        update configList;
         
        DataManagementController.queryAllAnswerRecords(assManager.Id,false);
    }
    static testMethod void method2() {
        
        Account acc = new Account();
        acc.Name ='Test';
        insert acc;
        
        contact con = new contact();
        con.AccountId = acc.Id;
        con.LastName = 'TestLastName';
        insert con;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        insert assTemp;
        
        IssueRequest_Life_Cycle__c assManager1 = new IssueRequest_Life_Cycle__c();
        assManager1.investigationType__c = assTemp.Id;
        insert assManager1;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.investigationType__c = assTemp.Id;
        assManager.Related_Assignment_Manager1__c = assManager1.Id;
        assManager.Related_Assignment_Manager2__c = assManager1.Id;
        assManager.Related_Assignment_Manager3__c = assManager1.Id;
        insert assManager;
        
        Section_Template__c secTemp = new Section_Template__c();
        secTemp.Questionnaire_Section__c = assTemp.Id;
        insert secTemp;
        
        Question_Template__c quesTemp = new Question_Template__c();
        quesTemp.Section_Question__c = secTemp.Id;
        insert quesTemp;
        
        Questionnaire_Response__c queRes = new Questionnaire_Response__c();
        queRes.Question_Template__c = quesTemp.Id;
        queRes.Account_to_Response__c = acc.Id;
        queRes.deficiency_status__c = 'Closed';
        queRes.Comment__c = 'Test';
        queRes.Issue_Request__c = assManager.Id;
        queRes.Weight_Response__c = 765629;
        queRes.Response__c = 'test';
        queRes.Responsible_Party__c = con.Id;
        queRes.Priority__c ='high';
        insert queRes;
        
        Attachment attach = new Attachment();
        attach.ParentId = queRes.Id;
        attach.name = 'testAttach';
        attach.Body = Blob.valueof('TestAttachBody');
        insert attach;
        
        ApexPages.currentPage().getParameters().put('amid',assManager.Id);
        
        DataManagementController.queryAllAnswerRecords(assManager.Id,true);
        String deleteAnswerRecordResult = DataManagementController.deleteAnswerRecord(queRes.Id);
        
        System.assertEquals('success', deleteAnswerRecordResult);
        DataManagementController dataMngmt = new DataManagementController();
        
    }
    
}