src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Case_Configuration__c</fullName>
        <label>Case Configuration</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Enable_Case_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Case Survey</label>
        <type>Checkbox</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCaseHandler.cls
@isTest 
private class TestCaseHandler {
    static testMethod void method1() {
        
        Contact[] conList = new Contact[]{
            new Contact(LastName = 'test contact',Email = 'test@test.com') 
        };
        insert conList;
        
        case caseObj = new case();
        caseObj.ContactId = conList[0].Id;
        caseObj.Origin = 'Email';
        insert caseObj;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Template_Name__c = 'Test Template';
        insert assTemp;
        
        String json = '[{"configTempName":"'+assTemp.Id+'","configFieldValue":"Email","configFieldName":"Origin"}]';
        
        
        
        Map<Id,case> oldCaseMap = new Map<Id,case>();
        oldCaseMap.put(caseObj.Id,caseObj);
        
        
        
        //String json = '[{"configTempName":"'+assTemp.Id+'","configFieldValue":"Email","configFieldName":"Origin"}]';
        ExAM_Configuration__c exmConfig = new ExAM_Configuration__c();
        exmConfig.Name='Configuration';
        exmConfig.Enable_Case_Survey__c = true;
        exmConfig.Case_Configuration__c = json;
        insert exmConfig;
        
        case updateCaseObj = new case();
        updateCaseObj.Id = caseObj.Id;
        updateCaseObj.status = 'Closed';
        try{
            update updateCaseObj;
        }catch(Exception e){
            System.debug('**e'+e);    
        }
        
        List<case> newCaseList = new List<case>();
        newCaseList.add(updateCaseObj);

        Test.startTest();
            CaseHandler ch = new CaseHandler();
            CaseHandler.createPublicAssessmentRecords(oldCaseMap,newCaseList);
        Test.stopTest();
        
        List<ExAM__Public_Assessment__c> paObj = new List<ExAM__Public_Assessment__c>();
        paObj = [SELECT Id,Assessment_Template__c FROM ExAM__Public_Assessment__c WHERE Assessment_Template__c = :assTemp.Id];
        system.assertNotEquals(1, paObj.size());
    }
}