src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Feedback_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feedback Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>ExAM Configurations</relationshipLabel>
        <relationshipName>ExAM_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestRestSaveFeedbackAnswers.cls
@isTest
private class TestRestSaveFeedbackAnswers{
    @testSetup 
    static void createRecords() {
        Main_questionaire__c assTemp = new Main_questionaire__c();
        insert assTemp;
        
        ExAM_Configuration__c ec= new ExAM_Configuration__c();
        ec.Feedback_Template__c = assTemp.Id;
        insert ec;
        
        Section_Template__c sec = new Section_Template__c();
        sec.Questionnaire_Section__c  = assTemp.Id;
        insert sec;
        
        IssueRequest_Life_Cycle__c m1 = new IssueRequest_Life_Cycle__c();
        m1.InvestigationType__c = assTemp.Id;
        insert m1;
        
        Question_Template__c[] qList = new Question_Template__c[]{
            new Question_Template__c(Question_Type__c = 'TEXT',Section_Question__c = sec.Id),
                new Question_Template__c(Question_Type__c = 'TEXT',Section_Question__c = sec.Id)
        };
        insert qList;
        
        Questionnaire_Response__c answer = new Questionnaire_Response__c();
        answer.Question_Template__c = qList[0].Id;
        answer.Issue_Request__c = m1.Id;
        answer.Response__c = 'Satisfied';
        insert answer;
    }
    static testMethod void saveFeedbackAnswersMethod1() {
        List<Main_questionaire__c> assTempList = new List<Main_questionaire__c>([SELECT Id,Name FROM Main_questionaire__c LIMIT 1]);
        System.assertEquals(assTempList.size(),1);
        List<IssueRequest_Life_Cycle__c> assManagerList =  new List<IssueRequest_Life_Cycle__c>([SELECT Id,Name FROM IssueRequest_Life_Cycle__c LIMIT 1]);
        System.assertEquals(assManagerList.size(),1);
        List<Question_Template__c> quesTempList = new List<Question_Template__c>([SELECT Id,Name FROM Question_Template__c]);
        System.assertEquals(quesTempList.size(),2);
        List<Questionnaire_Response__c> ansList =  new List<Questionnaire_Response__c>([SELECT Id,Name FROM Questionnaire_Response__c LIMIT 1]);
        System.assertEquals(ansList.size(),1);
        
        RestSaveFeedbackAnswers.FeedbackAnswersClass ansCls = new RestSaveFeedbackAnswers.FeedbackAnswersClass();
        ansCls.answerList = ansList;
        ansCls.userId = UserInfo.getUserId();
        ansCls.screenName = '';
        ansCls.decisionTreeQuestionId = quesTempList[1].id;
        
        String result = RestSaveFeedbackAnswers.saveFeedbackAnswers(ansCls);
    }
}