src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDecisionTreeConfigController.cls
@isTest
public class TestDecisionTreeConfigController {
    Static testMethod void method1() {
        ExAM_Configuration__c config = new ExAM_Configuration__c();
        config.Name ='Configuration';
        config.Decision_Tree__c='TestFiels';
        insert config;
        List<ExAM_Configuration__c> configList = [Select Id from ExAM_Configuration__c Where Name = 'Configuration']; 
        System.assert(configList.size() == 1);
        
        DecisionTreeConfigController dt = new DecisionTreeConfigController();  
        DecisionTreeConfigController.saveDecisionTreeConfig('TestFields');
    }
}