src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Mobile_Sync_Additional_Templates__c</fullName>
        <description>Field to hold the Ids of the Assessment Templates that need to be synced into mobile app (in addition to the ones configured for Lens Viewer)</description>
        <inlineHelpText>Field to hold the Ids of the Assessment Templates that need to be synced into mobile app (in addition to the ones configured for Lens Viewer)</inlineHelpText>
        <label>Mobile Sync Additional Templates</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mobile_Sync_Assignment_Manager_Statuses__c</fullName>
        <description>Field to hold the Statuses used to filter the Assignment Managers synced for the mobile app</description>
        <label>Mobile Sync Assignment Manager Statuses</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mobile_Sync_Last_X_Days__c</fullName>
        <label>Mobile Sync Last X Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestMobileConfigController.cls
@isTest
public class TestMobileConfigController{
    
    static testMethod void test2(){
        
        Main_questionaire__c temp = new Main_questionaire__c();//Template creation
        temp.Template_name__c = 'Template1';
        insert temp;
        Main_questionaire__c temp1 = new Main_questionaire__c();//Template creation
        temp1.Template_name__c = 'Template11';
        insert temp1; 
        
        MobileConfigController mcc = new MobileConfigController();
        
        List<String> statusList = MobileConfigController.getOverallStatusList();
        System.assert(statusList.size()>0);
        
        String result = MobileConfigController.saveMobileConfig(new ExAM_Configuration__c(),String.valueOf(10),String.valueOf(10));
        //System.assertEquals('null', result);
    }
    static testMethod void test1(){
        
        Main_questionaire__c temp = new Main_questionaire__c();//Template creation
        temp.Template_name__c = 'Template1';
        insert temp;
        Main_questionaire__c temp1 = new Main_questionaire__c();//Template creation
        temp1.Template_name__c = 'Template11';
        insert temp1; 
        
        ExAM_Configuration__c e = new ExAM_Configuration__c();
        e.Name = 'Configuration';
        e.Mobile_Sync_Additional_Templates__c = temp.Id+'~'+temp1.Id;
        e.Mobile_Sync_Assignment_Manager_Statuses__c = 'safkjnsfdajsdas'; 
        e.Mobile_Sync_Last_X_Days__c = 23; 
        insert e;
        
        MobileConfigController mcc = new MobileConfigController();
        
        List<String> statusList = MobileConfigController.getOverallStatusList();
        System.assert(statusList.size()>0);
        
        String result = MobileConfigController.saveMobileConfig(new ExAM_Configuration__c(),string.valueOf(10),String.valueOf(10));
        System.assertEquals('success', result);
    }
}