src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Assignment_Manager_List_Status_Filter__c</fullName>
        <label>Assignment Manager List Status Filter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assessment_Template_Type__c</fullName>
        <formula>if((InvestigationType__c==&apos;&apos;),&apos;&apos;, InvestigationType__r.Template_name__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The name of the Assessment Template in use by the Assignment Manager.</inlineHelpText>
        <label>Assessment Template Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Assigned Resource is typically the Salesforce user assigned with gathering the data or ensuring the gathering of the data.</inlineHelpText>
        <label>Assigned Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssignmentManagerListController.cls
public with sharing class AssignmentManagerListController {

    public string assMngrPrefix{get; set;}

    public AssignmentManagerListController() {
        Schema.DescribeSObjectResult d = ExAM__IssueRequest_Life_Cycle__c.sObjectType.getDescribe();
        assMngrPrefix = d.getkeyPrefix(); 
    }

    @RemoteAction
    public static string queryAllASMRecords() {

        try {

            List<IssueRequest_Life_Cycle__c> assignmentManagerList = new List<IssueRequest_Life_Cycle__c>();

            SFDCAccessController accessEC = ExAMUtilClass.AccessController;
            List<string> fieldsListAC = new List<string>{'ExAM__Assignment_Manager_List_Status_Filter__c'};
            accessEC.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__ExAM_Configuration__c'), fieldsListAC);

            SFDCAccessController accessAM = ExAMUtilClass.AccessController;
            List<string> fieldsListAM = new List<string>{'ExAM__Assessor_Resource__c', 'ExAM__Assessment_Template_Type__c', 'ExAM__Priority__c', 'ExAM__Status__c'};
            accessAM.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__IssueRequest_Life_Cycle__c'), fieldsListAM);

            List<ExAM_Configuration__c> configList = new List<ExAM_Configuration__c>();
            configList = [SELECT Assignment_Manager_List_Status_Filter__c, Id FROM ExAM_Configuration__c WHERE Assignment_Manager_List_Status_Filter__c != NULL ORDER BY CreatedDate DESC LIMIT 1];

            if(configList != null && configList.size() > 0) {

                assignmentManagerList = [
                    SELECT Id, Name, Status__c, Assessment_Template_Type__c, Assessor_Resource__c, Assessor_Resource__r.Name, Priority__c, CreatedDate  
                    FROM   IssueRequest_Life_Cycle__c
                    WHERE  Status__c = :configList[0].Assignment_Manager_List_Status_Filter__c AND Assessor_Resource__c = :UserInfo.getUserId()
                    ORDER BY CreatedDate, Assessor_Resource__c DESC LIMIT 100
                ];
            
            } else {

                assignmentManagerList = [
                    SELECT Id, Name, Status__c, Assessment_Template_Type__c, Assessor_Resource__c, Assessor_Resource__r.Name, Priority__c, CreatedDate  
                    FROM   IssueRequest_Life_Cycle__c
                    WHERE  Assessor_Resource__c = :UserInfo.getUserId()
                    ORDER BY CreatedDate, Assessor_Resource__c DESC LIMIT 100
                ];

            }
            return JSON.serialize(assignmentManagerList);
        } catch (Exception ex) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()) );
        } 
        return null;
    }
}