src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Knowledge_Article_Content_Field_Name__c</fullName>
        <label>Knowledge Article Content Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Knowledge_Article_Type_Name__c</fullName>
        <label>Knowledge Article Type Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestKnowledgeArticleController.cls
@isTest
private class TestKnowledgeArticleController {

    static testMethod void knowledgeQuery() { 
        new KnowledgeArticleController(); 
        ExAM_Configuration__c[] configList = new ExAM_Configuration__c[]{
            new ExAM_Configuration__c(Name = 'test', Knowledge_Article_Type_Name__c = 'Know__c',
                                     Knowledge_Article_Content_Field_Name__c = 'ArticleNumber'
                                     )    
        };
        insert configList;
        KnowledgeArticleController.KnowledgeArticles sobj = KnowledgeArticleController.returnKnowledgeArticles();
        System.assertEquals(null, sobj.summaryField);
        List<ExAM_Configuration__c> configList1 = [SELECT Id, Knowledge_Article_Content_Field_Name__c FROM ExAM_Configuration__c];
        //System.assertEquals('ArticleNumber', sobj.summaryField );
        delete configList1;
        KnowledgeArticleController.KnowledgeArticles sobj1 = KnowledgeArticleController.returnKnowledgeArticles();
    }
    static testMethod void knowledgeQuery1() {
        ExAM_Configuration__c[] configList = new ExAM_Configuration__c[]{
            new ExAM_Configuration__c(Name = 'test', Knowledge_Article_Type_Name__c = 'Account',
                                     Knowledge_Article_Content_Field_Name__c = 'Name'
                                     )    
        };
        insert configList;
        KnowledgeArticleController.KnowledgeArticles sobj = KnowledgeArticleController.returnKnowledgeArticles();
        System.assertEquals(null, sobj.summaryField);
        List<ExAM_Configuration__c> configList1 = [SELECT Id, Knowledge_Article_Content_Field_Name__c FROM ExAM_Configuration__c];
        delete configList1;
        KnowledgeArticleController.KnowledgeArticles sobj1 = KnowledgeArticleController.returnKnowledgeArticles();
    }
}