src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Case_Configuration__c</fullName>
        <label>Case Configuration</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Enable_Case_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Case Survey</label>
        <type>Checkbox</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCaseSurveyConfigurationCtlr.cls
@isTest 

private class TestCaseSurveyConfigurationCtlr {

    static testMethod void method1() {
    
        String json = '[{"configTempName":"T-1058","configFieldValue":"Mechanical","configFieldName":"Type"}]';
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Template_Name__c = 'Test Template';
        insert assTemp;
        
        ExAM_Configuration__c exmConfig = new ExAM_Configuration__c();
        exmConfig.Name='Configuration';
        exmConfig.Enable_Case_Survey__c = false;
        exmConfig.Case_Configuration__c = '[{"configTempName":"T-1058","configFieldValue":"Mechanical","configFieldName":"Type"},{"configTempName":"T-1058","configFieldValue":"Mechanical","configFieldName":"Type"}]';
        insert exmConfig;
        
        CaseSurveyConfigurationCtlr ctr = new CaseSurveyConfigurationCtlr(); 
        CaseSurveyConfigurationCtlr.saveFieldConfiguration(json,'false');
        
        List<ExAM_Configuration__c> config = new List<ExAM_Configuration__c>();
        config = [SELECT Id,Enable_Case_Survey__c,Case_Configuration__c FROM ExAM_Configuration__c WHERE Name='Configuration' ORDER BY CreatedDate DESC LIMIT 1];
        System.assert(config[0].Case_Configuration__c==json);
        System.assert(config[0].Enable_Case_Survey__c==false);
    }
    static testMethod void method2() {
        String json = '[{"configTempName":"T-1058","configFieldValue":"Mechanical","configFieldName":"Type"}]';
        CaseSurveyConfigurationCtlr ctr = new CaseSurveyConfigurationCtlr(); 
        CaseSurveyConfigurationCtlr.saveFieldConfiguration(json,'true');
        
        List<ExAM_Configuration__c> config = new List<ExAM_Configuration__c>();
        config = [SELECT Id,Enable_Case_Survey__c,Case_Configuration__c FROM ExAM_Configuration__c WHERE Name='Configuration' ORDER BY CreatedDate DESC LIMIT 1];
        System.assert(config[0].Case_Configuration__c==json);
        System.assert(config[0].Enable_Case_Survey__c==true);
    }
}