src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Add_Response_Score__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add Response Score</label>
        <type>Checkbox</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestExportAnswersPerAMController.cls
@isTest
public class TestExportAnswersPerAMController {
    @testSetup
    public static void testSetUp() { 
        
        List<Account> acList = new List<Account>{
                               new Account(Name = 'testAcc')
        };
        insert acList;
        
        List<ExAM_Configuration__c> exConfigList = new List<ExAM_Configuration__c> {
                                                   new ExAM_Configuration__c(Add_Response_Score__c = true),
                                                   new ExAM_Configuration__c(Add_Response_Score__c = false)};
        insert exConfigList;                                           
        
        List<Main_questionaire__c> assTempList = new List<Main_questionaire__c>{
                                                 new Main_questionaire__c(),
                                                 new Main_questionaire__c()
        };
        insert assTempList;
        System.assert(assTempList [0].Id != null);
        
        List<Section_Template__c> secList = new List<Section_Template__c>{
                                            new Section_Template__c(Questionnaire_Section__c=assTempList[0].Id)
        };
        insert secList;
        
        List<Question_Template__c> quesList = new List<Question_Template__c>{
                                              new Question_Template__c(Subquestion_Label__c='test q1', Section_Question__c=secList[0].Id, Question_Label__c = 'test label'),
                                              new Question_Template__c(Subquestion_Label__c='test q1', Section_Question__c=secList[0].Id)                        
        };
        insert quesList;
        
        List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c>{
                                                  new IssueRequest_Life_Cycle__c(InvestigationType__c = assTempList[0].Id, Facility_Name__c = acList[0].Id)
        };
        insert amList;
    }
    public static testMethod void testExportAnswerrecords(){
    
        List<Main_questionaire__c> assTemplateList = [SELECT Id FROM Main_questionaire__c];
        List<Account> acList = [SELECT Id FROM Account];
        List<Question_Template__c> quesList = [SELECT Id FROM Question_Template__c];
        
        List<IssueRequest_Life_Cycle__c> amList = new List<IssueRequest_Life_Cycle__c>{
                                                  new IssueRequest_Life_Cycle__c(InvestigationType__c = assTemplateList[0].Id, Facility_Name__c = acList[0].Id)
        };
        insert amList;
        
        List<Questionnaire_Response__c> ansList = new List<Questionnaire_Response__c>{
                                                  new Questionnaire_Response__c(Issue_Request__c = amList[0].Id, Question_Template__c = quesList[0].Id, Response__c = 'Answer1'),
                                                  new Questionnaire_Response__c(Issue_Request__c = amList[0].Id, Question_Template__c = quesList[1].Id)
        };
        insert ansList;
        
        ExportAnswersPerAMController eCSVcntrlr = new ExportAnswersPerAMController();
        ExportAnswersPerAMController.WrapperClass wc = new ExportAnswersPerAMController.WrapperClass();
        ExportAnswersPerAMController.WrapperClass wc1 = new ExportAnswersPerAMController.WrapperClass();
        ExportAnswersPerAMController.WrapperClass wc2 = new ExportAnswersPerAMController.WrapperClass();
        ExportAnswersPerAMController.WrapperClass wc3 = new ExportAnswersPerAMController.WrapperClass();
        ExportAnswersPerAMController.WrapperClass wc4 = new ExportAnswersPerAMController.WrapperClass();
        ExportAnswersPerAMController.WrapperClass wc5 = new ExportAnswersPerAMController.WrapperClass();
        
        List<ExAM_Configuration__c> exConfigList1 = new List<ExAM_Configuration__c> {
                                                    new ExAM_Configuration__c(Add_Response_Score__c = true)};
        insert exConfigList1;                                           
        
        List<String> fieldList = new List<String>{
            'Facility_Name__c'
        };
        
        Datetime yourDate = Datetime.now();
        String startdate = yourDate.format('MM/dd/yyyy');
        Datetime yourDate1 = System.today()+3;
        String endDate = yourDate1.format('MM/dd/yyyy');
        
        wc = ExportAnswersPerAMController.exportAnswersRecords(startdate,endDate , null,fieldList, '','');
        System.assert(wc != null);
        
        wc2 = ExportAnswersPerAMController.exportAnswersRecords(startdate,null ,assTemplateList[0].Id,fieldList,'','');
        wc3 = ExportAnswersPerAMController.exportAnswersRecords('','' ,'',fieldList,'','');
        
        wc1 = ExportAnswersPerAMController.exportAnswersRecords('','' , assTemplateList[0].Id,fieldList,startdate,endDate );
        System.assertEquals('OK',wc1.status = 'OK');
        
        wc4 = ExportAnswersPerAMController.exportAnswersRecords('','' , assTemplateList[0].Id,fieldList,null,null);
        System.assertEquals(2,wc4.ansLength);
        
        wc5 = ExportAnswersPerAMController.exportAnswersRecords('','' , assTemplateList[1].Id,fieldList,startdate,endDate );
        System.assertEquals('OK',wc5.status = 'OK');
    } 
    
    public static testMethod void testExportAnswerrecordswithNullAnsList(){
    
        List<String> fieldList = new List<String>{
            'Facility_Name__c'
        };
        
        List<String> fieldList1 = new List<String>{
            'ExAM__Facility_Name__c'
        };
        
        List<Main_questionaire__c> assTemplateList = [SELECT Id FROM Main_questionaire__c];
        List<Question_Template__c> quesList = [SELECT Id FROM Question_Template__c];
        
        List<Questionnaire_Response__c> ansList = new List<Questionnaire_Response__c>{
                                                  new Questionnaire_Response__c( Question_Template__c = quesList[0].Id, Response__c = 'Answer1'),
                                                  new Questionnaire_Response__c( Question_Template__c = quesList[1].Id)
        };
        insert ansList;
        Datetime yourDate = Datetime.now();
        String startdate = yourDate.format('MM/dd/yyyy');
        Datetime yourDate1 = System.today()+3;
        String endDate = yourDate1.format('MM/dd/yyyy');
        
        ExportAnswersPerAMController.WrapperClass wc1 = new ExportAnswersPerAMController.WrapperClass();
        wc1 = ExportAnswersPerAMController.exportAnswersRecords('','' , assTemplateList[0].Id,fieldList,startdate,endDate);
        System.assertEquals(0, wc1.ansLength);
        System.assertEquals('FAIL',wc1.status = 'FAIL');
        
        ExportAnswersPerAMController.WrapperClass wc2 = new ExportAnswersPerAMController.WrapperClass();
        wc2 = ExportAnswersPerAMController.exportAnswersRecords('','' , assTemplateList[0].Id,fieldList1,startdate,endDate);
        System.assertEquals(0, wc2.ansLength);
        System.assertEquals('FAIL',wc2.status = 'FAIL');
        
        ExportAnswersPerAMController.WrapperClass wc3 = new ExportAnswersPerAMController.WrapperClass();
        wc3 = ExportAnswersPerAMController.exportAnswersRecords(null,null ,null,fieldList,'','');
        System.assertEquals(Null, wc3);
   }     
    
    public static testMethod void testsaveExAMConfiguration() {
    
        List<ExAM_Configuration__c> exConfigList = new List<ExAM_Configuration__c> {
                                                   new ExAM_Configuration__c(Add_Response_Score__c = false),
                                                   new ExAM_Configuration__c(Add_Response_Score__c = true)};
        insert exConfigList;
        
        string str1 = ExportAnswersPerAMController.saveExAMConfiguration(exConfigList[1].Id, 'true');
        string str = ExportAnswersPerAMController.saveExAMConfiguration(exConfigList[0].Id, 'true');
        System.assertEquals('Success', str);
    }     
}