src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Data_Management_Tab_Filter__c</fullName>
        <label>Data Management Tab Filter</label>
        <type>TextArea</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Comment__c</fullName>
        <inlineHelpText>Any user comment associated with this specific Answer record.</inlineHelpText>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Report_Builder_Configuration__c.object
<CustomObject>
    <description>Used to support individual report configurations so that ExAM reports can be saved for future use.</description>
    <fields>
        <fullName>Assessment_Data_Config__c</fullName>
        <label>Assessment Data Config</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Report Builder Configurations</relationshipLabel>
        <relationshipName>Report_Builder_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Manager_position__c</fullName>
        <label>Assignment Manager position</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Choosed_Assignment_manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Choosed Assignment manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Report Builder Configurations</relationshipLabel>
        <relationshipName>Report_Builder_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Range__c</fullName>
        <label>End Date Range</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Output_Format__c</fullName>
        <label>Output Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PDF</fullName>
                </value>
                <value>
                    <fullName>HTML</fullName>
                </value>
                <value>
                    <fullName>JSON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Range__c</fullName>
        <label>Start Date Range</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Report Builder Configuration</label>
    <nameField>
        <label>Report Builder Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Builder Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAssignmentManagerAnswerJSONExportCls.cls
@isTest
private class TestAssignmentManagerAnswerJSONExportCls {
    
    @istest
    static void allTheDataForThisTestClass() {
        ExAM_Configuration__c exConfig = new ExAM_Configuration__c();
        exConfig.Name = 'Configuration';
        exConfig.Data_Management_Tab_Filter__c = 'opt1,opt2';
        insert exConfig;
        
        Account acc = new Account();
        acc.Name = 'Accname';
        insert acc;
            
        Main_questionaire__c temp = new Main_questionaire__c();//Template creation
        temp.Template_name__c = 'Template1';
        insert temp;
        
        IssueRequest_Life_Cycle__c assM = new IssueRequest_Life_Cycle__c();//AssignmentManager creation
        assM.InvestigationType__c = temp.Id;
        assM.Facility_Name__c = acc.Id;
        insert assM;
        
        Section_Template__c sec = new Section_Template__c();
        sec.Questionnaire_Section__c  = temp.Id;
        insert sec;
        
        List<Question_Template__c> qtList = new List<Question_Template__c>();
        Question_Template__c q1 = new Question_Template__c();
        q1.Question_Type__c = 'TEXT';
        q1.Section_Question__c = sec.Id;
        q1.Subquestion_Label__c = 'NA~N/A';
        qtList.add(q1);
        
        Question_Template__c q3 = new Question_Template__c();
        q3.Question_Type__c = 'RadioPicklist';
        q3.Weight_of_Answer__c = '0~100~0';
        q3.Subquestion_Label__c = 'NA~N/A~subquestion2';
        q3.Section_Question__c = sec.Id;
        qtList.add(q3);
        
        Question_Template__c q4 = new Question_Template__c();
        q4.Question_Type__c = 'RadioPicklist';
        q4.Weight_of_Answer__c = '0~100~0';
        q4.Subquestion_Label__c = 'N/A~NA~subquestion2';
        q4.Section_Question__c = sec.Id;
        qtList.add(q4);
        insert qtList;
        
        List<Questionnaire_Response__c> qrList = new List<Questionnaire_Response__c>{
            new Questionnaire_Response__c(Question_Template__c = q4.Id,
                                          Issue_Request__c = assM.Id,
                                          Response__c = 'AnswerTest1',
                                          Comment__c = 'Good'
                                         ),
            new Questionnaire_Response__c(Question_Template__c = q3.Id,
                                          Issue_Request__c = assM.Id,
                                          Response__c = 'AnswerTest1',
                                          Comment__c = 'Good'
                                         )
        };
        insert qrList;
        
        Report_Builder_Configuration__c rbc = new Report_Builder_Configuration__c();
        rbc.Output_Format__c = 'JSON';
        rbc.Name = 'rbc1';
        rbc.Assessment_Data_Config__c = '{"Comments":true,"Pictures":true}';
        rbc.Assignment_Manager_position__c = '[{"position":1,"labelName":"Account Name","apiName":"ExAM__Facility_Name__c"},{"position":2,"labelName":"Record ID","apiName":"Id"},{"position":3,"labelName":"Priority","apiName":"ExAM__Priority__c"},{"position":4,"labelName":"Actual Start Time","apiName":"ExAM__Field_Start_Time__c"},{"position":5,"labelName":"Actual End Time","apiName":"ExAM__Field_End_Time__c"}]';
        rbc.Choosed_Assignment_manager__c = assM.Id;
        rbc.Start_Date_Range__c = 'November 12, 2016 1:16:22 PM GMT';
        rbc.End_Date_Range__c = 'November 22, 2017 1:16:22 PM GMT';
        rbc.Assessment_Template__c = temp.Id;
        insert rbc;    
        
        System.currentPageReference().getParameters().put('reportbuilderid', rbc.Id);
        
        String id=  apexPages.currentPage().getParameters().get('reportbuilderid');
        System.debug(id);
        
        
        
        AssignmentManagerAnswerJSONExportCtrl.assignmentManagerRecord amrec = new AssignmentManagerAnswerJSONExportCtrl.assignmentManagerRecord();
        AssignmentManagerAnswerJSONExportCtrl.assignmentManagerFieldValue amfld = new AssignmentManagerAnswerJSONExportCtrl.assignmentManagerFieldValue();
        
        amrec.amName = 'test';
        amrec.amId = null;
        amrec.amFieldValues = null;
        
        amfld.apiName = 'ExAM__Facility_Name__c';
        amfld.labelName = 'Account';
        amfld.position = 1;
        amfld.fieldvalue = 'Test';
        amfld.apiName2 = 'ExAM__Priority__c';
        amfld.labelName2 ='Priority';
        amfld.position2 = 2;
        amfld.fieldvalue2 = 'Open';
        
        AssignmentManagerAnswerJSONExportCtrl amajec = new AssignmentManagerAnswerJSONExportCtrl();
        system.assertNotEquals(amajec.jsonString, null);
    }    
}