src/objects/ExAM_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the ExAM App.</description>
    <fields>
        <fullName>Mobile_Sync_Additional_Templates__c</fullName>
        <description>Field to hold the Ids of the Assessment Templates that need to be synced into mobile app (in addition to the ones configured for Lens Viewer)</description>
        <inlineHelpText>Field to hold the Ids of the Assessment Templates that need to be synced into mobile app (in addition to the ones configured for Lens Viewer)</inlineHelpText>
        <label>Mobile Sync Additional Templates</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mobile_Sync_Assignment_Manager_Statuses__c</fullName>
        <description>Field to hold the Statuses used to filter the Assignment Managers synced for the mobile app</description>
        <label>Mobile Sync Assignment Manager Statuses</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mobile_Sync_Future_X_Days__c</fullName>
        <label>Mobile Sync Future X Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mobile_Sync_Last_X_Days__c</fullName>
        <label>Mobile Sync Last X Days</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Assessment_Type_Template__c</fullName>
        <label>Primary Assessment Type Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Assessment_Type_1_Template__c</fullName>
        <label>Related Assessment Type 1 Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Assessment_Type_2_Template__c</fullName>
        <label>Related Assessment Type 2 Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Assessment_Type_3_Template__c</fullName>
        <label>Related Assessment Type 3 Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_Assessment_Type_4_Template__c</fullName>
        <label>Related Assessment Type 4 Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ExAM Configuration</label>
    <nameField>
        <label>ExAM Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ExAM Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewer_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enables you select a specific configuration of the Standard Viewer to be used for the specified Assessment Template. You can create Standard Viewer configurations that include or exclude specific tabs in the ExAM Configuration tab.</inlineHelpText>
        <label>Viewer Configuration</label>
        <referenceTo>Viewer_Custom_Configuration__c</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Assessment_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Viewer_Custom_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the standard viewer on an Assessment Template by Assessment Template basis. This configuration is done in the ExAM Configuration tab.</description>
    <fields>
        <fullName>Answer_Options__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Answer Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Management</label>
        <type>Checkbox</type>
    </fields>
    <label>Viewer Custom Configuration</label>
    <nameField>
        <label>Viewer Custom Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewer Custom Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRestGetAssignmentManagersNew.cls
@isTest

private class TestRestGetAssignmentManagersNew {

    static testMethod void method1() {
        Viewer_Custom_Configuration__c vcc = new Viewer_Custom_Configuration__c(Answer_Options__c = true, Data_Management__c = true);
        insert vcc;
        List<Main_questionaire__c> tempList = new List<Main_questionaire__c> {
                new Main_questionaire__c (Template_name__c = 'Unit Template',Viewer_Configuration__c = vcc.Id),
                new Main_questionaire__c (Template_name__c = 'Site Template',Viewer_Configuration__c = vcc.Id),
                new Main_questionaire__c (Template_name__c = 'Common Template',Viewer_Configuration__c = vcc.Id),
                new Main_questionaire__c (Template_name__c = 'System Template',Viewer_Configuration__c = vcc.Id),
                new Main_questionaire__c (Template_name__c = 'Exterior Template',Viewer_Configuration__c = vcc.Id)
        };
        insert tempList;
        
        ExAM_Configuration__c ec = new ExAM_Configuration__c();
        ec.Primary_Assessment_Type_Template__c = tempList[0].Id;
        ec.Related_Assessment_Type_1_Template__c = tempList[1].Id;
        ec.Related_Assessment_Type_2_Template__c = tempList[2].Id;
        ec.Related_Assessment_Type_3_Template__c = tempList[3].Id;
        ec.Related_Assessment_Type_4_Template__c = tempList[4].Id;
        ec.Mobile_Sync_Additional_Templates__c = tempList[0].Id+'~'+tempList[1].Id;
        ec.Mobile_Sync_Assignment_Manager_Statuses__c = 'Open~Completed';
        ec.Mobile_Sync_Last_X_Days__c = 160;
        ec.Mobile_Sync_Future_X_Days__c = 170;
        insert ec;
        
        List<Main_questionaire__c>  assTemp = [Select Id FROM Main_questionaire__c WHERE Viewer_Configuration__c = :vcc.Id];
        system.assertEquals(assTemp.size(),5);
        
        List<Id> tempIdList = new List<Id>();
        for(Main_questionaire__c temp : assTemp) {
            tempIdList.add(temp.Id);
        }
        RestGetAssignmentManagersNew.getAssignmentManagersNew(tempIdList);
        ExAM_Configuration__c ec1 = new ExAM_Configuration__c();
        ec1.Primary_Assessment_Type_Template__c = tempList[0].Id;
        ec1.Related_Assessment_Type_1_Template__c = tempList[1].Id;
        ec1.Related_Assessment_Type_2_Template__c = tempList[2].Id;
        ec1.Related_Assessment_Type_3_Template__c = tempList[3].Id;
        ec1.Related_Assessment_Type_4_Template__c = tempList[4].Id;
        ec1.Mobile_Sync_Additional_Templates__c = tempList[0].Id+'~'+tempList[1].Id;
        ec1.Mobile_Sync_Assignment_Manager_Statuses__c = 'Open~Completed';
        ec1.Mobile_Sync_Last_X_Days__c = 160;
        //ec.Mobile_Sync_Future_X_Days__c = 170;
        insert ec1;
        RestGetAssignmentManagersNew.getAssignmentManagersNew(tempIdList);
        
        ExAM_Configuration__c ec2 = new ExAM_Configuration__c();
        ec2.Primary_Assessment_Type_Template__c = tempList[0].Id;
        ec2.Related_Assessment_Type_1_Template__c = tempList[1].Id;
        ec2.Related_Assessment_Type_2_Template__c = tempList[2].Id;
        ec2.Related_Assessment_Type_3_Template__c = tempList[3].Id;
        ec2.Related_Assessment_Type_4_Template__c = tempList[4].Id;
        ec2.Mobile_Sync_Additional_Templates__c = tempList[0].Id+'~'+tempList[1].Id;
        ec2.Mobile_Sync_Assignment_Manager_Statuses__c = 'Open~Completed';
        //ec2.Mobile_Sync_Last_X_Days__c = 160;
        ec2.Mobile_Sync_Future_X_Days__c = 170;
        insert ec2;
        RestGetAssignmentManagersNew.getAssignmentManagersNew(tempIdList);
    }
}