src/objects/Fact_Score_Data__c.object
<CustomObject>
    <description>Used to support advanced scoring models and outside data for advanced analytics.</description>
    <fields>
        <fullName>Assessment_Completed_URL_JSON__c</fullName>
        <label>Assessment Completed URL JSON</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Fact Score Data</relationshipLabel>
        <relationshipName>Fact_Score_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fact Score Data</label>
    <nameField>
        <label>Fact Score Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fact Score Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Assessment_Completed_URL__c</fullName>
        <label>Assessment Completed URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestScoreBasedPageForwardingController.cls
@isTest 

private class TestScoreBasedPageForwardingController {
    
    static testMethod void testSaveUrls() {
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Template_name__c= 'testTemplate1';
        insert assTemp;
        
        Fact_Score_Data__c factScore = new Fact_Score_Data__c();
        factScore.Assessment_Template__c = assTemp.Id;
        factScore.Assessment_Completed_URL_JSON__c = '[{"fromScore":"1","toScore":"12","urlStr":"www.google.com"},{"fromScore":"13","toScore":"23","urlStr":"www.salesforce.com"}]';
        insert factScore;
        
        ApexPages.currentPage().getParameters().put('tempId',assTemp.Id);
        Test.startTest();
            ScoreBasedPageForwardingController score = new ScoreBasedPageForwardingController();
            ScoreBasedPageForwardingController.saveUrls('www.google.com','[{"fromScore":"1","toScore":"12","urlStr":"www.google.com"},{"fromScore":"13","toScore":"23","urlStr":"www.salesforce.com"}]',assTemp.Id);
        Test.stopTest();
        List<Main_questionaire__c> assTempList = [SELECT Id, Assessment_Completed_URL__c FROM Main_questionaire__c];
        List<Fact_Score_Data__c> factScoreList =[SELECT Id,Assessment_Template__c,Assessment_Completed_URL_JSON__c
                                                FROM Fact_Score_Data__c 
                                                WHERE Assessment_Template__c = :assTemp.Id];
        System.assert(factScoreList.size()==1);
        System.assertEquals('www.google.com', assTempList[0].Assessment_Completed_URL__c);
    }
}