src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To create a hierarchy of sub issues or deficiencies</inlineHelpText>
        <label>Related Assignment</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Assignment Manager List</relationshipLabel>
        <relationshipName>Assignment_Manager_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the organization for which the template is created</description>
        <inlineHelpText>This is the main organization for which the template is created e.g. DOI etc.This has child accounts for each school and school has child accounts of facility or surveys</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Main_Questionnaire_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Intercept_Header__c</fullName>
        <label>Web Intercept Header</label>
        <type>TextArea</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment__c.object
<CustomObject>
    <description>Used to support the collection of information necessary to perform data collections that primarily occur outside of Salesforce.</description>
    <fields>
        <fullName>Assessible_Object_ID__c</fullName>
        <inlineHelpText>This is the Salesforce record ID of the Assessable Object.</inlineHelpText>
        <label>Assessable Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assessment Template ID that is being used for the Assessment.</inlineHelpText>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Assignment Manager record associated with the Public Assessment.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Public Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Public Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Site_URL__c</fullName>
        <label>Site URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Public Assessment Configuration</label>
</CustomObject>

src/classes/TestRestGetIntercept.cls
@isTest 
private class TestRestGetIntercept {

    static testMethod void method1() {
    
        Public_Assessment_Configuration__c setting = new Public_Assessment_Configuration__c();
        setting.Site_URL__c = 'http://www.google.com';
        insert setting;
        
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Account__c = acc.Id;
        assTemp.Template_name__c = 'Test Template';
        assTemp.Web_Intercept_Header__c = 'Test webIntercept header';
        insert assTemp;
        
        Public_Assessment__c pa = new Public_Assessment__c();
        pa.Assessible_Object_ID__c = acc.Id;
        pa.Assessment_Template__c = assTemp.Id;
        insert pa;
        
        RestRequest req = new RestRequest();
        req.params.put('tempId', assTemp.Id);
        req.params.put('objId', acc.Id);
        req.httpMethod = 'GET';

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();
            RestGetIntercept.doGet();
            Blob b1 = Blob.valueOf('test 1');
            system.assertNotEquals(RestContext.Response.ResponseBody, b1);
        Test.stopTest();
    }
    static testMethod void method2() {
        
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Account__c = acc.Id;
        assTemp.Template_name__c = 'Test Template';
        assTemp.Web_Intercept_Header__c = 'Test web Intercept header';
        insert assTemp;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.Facility_Name__c = acc.Id;
        assManager.InvestigationType__c = assTemp.Id;
        insert assManager;
        
        Public_Assessment__c pa = new Public_Assessment__c();
        pa.Assignment_Manager__c = assManager.Id;
        insert pa;
        
        RestRequest req = new RestRequest();
        req.params.put('amId', assManager.Id);
        req.httpMethod = 'GET';

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();
            RestGetIntercept.doGet();
            Blob b2 = Blob.valueOf('test 2');
            system.assertNotEquals(RestContext.Response.ResponseBody, b2);
        Test.stopTest();
    }
    static testMethod void method3() {
    
        Public_Assessment_Configuration__c setting = new Public_Assessment_Configuration__c();
        setting.Site_URL__c = 'http://www.google.com';
        insert setting;
        
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Account__c = acc.Id;
        assTemp.Template_name__c = 'Test Template';
        insert assTemp;
        
        RestRequest req = new RestRequest();
        req.params.put('tempId', assTemp.Id);
        req.params.put('objId', acc.Id);
        req.httpMethod = 'GET';

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();
            RestGetIntercept.doGet();
            Blob b3 = Blob.valueOf('test 3');
            system.assertNotEquals(RestContext.Response.ResponseBody, b3);
        Test.stopTest();
    }
    static testMethod void method4() {
        
        Account acc = new Account();
        acc.name = 'Test Account';
        insert acc;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Account__c = acc.Id;
        assTemp.Template_name__c = 'Test Template';
        insert assTemp;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.Facility_Name__c = acc.Id;
        assManager.InvestigationType__c = assTemp.Id;
        insert assManager;
        
        RestRequest req = new RestRequest();
        req.params.put('amId', assManager.Id);
        req.httpMethod = 'GET';

        RestResponse res = new RestResponse();
        RestContext.request = req;
        RestContext.response = res;
    
        Test.startTest();
            RestGetIntercept.doGet();
            Blob b4 = Blob.valueOf('test 4');
            system.assertNotEquals(RestContext.Response.ResponseBody, b4);
        Test.stopTest();
    }
}