src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRestGetAssignmentManagers.cls
@isTest
public class TestRestGetAssignmentManagers {
    static testMethod void method1() {
        Main_questionaire__c aT1 = new Main_questionaire__c();
        aT1.Template_name__c = 'aT1';
        insert aT1;
        Main_questionaire__c aT2 = new Main_questionaire__c();
        aT1.Template_name__c = 'aT2';
        insert aT2;
        
        IssueRequest_Life_Cycle__c aM1 = new IssueRequest_Life_Cycle__c();
        aM1.InvestigationType__c = aT1.Id;
        insert aM1;
        IssueRequest_Life_Cycle__c aM2 = new IssueRequest_Life_Cycle__c();
        aM2.InvestigationType__c = aT2.Id;
        insert aM2;
        
        List<Id> managersId = new List<Id>();
        managersId.add(aM1.Id);
        managersId.add(aM2.Id);
        String managers = RestGetAssignmentManagers.getAssignmentManagers(managersId);
        System.assert(managers != NULL);
    }
}