src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Date_Completed__c</fullName>
        <inlineHelpText>This field is updated with the most recent time the Assignment Manager was submitted.</inlineHelpText>
        <label>Date/Time Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAuraAMAnalyticsController.cls
@isTest
private class TestAuraAMAnalyticsController {
    
    public static List<AuraAMAnalyticsController.AMAnalytic> responseOfAM_Analytic;
    
    @testSetup static void generateInputToChart(){
        Main_questionaire__c assessment = new Main_questionaire__c(Template_name__c = 'testing');
        insert assessment;
        DateTime completedDate = (DateTime) Date.today();
        List<IssueRequest_Life_Cycle__c> AssignmentManagers = new List<IssueRequest_Life_Cycle__c>{
            new IssueRequest_Life_Cycle__c(Status__c = 'Completed', InvestigationType__c = assessment.Id),
            new IssueRequest_Life_Cycle__c(Status__c = 'Open', InvestigationType__c = assessment.Id, Date_Completed__c=completedDate)
        };
        insert AssignmentManagers;
        
    }
    
    static testMethod void validateAuraAMByStatus() {
        List<Main_questionaire__c> assessments = [SELECT Id FROM Main_questionaire__c];
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByOverallStatus(assessments[0].Id, '');
        /**
        System.assertEquals('Open', responseOfAM_Analytic[0].Xaxis);
        System.assertEquals(1, responseOfAM_Analytic[0].Yaxis);
        System.assertEquals('Completed', responseOfAM_Analytic[1].Xaxis);
        System.assertEquals(1, responseOfAM_Analytic[1].Yaxis);
        **/
    }
    static testMethod void validateAuraAMByCreatedDate() {
        List<Main_questionaire__c> assessments = [SELECT Id FROM Main_questionaire__c];
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCreatedDate(assessments[0].Id, 'THIS_WEEK');
        Date todayDate = Date.today();
        String recordCreatedDate = todayDate.format();
        Integer getDay = AuraAMAnalyticsController.getDay(todayDate);
        //System.assertEquals(2, responseOfAM_Analytic[getDay].Yaxis);
        
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCreatedDate(assessments[0].Id, 'LAST_WEEK');
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCreatedDate(assessments[0].Id, 'THIS_MONTH');
        Integer day = todayDate.day();
        Integer getWeek = Math.round(day/ 7); 
        //System.assertEquals(2, responseOfAM_Analytic[getWeek].Yaxis);
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCreatedDate(assessments[0].Id, 'LAST_MONTH');
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCreatedDate(assessments[0].Id, 'THIS_YEAR');
        Integer getMonth = todayDate.month();
        //System.assertEquals(2, responseOfAM_Analytic[getMonth-1].Yaxis);
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCreatedDate(assessments[0].Id, 'LAST_YEAR');
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCreatedDate(assessments[0].Id, 'LAST_N_YEARS:2');
        List<Integer> getYears = AuraAMAnalyticsController.getYears(todayDate.year(), 2);
        //System.assertEquals(getYears[0], Integer.valueOf(responseOfAM_Analytic[0].Xaxis));
        //System.assertEquals(getYears[1], Integer.valueOf(responseOfAM_Analytic[1].Xaxis));
        
    }
    static testMethod void validateAuraAMByCompletedDate() {
        List<Main_questionaire__c> assessments = [SELECT Id FROM Main_questionaire__c];
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCompletedDate(assessments[0].Id, 'THIS_WEEK');
        Date todayDate = Date.today();
        String recordCreatedDate = todayDate.format();
        Integer getDay = AuraAMAnalyticsController.getDay(todayDate);
        //System.assertEquals(1, responseOfAM_Analytic[getDay].Yaxis);
        
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCompletedDate(assessments[0].Id, 'LAST_WEEK');
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCompletedDate(assessments[0].Id, 'THIS_MONTH');
        Integer day = todayDate.day();
        Integer getWeek = Math.round(day/ 7); 
        //System.assertEquals(1, responseOfAM_Analytic[getWeek].Yaxis);
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCompletedDate(assessments[0].Id, 'LAST_MONTH');
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCompletedDate(assessments[0].Id, 'THIS_YEAR');
        Integer getMonth = todayDate.month();
        //System.assertEquals(1, responseOfAM_Analytic[getMonth-1].Yaxis);
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCompletedDate(assessments[0].Id, 'LAST_YEAR');
        
        responseOfAM_Analytic = AuraAMAnalyticsController.getAmByCompletedDate(assessments[0].Id, 'LAST_N_YEARS:2');
        List<Integer> getYears = AuraAMAnalyticsController.getYears(todayDate.year(), 2);
        //System.assertEquals(getYears[0], Integer.valueOf(responseOfAM_Analytic[0].Xaxis));
        //System.assertEquals(getYears[1], Integer.valueOf(responseOfAM_Analytic[1].Xaxis));
    }
    
}