src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Show_Configuration_Options_in_Viewer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this box enables the end user to configure the Standard Viewer for the purposes of this specific Assignment Manager. For example, adding and removing tabs.</inlineHelpText>
        <label>Show Configuration Options in Viewer</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Viewer_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enables you select a specific configuration of the Standard Viewer to be used for the specified Assessment Template. You can create Standard Viewer configurations that include or exclude specific tabs in the ExAM Configuration tab.</inlineHelpText>
        <label>Viewer Configuration</label>
        <referenceTo>Viewer_Custom_Configuration__c</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Assessment_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Focus_category__c</fullName>
        <description>Group which will have questions from different sections</description>
        <inlineHelpText>Group which will have questions from different sections</inlineHelpText>
        <label>Focus category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Question__c</fullName>
        <label>Next Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Viewer_Custom_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the standard viewer on an Assessment Template by Assessment Template basis. This configuration is done in the ExAM Configuration tab.</description>
    <label>Viewer Custom Configuration</label>
    <nameField>
        <label>Viewer Custom Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewer Custom Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPublicAssessmentModalController.cls
@isTest
private class TestPublicAssessmentModalController {
    static testMethod void method1() {
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        Viewer_Custom_Configuration__c viewerRec = new Viewer_Custom_Configuration__c();
        insert viewerRec;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Viewer_Configuration__c = viewerRec.Id;
        insert assTemp;
        
        Section_Template__c secTemp = new Section_Template__c();
        secTemp.Questionnaire_Section__c = assTemp.Id;
        insert secTemp;
        
        List<Question_Template__c> quesTempList = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c = secTemp.id, Question_Label__c = 'test Question0', Question_Order_No__c = 1, Question_Type__c = 'Text', Focus_category__c = 'CCTV', Weight_of_Answer__c = '4',Subquestion_Label__c='opt1~opt2'),
            new Question_Template__c(Section_Question__c = secTemp.id, Question_Label__c = 'Test Question1', Question_Order_No__c = 2, Question_Type__c = 'RadioPicklist',Subquestion_Label__c='opt1~opt2'),
            new Question_Template__c(Section_Question__c = secTemp.id, Question_Label__c = 'Test Question2', Question_Order_No__c = 2, Question_Type__c = 'RadioPicklist',Subquestion_Label__c='opt1~opt2'),
            new Question_Template__c(Section_Question__c = secTemp.id, Question_Label__c = 'Test Question3', Question_Order_No__c = 2, Question_Type__c = 'RadioPicklist',Subquestion_Label__c='opt1~opt2')
        };
        insert quesTempList;
        List<Question_Template__c> updateQuesTempList = new List<Question_Template__c> {
           new Question_Template__c(Id=quesTempList[1].Id,Next_Question__c=quesTempList[2].Name),
           new Question_Template__c(Id=quesTempList[2].Id,Next_Question__c=quesTempList[3].Name)
        };
        update updateQuesTempList;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.investigationType__c = assTemp.Id;
        assManager.Facility_Name__c = acc.Id;
        assManager.Show_Configuration_Options_in_Viewer__c = True;
        insert assManager;
        
        List<Questionnaire_Response__c> dependAnsList = new  list<Questionnaire_Response__c>{
            new Questionnaire_Response__c(Question_Template__c=quesTempList[1].Id,Response__c='opt2',Issue_Request__c=assManager.Id),
            new Questionnaire_Response__c(Question_Template__c=quesTempList[2].Id,Response__c='opt1',Issue_Request__c=assManager.Id),
            new Questionnaire_Response__c(Question_Template__c=quesTempList[3].Id,Response__c='opt2',Issue_Request__c=assManager.Id)
        };
        insert dependAnsList;

        List<PublicAssessmentModalController.AssessableRecordClass> recordClassList = new List<PublicAssessmentModalController.AssessableRecordClass>();

        PublicAssessmentModalController.AssessableRecordClass recordClass = new PublicAssessmentModalController.AssessableRecordClass();
        recordClass.RecordName = 'Test';
        recordClass.RecordId = acc.Id;
        recordClassList.add( recordClass );
        
        PublicAssessmentModalController.AssessableQueryResultClass assResultError = new PublicAssessmentModalController.AssessableQueryResultClass();
        assResultError.assessableRecords = recordClassList;
        assResultError.success = 'success';
        assResultError.error = '';

        string recordClassStr = Json.serialize( assResultError );


        Test.startTest();
        
            PublicAssessmentModalController pa = new PublicAssessmentModalController();
            string response = PublicAssessmentModalController.queryAssessableRecords('test','Account');
            system.assertEquals(recordClassStr, response);
        Test.stopTest();
    }

    static testMethod void method2() {
    
        contact con = new contact();
        con.FirstName = 'TestCon';
        con.LastName = 'TestCon';
        insert con;
        
        Test.startTest();
            List<contact> conList = new List<contact>();
            conList = [SELECT Id,FirstName,Lastname FROM contact where Lastname = 'TestCon'];
            System.assertEquals(1,conList.size());

            List<PublicAssessmentModalController.AssessableRecordClass> recordClassList = new List<PublicAssessmentModalController.AssessableRecordClass>();

            PublicAssessmentModalController.AssessableRecordClass recordClass = new PublicAssessmentModalController.AssessableRecordClass();
            recordClass.RecordName = conList[0].FirstName+' '+conList[0].Lastname;
            recordClass.RecordId = conList[0].Id;
            recordClassList.add( recordClass );
            
            PublicAssessmentModalController.AssessableQueryResultClass assResultError = new PublicAssessmentModalController.AssessableQueryResultClass();
            assResultError.assessableRecords = recordClassList;
            assResultError.success = 'success';
            assResultError.error = '';
            string recordClassStr = Json.serialize( assResultError );

            PublicAssessmentModalController pa = new PublicAssessmentModalController();
            string response = PublicAssessmentModalController.queryAssessableRecords('test','contact');
            system.assertEquals(recordClassStr, response);
        Test.stopTest();
    }

    static testMethod void method3() {
    
        case c = new case();
        c.status ='working';
        c.origin ='Email';
        insert c;
        
        Test.startTest();

            List<case> caseList = new List<case>([SELECT Id,CaseNumber From Case]);
            System.assertEquals(1,caseList.size());

            List<PublicAssessmentModalController.AssessableRecordClass> recordClassList = new List<PublicAssessmentModalController.AssessableRecordClass>();

            PublicAssessmentModalController.AssessableRecordClass recordClass = new PublicAssessmentModalController.AssessableRecordClass();
            recordClass.RecordName = caseList[0].caseNumber;
            recordClass.RecordId = caseList[0].Id;
            recordClassList.add( recordClass );
            
            PublicAssessmentModalController.AssessableQueryResultClass assResultError = new PublicAssessmentModalController.AssessableQueryResultClass();
            assResultError.assessableRecords = recordClassList;
            assResultError.success = 'success';
            assResultError.error = '';
            
            string recordClassStr = Json.serialize( assResultError );
            
            PublicAssessmentModalController pa = new PublicAssessmentModalController();
            string response = PublicAssessmentModalController.queryAssessableRecords(caseList[0].caseNumber,'case');
            system.assertEquals(recordClassStr, response);
        Test.stopTest();
    }
}