src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Template External Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Question External Id</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Comment__c</fullName>
        <inlineHelpText>Any user comment associated with this specific Answer record.</inlineHelpText>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestJSONUploadAMAndAnswerController.cls
@isTest
public class TestJSONUploadAMAndAnswerController {
  
    static testMethod void method(){
      
        Account acc = new Account(Name = 'TestAccount');
        insert acc;
        
        Main_questionaire__c temp = new Main_questionaire__c();//Template creation
        temp.Template_name__c = 'Template1';
        temp.Template_External_Id__c = 'test_test_testclass';
        insert temp;
        
        IssueRequest_Life_Cycle__c assM = new IssueRequest_Life_Cycle__c();//AssignmentManager creation
        assM.InvestigationType__c = temp.Id;
        assM.Facility_Name__c = acc.Id;
        insert assM;
        
        Section_Template__c sec = new Section_Template__c();
        sec.Questionnaire_Section__c  = temp.Id;
        insert sec;
        
        Question_Template__c q3 = new Question_Template__c();
        q3.Question_Type__c = 'RadioPicklist';
        q3.Weight_of_Answer__c = '0~100~0';
        q3.Subquestion_Label__c = 'NA~N/A~subquestion2';
        q3.Section_Question__c = sec.Id;
        q3.Question_External_Id__c = 'test_test_class';
        insert q3;
        
        Questionnaire_Response__c qr = new Questionnaire_Response__c(Question_Template__c = q3.Id,
                                          Issue_Request__c = assM.Id,
                                          Response__c = 'AnswerTest1',
                                          Comment__c = 'Good'
                                         );
        insert qr;
        
      String amAndAnsJSONListStr = '[{"assignmentManagerValue":[{"f_Value":"2016-10-13 15:39:38","f_Api":"exam__scheduled_start_date__c"}'
                                  + '],"assignment_ManagerName":"AM-51554  10-13-2016","assignment_ManagerId":"'+assM.Id+'",'
                                  + '"assessmentTemplateName":"My VA Survey","assessmentTemplateId":"'+temp.Id+'","assessmentTemplateExternalId"'
                                  + ':"test_test_testclass","assessableRecordId":"'+acc.Id+'","assessableRecord":{"assessableValue":'
                                  + '[{"ass_f_Value":"Dickenson plc","ass_f_Api":"Name"}]},"assessableObject":"Account","assessableFieldAPI"'
                                  + ':"exam__facility_name__c","answers":[{"weightResponse":null,"responsible_Party":null,"response":"Yes"'
                                  + ',"questionWeight":0,"questionName":"Q-33948","questionnaire_Taker_user":null,"questionId":"'+q3.Id+'"'
                                  + ',"q_ExternalId":"test_test_class","priority":"Routine","maxScore":null,"deficiency_status":"Open",'
                                  + '"comment":null,"assessableFieldValue":null,"assessableApi":null,"answerId":"'+qr.Id+'","answer_text"'
                                  + ':null,"AM_Id":"'+assM.Id+'"}]}]'; 
       String rescls = JSONUploadAMAndAnswerController.saveRecords(amAndAnsJSONListStr);
        System.assert(rescls.contains('Upload process has completed successfully'));
        System.debug('rescls'+rescls);
    }
    static testMethod void method1(){
      
        Account acc = new Account(Name = 'TestAccount');
        insert acc;
        
        Main_questionaire__c temp = new Main_questionaire__c();//Template creation
        temp.Template_name__c = 'Template1';
        temp.Template_External_Id__c = 'test_test_testclass';
        insert temp;
        
        IssueRequest_Life_Cycle__c assM = new IssueRequest_Life_Cycle__c();//AssignmentManager creation
        assM.InvestigationType__c = temp.Id;
        assM.Facility_Name__c = acc.Id;
        insert assM;
        
        Section_Template__c sec = new Section_Template__c();
        sec.Questionnaire_Section__c  = temp.Id;
        insert sec;
        
        Question_Template__c q3 = new Question_Template__c();
        q3.Question_Type__c = 'RadioPicklist';
        q3.Weight_of_Answer__c = '0~100~0';
        q3.Subquestion_Label__c = 'NA~N/A~subquestion2';
        q3.Section_Question__c = sec.Id;
        q3.Question_External_Id__c = 'test_test_class';
        insert q3;
        
        Questionnaire_Response__c qr = new Questionnaire_Response__c(Question_Template__c = q3.Id,
                                          Issue_Request__c = assM.Id,
                                          Response__c = 'AnswerTest1',
                                          Comment__c = 'Good'
                                         );
        insert qr;
        
      String amAndAnsJSONListStr = '[{"assignmentManagerValue":[{"f_Value":"2016-10-13 15:39:38","f_Api":"exam__scheduled_start_date__c"}'
                                   + ',{"f_Value":"100.00","f_Api":"exam__Max_Score__c"},{"f_Value":"True","f_Api"'
                                   + ':"exam__Show_Configuration_Options_in_Viewer__c"},{"f_Value":"True","f_Api":"exam__URL_String__c"}]'
                                   + ',"assignment_ManagerName":"AM-51554  10-13-2016","assignment_ManagerId":"'+assM.Id+'",'
                                   + '"assessmentTemplateName":"My VA Survey","assessmentTemplateId":"'+temp.Id+'",'
                                   + '"assessmentTemplateExternalId":null,"assessableRecordId":"'+acc.Id+'","assessableRecord"'
                                   + ':{"assessableValue":[{"ass_f_Value":"Dickenson plc","ass_f_Api":"Name"},{"ass_f_Value":'
                                   + '"2016-10-13 15:39:38","ass_f_Api":"exam__scheduled_start_date__c"},{"ass_f_Value":"100.00",'
                                   + '"ass_f_Api":"exam__Max_Score__c"},{"ass_f_Value":"True","ass_f_Api":'
                                   + '"exam__Show_Configuration_Options_in_Viewer__c"}]},"assessableObject":"Account","assessableFieldAPI"'
                                   + ':"exam__facility_name__c","answers":[{"weightResponse":null,"responsible_Party":null,"response":"Yes"'
                                   + ',"questionWeight":0,"questionName":"Q-33948","questionnaire_Taker_user":null,"questionId":"'+q3.Id+'",'
                                   + '"q_ExternalId":null,"priority":"Routine","maxScore":null,"deficiency_status":"Open","comment":null,'
                                   + '"assessableFieldValue":null,"assessableApi":null,"answerId":"'+qr.Id+'","answer_text":null,'
                                   + '"AM_Id":"'+assM.Id+'"}]}]'; 
       String rescls = JSONUploadAMAndAnswerController.saveRecords(amAndAnsJSONListStr);
        System.assert(rescls.contains('Template does not have external Id value'));
        System.debug('rescls'+rescls);
    }
}