src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRestGetAssesableRecords.cls
@isTest
public class TestRestGetAssesableRecords {
    static testMethod void method1() {
        Account a = new Account();
        a.Name = 'TestAcc';
        insert a;
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Template_name__c = 'TempName';
        insert assTemp;
        IssueRequest_Life_Cycle__c newAssignmentManager = new IssueRequest_Life_Cycle__c();
        newAssignmentManager.Facility_Name__c = a.Id;
        insert newAssignmentManager;
        RestGetAssesableRecords obj = new RestGetAssesableRecords();
        String assRec = RestGetAssesableRecords.getAssesableRecord(newAssignmentManager.Id);
        List<Schema.FieldSetMember> fSet = obj.readFieldSet('New_Account_Mobile', 'Account');
        System.assert(assRec != NULL);
        System.assert(fSet != NULL);
    }
}