src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To create a hierarchy of sub issues or deficiencies</inlineHelpText>
        <label>Related Assignment</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Assignment Manager List</relationshipLabel>
        <relationshipName>Assignment_Manager_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public_Assessment_URL__c</fullName>
        <label>Public Assessment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Related_Assignment_Manager1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Assignment Manager 1</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Assignment Manager (Related Assignment Manager 1)</relationshipLabel>
        <relationshipName>Assignment_Manager</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Web_Intercept_Header__c</fullName>
        <label>Web Intercept Header</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Web_Intercept_Static_Resource_Name__c</fullName>
        <label>WI CSS Override Static Resource Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment__c.object
<CustomObject>
    <description>Used to support the collection of information necessary to perform data collections that primarily occur outside of Salesforce.</description>
    <fields>
        <fullName>Assessible_Object_ID__c</fullName>
        <inlineHelpText>This is the Salesforce record ID of the Assessable Object.</inlineHelpText>
        <label>Assessable Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assessment Template ID that is being used for the Assessment.</inlineHelpText>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Assignment Manager record associated with the Public Assessment.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Public_Assessment_URL__c</fullName>
        <formula>$Setup.Public_Assessment_Configuration__c.Site_URL__c + &apos;/ExAM__AMAndAnswerCreationPage?paId=&apos;+ Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the full URL that can be used to access this Public Assessment.</inlineHelpText>
        <label>Public Assessment URL</label>
        <type>Text</type>
    </fields>
    <label>Public Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Public Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Site_URL__c</fullName>
        <label>Site URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Public Assessment Configuration</label>
</CustomObject>

src/classes/RestGetIntercept.cls
@RestResource(urlMapping='/RestGetIntercept')
global class RestGetIntercept {

    @HttpGet
    global static void doGet() {
     
        Public_Assessment_Configuration__c paConfig = Public_Assessment_Configuration__c.getOrgDefaults();
        String clientURL = '';
        String clientHeader = '';
        String wi_CSS_Override_Static_Resource_Name = '';
        String returnBody = '';
        List<Public_Assessment__c> publicAssessmentList = new List<Public_Assessment__c>(); 

        RestRequest req = RestContext.request;

        try{
        
            if(req.params.get('amId') != null && req.params.get('amId') != '') {

                String amId = req.params.get('amId');

                publicAssessmentList = [
                    SELECT   Assignment_Manager__c, Assignment_Manager__r.InvestigationType__r.Web_Intercept_Header__c,
                             Assignment_Manager__r.InvestigationType__r.Web_Intercept_Static_Resource_Name__c,
                             Assessible_Object_ID__c, Assessment_Template__c, CreatedDate, Id, Name, Public_Assessment_URL__c
                    FROM     Public_Assessment__c
                    WHERE    Assignment_Manager__c = :amId
                    ORDER BY CreatedDate DESC LIMIT 1
                ];     
                if( !publicAssessmentList.isEmpty() ) {     
                    clientURL = publicAssessmentList[0].Public_Assessment_URL__c+'&WebIntercept=true';
                    if (publicAssessmentList[0].Assignment_Manager__r.InvestigationType__r.Web_Intercept_Header__c != null && publicAssessmentList[0].Assignment_Manager__r.InvestigationType__r.Web_Intercept_Header__c != ''){
                        clientHeader = publicAssessmentList[0].Assignment_Manager__r.InvestigationType__r.Web_Intercept_Header__c;
                    }
                    if (publicAssessmentList[0].Assignment_Manager__r.InvestigationType__r.Web_Intercept_Static_Resource_Name__c != null && publicAssessmentList[0].Assignment_Manager__r.InvestigationType__r.Web_Intercept_Static_Resource_Name__c != ''){
                        wi_CSS_Override_Static_Resource_Name = publicAssessmentList[0].Assignment_Manager__r.InvestigationType__r.Web_Intercept_Static_Resource_Name__c;
                    }
                } else {

                    Public_Assessment__c pa = new Public_Assessment__c();       
                    pa.Assignment_Manager__c = amId;        
                    insert pa;
                    clientURL = paConfig.Site_URL__c+'/ExAM__AMAndAnswerCreationPage?paId='+pa.Id+'&WebIntercept=true';
                }
            }
            else if(req.params.get('tempId') != null && req.params.get('tempId') != ''
                    && req.params.get('objId') != null && req.params.get('objId') != '' ) {

                String tempId = req.params.get('tempId');
                String objId = req.params.get('objId');

                publicAssessmentList = [
                    SELECT Assessible_Object_ID__c, Assignment_Manager__c, Assessment_Template__c,
                           Assessment_Template__r.Web_Intercept_Header__c,
                           Assessment_Template__r.Web_Intercept_Static_Resource_Name__c,
                           CreatedDate, Id, Name, Public_Assessment_URL__c
                    FROM   Public_Assessment__c       
                    WHERE  Assessible_Object_ID__c = :objId AND Assessment_Template__c = :tempId
                    ORDER BY CreatedDate DESC LIMIT 1
                ];

                if( !publicAssessmentList.isEmpty() ) {      
                    clientURL = publicAssessmentList[0].Public_Assessment_URL__c+'&WebIntercept=true';
                    if (publicAssessmentList[0].Assessment_Template__r.Web_Intercept_Header__c != null && publicAssessmentList[0].Assessment_Template__r.Web_Intercept_Header__c != '' ){
                        clientHeader = publicAssessmentList[0].Assessment_Template__r.Web_Intercept_Header__c;
                    }
                    if (publicAssessmentList[0].Assessment_Template__r.Web_Intercept_Static_Resource_Name__c != null && publicAssessmentList[0].Assessment_Template__r.Web_Intercept_Static_Resource_Name__c != '' ){
                        wi_CSS_Override_Static_Resource_Name = publicAssessmentList[0].Assessment_Template__r.Web_Intercept_Static_Resource_Name__c;
                    }
                } else {

                    Public_Assessment__c pa = new Public_Assessment__c();       
                    pa.Assessment_Template__c = tempId;     
                    pa.Assessible_Object_ID__c = objId;     
                    insert pa;  
                    clientURL = paConfig.Site_URL__c+'/ExAM__AMAndAnswerCreationPage?paId='+pa.Id+'&WebIntercept=true';    
                }
            }
            if (clientHeader == '' ) {
                clientHeader = 'ExAM Survey';
            }

            StaticResource static_resource = [
                SELECT Id, Body, Name, SystemModStamp
                FROM   StaticResource
                WHERE  Name = 'exam2InterceptHtml' LIMIT 1
            ];

            String dynamicStyle = '';
            if( wi_CSS_Override_Static_Resource_Name != '' ){
    
                String queryDynamicStaticResource = 'SELECT Id, Body, Name, SystemModStamp FROM StaticResource WHERE Name = \''+wi_CSS_Override_Static_Resource_Name +'\' LIMIT 1';
                StaticResource css_Override_static_resource = Database.query(queryDynamicStaticResource);
                dynamicStyle = css_Override_static_resource.Body.toString();
            }
            returnBody = static_resource.Body.toString();
        
            Integer styleStartIndex = returnBody.indexOf('<style>');
            Integer styleEndIndex = returnBody.indexOf('</style>');
            styleEndIndex = styleEndIndex+8;
        
            if( dynamicStyle != '' ) {
                returnBody = returnBody.replace(returnBody.substring(styleStartIndex,styleEndIndex),'<style>'+ dynamicStyle +'</style>');
            }
            returnBody = returnBody.replace('{{clientHeader}}', clientHeader);
            returnBody = returnBody.replace('{{clientURL}}', clientURL);

        }
        catch(Exception e) {
            returnBody = e.getMessage();
        }
        System.debug('::::returnBody::::'+returnBody);
        RestContext.response.addHeader('Content-Type', 'text/html ');
        RestContext.response.addHeader('Access-Control-Allow-Origin','*');
        RestContext.response.addHeader('Access-Control-Allow-Headers','X-Custom-Header');
        RestContext.response.addHeader('Access-Control-Allow-Methods', 'POST, GET, PUT, OPTIONS, DELETE');
        RestContext.response.responseBody = Blob.valueOf(returnBody);
    }
}