src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Date__c</fullName>
        <inlineHelpText>This is the date and time that the Assignment is scheduled to take place.</inlineHelpText>
        <label>Scheduled Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Show_Configuration_Options_in_Viewer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this box enables the end user to configure the Standard Viewer for the purposes of this specific Assignment Manager. For example, adding and removing tabs.</inlineHelpText>
        <label>Show Configuration Options in Viewer</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Weight_Of_Question__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>This is the question weight</inlineHelpText>
        <label>Question Weight</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAssessableFieldQuestionMappingCtr.cls
@isTest

private class TestAssessableFieldQuestionMappingCtr {
    
    @testSetup
    static void createTestRecordsForAssessableFieldMapping() {

        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;

        Main_questionaire__c assessmentTemplate = new Main_questionaire__c();
        assessmentTemplate.Template_Name__c = 'Test Template';
        insert assessmentTemplate;

        Section_Template__c sectionTemplate = new Section_Template__c();
        sectionTemplate.Questionnaire_Section__c = assessmentTemplate.Id;
        sectionTemplate.Section_label__c = 'Test Section';
        insert sectionTemplate;

        Question_Template__c qtnTemplate = new Question_Template__c();
        qtnTemplate.Section_Question__c = sectionTemplate.Id;
        qtnTemplate.Question_Label__c = 'How is your experience with our service?';
        qtnTemplate.Subquestion_Label__c = 'Very Satisfied~Satisfied~Not Satisfied';
        qtnTemplate.Weight_of_Answer__c = '10~50~40';
        qtnTemplate.Question_Type__c = 'RadioPicklist';
        qtnTemplate.Weight_Of_Question__c = 10;
        insert qtnTemplate;

        IssueRequest_Life_Cycle__c managerRecord = new IssueRequest_Life_Cycle__c();
        managerRecord.investigationType__c = assessmentTemplate.Id;
        managerRecord.Facility_Name__c = acc.Id;
        managerRecord.scheduled_start_date__c = Date.today()-5;
        managerRecord.Show_Configuration_Options_in_Viewer__c = True;
        insert managerRecord;

        Questionnaire_Response__c answer = new Questionnaire_Response__c();
        answer.Question_Template__c = qtnTemplate.Id;
        answer.Issue_Request__c = managerRecord.Id;
        answer.Response__c = 'Satisfied';
        insert answer;

        List<Questionnaire_Response__c> answerList = new List<Questionnaire_Response__c>([SELECT Id, Name FROM Questionnaire_Response__c LIMIT 1]);
        system.assertEquals(answerList.size(), 1);
    }

    static testMethod void method1() {

        AssessableFieldQuestionMappingController fieldMappingCtrller = new AssessableFieldQuestionMappingController();

        AssessableFieldQuestionMappingController.assessableFields('Account');

        List<Main_questionaire__c> assessmentTemplateList = new List<Main_questionaire__c>([SELECT Id, Name, Template_Name__c FROM Main_questionaire__c WHERE Template_Name__c = 'Test Template' LIMIT 1]);

        if (!assessmentTemplateList.isEmpty() ) {

            string assessmentTemplateId = assessmentTemplateList[0].Id;

            AssessableFieldQuestionMappingController.getQuestionRecords( assessmentTemplateId );

            List<Question_Template__c> qtnTemplateList = new List<Question_Template__c>([SELECT Id, Name, Section_Question__c, Section_Question__r.Questionnaire_Section__c FROM Question_Template__c WHERE Section_Question__r.Questionnaire_Section__c = :assessmentTemplateId LIMIT 1]);

            if (!qtnTemplateList.isEmpty() ) {

                AssessableFieldQuestionMappingController.AssessableMappingClass fieldMappingInstance1 = new AssessableFieldQuestionMappingController.AssessableMappingClass();
                fieldMappingInstance1.assessableFieldsApi = 'Type';
                fieldMappingInstance1.questionId = qtnTemplateList[0].Id;
                fieldMappingInstance1.MappingRecordId = null;
                fieldMappingInstance1.storeAnswerResponseOrWeight = 'Response';
                fieldMappingInstance1.mappedFrom = 'Answer';
                fieldMappingCtrller.assMappingResponseList.add( fieldMappingInstance1 );

                AssessableFieldQuestionMappingController.AssessableMappingClass fieldMappingInstance2 = new AssessableFieldQuestionMappingController.AssessableMappingClass();
                fieldMappingInstance2.assessableFieldsApi = 'ExAM__Adequate_Lighting_Score__c';
                fieldMappingInstance2.questionId = qtnTemplateList[0].Id;
                fieldMappingInstance2.MappingRecordId = null;
                fieldMappingInstance2.storeAnswerResponseOrWeight = 'Score';
                fieldMappingInstance2.mappedFrom = 'Answer';
                fieldMappingCtrller.assMappingResponseList.add( fieldMappingInstance2 );

                AssessableFieldQuestionMappingController.AssessableMappingClass fieldMappingInstance3 = new AssessableFieldQuestionMappingController.AssessableMappingClass();
                fieldMappingInstance3.assessableFieldsApi = 'ExAM__Status__c';
                fieldMappingInstance3.MappingRecordId = null;
                fieldMappingInstance3.mappedFrom = 'Assignment Manager';
                fieldMappingInstance3.amFieldAPI = 'ExAM__Status__c';
                fieldMappingCtrller.assMappingResponseList.add( fieldMappingInstance3 );

                AssessableFieldQuestionMappingController.saveFieldMapping('Account', fieldMappingCtrller.assMappingResponseList, assessmentTemplateId, false);

                string existingAFMRecord = AssessableFieldQuestionMappingController.existingFieldMapping('Account', assessmentTemplateId, false);
                if (string.isNotBlank(existingAFMRecord) ) {

                    AssessableFieldQuestionMappingController.AFMDetail existingAFMObj = (AssessableFieldQuestionMappingController.AFMDetail)JSON.deserialize(existingAFMRecord, AssessableFieldQuestionMappingController.AFMDetail.class);
                    String existingAFMListStr = existingAFMObj.afms;
                    
                    List<AssessableFieldQuestionMappingController.AssessableMappingClass> existingAFMList = (List<AssessableFieldQuestionMappingController.AssessableMappingClass>)JSON.deserialize(existingAFMListStr,List<AssessableFieldQuestionMappingController.AssessableMappingClass>.class);
                    
                    if (!existingAFMList.isEmpty() && existingAFMObj.errorMsg != null && existingAFMObj.errorMsg != '' ) {
                        
                        system.assertNotEquals(existingAFMList[0].MappingRecordId, assessmentTemplateId);

                        fieldMappingCtrller.assMappingResponseList = new List<AssessableFieldQuestionMappingController.AssessableMappingClass>();

                        AssessableFieldQuestionMappingController.AssessableMappingClass fieldMappingInstance4 = new AssessableFieldQuestionMappingController.AssessableMappingClass();
                        fieldMappingInstance4.assessableFieldsApi = 'ExAM__UpsellOpportunity__c';
                        fieldMappingInstance4.MappingRecordId = existingAFMList[0].MappingRecordId;
                        fieldMappingInstance4.mappedFrom = 'Assignment Manager';
                        fieldMappingInstance4.amFieldAPI = 'ExAM__Status__c';
                        fieldMappingCtrller.assMappingResponseList.add( fieldMappingInstance4 );

                        AssessableFieldQuestionMappingController.saveFieldMapping('Account', fieldMappingCtrller.assMappingResponseList, assessmentTemplateId, false);

                        AssessableFieldQuestionMappingController.deleteMappingRecord( existingAFMList[0].MappingRecordId );

                        AssessableFieldQuestionMappingController.deleteMappingRecord( 'Tobe Deleted Record Id' );


                        fieldMappingCtrller.assMappingResponseList = new List<AssessableFieldQuestionMappingController.AssessableMappingClass>();

                        AssessableFieldQuestionMappingController.AssessableMappingClass fieldMappingInstance5 = new AssessableFieldQuestionMappingController.AssessableMappingClass();
                        fieldMappingInstance5.assessableFieldsApi = 'ExAM__UpsellOpportunity__c';
                        fieldMappingInstance5.MappingRecordId = 'DUMMY ASSESSABLE FIELD MAPPING RECORD ID';
                        fieldMappingInstance5.mappedFrom = 'Assignment Manager';
                        fieldMappingInstance5.amFieldAPI = 'ExAM__Status__c';
                        fieldMappingCtrller.assMappingResponseList.add( fieldMappingInstance5 );

                        String savedResponse = AssessableFieldQuestionMappingController.saveFieldMapping('Account', fieldMappingCtrller.assMappingResponseList, assessmentTemplateId, false);

                        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(savedResponse);
                        if (responseMap != null) {
                            system.assertEquals(responseMap.get('status'), false);
                            system.assertEquals(responseMap.get('resultMsg'), 'Invalid id: DUMMY ASSESSABLE FIELD MAPPING RECORD ID');
                        }
                    }
                }
            }
        }
    }
}