src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>To create a hierarchy of sub issues or deficiencies</inlineHelpText>
        <label>Related Assignment</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Assignment Manager List</relationshipLabel>
        <relationshipName>Assignment_Manager_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssessableRecordDetailController.cls
public with sharing class AssessableRecordDetailController {

    public SObject assessableRec { get; set; }

    public List<Schema.FieldSetMember> fields { get; set; }

    public AssessableRecordDetailController() {

        try {

            assessableRec = Schema.getGlobalDescribe().get('Account').newSObject() ;

            fields = new List<Schema.FieldSetMember> ();
            String assignmentManagerId = apexPages.currentPage().getparameters().get('amid');

            List<ExAMUtilClass.AssessableRecordsClass> AssessableRecords = new List<ExAMUtilClass.AssessableRecordsClass>();

            ExAMUtilClass.AssessableObjectDetails objectDetail = ExAMUtilClass.getAssessableObjectDetails('ExAM__IssueRequest_Life_Cycle__c');
            Map<string, string> fieldsMap = objectDetail.assessableObjectAPIMap;

            SFDCAccessController accessAM = ExAMUtilClass.AccessController;
            List<String> fieldsListAM = new List<String>{'ExAM__Assignment_Manager__c', 'ExAM__InvestigationType__c'};

            if ( assignmentManagerId != null && assignmentManagerId != '') {
                Id assignmentId = Id.valueOf(assignmentManagerId);
                String amQuery = 'SELECT Assignment_Manager__c, Facility_Name__r.Name, Id, InvestigationType__c, InvestigationType__r.Name, Name';
                for (String fldName : fieldsMap.keySet()) {
                    amQuery += ', ' + fldName;
                    fieldsListAM.add( fldName );
                }
                amQuery += ' FROM IssueRequest_Life_Cycle__c WHERE Id = :assignmentManagerId LIMIT 1';

                accessAM.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__IssueRequest_Life_Cycle__c'), fieldsListAM);

                List<IssueRequest_Life_Cycle__c> assignmentManagerList = Database.query(amQuery );

                System.debug(':::assignmentManagerList :::'+assignmentManagerList );
                if (assignmentManagerList != null && assignmentManagerList.size() > 0 ) {

                    ExAMUtilClass.AssessableObjectInAMClass assessableObjectDetails = ExAMUtilClass.getAssessableObjectDetailsFromAM( assignmentManagerList );
                    Id AssessableObjectId = assessableObjectDetails.managerIdWithAssessableObjectIdMap.get( assignmentManagerList[0].Id );
                    string AssessableObjectAPIName = assessableObjectDetails.managerIdWithAssessableObjectAPINameMap.get( assignmentManagerList[0].Id );
                    string truncatedSObjectApiName = (AssessableObjectAPIName.endsWithIgnoreCase('__c')) ? AssessableObjectAPIName.substringBefore('__c') : AssessableObjectAPIName;
                    string fieldSetName = 'ViewerFieldSet_'+truncatedSObjectApiName;
                    fields = ExAMUtilClass.getFieldSetMembers(AssessableObjectAPIName, fieldSetName);

                    AssessableRecords = ExAMUtilClass.getAssessableRecords(assignmentManagerList, false);
                    for (ExAMUtilClass.AssessableRecordsClass eachRecord : AssessableRecords) {
                        if (eachRecord.recordId == AssessableObjectId) {
                            assessableRec = eachRecord.sObjectRecord;
                            break;
                        }
                    }
                }
            }
        }
        catch(Exception e) {
            fields = new List<Schema.FieldSetMember> ();
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    } 
}