src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Issue_request__c</fullName>
        <inlineHelpText>Textual description of the Assignment. Often used to communicate any specific requirements for a particular data collection activity.</inlineHelpText>
        <label>Issue/request</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>The priority of the Assignment Manager. This field is typically customized to meet the requirements of the ExAM use case.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scheduled_End_Date__c</fullName>
        <inlineHelpText>This is the date and time that the Assignment is scheduled to be completed.</inlineHelpText>
        <label>Scheduled End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled_Start_Date__c</fullName>
        <inlineHelpText>This is the date and time that the Assignment is scheduled to take place.</inlineHelpText>
        <label>Scheduled Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>This is the overall lifecycle status of the Assignment Manager. The status of this field is typically automatically updated on the submission of an Assignment Manager.</inlineHelpText>
        <label>Overall Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Issue_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assignment Manager related to the Answer record.</inlineHelpText>
        <label>Assignment Manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Answers</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>This is the priority of the Answer being provided.</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Routine</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAnswerSurveyController.cls
@isTest
private class TestAnswerSurveyController {
    public class SearchCriteriaClass{
        Id templateId;
        String status;
        List<Id> qtnIdList;
        String createdDate;
        String amStartDate;
        String amEndDate;
        public SearchCriteriaClass(Id templateId,String status,List<Id> qtnIdList,String createdDate,String amStartDate,String amEndDate){
            this.qtnIdList = new List<Id>();
            this.templateId = templateId;
            this.status = status;
            this.qtnIdList = qtnIdList;
            this.createdDate = createdDate;
            this.amStartDate = amStartDate;
            this.amEndDate = amEndDate;
        }
    }
    static testMethod void method1() {
        String searchCriteria = '';
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Template_name__c = 'Test Template';
        insert assTemp;
        
        Section_Template__c secTemp = new Section_Template__c();
        secTemp.Questionnaire_Section__c = assTemp.Id;
        insert secTemp;
        
        List<Question_Template__c> quesTemp = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c=secTemp.Id,Question_Label__c = 'Test Question1'),
            new Question_Template__c(Section_Question__c=secTemp.Id,Question_Label__c = 'Test Question2'),
            new Question_Template__c(Section_Question__c=secTemp.Id,Question_Label__c = 'Test Question3'),
            new Question_Template__c(Section_Question__c=secTemp.Id,Question_Label__c = 'Test Question4')
        };
        insert quesTemp;
        List<Id> quesIdList = new List<Id>();
        quesIdList.add(quesTemp[0].Id);
        quesIdList.add(quesTemp[1].Id);
        quesIdList.add(quesTemp[2].Id);
        quesIdList.add(quesTemp[3].Id);
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.investigationType__c = assTemp.Id;
        assManager.Status__c = 'open';
        DateTime myDateTime = DateTime.newInstance(2017,03, 16, 23, 0, 0);
        Date myDate = myDateTime.dateGMT();
        DateTime myDateTime1 = DateTime.newInstance(2017,10,16,23, 0, 0);
        Date myDate1 = myDateTime1.dateGMT();
        assManager.Scheduled_Start_Date__c = myDate;
        assManager.Scheduled_End_Date__c = myDate1;
        insert assManager;
        System.debug('::::aaaaa'+assManager);
        List<IssueRequest_Life_Cycle__c> amlist = [SELECT CreatedDate, Id, Status__c, Scheduled_Start_Date__c, Scheduled_End_Date__c FROM IssueRequest_Life_Cycle__c];
        //String creDate = String.valueOf(amlist[0].CreatedDate.getTime());
        //String creDate = String.valueOf(amlist[0].CreatedDate);
        String creDate = String.valueOf('2017-10-24T09:31:08');
        String startDate = '2017/03/16';
        String endDate = '2017/10/16';
        List<Questionnaire_Response__c> quesResList = new List<Questionnaire_Response__c> {
            new Questionnaire_Response__c(Response__c='Test Response1',Priority__c='High',Issue_Request__c=assManager.Id,Question_Template__c=quesTemp[0].Id),
            new Questionnaire_Response__c(Response__c='Test Response2',Priority__c='Emergency',Issue_Request__c=assManager.Id,Question_Template__c=quesTemp[1].Id),
            new Questionnaire_Response__c(Response__c='Test Response3',Priority__c='high',Issue_Request__c=assManager.Id,Question_Template__c=quesTemp[2].Id),
            new Questionnaire_Response__c(Response__c='Test Response4',Priority__c='Emergency',Issue_Request__c=assManager.Id,Question_Template__c=quesTemp[3].Id)
        };
        insert quesResList;
        
        System.assert(quesResList.size()==4);
        List<Id> quesTempId = new List<Id>();
        quesTempId.add(quesTemp[0].Id);
        quesTempId.add(quesTemp[1].Id);
        
        SearchCriteriaClass searchCriteriaObj = new SearchCriteriaClass(assTemp.Id,'open',quesIdList,creDate,startDate,endDate);
        System.debug('searchCriteriaObj::'+searchCriteriaObj);
        searchCriteria = JSON.serialize(searchCriteriaObj);
        
        Test.startTest();
            AnswerSurveyController ansSurvey = new AnswerSurveyController();
            AnswerSurveyController.answerQuery(assTemp.Id,'15/10/2016','15/10/2016',quesTempId,'open');
            AnswerSurveyController.answerQuery1(assTemp.Id,'15/10/2016','15/10/2016',quesTempId,'open','1476447869000');
            AnswerSurveyController.questionTempalteQuery(assTemp.Id);
            String queryStr = AnswerSurveyController.queryAnswers(searchCriteria);
            String queryQuesStr = AnswerSurveyController.queryQuestionTemplates(searchCriteria);
            System.debug(':::::'+queryStr);
        Test.stopTest();
            quesIdList = new List<Id>();
            Main_questionaire__c assTemp1 = new Main_questionaire__c();
            assTemp1.Template_name__c = 'Test Template';
            insert assTemp1;
            SearchCriteriaClass searchCriteriaObj1 = new SearchCriteriaClass(assTemp1.Id,'open',quesIdList,creDate,startDate,endDate);
            System.debug('searchCriteriaObj::'+searchCriteriaObj1);
            String searchCriteria1 = JSON.serialize(searchCriteriaObj1);
            String queryStr1 = AnswerSurveyController.queryAnswers(searchCriteria1);
            String queryQuesStr1 = AnswerSurveyController.queryQuestionTemplates(searchCriteria1);
    }
}