src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSigntureAttachmentPageController.cls
@isTest
public class TestSigntureAttachmentPageController {

    static testMethod void method1(){

        List<Account> accList = new List<Account>{
            new Account(Name = 'account1')
        };
        insert accList;    

        List<IssueRequest_Life_Cycle__c> managerList = new List<IssueRequest_Life_Cycle__c> {
            new IssueRequest_Life_Cycle__c(Facility_Name__c = accList[0].Id)
        };
        insert managerList;    

        List<Attachment> attList = new List<Attachment>{
            new Attachment(Name = 'Signature1', Body = Blob.valueOf('test'), ParentId = managerList[0].Id)
        };
        insert attList;    
        
        String asMId = String.valueOf(managerList[0].Id);
        String getterString = SigntureAttachmentPageController.attachmentGetter(asMId);

        System.assert(getterString.contains(attList[0].Name));
        
        String deleteString = SigntureAttachmentPageController.attachmentDeleter(attList);
        System.assertEquals('Deleted', deleteString);
    }
}