src/objects/IssueRequest_Life_Cycle__c.object
<CustomObject>
    <description>Assignment Managers support your assessments, data calls, surveys, and inspections by providing the metadata required to support these information gathering activities.</description>
    <fields>
        <fullName>Facility_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the Account that is being assessed. Assess Anything is enabled by default against the Account object. To add other accessible objects go to ExAM Configuration.</inlineHelpText>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assignment Manager</relationshipLabel>
        <relationshipName>Issue_Request_Life_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>InvestigationType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Salesforce ID for the Assessment Template.</inlineHelpText>
        <label>Assessment Template ID</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Assignment Managers</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Show_Configuration_Options_in_Viewer__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Checking this box enables the end user to configure the Standard Viewer for the purposes of this specific Assignment Manager. For example, adding and removing tabs.</inlineHelpText>
        <label>Show Configuration Options in Viewer</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Manager</label>
    <nameField>
        <displayFormat>AM-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the organization for which the template is created</description>
        <inlineHelpText>This is the main organization for which the template is created e.g. DOI etc.This has child accounts for each school and school has child accounts of facility or surveys</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Main_Questionnaire_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContactOrganization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the name of the organization that is responsible for maintaining the Assessment Template.</inlineHelpText>
        <label>Contact Organization</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Main_questionnaire_template</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Report_Builder_Configuration__c.object
<CustomObject>
    <description>Used to support individual report configurations so that ExAM reports can be saved for future use.</description>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Report Builder Configurations</relationshipLabel>
        <relationshipName>Report_Builder_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assignment_Manager_position__c</fullName>
        <label>Assignment Manager position</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Choosed_Assignment_manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Choosed Assignment manager</label>
        <referenceTo>IssueRequest_Life_Cycle__c</referenceTo>
        <relationshipLabel>Report Builder Configurations</relationshipLabel>
        <relationshipName>Report_Builder_Configurations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date_Range__c</fullName>
        <label>End Date Range</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Output_Format__c</fullName>
        <label>Output Format</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PDF</fullName>
                </value>
                <value>
                    <fullName>HTML</fullName>
                </value>
                <value>
                    <fullName>JSON</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selected_Sections__c</fullName>
        <label>Selected Sections</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Start_Date_Range__c</fullName>
        <label>Start Date Range</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Report Builder Configuration</label>
    <nameField>
        <label>Report Builder Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Builder Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestReportBuilderConfigController.cls
@isTest 
public class TestReportBuilderConfigController {

    static testMethod void method1() {
    
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        contact con = new contact();
        con.AccountId=acc.id;
        con.LastName ='testCon';
        insert con;
        
        Main_questionaire__c assTemp = new Main_questionaire__c();
        assTemp.Account__c = acc.Id;
        assTemp.ContactOrganization__c = con.Id;
        insert assTemp;
        
        IssueRequest_Life_Cycle__c assManager = new IssueRequest_Life_Cycle__c();
        assManager.investigationType__c = assTemp.Id;
        assManager.Facility_Name__c = acc.Id;
        assManager.Show_Configuration_Options_in_Viewer__c = True;
        insert assManager;
        
        List<Report_Builder_Configuration__c> reportList = new List<Report_Builder_Configuration__c>{
            new Report_Builder_Configuration__c(Name = 'TestReport',Output_Format__c = 'PDF',Start_Date_Range__c = String.valueOf(Date.today()-5),End_Date_Range__c = String.valueof(Date.today()-2),
            Choosed_Assignment_manager__c = assManager.Id,Assignment_Manager_position__c = 'Test',Selected_Sections__c = 'test',Assessment_Template__c = assTemp.Id)};
        insert reportList;
        
        Test.startTest();
            ReportBuilderConfigController report = new ReportBuilderConfigController();
            ReportBuilderConfigController.queryAssignmentManagers('test','Test','2016/1/12','2016/2/12');
            ReportBuilderConfigController.querySectionTemplate(assTemp.Id);
            ReportBuilderConfigController.saveReportBuilderConfig(String.valueOf(reportList[0].Id),assTemp.Id,reportList[0].Name,'2016/1/12','2016/2/12','PDF',assManager.Id,'Test','All', false,'{"Comments":true,"Pictures":true}','','In Progress, Open, Completed');
            ReportBuilderConfigController.queryAssignmentManager(assManager.Id);
        Test.stopTest();
        
        List<Report_Builder_Configuration__c> reportBuildList = [SELECT Id,Name,Selected_Sections__c,Assignment_Manager_position__c FROM Report_Builder_Configuration__c LIMIT 1];
        System.assertEquals(reportBuildList[0].Selected_Sections__c,'All');
    }
}