src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Hotspot_Image_Properties__c</fullName>
        <label>Hotspot Image Properties</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Order_No__c</fullName>
        <description>Question Order No to specify which questions should be displayed first</description>
        <label>Question Order No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Weight_of_Answer__c</fullName>
        <inlineHelpText>Each answer weight/score is entered with tilde sign and total should be 100%.E.g. 10~50~40 for each answer option.</inlineHelpText>
        <label>Answer Options Weight(%)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestUploadHotspotImageCtlr.cls
@isTest
private class TestUploadHotspotImageCtlr {
    
    @testSetUp
    public static void testSetUp() {
       
        List<Main_questionaire__c> asstempList = new List<Main_questionaire__c> {
            new Main_questionaire__c (Template_name__c = 'Test HotspotImage Template')
        };
        insert asstempList;
        
        List<Section_Template__c> secTempList = new List<Section_Template__c>{
            new Section_Template__c(Questionnaire_Section__c = asstempList[0].id, Section_label__c = 'HotSpot Section')
        };
        insert secTempList;
        
        List<Question_Template__c> quesTempList = new List<Question_Template__c> {
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Ur Hotspot Image Question is Shown below', 
                Question_Order_No__c = 1, Question_Type__c = 'Hotspot Image', Weight_of_Answer__c  = '10'),
            new Question_Template__c(Section_Question__c = secTempList[0].id, Question_Label__c = 'Ur Hotspot Image1 Question is Shown below', 
                Question_Order_No__c = 1, Question_Type__c = 'Hotspot Image', Weight_of_Answer__c  = '10')
        };
        insert quesTempList;
    }
    
    public static testMethod Void testUploadHotspotImageCtlrCons() {
        
        List<Question_Template__c> quesTempList = [SELECT Id, Name, Hotspot_Image_Properties__c FROM Question_Template__c];
        List<Attachment> attachList = new List<Attachment> {
            new Attachment(ParentId = quesTempList[0].Id, ContentType = 'Image', Name = String.valueof('Hotspot-Image'), Body = Blob.valueof('attached'))
        };
        
        List<UploadHotspotImageCtlr.AreaClass> areaList2 = new List<UploadHotspotImageCtlr.AreaClass>();
        UploadHotspotImageCtlr.AreaClass areaCls2 = new UploadHotspotImageCtlr.AreaClass();
        areaCls2.shape = '';
        areaCls2.coords = '';
        areaCls2.areaValue = '';
        areaList2.add(areaCls2);
                
        UploadHotspotImageCtlr.HotspotImagePropertyClass hsImagePrpty1 = new UploadHotspotImageCtlr.HotspotImagePropertyClass();
        hsImagePrpty1.area = areaList2;
        hsImagePrpty1.imageWidth = 240;
        hsImagePrpty1.imageHeight = 320;
        hsImagePrpty1.questionId = quesTempList[0].Id;
        hsImagePrpty1.questionImageId = '';
        String hotspotStr1 = JSON.serialize(hsImagePrpty1);
        
        UploadHotspotImageCtlr.AttachmentClass attachCls1 = new UploadHotspotImageCtlr.AttachmentClass();
        attachCls1.name = 'No file chosen';
        String attachStr1 = Json.serialize(attachCls1);
        
        //Case 1 (a): No Attachments are found under Ques @ initial condition
        
        ApexPages.currentPage().getParameters().put('quesTempId', quesTempList[0].Id);
        UploadHotspotImageCtlr uploadImg = new UploadHotspotImageCtlr();
        System.assertEquals(attachStr1, uploadImg.attStr);
        System.assertEquals(hotspotStr1, uploadImg.hotspotPropertyStr);
        
        // Case 2 (a): Save Attachment
        
        UploadHotspotImageCtlr.AttachmentClass attachCls = new UploadHotspotImageCtlr.AttachmentClass();
        attachCls.parentId = attachList[0].ParentId;
        attachCls.name = attachList[0].Name;
        attachCls.contenttype = attachList[0].ContentType;
        attachCls.resultbody = attachList[0].Body;
        String attachStr = Json.serialize(attachCls);
        
        List<UploadHotspotImageCtlr.AreaClass> areaList = new List<UploadHotspotImageCtlr.AreaClass>();
        UploadHotspotImageCtlr.AreaClass areaCls = new UploadHotspotImageCtlr.AreaClass();
        areaCls.shape = 'Square';
        areaCls.coords = '123';
        areaCls.areaValue = 'Rose';
        areaList.add(areaCls);
        
        UploadHotspotImageCtlr.HotspotImagePropertyClass hsImagePrpty = new UploadHotspotImageCtlr.HotspotImagePropertyClass();
        hsImagePrpty.area = areaList;
        hsImagePrpty.imageWidth = 240;
        hsImagePrpty.imageHeight = 320;
        hsImagePrpty.questionId = quesTempList[0].Id;
        hsImagePrpty.questionImageId = '';
        String hotspotStr = JSON.serialize(hsImagePrpty);
        
        String retSaveStr = UploadHotspotImageCtlr.saveHotspotImage(attachCls, hsImagePrpty);
        UploadHotspotImageCtlr.ReturnResponses retCls1 = (UploadHotspotImageCtlr.ReturnResponses)JSON.deserialize(retSaveStr, UploadHotspotImageCtlr.ReturnResponses.class);
        
        //Attachment saved under This Ques 
        List<Attachment> attachList1 = [SELECT Id, Name, ParentId, ContentType, Body FROM Attachment WHERE ParentId = :quesTempList[0].Id ];
        System.assertEquals('success', retCls1.message );
        System.assertEquals('Hotspot-Image', attachList1[0].Name);
        
        ApexPages.currentPage().getParameters().put('quesTempId', quesTempList[0].Id);
        UploadHotspotImageCtlr uploadImg2 = new UploadHotspotImageCtlr();
        
        UploadHotspotImageCtlr.AttachmentClass attachCls2 = new UploadHotspotImageCtlr.AttachmentClass();
        attachCls2.attId = attachList1[0].Id;
        attachCls2.parentId = attachList1[0].ParentId;
        attachCls2.name = attachList1[0].Name;
        attachCls2.contenttype = attachList1[0].ContentType;
        attachCls2.resultbody = attachList1[0].Body;
        String attachStr2 = Json.serialize(attachCls2);
        
        List<Question_Template__c> quesTempList1 = [SELECT Id, Name, Hotspot_Image_Properties__c FROM Question_Template__c];
        System.assertEquals(quesTempList1[0].Hotspot_Image_Properties__c , uploadImg2.hotspotPropertyStr);
        System.assertEquals(attachStr2, uploadImg2.attStr);
        
       //case 3 : Delete Existing attachment
        
        String retDelStr = UploadHotspotImageCtlr.deleteImage(attachCls2);
        UploadHotspotImageCtlr.ReturnResponses retCls = (UploadHotspotImageCtlr.ReturnResponses)JSON.deserialize(retDelStr, UploadHotspotImageCtlr.ReturnResponses.class);
        System.assertEquals('success', retCls.message);
        System.assertEquals(hotspotStr1, retCls.hotspotPropertyStr);
        System.assertEquals(attachStr1, retCls.attStr);
        
        //Case 2 (b): Save Exception block
        
        String retSaveStr2 = UploadHotspotImageCtlr.saveHotspotImage(attachCls2, hsImagePrpty);
        UploadHotspotImageCtlr.ReturnResponses retCls3 = (UploadHotspotImageCtlr.ReturnResponses)JSON.deserialize(retSaveStr2, UploadHotspotImageCtlr.ReturnResponses.class);
        System.assertEquals('failure', retCls3.message );
    }
}