src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>One_Time_Assessment__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>When One Time Assessment is checked answered provided during a previous submission will be displayed in the viewer. Without it checked they will not see any previously submitted answers and new answers can be added.</inlineHelpText>
        <label>One Time Assessment</label>
        <type>Checkbox</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public_Assessment__c.object
<CustomObject>
    <description>Used to support the collection of information necessary to perform data collections that primarily occur outside of Salesforce.</description>
    <fields>
        <fullName>Assessment_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>This is the Assessment Template ID that is being used for the Assessment.</inlineHelpText>
        <label>Assessment Template</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipLabel>Public Assessments</relationshipLabel>
        <relationshipName>Public_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Public Assessment</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Public Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Public Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssessmentTemplateTriggerHandler.cls
public class AssessmentTemplateTriggerHandler {

    public static void onBeforeUpdate(Map<Id, Main_questionaire__c> oldTemplateMap, Map<Id, Main_questionaire__c> newTemplateMap, List<Main_questionaire__c> templatesList) {
        setOneTimeAssessmentOnlyWhenTemplateHasNoPublicAssessments(oldTemplateMap, templatesList);
    }

    public static void setOneTimeAssessmentOnlyWhenTemplateHasNoPublicAssessments(Map<Id, Main_questionaire__c> oldTemplateMap, List<Main_questionaire__c> templatesList) {

        List<Main_questionaire__c> templates = new List<Main_questionaire__c>();
        Map<Id, List<Public_Assessment__c>> templateIdPublicAssessmentsMap = new Map<Id, List<Public_Assessment__c>>();

        if (templatesList != null && templatesList.size() > 0) {

            for (Main_questionaire__c template : templatesList) {

                if (template.One_Time_Assessment__c
                    && (oldTemplateMap.get(template.Id).One_Time_Assessment__c != template.One_Time_Assessment__c)
                ) {
                    templates.add( template );
                }
            }
            if (templates != null && templates.size() > 0) {
                for (Public_Assessment__c pa : [SELECT Assessment_Template__c , Id, Name FROM Public_Assessment__c WHERE Assessment_Template__c IN :templates]) {
                    if (!templateIdPublicAssessmentsMap.containsKey(pa.Assessment_Template__c)) {
                        templateIdPublicAssessmentsMap.put(pa.Assessment_Template__c, new List<Public_Assessment__c>());
                    }
                    templateIdPublicAssessmentsMap.get(pa.Assessment_Template__c).add( pa );
                }
                for (Main_questionaire__c template : templates) {
                    if (templateIdPublicAssessmentsMap.containsKey(template.Id)
                        && templateIdPublicAssessmentsMap.get(template.Id) != null
                        && templateIdPublicAssessmentsMap.get(template.Id).size() > 0
                    ) {
                        template.addError( 'One Time Assessment cannot be set as true since this template has existing public assessments below it' );
                    }
                }
            }
        }
    }
}