src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Web_Intercept_Header__c</fullName>
        <label>Web Intercept Header</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Web_Intercept_PA_Resource_File_Path__c</fullName>
        <label>Web Intercept PA Resource File Path</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Web_Intercept_PA_Static_Resource_Name__c</fullName>
        <label>Web Intercept PA Static Resource Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Intercept_Static_Resource_Name__c</fullName>
        <label>WI CSS Override Static Resource Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestWebInterceptConfigurationController.cls
@isTest
private class TestWebInterceptConfigurationController {
    static  testMethod void method1(){
        
        Main_questionaire__c templateRec = new Main_questionaire__c(
            Web_Intercept_PA_Resource_File_Path__c = 'test file path', Web_Intercept_Header__c = 'test header', 
            Web_Intercept_Static_Resource_Name__c = 'test modal css resource name',
            Web_Intercept_PA_Static_Resource_Name__c = 'test pa sr name'
        );
        insert templateRec;
        
        ApexPages.currentPage().getParameters().put('templateId',templateRec.Id);
        String templateRecString = JSON.serialize(templateRec);
        
        WebInterceptConfigurationController wicc = new WebInterceptConfigurationController();
        
        String saveWIConfigResult = WebInterceptConfigurationController.saveWIConfig(templateRecString);
        System.assertEquals('success', saveWIConfigResult);
        
        templateRecString = templateRecString.replace(templateRec.Id, '');
        String saveWIConfigResult1 = WebInterceptConfigurationController.saveWIConfig(templateRecString);
    }
}