src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExamFieldEditorController.cls
public with sharing class ExamFieldEditorController {
    
    public static sObject updateRecord(String ObjectName, String JSONStr){
        
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Set<String> objectKeys = gd.keySet();
        sObject sObj;
        String assessmentId;
        if(objectKeys.contains(Objectname.toLowerCase()))
        {   
            
            System.debug('JSONStr:::'+JSONStr);
            
            Type sObjectType = Type.forName(ObjectName);
            sObj = (sObject)JSON.deserialize(JSONStr, sObjectType);
            
            try{
                //FieldLevelSecurity.checkFieldAccessByCriteria(sObj, 'update', ObjectName);
                update sObj;
                if(ObjectName != 'ExAM__Main_questionaire__c'){
                    if(ObjectName == 'ExAM__Section_Template__c'){
                        FieldLevelSecurity.checkFieldAccessByCriteria('ExAM__Questionnaire_Section__c', 'view', ObjectName);
                        Section_Template__c section = [SELECT Id, Questionnaire_Section__c FROM Section_Template__c WHERE Id =:sObj.Id];
                        assessmentId = section.Questionnaire_Section__c;
                    }else if(ObjectName == 'ExAM__Question_Template__c'){
                        FieldLevelSecurity.checkFieldAccessByCriteria('ExAM__Section_Question__c', 'view', ObjectName);
                        FieldLevelSecurity.checkFieldAccessByCriteria('ExAM__Questionnaire_Section__c', 'view', 'exam__Section_Template__c');
                        Question_Template__c question = [SELECT Id, Section_Question__c, Section_Question__r.Questionnaire_Section__c  FROM Question_Template__c WHERE Id =:sObj.Id];
                        assessmentId = question.Section_Question__r.Questionnaire_Section__c;
                    }
                }

                if(assessmentId != null && assessmentId != 'undefined'){
                    AssessmentService.updateAssessmentDueToChildUpdates(assessmentId);
                }
                
            }
            catch(Exception e){
                throw new AuraHandledException(e.getMessage());
            }
            
        }
        return sObj;
    }
    
    
    /*public static sObject updateRecord(String ObjectName, String id, String fieldName, String fieldVal){
        
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        Set<String> objectKeys = gd.keySet();
        sObject sObj;
        String assessmentId;
        if(objectKeys.contains(Objectname.toLowerCase()))
        {   
            //Creating a new sObject
            sObj = Schema.getGlobalDescribe().get(ObjectName).newSObject() ;
            sObj.put('id',id);
            sObj.put(fieldName,fieldVal);
            
            try{
                FieldLevelSecurity.checkFieldAccessByCriteria(fieldName, 'update', ObjectName);
                update sObj;
                if(ObjectName != 'Main_questionaire__c'){
                    if(ObjectName == 'Section_Template__c'){
                        FieldLevelSecurity.checkFieldAccessByCriteria('Questionnaire_Section__c', 'view', ObjectName);
                        Section_Template__c section = [SELECT Id, Questionnaire_Section__c FROM Section_Template__c WHERE Id =:sObj.Id];
                        assessmentId = section.Questionnaire_Section__c;
                    }else if(ObjectName == 'Question_Template__c'){
                        FieldLevelSecurity.checkFieldAccessByCriteria('Section_Question__c', 'view', ObjectName);
                        FieldLevelSecurity.checkFieldAccessByCriteria('Questionnaire_Section__c', 'view', 'Section_Template__c');
                        Question_Template__c question = [SELECT Id, Section_Question__c, Section_Question__r.Questionnaire_Section__c  FROM Question_Template__c WHERE Id =:sObj.Id];
                        assessmentId = question.Section_Question__r.Questionnaire_Section__c;
                    }
                }
                
                if(assessmentId != null && assessmentId != 'undefined'){
                    AssessmentService.updateAssessmentDueToChildUpdates(assessmentId);
                }
            }
            catch(Exception e){
                throw new AuraHandledException(e.getMessage());
            }
            
        }
        return sObj;
    }*/
}