src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree Result Page Fields</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Viewer_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Enables you select a specific configuration of the Standard Viewer to be used for the specified Assessment Template. You can create Standard Viewer configurations that include or exclude specific tabs in the ExAM Configuration tab.</inlineHelpText>
        <label>Viewer Configuration</label>
        <referenceTo>Viewer_Custom_Configuration__c</referenceTo>
        <relationshipLabel>Assessment Templates</relationshipLabel>
        <relationshipName>Assessment_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Decision_Tree__c</fullName>
        <label>Decision Tree Result Page Fields Default</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Section_label__c</fullName>
        <description>Put label  in section1:section1.1 form</description>
        <inlineHelpText>Put label  in section1:section1.1 form</inlineHelpText>
        <label>Section Name</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Viewer_Custom_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the standard viewer on an Assessment Template by Assessment Template basis. This configuration is done in the ExAM Configuration tab.</description>
    <label>Viewer Custom Configuration</label>
    <nameField>
        <label>Viewer Custom Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewer Custom Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestResultTemplateConfigurationCtrller.cls
@isTest
public class TestResultTemplateConfigurationCtrller {

    static testmethod void method1() {

        Viewer_Custom_Configuration__c vc = new Viewer_Custom_Configuration__c();
        vc.Name ='Viewer 1';
        insert vc;

        Main_questionaire__c[] templateList = new Main_questionaire__c[] {
            new Main_questionaire__c(Template_name__c = 'General Safety', Viewer_Configuration__c = vc.Id),
            new Main_questionaire__c(Decision_Tree__c = 'exam__deficiency_status__c:true:false~exam__Priority__c:true:true', Template_name__c = 'General Instructions', Viewer_Configuration__c = vc.Id)
        };
        insert templateList;

        Section_Template__c[] sectionTemplateList = new Section_Template__c[] {
            new Section_Template__c(Questionnaire_Section__c = templateList[0].Id, Section_label__c = 'General Safety Section'),
            new Section_Template__c(Questionnaire_Section__c = templateList[1].Id, Section_label__c = 'General Instructions Section')
        };
        insert sectionTemplateList;

        Question_Template__c[] questionTemplateList = new Question_Template__c[] {
            new Question_Template__c(Question_Label__c = 'Result Question 1', Question_Type__c = 'Result', Section_Question__c = sectionTemplateList[0].Id),
            new Question_Template__c(Decision_Tree__c = 'exam__deficiency_status__c:Open~exam__Priority__c:High', Question_Label__c = 'Result Question 2', Question_Type__c = 'Result', Section_Question__c = sectionTemplateList[1].Id)
        };
        insert questionTemplateList;

        List<ResultTemplateConfigurationController.FieldVisibilityClass> fieldVisibilityList1 = new List<ResultTemplateConfigurationController.FieldVisibilityClass>();
        List<ResultTemplateConfigurationController.FieldDefaultValueClass> fieldDefaultValueList1 = new List<ResultTemplateConfigurationController.FieldDefaultValueClass>();

        ApexPages.currentPage().getParameters().put('assessmentTemplateId', templateList[0].Id);
        ApexPages.currentPage().getParameters().put('questionTemplateId', questionTemplateList[0].Id);
        ResultTemplateConfigurationController resultTemplateConfigCtrller1 = new ResultTemplateConfigurationController();

        for(ResultTemplateConfigurationController.FieldVisibilityClass f : resultTemplateConfigCtrller1.fieldVisibilityList) {
            f.hasSelected = true;
            fieldVisibilityList1.add( f );
        }

        Integer i1 = 1;
        for(ResultTemplateConfigurationController.FieldDefaultValueClass f : resultTemplateConfigCtrller1.fieldDefaultValueList) {

            f.defaultValue = 'TEST DEFAULT VALUE '+i1;
            fieldDefaultValueList1.add( f );
            i1++;
        }

        List<ExAM__Main_questionaire__c> tempListBeforeSave = new List<ExAM__Main_questionaire__c>([SELECT ExAM__Decision_Tree__c, Id, Name FROM ExAM__Main_questionaire__c WHERE Id = :templateList[0].Id]);
        system.assertEquals(tempListBeforeSave[0].ExAM__Decision_Tree__c, null);
        
        ResultTemplateConfigurationController.TemplateClass templateCls = new ResultTemplateConfigurationController.TemplateClass();
        templateCls.id = templateList[0].Id;
        templateCls.resultQuesButtonText = 'Submit';
        templateCls.fieldVisibilityList = fieldVisibilityList1;
        ResultTemplateConfigurationController.saveFieldVisibility(JSON.serializePretty(templateCls));
        resultTemplateConfigCtrller1.saveFieldDefaultValues();
        
        
        List<ResultTemplateConfigurationController.FieldVisibilityClass> fieldVisibilityList2 = new List<ResultTemplateConfigurationController.FieldVisibilityClass>();
        List<ResultTemplateConfigurationController.FieldDefaultValueClass> fieldDefaultValueList2 = new List<ResultTemplateConfigurationController.FieldDefaultValueClass>();

        ApexPages.currentPage().getParameters().put('assessmentTemplateId', templateList[1].Id);
        ApexPages.currentPage().getParameters().put('questionTemplateId', questionTemplateList[1].Id);
        ResultTemplateConfigurationController resultTemplateConfigCtrller2 = new ResultTemplateConfigurationController();

        for(ResultTemplateConfigurationController.FieldVisibilityClass f : resultTemplateConfigCtrller2.fieldVisibilityList) {

            f.hasSelected = true;
            fieldVisibilityList2.add( f );
        }

        Integer i2 = 1;
        for(ResultTemplateConfigurationController.FieldDefaultValueClass f : resultTemplateConfigCtrller2.fieldDefaultValueList) {

            f.defaultValue = 'TEST DEFAULT VALUE '+i2;
            fieldDefaultValueList2.add( f );
            i2++;
        }
        ResultTemplateConfigurationController.TemplateClass tempCls = new ResultTemplateConfigurationController.TemplateClass();
        tempCls.id = templateList[0].Id;
        tempCls.resultQuesButtonText = 'Submit';
        tempCls.fieldVisibilityList = fieldVisibilityList2;
        ResultTemplateConfigurationController.saveFieldVisibility(JSON.serializePretty(tempCls));
        resultTemplateConfigCtrller2.saveFieldDefaultValues();

        List<ExAM__Main_questionaire__c> tempListAfterSave = new List<ExAM__Main_questionaire__c>([SELECT ExAM__Decision_Tree__c, Id, Name FROM ExAM__Main_questionaire__c WHERE Id = :templateList[0].Id]);
        system.assertNotEquals(tempListAfterSave[0].ExAM__Decision_Tree__c, null);
    }
}