src/objects/Main_questionaire__c.object
<CustomObject>
    <description>Assessment Templates are containers for your Sections. They also help determine how your Assessment process will flow as well as providing key information for supporting the look and feel of your assessment across all viewers.</description>
    <fields>
        <fullName>Template_name__c</fullName>
        <inlineHelpText>This is the field which uniquely identifies the template for the Organization</inlineHelpText>
        <label>Template name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Assessment Template</label>
    <nameField>
        <displayFormat>T-{0}</displayFormat>
        <label>Main_questionnaire_template_id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestRestGetDecisionTree.cls
@isTest

public class TestRestGetDecisionTree {
    
    static testmethod void method1(){
        List<String> templateIdList = new List<String>();
        
        Main_questionaire__c temp = new Main_questionaire__c();//Template creation
        temp.Template_name__c = 'Template1';
        insert temp;
        Main_questionaire__c temp1 = new Main_questionaire__c();//Template creation
        temp1.Template_name__c = 'Template2';
        insert temp1;
        
        templateIdList.add(temp.Id);
        templateIdList.add(temp1.Id);
        String ret = RestGetDecisionTree.getDecisionTree(templateIdList);
    
    System.assert( ret != Null );        
    }
}