src/objects/Mobile_Incident_Report_Form__c.object
<CustomObject>
    <description>Used to support event and incident reporting.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Drug/Alcohol Offenses</fullName>
                </value>
                <value>
                    <fullName>Crimes Against Persons</fullName>
                </value>
                <value>
                    <fullName>Crimes Against Property</fullName>
                </value>
                <value>
                    <fullName>Security Threats</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mobile Incident Report</label>
    <nameField>
        <label>Mobile Incidence Reporting Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobile Incident Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestIncidentLocationMAPController.cls
@isTest
public class TestIncidentLocationMAPController {
    
    static testMethod void method1(){

        List<Mobile_Incident_Report_Form__c> mirfList = new List<Mobile_Incident_Report_Form__c>{
            new Mobile_Incident_Report_Form__c(Name = 'test Form',Category__c = '')
        };
        insert mirfList;

        IncidentLocationMAPController tilMapCntrlr = new IncidentLocationMAPController();
        String tilMapRes = tilMapCntrlr.getincidentslist();
        system.assertEquals(tilMapCntrlr.incidents.size(), 1);
    }
}