src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UploadAnswerOptionImagesController.cls
public with sharing class UploadAnswerOptionImagesController {

    public Integer noOfOptions { get; set; }
    public string baseUrl { get; set; }
    public string options { get; set; }
    
    public UploadAnswerOptionImagesController() {
    
        baseUrl = Url.getSalesforceBaseUrl().toExternalForm();
        options = '';
        String queTempId = ApexPages.currentPage().getParameters().get('quesTempId');

        List<Question_Template__c> quesTempList = new List<Question_Template__c>();
        
        if(queTempId != null && queTempId != '' ) {
        
            noOfOptions = 1;
            quesTempList = [SELECT Id, Name, Subquestion_Label__c FROM Question_Template__c WHERE Id = :queTempId LIMIT 1];
            
            if(quesTempList != null && quesTempList.size() > 0) {

                if (string.isNotBlank(quesTempList[0].Subquestion_Label__c)) {
                    options = quesTempList[0].Subquestion_Label__c;
                    if (quesTempList[0].Subquestion_Label__c.contains('~') ) {
                        noOfOptions = noOfOptions + quesTempList[0].Subquestion_Label__c.countMatches('~');
                    }
                }
            }
        }
    }
}