src/objects/Question_Template__c.object
<CustomObject>
    <description>Used to collect the information needed to support the Questions ExAM uses to elicit participant information.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <description>This is the question label eg. What are the standard operating hours?</description>
        <inlineHelpText>This is the question label eg. What are the standard operating hours?</inlineHelpText>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <inlineHelpText>Pick from a list text, picklist etc</inlineHelpText>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>MultiselectPicklist</fullName>
                </value>
                <value>
                    <fullName>RadioPicklist</fullName>
                </value>
                <value>
                    <fullName>Dropdown Picklist</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Textarea</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Result</fullName>
                </value>
                <value>
                    <fullName>Assessment Completed</fullName>
                </value>
                <value>
                    <fullName>Image</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Number</fullName>
                </value>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>File Question - Answer</fullName>
                </value>
                <value>
                    <fullName>File Question - AM</fullName>
                </value>
                <value>
                    <fullName>Signature</fullName>
                </value>
                <value>
                    <fullName>Hotspot Image</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
                <value>
                    <fullName>Case</fullName>
                </value>
                <value>
                    <fullName>Horizontal Radiopicklist</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Hidden</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>File Question - Assessable Object</fullName>
                </value>
                <value>
                    <fullName>Likert</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Question__c</fullName>
        <description>Master- Detail relationship- Section is Master and Detail is Question</description>
        <inlineHelpText>Master- Detail relationship- Section is Master and Detail is Question</inlineHelpText>
        <label>Master Section to Detail Question</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipName>Question_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Single_Next_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to next question in decision tree</description>
        <inlineHelpText>Lookup to next question in decision tree</inlineHelpText>
        <label>Single Next Question</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Question Templates</relationshipLabel>
        <relationshipName>Question_Template</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subquestion_Label__c</fullName>
        <description>Put all values ~ separated</description>
        <inlineHelpText>Put all values ~ separated</inlineHelpText>
        <label>Answer Options</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Template</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Question_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questionnaire_Response__c.object
<CustomObject>
    <description>Where ExAM stores the response data from your Assessments.</description>
    <fields>
        <fullName>Question_Label__c</fullName>
        <formula>Question_Template__r.Question_Restricted_Length__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is the label of the question that is related to the Answer being provided.</inlineHelpText>
        <label>Question Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Template__c</fullName>
        <description>question to response table</description>
        <inlineHelpText>This is the Question Id for the question that was the basis for this Answer.</inlineHelpText>
        <label>Question Template - Response</label>
        <referenceTo>Question_Template__c</referenceTo>
        <relationshipLabel>Answers (Question Template - Response)</relationshipLabel>
        <relationshipName>Questionnaire_Response</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <inlineHelpText>This is the response selected or entered by the participant.</inlineHelpText>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Answer</label>
    <nameField>
        <displayFormat>QR-{0}</displayFormat>
        <label>Assessment Response id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>Questionnaire_Section__c</fullName>
        <inlineHelpText>Master Detail Relationship - Main Questionaire is master and section is detail.</inlineHelpText>
        <label>Master Questionnaire to Detail Section</label>
        <referenceTo>Main_questionaire__c</referenceTo>
        <relationshipName>Section_Template</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuestionResponseAnalyticsController.cls
public with sharing class QuestionResponseAnalyticsController {
    @AuraEnabled 
    public static QuestionAnalyticInfo getAnswerResponseWithCount(String assessmentId, Integer offset){
        
        Map<Id, Section_Template__c> sectionTemplates = new Map<Id, Section_Template__c>([SELECT Id, Questionnaire_Section__c FROM Section_Template__c WHERE Questionnaire_Section__c = :assessmentId]);
        Map<Id, List<Questionnaire_Response__c>> questionIdWthAnswers = new Map<Id, List<Questionnaire_Response__c>>();
        
        Set<String> OptionBasedQuestionTypes = new Set<String>{'Dropdown Picklist','RadioPicklist', 
            'Button', 'MultiselectPicklist', 'List', 'Image', 'Horizontal Radiopicklist',
            'Hotspot Image'};
                
        List<String> filteringQuestionTypes = new List<String>{'Text','Textarea','Email'};
                    
        filteringQuestionTypes.addAll(OptionBasedQuestionTypes);
                
        String fields = 'Question_Template__c, Response__c';
        FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'view', 'Questionnaire_Response__c');     
        
        List<Questionnaire_Response__c>  answerRecords = [SELECT Id, Question_Template__c, Response__c
                                                                  FROM Questionnaire_Response__c 
                                                                  WHERE Question_Template__r.Section_Question__c IN :sectionTemplates.keySet() 
                                                                  AND Question_Template__r.Question_Type__c IN :filteringQuestionTypes];
        
        for(Questionnaire_Response__c answerRecord : answerRecords){
            
            if(questionIdWthAnswers.containsKey(answerRecord.Question_Template__c)){
                questionIdWthAnswers.get(answerRecord.Question_Template__c).add(answerRecord);
            }else{
                questionIdWthAnswers.put(answerRecord.Question_Template__c, new List<Questionnaire_Response__c>{answerRecord});
            }
            
        }
        
        Set<Id> questionIds = questionIdWthAnswers.keySet();
        
        fields = 'Question_Label__c, Subquestion_Label__c, Question_Type__c';
        FieldLevelSecurity.checkFieldAccessByCriteria(fields, 'view', 'Question_Template__c');  
        
        String strQuery = 'SELECT Id, Question_Label__c, Subquestion_Label__c, Question_Type__c' 
            +' FROM Question_Template__c'
            +' WHERE Id IN : questionIds '            
            +' ORDER BY CreatedDate LIMIT 10 OFFSET ' + offset;
        
        
        List<Question_Template__c>  questions = Database.query(strQuery);
        List<QuestionAnalytic> QuestionAnalyticResponse = new List<QuestionAnalytic>();
        
        for(Question_Template__c question : questions){            
            List<Questionnaire_Response__c> answers = questionIdWthAnswers.get(question.Id);
            QuestionAnalytic questionResponse = new QuestionAnalytic();
            questionResponse.questionLablel = question.Question_Label__c;
            List<AnswerAnalytic> answerResponse = constructAnswerResponse(question, answers);
            
            if(OptionBasedQuestionTypes.contains(question.Question_Type__c)){
                questionResponse.optionBased = true;
                questionResponse.answer = answerResponse;
            }else{
                questionResponse.optionBased = false;
                if(answerResponse.size() > 15){
                    List<AnswerAnalytic> answerResponseDescList = new List<AnswerAnalytic>();
                    answerResponse.sort();
                    for(Integer i = 0; i < answerResponse.size()-1; i++){
                        
                        AnswerAnalytic answerResponseDesc = new AnswerAnalytic();
                        answerResponseDesc.Name = answerResponse[i].Name;
                        answerResponseDesc.weight = answerResponse[i].weight;
                        answerResponseDescList.add(answerResponseDesc);
                        
                        if(answerResponseDescList.size() == 15){
                            break;
                        }
                        
                    }
                    questionResponse.answer = answerResponseDescList; 
                }else{
                    questionResponse.answer = answerResponse;
                }
            }
            
            QuestionAnalyticResponse.add(questionResponse);
            
        }
        
        QuestionAnalyticInfo questionSizeAndCurrentViewer = new QuestionAnalyticInfo();
        questionSizeAndCurrentViewer.noOfQuestions = questionIds.size();
        questionSizeAndCurrentViewer.questions = QuestionAnalyticResponse;
        
        return questionSizeAndCurrentViewer;
    }
    
    public static List<AnswerAnalytic> constructAnswerResponse(Question_Template__c question, List<Questionnaire_Response__c> answers){
        Map<String, AnswerAnalytic> responseNameWthAnswerAnalytic = new Map<String, AnswerAnalytic>();
        for(Questionnaire_Response__c answer : answers){            
            if(question.Question_Type__c == 'MultiselectPicklist'){
                constructMultiPickResponse(answer.Response__c, responseNameWthAnswerAnalytic);
            }else{
                
                if(responseNameWthAnswerAnalytic.containsKey(answer.Response__c)){
                    AnswerAnalytic oldResponse = responseNameWthAnswerAnalytic.get(answer.Response__c);
                    oldResponse.weight += 1;
                }else{
                    AnswerAnalytic newResponse = new AnswerAnalytic();
                    newResponse.name = answer.Response__c;
                    newResponse.weight = 1;
                    responseNameWthAnswerAnalytic.put(answer.Response__c, newResponse);
                }
                
            }            
        }
        return responseNameWthAnswerAnalytic.values();
    }
    
    public static Map<String, AnswerAnalytic> constructMultiPickResponse(String answer, Map<String, AnswerAnalytic> responseNameWthAnswerAnalytic){
        List<String> answerResponse = answer.split('~');
        for(Integer i = 0; i < answerResponse.size(); i++){
            if(responseNameWthAnswerAnalytic.containsKey(answerResponse[i])){
                AnswerAnalytic oldResponse = responseNameWthAnswerAnalytic.get(answerResponse[i]);
                oldResponse.weight += 1; 
            }else{
                AnswerAnalytic newResponse = new AnswerAnalytic();
                newResponse.name = answerResponse[i];
                newResponse.weight = 1;
                responseNameWthAnswerAnalytic.put(answerResponse[i], newResponse);
            }
        }
        return responseNameWthAnswerAnalytic;
    }
    public class QuestionAnalyticInfo {
        @AuraEnabled
        public Integer noOfQuestions;
        @AuraEnabled
        public List<QuestionAnalytic> questions;
    }
    public class QuestionAnalytic {
        @AuraEnabled
        public String questionLablel;
        @AuraEnabled
        public Boolean optionBased;
        @AuraEnabled
        public List<AnswerAnalytic> answer;
    }
    public class AnswerAnalytic implements Comparable{
        @AuraEnabled
        public String name;	// response name of Answer
        @AuraEnabled
        public Integer weight; // count
        public Integer compareTo(Object compareTo) {
            
            AnswerAnalytic other = (AnswerAnalytic) compareTo;
            
            if (this.weight <= other.weight)
                return 1;
            else if (this.weight > other.weight)
                return 0;
            return -1;
        }
    }
}