src/objects/Report_Builder_Configuration__c.object
<CustomObject>
    <description>Used to support individual report configurations so that ExAM reports can be saved for future use.</description>
    <fields>
        <fullName>Is_Temporary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Temporary</label>
        <type>Checkbox</type>
    </fields>
    <label>Report Builder Configuration</label>
    <nameField>
        <label>Report Builder Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Report Builder Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DelTemporaryReportBuilderController.cls
global with sharing class DelTemporaryReportBuilderController implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT ID, Is_Temporary__c, CreatedDate FROM Report_Builder_Configuration__c WHERE Is_Temporary__c = true AND CreatedDate != TODAY';
        return Database.getQueryLocator(query);    
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> tempReportBuilderList){
        if (tempReportBuilderList != null && tempReportBuilderList.size() > 0) {
            delete tempReportBuilderList;
        }
    }
    
    global void finish(Database.BatchableContext BC){
    
    }
}