src/objects/Section_Template__c.object
<CustomObject>
    <description>Used to group questions and support the logical separation of groups of questions within Assessment Templates.</description>
    <fields>
        <fullName>status__c</fullName>
        <inlineHelpText>This is to set whether the section is complete or not. We can set in the apex code when the user answers all the questions of a section.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incomplete</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Section Template</label>
    <nameField>
        <displayFormat>Sec-{0}</displayFormat>
        <label>Section_Template id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SectionStatus__c.object
<CustomObject>
    <description>Used to support the evaluation of the completeness of sections within an Assessment Template.</description>
    <fields>
        <fullName>Account_to_SectionStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the lookup object that will be used in a survey.So we are not using user but accounts to create number of surveys.The no of surveys would be same as no of accounts whose craete_survey field(on Account object) is set to true</description>
        <inlineHelpText>This is the lookup object that will be used in a survey.So we are not using user but accounts to create number of surveys.The no of surveys would be same as no of accounts whose craete_survey field(on Account object) is set to true</inlineHelpText>
        <label>Account to SectionStatus</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SectionStatus</relationshipLabel>
        <relationshipName>SectionStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>section table id in section status table</inlineHelpText>
        <label>Section Template</label>
        <referenceTo>Section_Template__c</referenceTo>
        <relationshipLabel>SectionStatus</relationshipLabel>
        <relationshipName>SectionStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Incomplete&quot;</defaultValue>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SectionStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SectionStatus</label>
    <nameField>
        <displayFormat>Status-{0}</displayFormat>
        <label>SectionStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SectionStatus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Visitor_Register__c.object
<CustomObject>
    <description>Used to collect information on ExAM Assessment participants. Enables analysis against visitors and participants in ExAM data collections.</description>
    <fields>
        <fullName>Date_and_TimeIN__c</fullName>
        <label>Date and Time-IN</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Visitor_Last_Name__c</fullName>
        <label>Visitor Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visitor__c</fullName>
        <label>Visitor First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Visitor Register</label>
    <nameField>
        <label>Visitor Register Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitor Register</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisitorsRegisterController.cls
public with sharing class VisitorsRegisterController {

    public PageReference refresh = new PageReference(ApexPages.currentPage().getUrl());
    public Visitor_Register__c VisRecord;

    public VisitorsRegisterController(ApexPages.StandardController controller)
    {

        VisRecord = (Visitor_Register__c)controller.getRecord();
        VisRecord.Date_and_TimeIN__c = System.now();//Date.today();
    }
    
    public VisitorsRegisterController(){}

    public PageReference save()
    {

        try {

            if (string.isBlank(visRecord.ExAM__Visitor__c) && string.isBlank(visRecord.Visitor_Last_Name__c)) {
                ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, 'Please enter value for Visitors Name') );
                return null;
            }
            else {

                SFDCAccessController access = ExAMUtilClass.AccessController;
                List<String> fieldsList = new List<String>{'ExAM__Date_and_TimeIN__c', 'ExAM__Person_Place_Visiting__c', 'ExAM__Visitor__c', 'ExAM__Visitor_Last_Name__c'};
                access.assertAuthorizedToCreate(Schema.getGlobalDescribe().get('exam__Visitor_Register__c'), fieldsList);
                access.assertAuthorizedToUpdate(Schema.getGlobalDescribe().get('exam__Visitor_Register__c'), fieldsList);

                //Visitor_Register__c visitorRecord=new Visitor_Register__c();
                upsert visRecord;

                PageReference cancelClicked = new PageReference('/home/home.jsp');
                cancelClicked.setRedirect(false);
                return cancelClicked;
            }
        }
        catch (Exception e) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
        return null;
    }

    public static testMethod void testVisitorReport() {

        PageReference pageRef = Page.VisitorsRegister;
        Test.setCurrentPage(pageRef);
        Visitor_Register__c ac=new Visitor_Register__c(Visitor_Last_Name__c='testvisitor',Visitor__c='fnvisitor');
        insert ac;    // [Select id,Visitor__c from Visitor_Register__c limit 1];      
        VisitorsRegisterController d= new VisitorsRegisterController ();      
        ApexPages.currentPage().getUrl();
        // Visitor_Register__c ac=[Select id,Visitor__c from Visitor_Register__c limit 1]; 
        ApexPages.StandardController sc = new ApexPages.StandardController(ac);
        VisitorsRegisterController d1= new VisitorsRegisterController (sc);  
        
        Test.startTest();
        d.VisRecord=ac;
        d.VisRecord.Date_and_TimeIN__c= System.now();
        d.save();
        Test.stopTest();

        //assert results
        System.assert(ac!=null,'Report is null');     
     }

    /* @isTest(SeeAllData=true)
    public static  void testVisitorReport() {

        PageReference pageRef = Page.VisitorsRegister;
        Test.setCurrentPage(pageRef);
        VisitorsRegisterController d= new VisitorsRegisterController ();      
        ApexPages.currentPage().getUrl();
        Visitor_Register__c ac=[Select id,Visitor__c from Visitor_Register__c limit 1]; 
        ApexPages.StandardController sc = new ApexPages.StandardController(ac);
        VisitorsRegisterController d1= new VisitorsRegisterController (sc);  

        Test.startTest();
        d.VisRecord=ac;
        d.VisRecord.Date_and_TimeIN__c= System.now();
        d.save();
        Test.stopTest();

        //assert results
        System.assert(ac!=null,'Report is null');     
     }*/

    /*public PageReference submitForApproval()
    {
        //SectionStatus__c[] userSectionStatus=[Select id,Section_Template__c,Status__c,User__c from SectionStatus__c where User__c= :UserInfo.getUserId()] ;
        SectionStatus__c[] userSectionStatus=[Select id,Section_Template__c,Status__c,Account_to_SectionStatus__c,User__c from SectionStatus__c where Account_to_SectionStatus__c= :accountId] ;
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(userSectionStatus[0].id);
        Approval.ProcessResult result = Approval.process(req1); 
        System.assert(result.isSuccess());  
        PageReference cancelClicked=new PageReference('/apex/OHSESMain');
        cancelClicked.setRedirect(false);
        return cancelClicked;
    }*/

    /* public PageReference cancel()
    {
        //Default goes to Home page so not putting anything here
        //PageReference cancelClicked=new PageReference('/apex/QuestionnaireCustom');
        PageReference cancelClicked=new PageReference('/apex/SurveyList');
        cancelClicked.setRedirect(false);
        return cancelClicked;  
    }*/
}