src/objects/Section_Group__c.object
<CustomObject>
    <description>Used to group multiple sections in order to support complex assessments that require sections from multiple ExAM Assessment Templates.</description>
    <fields>
        <fullName>Group_Name__c</fullName>
        <label>Group Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Section Group</label>
    <nameField>
        <displayFormat>SG-{0}  {MM}-{DD}-{YYYY}</displayFormat>
        <label>Section Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Section Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestReportConfigController.cls
@isTest
private class TestReportConfigController {
    static testMethod void method1() {
        Section_Group__c sG = new Section_Group__c();
        sG.Group_Name__c = 'TEST';
        insert sG;
        
    ReportConfigController reportConfigObject = new ReportConfigController();
        reportConfigObject.getAssignItems();
        List<SelectOption> opt = reportConfigObject.getSectionItems();
      System.assertEquals(1, opt.size());
    }
}