src/objects/Viewer_Custom_Configuration__c.object
<CustomObject>
    <description>Used to support the configuration of the standard viewer on an Assessment Template by Assessment Template basis. This configuration is done in the ExAM Configuration tab.</description>
    <fields>
        <fullName>Answer_Options__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Answer Options</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assignment_Manager_List__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assignment Manager List</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assignment_Manager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assignment Manager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Data Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Hierarchical_Object__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hierarchical Object</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Single_Question_Mode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Single Question Mode</label>
        <type>Checkbox</type>
    </fields>
    <label>Viewer Custom Configuration</label>
    <nameField>
        <label>Viewer Custom Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Viewer Custom Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ViewerConfigurationController.cls
public with sharing class ViewerConfigurationController {
    
    public String viewerConfigJSON { get; set; }
    
    public ViewerConfigurationController() {

        viewerConfigJSON = '';
        try {

            SFDCAccessController access = ExAMUtilClass.AccessController;
            List<String> fieldsList = new List<String>{'ExAM__Answer_Options__c', 'ExAM__Assignment_Manager__c', 'ExAM__Assignment_Manager_List__c', 'ExAM__Data_Management__c', 'ExAM__Hierarchical_Object__c', 'ExAM__Single_Question_Mode__c'};
            access.assertAuthorizedToView(Schema.getGlobalDescribe().get('exam__Viewer_Custom_Configuration__c'), fieldsList);

            List<Viewer_Custom_Configuration__c > viewerCustomConfigList = [
                SELECT Answer_Options__c, Assignment_Manager__c, Assignment_Manager_List__c,
                       Data_Management__c, Hierarchical_Object__c, Id, Name, Single_Question_Mode__c
                FROM   Viewer_Custom_Configuration__c ORDER BY Name ASC Limit 1000
            ];
            if (viewerCustomConfigList != null && viewerCustomConfigList.size() > 0) {
                viewerConfigJSON = JSON.serialize(viewerCustomConfigList);
            }
        }
        catch (Exception e) {
            ApexPages.addMessage( new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()) );
        }
    }

    @RemoteAction 
    public static String saveCustomConfigurationViewer1(Viewer_Custom_Configuration__c viewerRec) {

        String resultMessage = '';
        try {    
            if (viewerRec.Name != null && viewerRec.Name != '') {

                SFDCAccessController access = ExAMUtilClass.AccessController;
                List<String> fieldsListToCreate = new List<String>{'ExAM__Answer_Options__c', 'ExAM__Assignment_Manager__c', 'ExAM__Assignment_Manager_List__c', 'ExAM__Data_Management__c', 'ExAM__Hierarchical_Object__c', 'ExAM__Single_Question_Mode__c'};
                access.assertAuthorizedToCreate(Schema.getGlobalDescribe().get('exam__Viewer_Custom_Configuration__c'), fieldsListToCreate);

                insert viewerRec;
                resultMessage = 'success';
            } else {
                resultMessage = 'Viewer Name was blank';
            }
        } catch(Exception ex) {
            resultMessage = ex.getMessage();
        }
        return resultMessage;
    } 
}